### ISSUE TITLE
Settings files not valid

### ISSUE THREAD

**Issue by cercata** [LukeRoss00/gta5-real-mod#1]
The settings file you provide are not valid for me, the game changes them.
I guess it detects it's another system, and it resets somethings, as a result, I didn't have square resolution anymore.

I'm afraid it can be happening to many people

**Comment by LukeRoss00** [comment]
Another user solved this by making the settings file read-only. I'm not sure what triggers the issue, but thanks for reporting it; as soon as we find the root cause I'll update the FAQ section.

**Comment by cercata** [comment]
It's maybe the videocard description ?

I'm afraid many people complaining of issues because of "alternate eye", in fact they have bad settings.
I just enterered your setting manually into my file, and now the game runs much much better, huge difference

**Comment by LukeRoss00** [comment]
It could well be. Could you please post your settings.xml file here?

**Comment by cercata** [comment]
[settings.zip](https://github.com/LukeRoss00/gta5-real-mod/files/3748109/settings.zip)

**Comment by LukeRoss00** [comment]
In fact, in your case the only difference seems to be the videocard description. However, there might also be some interaction with the `pc_settings.bin` file, because user comments are all over the place...
