### ISSUE TITLE
please,make a options for can use mods in vr

### ISSUE THREAD

**Issue by oscarstg1** [LukeRoss00/gta5-real-mod#101]
i install the vr normal in gta v and run nice,but i put mods type Superman,o  ironman thanos,o other and happend this:(i install AddonPeds  and mod necesary for this)There is a problem. I installed the mods, but when you start the game the world looks good on vr, but right in front of you comes a giant movie screen showing what you see in (2d). You can't play because this screen comes out and you don't I know how to remove it. Help

**Comment by oscarstg1** [comment]
helppp.i install the vr normal in gta v and run nice,but i put mods type Superman,o  ironman thanos,o other and happend this:(i install AddonPeds  and mod necesary for this)There is a problem. I installed the mods, but when you start the game the world looks good on vr, but right in front of you comes a giant movie screen showing what you see in (2d). You can't play because this screen comes out and you don't I know how to remove it. Help

**Comment by LukeRoss00** [comment]
I can't possibly guarantee compatibility with all other mods out there! If they work it's a good thing, if they don't there's nothing I can do
