### ISSUE TITLE
Launches oculus software instead of connected Vive Pro

### ISSUE THREAD

**Issue by mazina** [LukeRoss00/gta5-real-mod#102]
Hi, I am trying to launch GTA 5 with my Vive Pro Wireless, but I'm having problems.  It sounds like SteamVR support is a new feature, so perhaps this is a weird use case that it doesn't yet handle.

So, I have both a Quest and Vive wireless.  If the quest is plugged in, everything works great and I can successfully run your mod on the quest.  

But if I unplug it, quit the oculus app and launch the Vive wireless app running, it still thinks I want to play it on my Quest.  It launches the Oculus software, and, since the quest isn't plugged in, the video gets rendered to the screen and audio to the vive. If I try to launch it with either SteamVR or Viveport running, GTA launches as a desktop app with a warning about hurting my VR performance.  Whatever VR home app I have running at the time continues to run.  

Does having oculus software installed cause a conflict with the new SteamVR support?  Or am I wrong about SteamVR support?  It seemed like that was crossed off the to-do list at the end of the ReadMe.

Thanks for a cool mod, by the way.  From what I saw when I tested it on the quest, it looked like it's going to be really interesting.

**Comment by LukeRoss00** [comment]
That's because the Oculus service is always running, even when the Quest is unplugged. Try creating an empty file called `SteamVR.dev` in the `GTA5.exe` folder to force the mod to use SteamVR even when it detects the Oculus runtime

**Comment by mazina** [comment]
I ended up getting rid of the Vive Pro, but thanks for the workaround!
