### ISSUE TITLE
Black screen in VR - but menus work fine

### ISSUE THREAD

**Issue by matthiasmilli** [LukeRoss00/gta5-real-mod#104]
So i followed all the instructions - But when i play the game, all the loading screens are working, but the game itself is pure black so can't see anything. The map in the bottom right works, the pause menu works and so does the phone in the bottom left corner - but thats it. Any ideas what i'm missing?

**Comment by LukeRoss00** [comment]
Add the line `RVRLog = 2` at the end of your `RealVR.ini` and try launching the game again. Once the game has fully loaded and you have control of your character, wait a couple of seconds and then quit the game. At that point you should have a new `RVRLog.txt` file, please attach it here.

**Comment by matthiasmilli** [comment]
Hmm.. it created a 73mb file - and the limit is 10mb! Ooops

**Comment by LukeRoss00** [comment]
Just zip it, it's a text file so it compresses very well

**Comment by matthiasmilli** [comment]
[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4188233/RVRLog.zip)

**Comment by matthiasmilli** [comment]
Cheers!

**Comment by LukeRoss00** [comment]
So, your log file shows several problems. One of them is that the game appears to take more than 7 minutes to load, which is completely abnormal (usual time is about 1 minute). Another issue is that the graphics settings are all wrong, which means that something went south with the mod installation process (you probably didn't notice that the batch file was giving you errors).

I'd advise the following: uninstall the game and completely remove the folder where `GTA5.exe` is, together with all its subfolders. Then install the game again (without any other mods), and then follow the https://github.com/LukeRoss00/gta5-real-mod#quick-setup instructions from the start, but this time use the new `RealConfig.bat` that I added to Release 4 as Hotfix 4.2.

**Comment by matthiasmilli** [comment]
Thanks,i'll resinstall it and try again - although the 7 minute loading isn't right. It does only take about 1 minute so not sure what thats about!

Will try again...cheers

**Comment by Jesusavesouls** [comment]
Matt,I had this same issue today but not long loading times.I may of not unchecked steamvr theater active.I uninstalled the game and files to test the new alpha of grandtheftvr.com.Got it working only by a fresh install and removed to put back lukeross mod but only then got a menu but no hmd tracking and a black screen.Now doing a clean again install.These two devs mods need to work better together and interchanging.Some like the gamepad and others motion control.

**Comment by Jesusavesouls** [comment]
Fresh install and still black screen.Only menu but no hmd tracking.

**Comment by Jesusavesouls** [comment]
Problem solved:
I had the asi folder in the gta directory but nothing inside.No realvr.asi file inside the folder.I just added it again and its all fixed now.Praise Jesus!
