### ISSUE TITLE
Game very jittery when playing

### ISSUE THREAD

**Issue by bey108** [LukeRoss00/gta5-real-mod#105]
Whenever I look around in a cutscene or in the main game, the game jitters in a way that makes the game unplayable. I know this issue didn't happen before since I played it with a few mates before installing the mod.

**Comment by LukeRoss00** [comment]
> didn't happen before since I played it with a few mates before installing the mod

You mean that it doesn't jitter in 2D? Or with a previous release of my mod? Also, are you using a WMR headset?

**Comment by bey108** [comment]
I am using a WMR, I think that might be the issue. Also it didn’t happen
when I played 2D

**Comment by LukeRoss00** [comment]
Yep, unfortunately until Microsoft fix their driver to allow for alternate eye rendering the mod will only work in monoscopic mode on WMR headsets
