### ISSUE TITLE
Subtitles in the middle of the screen

### ISSUE THREAD

**Issue by Javierusan** [LukeRoss00/gta5-real-mod#107]
The first thing to say is that the mod is incredible!. Thank you for this!.
I wanted to ask if it is possible to change the height of the subtitles. As they are located far below, I miss any cutscenes of the game while I read. I tried to change the update.crf file with OpenIV, but it doesn't work for me.

Thank you.

**Comment by LukeRoss00** [comment]
What changes did you try with OpenIV?

**Comment by Javierusan** [comment]
> 
> 
> What changes did you try with OpenIV?

I try this mod:
https://es.gta5-mods.com/misc/bigger-subtitles
but don't work.

**Comment by LukeRoss00** [comment]
I guess it doesn't work because it's from 2015. But `frontend.xml` is indeed the file you want to edit if you want to move or resize HUD elements. I cannot give you much support on this, but there should be enough information on the web to get what you want

**Comment by Javierusan** [comment]
> 
> 
> I guess it doesn't work because it's from 2015. But `frontend.xml` is indeed the file you want to edit if you want to move or resize HUD elements. I cannot give you much support on this, but there should be enough information on the web to get what you want

Thank you, I have already solved it. The GTA launcher removed the changes from frontend.xml file. I have installed a mod to not use the launcher and now everything is fine. Thank you.
