### ISSUE TITLE
Gta5 VR issue floating screen.

### ISSUE THREAD

**Issue by spunkfire** [LukeRoss00/gta5-real-mod#108]
Floating screen in vr mode with wmr. Like a Reproduction of vr on a floating screen in game..

**Comment by LukeRoss00** [comment]
> make sure that "Use Desktop Game Theatre while SteamVR is active" is unchecked in the game properties page for Steam

**Comment by spunkfire** [comment]
Sorry i should have said,desktop theater was/is unchecked,also if I turn 180 in game the reproduction is behind me and out off my site fov,it's my temp workaround hehe.
Ps BIG TY for the mod i love it.

**Comment by LukeRoss00** [comment]
Add the line `RVRLog = 2` at the end of your `RealVR.ini` and try launching the game again. Once the game has fully loaded and you have control of your character, wait a couple of seconds and then quit the game. At that point you should have a new `RVRLog.txt` file, please attach it here (zip it if it's too big).

**Comment by spunkfire** [comment]
[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4202208/RVRLog.zip)

**Comment by LukeRoss00** [comment]
It looks like something has gone wrong with the mod installation. The .asi file is not even being loaded, and your graphics settings are messed up. Please also post your `asiloader.log` and `ScriptHookV.log` files

**Comment by spunkfire** [comment]
Hello again kudos for the mod it's all working great now with my wmr and quest.This labour of love on your behalf has been my best vr exp ever  bar non thanks for that,your a Rockstar.Kudos.

**Comment by LukeRoss00** [comment]
Thank you for the kind words!! A Rockstar, hehe :-D
