### ISSUE TITLE
In cutscenes when zoom is set to never, the occlusion culling only renders what the zoom sees and not what you do. If this could be fixed it would be much more immersive. Really enjoying it so far though regardless! :D

### ISSUE THREAD

**Issue by Gilderdale96** [LukeRoss00/gta5-real-mod#11]

**Comment by LukeRoss00** [comment]
Thanks! I guess that you mean frustum culling, not occlusion culling. Sadly the issue with frustum culling is not fixable at the moment, unless other modders have found a way to actually change the parameters of the cutscene camera.

**Comment by Gilderdale96** [comment]
Frustum, my bad. And it's not too intolerable when you keep your head still anyway, keep up the good work!
