### ISSUE TITLE
Configuration for PSVR

### ISSUE THREAD

**Issue by lucasndv** [LukeRoss00/gta5-real-mod#111]
How the best config for PSVR?
Its necessary "Trinus PSVR" , anyone know the bests config to use with de MOD?

Thanks

*Its possible to run with Trinus PSVR? it showing : "Script Hook V Error" CORE: exception.. "RealVR.asi" (0x00004FFE29FAA2E0), id 28. 

There's a few logs but the "RVRLog" its not creating

**Comment by cercata** [comment]
I though Trinus was dead and everyone used iVRy now ...

**Comment by lucasndv** [comment]
With iVRy working nice now!

Thanks!

*Remove GTA, install again from steam updated, install SteamVR, install iVRy.
Configure iVRy PSVR with 120frames.

**Comment by LukeRoss00** [comment]
Great info, thanks!
