### ISSUE TITLE
Status on HTC Vive Support.

### ISSUE THREAD

**Issue by Tone3Stark** [LukeRoss00/gta5-real-mod#112]
So I understand that HTC Vive support is not a thing yet. I gave your Git a quick once over so if I missed a post in regards to the Vive, please forgive me. Otherwise I would like to post this here to check and see if there may happen to be someone smarter than I that can update us on any VIVE progress? 
So following the directions as given by https://www.youtube.com/watch?v=VE4nxCUmPNE
This is as far as I get:

Running the GTA V  you do see the GTA logo popup on the VIVE in the theater mode for a few seconds then you see "Connecting to Game..." 
This however is where GTA V Crashed ssumedly and you are brought to the HTC VIVE Home.

If there are no foreseeable plans for this to get HTC Vive support, just let me know and I will move along but having Vive support for this would be amazing.

**Comment by LukeRoss00** [comment]
The mod should work correctly with the Vive. The tutorial you mentioned was good but is now outdated, please carefully follow the [Quick Setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) instructions that I provided.

**Comment by Tone3Stark** [comment]
Will do, thank uou.

**Comment by Tone3Stark** [comment]
Luke Sir I stand corrected, you are absolutely right.
You may want to add my experience to your next revision for those who may be using an HTC Vive. Not sure if is reproducible for someone on another system or not. Its hard to be scientific with only one setup here. Anyway, here is what I found out...
I stand corrected. I found that it does indeed work on the HTC Vive. The above game crash was due to me running STEAM VR to get my headset warmed-up before running the GTA5 Shortcut. 
Nope!, don't do that. Just close out of Steam VR totally before you run the GTA5 desktop shortcut. 
I am however getting some bad frame-rates much of the time. It tends to happen more if I'm moving in a car and turn my head. If I turn it slowly that its bearable but It didn't totally break the game immersion for me. 
Maybe there is some further tweaking or something that can be done? I'm not sure.
Either way, I played 4 hours straight last night before motion sickness got the best of me. Motion sickness isn't something that hits me hard but I was having such a BLAST, loving it! it was amazing!
The whole Head Aiming is brilliant. If anyone wants to hit me up on STEAM with some suggestions or just wants to talk tech then search me out "Tone3Stark"
My Game setup is as follows:
*HTC Vive (OG)
Acer Preditor Helios 300 (2019) Laptop w/1080p 144Hz display
* Intel Core i7-9750H processor
*Nvidia GeForce GTX 1660 Ti
*16GB of RAM

Thanks for the Mod Luke, you da man!

**Comment by LukeRoss00** [comment]
Great that you made it work!! Some frame drops are to be expected on a laptop (even a powerful one like yours), maybe you could try tweaking some of the game graphics settings to get the best performance
