### ISSUE TITLE
Windows Mixed Reality plus - double vision

### ISSUE THREAD

**Issue by kurrepa** [LukeRoss00/gta5-real-mod#113]
hello, I use Windows Mixed Reality plus and I have a 2070 super, i5 6400, 16 gb of ram, I have one and if I turn my head it looks all double, disable
Settings> Gamepad> Targeting Mode: Free Aim
Settings> Camera> Allow Independent Camera Modes: Off
Settings> Camera> First Person Head Bobbing: Off
Settings> Camera> First Person Third Person Cover: On
Settings> Camera> First Person Vehicle Hood: Off
I did everything, format my pc, install everything of 0, but the problem continues, I see everything as if it were double, just turning my head, if I close one eye the problem is the same. I also see two points when I aim with the guns.
The mod is amazing but I can't play it. What could I be doing wrong?
Thanks a lot

**Comment by LukeRoss00** [comment]
As explained in the release notes, WMR headsets still don't work correctly with the mod, because they don't support alternate eye rendering. The only way to use the mod with WMR for now is with monoscopic rendering (press `F11` and then `NUMPAD2`); of course it won't be stereo 3D.
