### ISSUE TITLE
Reprojection issues

### ISSUE THREAD

**Issue by Skeeva007** [LukeRoss00/gta5-real-mod#117]
Hello,

I picked medium settings for this game. The frame rate is good but the reprojection runs at 49% and makes me wanna barf. I'm not sure what to do to fix the reprojection issues. Any ideas? Any help would be appreciated []-)

I'm running the real VR mod on 
Valve Index
1080ti
I7 8700k
32GB RAM
1TB M.2 SSD Evo 960
Steam VR 1.9.16
Windows 10 Pro

**Comment by LukeRoss00** [comment]
> The frame rate is good but the reprojection runs at 49%

Which refresh frequency are you using on the Index? Also, what does the mod's own FPS counter say? You can activate it while in-game by pressing `F11` and then `N`
