### ISSUE TITLE
Sniper Rifle scope not working as intended in 3rd person mode

### ISSUE THREAD

**Issue by Akimya49** [LukeRoss00/gta5-real-mod#12]
Hello, it seems that i'm having an issue with the sniper rifle, I may have missed it from the readme, but i've tried to search for "snipe" "rifle" and "scope" and did not find anything about it. 

So it seems that if you are in 3rd person mod, with a gamepad or mouse/keyboard, if you aim with a sniper rifle, the head movement are only registered horizontaly for aiming. Wich is wired cause other weapons are working fine. 

You can "bypass" the issue by going in 1st person mode, then aim, and it will work well (maybe a bit fast at full zoom, but that's my taste).

Can this be fixed ? (Not really a big deal, just have to think to go in 1st person mod before sniping) 

Anyway, great job on this mod, this is truely amazing.

**Comment by LukeRoss00** [comment]
Thank you for the kind words! Unfortunately I cannot reproduce your problem here. Scoped rifles work equally well in 1st and 3rd person for me: looking up/down moves the aim as expected.

Perhaps it was just a temporary glitch? Did you try restarting the game, or even rebooting the system?

**Comment by Akimya49** [comment]
Yes tried multiple time. With 360 gamepad on and off at start. 

Same issue with mouse + keyboard

I don't have any other mods, this is a clean install from Rockstar launcher.

Happens only with the sniper rifle

Rebooting the system result with the same issue. Installing the mod again result in the same issue. 

Here is a short recording of it : https://youtu.be/rEUrJwaHx60

**Comment by LukeRoss00** [comment]
Oh okay, thanks for the video! So the aim actually moves up and down, it's the projectile trajectory that's wrong. I didn't get it from your previous comment, sorry.

I'll see if there's something I can do, in the meantime please use the workaround that you mentioned

**Comment by LukeRoss00** [comment]
I made a quick fix that seems to work for me, could you please test it on your side? Uncompress [this](https://github.com/LukeRoss00/gta5-real-mod/files/3776222/RealVR.zip) archive in the asi folder, replacing the previous `RealVR.asi` file

**Comment by Akimya49** [comment]
Looks ok to me :) 

I will continue my playthrough with this file, see if there is any issue with it and I will let you know. (if something happens i will roll back to the original file to see if the issue is due to the new file or not)

Thanks !

**Comment by dwwalcott** [comment]
I tested the updated RealVR.asi file last night (replayed the Merryweather Heist mission) and am pleased to report that it now works as expected!
