### ISSUE TITLE
Launches and runs great on first try, but crashes on each subsequent attempt.

### ISSUE THREAD

**Issue by LemonScentedAss** [LukeRoss00/gta5-real-mod#120]
When I first install the mod and run the batch file, the game launches and runs as usual, no complaints on that front. However, when I try to play again later, the game always crashes when I load into Story Mode. Any advice?

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/4241929/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/4241930/asiloader.log)
(When reading other issues I was told to provide these files)

**Comment by LukeRoss00** [comment]
> the game launches and runs as usual

Do you mean that the game runs in VR? Or flat? Does the batch file give you any errors?

**Comment by OmegaKiowa** [comment]
I myself am having the exact same issue, first time boot up was amazing, Vanilla GTA & GTAO are fine, the only mods im currently or have ever used is your VR mod, RagePluginHook, Gears Manual Transmission Mod.  The latter work fine together or standalone, when i try to boot just VR mod a rockstar error occurs shorting into singleplayer loading screen, ill provide logs once im home, thx o7

**Comment by LukeRoss00** [comment]
One likely cause is that something (the game, other mods, ...) changes the settings file while the game is running, so the next time you boot GTA V the graphics settings are invalid for the mod and crash the game.

You could try watching `Settings.xml` for changes, or running the batch file again, or marking the file as read-only.

**Comment by OmegaKiowa** [comment]
turns out it was commandline.txt that GTAV Mod Manager spit out that would overwrite the 1080x1080 resolution command you provided, i sorted it out.  I took your advice about setting.xml and applied it to the commanline.txt

**Comment by LukeRoss00** [comment]
That's very good to know, thanks!
