### ISSUE TITLE
Grand Theft Auto V exited unexpectedly

### ISSUE THREAD

**Issue by Bluscream** [LukeRoss00/gta5-real-mod#121]
![image](https://user-images.githubusercontent.com/3318223/75266429-9f079d80-57f2-11ea-90eb-943977f4bd9b.png)

Clean Vanilla Game ^

**Comment by brenbeep** [comment]
came here to post this same issue, tried everything. Crashes when story mode loads. Plz halp

**Comment by Bluscream** [comment]
I got my issue covered, it was cause by my mod manager symlinking the mod instead of copying it over. I'll keep this open for your issue tho

**Comment by LukeRoss00** [comment]
@Bluscream Glad that you solved your problem.

@brenbeep What messages does the batch file display when you run it?

**Comment by brenbeep** [comment]
Sorry for delay, my issue is fixed. I reinstalled on main HD again and edited user path in settings file. I don't know why it worked this time. Thanks a lot though, you're the man Luke
