### ISSUE TITLE
90FPS or is it 45FPS with the alternate rendering

### ISSUE THREAD

**Issue by rich0550** [LukeRoss00/gta5-real-mod#123]
Are most headsets capped at 90Hz?  If so that is the maximum the mod can play at correct?  And does that mean because the rendering is alternating that the frame rate is really half that?

So does that mean even with the next couple generations of cards the frame rate would still be limited to the effective frame rate of 45fps?

**Comment by LukeRoss00** [comment]
Not really: the Index for instance supports up to 144 Hz IIRC, and at that frequency alternate eye rendering looks basically perfect, so with the right headset and card, quality should definitely improve!

**Comment by rich0550** [comment]
oh no i see my viv pro only maxes out at 90Hz... sucks

**Comment by LukeRoss00** [comment]
I cannot advise upgrading from the Vive Pro to the Index just for my mod!! But if you intend to do it anyway, you'll get a better experience of course.

As I said everywhere on Reddit and in the README, playing GTA V in VR is more enjoyable if you have already developed your VR legs.
