### ISSUE TITLE
2080Ti, HTC Vive very laggy

### ISSUE THREAD

**Issue by ArekNoePhobia** [LukeRoss00/gta5-real-mod#125]
Hi Luke,

First of many thanks for all your hard work. 

Im running on MSI 2080Ti, Intel Core i7-9700K 3.6GHz, HTC Vive.

The game seems very laggy, unplayable. I havent checked the FPS counter yet, will do tonight F11 then "N".

I use the "high" preset for the batch file. I noticed the vid card name wasnt 2080Ti (it was 1080Ti which apparently is a default. Although with your Release 4 it apparently deosnt matter anymore?
 in the settings file after using the batch file, so i manually changed it. Also for HTC vive (90Hz) should I manually edit the settings file and change the refresh rate from 60 to 90?

**Comment by ArekNoePhobia** [comment]
Ok, so after further testing, went to the in-game menu, the refresh rate is greyed out and states auto, aspect ratio set to auto. The in-game FPS counter says A16-A17, while when the stereoscopic mode is off is showing M16. That means I am getting 8 frames per eye. On a 2080Ti. That is ridiculous.  Changing MSAA from off to 2x has no impact at all. Still A16-A17. I am so annoyed with this.

**Comment by LukeRoss00** [comment]
The most probable causes are: (1) an error with your settings, e.g. the batch file reported some errors that went unnoticed, or (2) conflicts with other mods or other software, like NVR that you mentioned in another thread.

With your system, on High settings, you should be getting a perfectly stable A90 while in Los Santos, and around A70-A80 in the desert where the view distance is huge.

**Comment by ArekNoePhobia** [comment]
Many thanks for your reply, I have used the batch file a few times, never any errors. Also manually checked the settings.xml file and everything looks absolutely fine. Also you mentioned it shoul work fine with NVR mod. I know I should be getting A90 and that is why it bothers me so much. :(

I put so much work into tweaking all the settings and installing other mods and cars.. but.. I will try to mod a clean copy with your mod first then add NVR, which then might break or interfere with your mod, since I had the "Are you sure you want to replace existing files". The NVR mod might or will replace some of your files if I do it the other way round. Damn..

**Comment by LukeRoss00** [comment]
Yeah, as I wrote in the README, I think the best approach is to install only my mod, and then after you're sure that everything is working correctly and the frame rate is good, carefully add other mods one by one to see which is the one that breaks stuff :-)

**Comment by ArekNoePhobia** [comment]
Ok sir! Will install your mod first and report back! I only want the NVR and a few cars is all.

**Comment by ArekNoePhobia** [comment]
So after you installed your own mod, while trying to install NVR did it not give you the " wanna replace files" pop up window. If it did, it didnt brake / interfere with your files?
