### ISSUE TITLE
Virtual Desktop 1.10 and Alternate Eye Rendering

### ISSUE THREAD

**Issue by OneToo** [LukeRoss00/gta5-real-mod#127]
I used your mod with Virtual Desktop 1.8 for streaming wirelessly from desktop and it was relatively stable.   I can use Link but wireless makes for a better experience for me.  The image quality is also better.   Since updating to 1.10, the image is unstable when looking left and right as if there is extreme ghosting.  

Virtual Desktop now has native support for Oculus games by way of their injector.   Is there a way to make your mod compatible with that new method?   Can I force oculus only mode?  I tried using -vrmode Oculus with no luck.   Everything is stable with Link btw.

**Comment by LukeRoss00** [comment]
I'm sorry but I don't have a way to test your configuration. You might have better luck asking on the Virtual Desktop Steam forums, ggodin (the developer) is very responsive and friendly.

**Comment by OneToo** [comment]
I'm bought up the issue on the Discord and ggodin said he would look into it but no eta.
