### ISSUE TITLE
Feature Request: Double-speed AER-mode

### ISSUE THREAD

**Issue by 60days** [LukeRoss00/gta5-real-mod#13]
Edit: changed this from a request to disable, to a request for double-speed, as I saw in another issue that the Oculus SDK won't accept >90fps frame submissions.

Although the readme (very fairly) states pretty much no hardware can run GTAV fast enough to provide both eyes at 90fps at reasonable settings, I think there is a narrow scenario where it might be possible, so would like to be able to disable AER and tweak settings to find it.

In particular, with the Rift S & Quest (via link) running at 80hz and 72hz the requirements drop a little (assuming the same rendering rez). This person gets close to the ~160hz needed with max settings and 3440x1440p: https://www.reddit.com/r/buildapcforme/comments/bxk0yd/gta_v_on_max_settings_at_144fps_on_144hz_1440p/eq8125r/
and some other benches with high settings: https://www.gamersnexus.net/images/media/2018/cpus/9900k/intel-9900k-review-gta-v-1440p.png

I think with a 9700k+ CPU, 2080ti+ GPU and low settings (with 1080p per-eye res) it would be possible to hit the required fps, albeit with regular drops in certain areas and situations (like rain). Very much an 'is-it-even-possible?' quest for overclockers/tinkerers, but eventually hardware should come around that will allow it comfortably too!

**Comment by LukeRoss00** [comment]
Unfortunately at the moment it isn't possible, due to this problem:

> GTA V, however, doesn't allow you to render the world twice without some time passing between frames (and without every moving object/NPC in the world animating)

Even if I wrote some special code to submit both eyes when they're ready in time, they wouldn't be aligned anyway

**Comment by 60days** [comment]
Thanks for the reply -I appreciate the support end of things is likely the least fun part of releasing something like this!

To clarify; at the moment theres a buffer somewhere that has both eyes. in any given 80hz tick (12.5ms) in the game, one eye is rendered on top of the old buffer (keeping the older eye content) and sent to oculus SDK for presentation, then the eye target is swapped. Hence each older eye has +11ms latency, and both eyes only update every other frame.

Would it be possible to attempt to render both eyes before sending to oculus SDK (so rendering 160hz in the engine) and submit a buffer with two 'new' eyes at 80hz? This would reduce the latency of the eye to 6.25m, but most significantly maintain a faster refresh for each individual eye (while acknowledging this is likely unfeasible for 95%+ of gaming PCs!).

**Comment by LukeRoss00** [comment]
The solution you are proposing is technically feasible. I'll think about it, although I cannot promise anything. It would mean a lot of changes to the code that would benefit perhaps 5% of the community, so I'm not sure it would be time well spent.

I'm also not convinced that the benchmark results you mentioned (which I take at face value) apply here. Without a doubt they were obtained using the standard FOV that GTA V uses in 2D, which is was smaller than the one needed for VR. I don't have a full graph of fps vs FOV, but I can tell you that on my system with high settings (1080x1080 base resolution) the game struggles to maintain a stable 90 fps in many areas, especially in the desert where the view distance is very high, and I have a Core i9-9900K and a GeForce GTX 1080 Ti. The 2080 Ti is only about 10-20% faster.

**Comment by skyworxx** [comment]
This is pretty much what I was asking (but much better worded). This feature is highly requested :)
