### ISSUE TITLE
Double image on one eye

### ISSUE THREAD

**Issue by conman588** [LukeRoss00/gta5-real-mod#131]
Thanks so much for all the hard work! Love the mod.

So I basically have the same issue as mentioned in #25 on which I already commented but I wasn’t sure if new comments in closed issues pop up.

I was wondering if there is any news on this issue? It seems like this effect is worse than the regular artifacts from alternate eye rendering, or do you think it is about the same in terms of comfort in your experience? Also by chance do you know if this affects all Rift S users or just some?
There seems to be almost no info on this topic on the web other than Flexy123 posting the issue on the oculus forum without reply. It would seem to me that this is a systematic error with alternate eye rendering on the Rift S that Oculus may fix if they actually recognize the problem. Love to hear your thoughts on all of this. Cheers

**Comment by LukeRoss00** [comment]
Unfortunately my reply at https://github.com/LukeRoss00/gta5-real-mod/issues/25#issuecomment-549131378 is still current and valid.

User reports seem to be unanimous: the higher the refresh frequency of the headset, the less visible the artifacts from AER. This is more or less independent from the actual frame rate (FPS) that the game can achieve.

So, the best headset in this regard is without doubt the Valve Index.

**Comment by conman588** [comment]
So this double image on eye effect is visible on all headsets but most prominent on the rift s due to the low fps? Would it be possible to increase the rendering frequency to let‘s say 160 hz with alternate eye rendering? That way you would still have a latency between left and right but you would have an actual 80 FPS on each eye without doubled frames. I get that this would be GPU intense but is it theoretically possible?

**Comment by LukeRoss00** [comment]
The headset refresh frequency in VR behaves like a hard v-sync that cannot be disabled, so no, it's not possible to render at a higher frequency.

If you're really bothered by the ghosting effect, you could try monoscopic mode (`F11` and then `NUMPAD2`). No ghosting, but also no stereoscopic 3D, which in practice means that nearby objects will appear larger than reality.

**Comment by conman588** [comment]
Yeah tried mono, which works fine. I still feel like this is a bug specific to the Rift S though, which goes beyond the regular aer artifacts and the low fps blur you suspected. 40 FPS on one eye is not ideal but it shouldn‘t be causing double images on one eye to the extent that it does. Just so we are on the same page, this also occurs if I take my phone or gun out and then turn my head. From #25 this only occurred on the rift s and not the rift or other HMDs, right? Do you know if this occurs just for a few rift s user or is it reproducible for all Rift S users? Sorry for being so pushy, I just feel like this is a Rift S bug they (Oculus, not you) should fix. Just trying to narrow down the issue and get Oculus to look at it. Thanks

**Comment by LukeRoss00** [comment]
I have no direct evidence that this should be a bug specific to the Rift S. In issue #25 several hypothesis were proposed, but the experiments didn't prove anything conclusively. Also, during the months since that conversation, _many_ users played the mod on the Rift S and were satisfied with the results.

So, my opinion at the moment is that the double image comes from a persistence illusion due to the strobing backlight, and the only improvement can be obtained from headsets that allow a higher strobing frequency. I don't think it's anything that Oculus can fix.

**Comment by sheepdestroyer** [comment]
I see the exact same thing on Valve Index, event when set and stable at 120fps ; that's not ideal
