### ISSUE TITLE
Luke what fps you getting ?

### ISSUE THREAD

**Issue by Jesusavesouls** [LukeRoss00/gta5-real-mod#137]
Gonna upgrade from a 1080 to a ti.See you built this on that.Would you share your fps on low,med and high ?

**Comment by LukeRoss00** [comment]
Please stop opening new issues for every single question that you have. This is not a discussion forum, and besides you're behaving like a spammer. As for the 1080, your money would probably be better spent upgrading your CPU which from #128 seems rather weak.
