### ISSUE TITLE
Getting: Error 23648

### ISSUE THREAD

**Issue by Totiusan** [LukeRoss00/gta5-real-mod#138]
Hello, I did try the update 4 and was working great.
Now After a month I went back and I cannot play the game anymore. If I uninstall everything it's ok, so it's not my pc. But when I put the files of the mod I get:

An error occurred while while updating gta v (app running):  
23648

Thanks in advance for any help.

**Comment by LukeRoss00** [comment]
Never seen that. Where does the error come from (Rockstar launcher, Steam, ...)?

**Comment by Totiusan** [comment]
I double click on desktop icon of GTA. That open both steam and rockstar
launcher. That o haver tô press again the GTA icon in the Rockstar
launcher, then it shows up the message I mentioned.

Il ven 20 mar 2020, 06:27 LukeRoss00 <notifications@github.com> ha scritto:

**Comment by LukeRoss00** [comment]
That's not normal. I have the Steam version of the game too, and the normal launch procedure is just to run the game from Steam (or from the desktop icon which does the same thing). There is no need to interact with the Rockstar launcher manually. I suspect that when you click on the GTA icon in the Rockstar launcher you are actually trying to run a second copy of the game (hence the error that says already running).

**Comment by Totiusan** [comment]
Hi Luke,
Thanks for your help. I found a fix, it's not elegant but it works. I close
steam, and I launch the game from the rockstar launcher. It opens steam
automatically and it works.
Again congratulations for the mod, is incredibly good. Only detail which
maybe could be improved is the smoothness when you rotate your head, even
if I recognize that your last update made a huge step in the right
direction.
Thanks again.

Il sab 21 mar 2020, 06:00 LukeRoss00 <notifications@github.com> ha scritto:
