### ISSUE TITLE
Scripthook no longer working. WORKING NOW-UPDATED: 4.4.20

### ISSUE THREAD

**Issue by OneToo** [LukeRoss00/gta5-real-mod#141]
Since the latest GTA update commenced, Scripthook is now reporting "FATAL: unknown game version".   Just giving you a heads up if you don't know already.  Hopefully, Scripthook team will update soon.

**Comment by mattmintun** [comment]
same here!

**Comment by tohakitubytsa** [comment]
after updating gta5 the game does not start please help me

**Comment by mattmintun** [comment]
This one isn't up to the developer. This is up to ScriptHook V updating to support the latest version.

**Comment by LukeRoss00** [comment]
Be patient! It usually takes a few days for Alexander Blade to update Script Hook V. In the meantime we can play Half-Life: Alyx :-)

**Comment by coru182** [comment]
In the meantime you can replace the gtav.exe with the old one. I kept a backup copy http://www.mediafire.com/file/obyzsh50xkvxnd0/GTA5.7z/file :)

**Comment by tohakitubytsa** [comment]
> Тем временем вы можете заменить gtav.ехе со старым одним. Я сохранил резервную копию http://www.mediafire.com/file/obyzsh50xkvxnd0/GTA5.7z/file :)

comon bro vr gta best..monitor noooooooo

**Comment by tohakitubytsa** [comment]
> Тем временем вы можете заменить gtav.ехе со старым одним. Я сохранил резервную копию http://www.mediafire.com/file/obyzsh50xkvxnd0/GTA5.7z/file :)
thank you bro you're the best let me give you a Donat

**Comment by coru182** [comment]
Np Glad to help

**Comment by conman588** [comment]
If you want to downgrade with Rockstar Launcher version (non-steam) you can use this open iv installer I found on youtube: https://bit.ly/3bMhBF7

**Comment by SoundstormVFX** [comment]
> 
> 
> In the meantime you can replace the gtav.exe with the old one. I kept a backup copy http://www.mediafire.com/file/obyzsh50xkvxnd0/GTA5.7z/file :)

Works perfectly! Thanks a lot!

**Comment by mikeglopez** [comment]
Any new fixes for this? Game won't start without update, game won't start without scripthook update, and mod is jerky with newest scripthook.

Thanks

**Comment by LukeRoss00** [comment]
@mikeglopez Update to Release 6 of the mod
