### ISSUE TITLE
Anyway to play this mod while having the steam verison?.. iro Scripthook V fatal error

### ISSUE THREAD

**Issue by Pent0s8008** [LukeRoss00/gta5-real-mod#144]
I know we will have to wait till Alexander updates Scripthook but how do I play this mod using an older version? I have the steam version of GTA V and would be very grateful if someone could let me know how to do this properly as I am new to using mods in any game, let alone GTA V.

**Comment by SoundstormVFX** [comment]
Just make a copy of your GTA V.exe then download and paste the version from this thread: https://github.com/LukeRoss00/gta5-real-mod/issues/141#issuecomment-607001464
