### ISSUE TITLE
 game crash during missions

### ISSUE THREAD

**Issue by guidosvr** [LukeRoss00/gta5-real-mod#147]
it is happening to me during some missions of franklin and michael which freezes the game when I get in the car. Do you know what the reason might be?

**Comment by LukeRoss00** [comment]
Game freezes are almost always caused by problems with your hardware (overheating, etc.). In all my time developing and using the mod I've never had the game freeze once, and there are no similar reports from other users

**Comment by guidosvr** [comment]
no I solved, I had downgraded badly not moving all the files. 
I have a performing PC, I use yes and no 1/3 of the power even putting everything to ultra
