### ISSUE TITLE
GTA V not utilizing GPU

### ISSUE THREAD

**Issue by LendroMendro** [LukeRoss00/gta5-real-mod#152]
I download the mod and after getting everything setup, I launched the game and everything was looking smooth. But when I loaded into story mode, the game ran at what looked like less than 1 fps. I looked at task manager and saw that my gpu was at 5%, so I'm assuming that's where the problem is. I don't know what's causing this, and I have a 2060 SUPER if that helps.

**Comment by LukeRoss00** [comment]
Task manager is not a reliable indicator of GPU usage, especially for GTA V. Most people use MSI Afterburner to gather statistics. That said, it's obvious that the game is not running correctly on your system. If you also have an integrated graphics card, try turning it off in the BIOS

**Comment by zxv2007** [comment]
> I download the mod and after getting everything setup, I launched the game and everything was looking smooth. But when I loaded into story mode, the game ran at what looked like less than 1 fps. I looked at task manager and saw that my gpu was at 5%, so I'm assuming that's where the problem is. I don't know what's causing this, and I have a 2060 SUPER if that helps.

I have the same problem with you. Have you ever tested the frame number? My GPU is also less than 5%, and the frame number is locked at 11-12 frames. There is no integrated graphics card and the driver is guaranteed to be the latest versio

**Comment by LendroMendro** [comment]
I had around 5 FPS, but my gpu was at 5% while being 60 C with no signs of changing, so I really don’t know what the problem is. I used MSI Afterburner this time and yet I was still getting weird reads.

**Comment by LendroMendro** [comment]
I just uninstalled the mod and verified my files and reinstalled it. To my surprise, that seemed to fix it and everything ran smoothly. I don’t know what was wrong before, but I’m glad I got it fixed.

**Comment by zxv2007** [comment]
> I just uninstalled the mod and verified my files and reinstalled it. To my surprise, that seemed to fix it and everything ran smoothly. I don’t know what was wrong before, but I’m glad I got it fixed.

Thank you. I'll try your way. I hope it works
