### ISSUE TITLE
Fault since Script hook Update

### ISSUE THREAD

**Issue by Gatmuss** [LukeRoss00/gta5-real-mod#154]
the game is running again with the new script hook , but it now runs almost like VorpX?
it warps slightly with head tracking like you are positioned a little too far back.
Also the driving 3rd person it stuttering around the car , but inside is almost impossible to see?
The cut scenes now have 2 Black vertical lines each side like boarders.
All setting maxed on 1080Ti

**Comment by LukeRoss00** [comment]
Nobody else has reported a similar issue, and I cannot reproduce it on my system (everything runs just fine after the update).

Likely something went wrong with your setup, I'd suggest verifying the files and possibly reinstalling the mod or even the game

**Comment by Gatmuss** [comment]
Thats strange? Ive fully downloaded from scratch 3 times , last one being only the VR Mod installed with only the scripthook being overwritten?
I will reset the Oculus and report back ;)

**Comment by Gatmuss** [comment]
I have noticed when setting up this time when running Realconfig.bat I get "the system can not find the path specified" message? 0 file(s)copied 1 file(s) copied?
![Untitled](https://user-images.githubusercontent.com/63306269/78886002-71e71580-7a55-11ea-837e-94379ac82cc1.jpg)
has that worked (1 file copied) or?..
thanks for your help btw , your mod is the reason am now playing single player GTA after having it for 5 years!

**Comment by Gatmuss** [comment]
Sorry I think its because Ive been playing different VR Games , and coming back to it the trackings is not the same , my fault.
Great Mod though , its the only reason I am playing GTA Single player in the 5 years I have had it!

**Comment by LukeRoss00** [comment]
No worries, thanks for your kind words!
