### ISSUE TITLE
Using GTA Vive mod problem/crash

### ISSUE THREAD

**Issue by KumpelKumplowski** [LukeRoss00/gta5-real-mod#155]
Hi
Your mod is functioning without problem but when I add GTA Vive mod (https://rly.sexy/project/gta-vive) for motion controllers support  I encounter a problem cause game crashes with this error "VR_InitInternal 2 cannot find input procedure in d3d11.dll library". I traced it to this article  https://github.com/ValveSoftware/openvr/issues/1221. Is there something you can do to fix this or is it GTA Vive mod doing something "wrong"? I have seen them both working together on this video https://www.youtube.com/watch?v=P1KxuAD5BEw&t=661s
Big thanks for making REAL Mod, it is awesome

**Comment by LukeRoss00** [comment]
I'm sorry but I cannot provide support for my mod being used together with others that also compete for access to SteamVR. It's an unstable configuration at best, and most likely it won't work at all.

If somebody actually managed to get the combo working correctly, you should ask them to provide some more details ;-)

**Comment by KumpelKumplowski** [comment]
Thanks for the answer. I understand the issue now and I think I messed up a bit cause those are to separate mods. I misunderstood video tutorial ;) I hope someday you will add Vive controllers support to your mod (maybe some side project or something ;) ). In REAL mod you really nailed FOV settings and other stuff. It is very comfortable to use. Just controllers missing for full immersion. Any way REAL Mod is awesome :)
