### ISSUE TITLE
Vr mod with FiveM or rage Multiplayer in the Future?

### ISSUE THREAD

**Issue by magyarfarkas** [LukeRoss00/gta5-real-mod#160]
I want to congratulate you on the mode! I love it! But my question... How can i use this Mode with FiveM or ragemp?
Minimum 300 hungarian vr Gamer waiting in my disvord to this solution😊 sorry for my english

**Comment by LukeRoss00** [comment]
As far as I know, for the moment no one has been able to make any form of multiplayer (official or unofficial) work in VR.
