### ISSUE TITLE
Right side of phone being chopped off?

### ISSUE THREAD

**Issue by dantharp** [LukeRoss00/gta5-real-mod#161]
I was just curious if anyone else was having the issue of the right side of the phone getting chopped off?
It's not a major issue....the phone still works fine and everything.  
It's just annoying that I can't read all of the texts or emails because maybe a fifth or sixth of the right side of the phone is just litterally cut off....like it won't fit on the screen or something.

**Comment by LukeRoss00** [comment]
That's a game bug due to the fact that GTA V doesn't support 1:1 aspect ratio properly. I fixed most of the HUD being chopped off at the sides, but not the phone. The problem should only happen in third person, though, and the mod is primarily focused on first person.

**Comment by dantharp** [comment]
Oh, OK.  Good to know.
Thanks!
Take care.
Dan
