### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by nicolasfromparis** [LukeRoss00/gta5-real-mod#162]
Hello, my GTA 5 game worked perfectly about 10 days ago until a new update arrive I guess. So basically I have deinstalled and reinstalled everything twice since then, I have followed exactly the same step as when I installed the game the first time when it worked and I still face the same issue. The problem is that the game launches normally but after the loading screen everything is black, I do not see anything except the radar at the bottom, the subtitles and I can access the pause menu, that's it. I can write each step of my set up if you want.As I told you I have bought this new PC gamer just for this GTA VR mode and I am quiet upset because GTA is my second life. I have even created a small GTA VR world on Recroom which took me around 200 hours to create.Please help me. :)

**Comment by LukeRoss00** [comment]
Hi, thanks for coming here from Reddit ;-) So, the first step in diagnosing what's wrong would be seeing your logs. Please attach here your `ScriptHookV.log` and `asiloader.log` files (do not simply copy them into the post as all formatting would be lost)

**Comment by nicolasfromparis** [comment]
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/4525352/asiloader.log)
[commandline.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4525353/commandline.txt)

**Comment by nicolasfromparis** [comment]
I cannot find the ScriptHookV.log

**Comment by LukeRoss00** [comment]
You seem to have a problem with your Script Hook V installation. `asiloader.log` reports that it cannot load "RealVR.asi", and `ScriptHookV.log` should always be present.

Let's see if your directory structure is correct. Open a command prompt, and enter the following commands:

```
cd C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V
dir /s > dir.txt
```

Then attach the resulting file `dir.txt` which will appear in the game folder.

**Comment by nicolasfromparis** [comment]
Here is it. Thank you for your time.
[dir.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4529299/dir.txt)

**Comment by LukeRoss00** [comment]
Okay, you shouldn't put the whole `ScriptHookV_1.0.1868.1.zip` archive in the game folder!! From it, extract the updated `ScriptHookV.dll` file and put _that_ in the folder :-)

**Comment by LukeRoss00** [comment]
In other words, you now have the `ScriptHookV.dll` file in a `bin` subfolder, where the game cannot find it. It should go in the main game folder instead

**Comment by nicolasfromparis** [comment]
OMG it works again!!! Thank you thank you so much!! I don't know why when I have unzipped the file it has created a new bin folder. Anyways it works now, so it's amawing, I'm gonna spend a wonderful weekend. Thank you so much. You are a legend.

**Comment by irin455** [comment]
Hey i am having the same issue with the black screen only showing the map box on the lower left of the screen. 
I extracted all files in the the GTA main directory  avoiding any sub directories then updated the hook files using the 3 files that included in the zip file  overriding the files in the main directory .. same issues ,,, it use to work with no problems .. Now just a Black screen with the map on the lower left of the screen, Any suggestions ?   

MY ScriptHookV.log FILE ATACTED  
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5610940/ScriptHookV.log)

**Comment by sonicyooth** [comment]
I too am having the same problem, have checked all the directory structures etc. Black screen, HUD and audio still work.

**Comment by irin455** [comment]
I really wish I can help assist you on fixing this issue but you are a
legend bro ..  I had The best VR experience because of you .. How much time
you think it’ll take to get this fixed ?  You think it’s cause may be from
a update from steam VR .. I’m thinking maybe we need to downgrade

**Comment by irin455** [comment]
OK so I found out how to fix this issue all you have to do is go to
 Program files (x86) /  Steamapps / Common Thank create a folder called
Grand Theft Auto V. Then extract The GTA real mod inside that folder.. Then
boom you all set

**Comment by irin455** [comment]
OK so I found out how to fix this issue all you have to do is go to
 Program files (x86) /  Steamapps / Common. Then create a folder called
Grand Theft Auto V. Then extract The GTA real mod inside that folder.. Then
boom you all set

**Comment by sonicyooth** [comment]
@irin455 Sorry, I don't understand. How is that any different from the normal installation instructions?

**Comment by LukeRoss00** [comment]
@sonicyooth Please read #239, make sure that you are updated to Release 6 of the mod and the latest Script Hook V version, and if that doesn't solve your problems just open a new issue

**Comment by irin455** [comment]
If you been putting the files on that folder then find your installation
folder other than the steamapp
 By right clicking on the game icon then selecting go to folder ... there
that’s the other installation folder put the files there as well ...

**Comment by rich0550** [comment]
Hi Hope not to late to post question here.

I have the blackscreen with map bottom.  Using win11, and HP Reverb (mixed reality) also have steam VR installed.

How do i fix? :) thank you.

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/8458066/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/8458067/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
@rich0550 Your issue is probably due to a known bug in the WMR driver for SteamVR. With the Reverb it's best to stick to OpenXR (see the [release notes](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r7) for details)

**Comment by rich0550** [comment]
Awesome thank you seems all to be working.   What role does steamVR play in this does it need to be installed?
would changing video card to 2080ti help in settings XML?  how about 2160x2160 for reverb?

**Comment by LukeRoss00** [comment]
SteamVR is not needed with my mods for WMR headsets. Changing the card in the settings has no influence whatsoever. For a full explanation on resolution, see the README starting from here: https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking

**Comment by rich0550** [comment]
would you recommend HP Reverb G1 or Oculus Quest 2?  Steam VR seems to like to start with it.. also is that a problem?

**Comment by LukeRoss00** [comment]
The Quest 2 is probably the best, but your Reverb G1 should give you acceptable quality too. I don't find the 120 Hz mode on the Quest 2 to be particularly helpful to be honest. Neither of the two headsets needs SteamVR however. What do you mean "seems to like to start with it"?

**Comment by rich0550** [comment]
The 120Hz is located in experimental the application apparently must support or ask for 120Hz.
https://www.youtube.com/watch?v=fryJ1aVXbDI
But when I do it the link USB goes from 90Hz to 72Hz again.

**Comment by rich0550** [comment]
I have to say the RDR2  mod you made makes the game look nearly movie quality,  for some reason looks allot nicer than GTAV maybe just a nicer looking game.  Would there be any advantage to turning up the device graphics options in oculus to 1.5 or 2.0?  Insane work my friend!

**Comment by rich0550** [comment]
sorry about multiple questions, does the trainer come with this mod? how do i get that going i read F4 but dint come up. thanksssd

**Comment by rich0550** [comment]
Insane work the RDR2 looks like a movie.  Its perfect.  Lots of blue screens but maybe its my setup.  Can GTA V VR be shut off and turned on like RDR2?  Sometimes its nice to toggle back to regular gameplay.

**Comment by chiefkeef99** [comment]
> I too am having the same problem, have checked all the directory structures etc. Black screen, HUD and audio still work.

Me too bro did you fix it ?
