### ISSUE TITLE
Display issue

### ISSUE THREAD

**Issue by willward12212** [LukeRoss00/gta5-real-mod#163]
Hi Luke, when i load into the game i get a theatre like vr view and when im in the game all i see is a panel showing the game blocked by another panel (like a big tv) and behind me is an upsidedown view of the vr game, very odd, i have unchecked the display setting in gta properties but i am sstuck on what to do next.
Many thanks 
Will

**Comment by LukeRoss00** [comment]
Did you make sure to turn off "Use Desktop Game Theatre while SteamVR is active"?

**Comment by willward12212** [comment]
Yes that is disabled

**Comment by willward12212** [comment]
My monitor displays the vr view well, the view from the head set itself is just completely glitched

**Comment by LukeRoss00** [comment]
Please provide details about your system configuration

**Comment by willward12212** [comment]
HTC vive
Amd 2600 
Nvidia gtx 970
Windows 10

**Comment by willward12212** [comment]
https://github.com/LukeRoss00/gta5-real-mod/issues/108

**Comment by willward12212** [comment]
this is similar to my issue

**Comment by LukeRoss00** [comment]
Yes, but the OP never explained what was wrong with his config. Do you get any errors when running the batch file?

**Comment by willward12212** [comment]
no errors, just loads the game in a sort of theatre environment, what do u mean running the batch file? sorry

**Comment by LukeRoss00** [comment]
https://github.com/LukeRoss00/gta5-real-mod#quick-setup

**Comment by willward12212** [comment]
no errors when running batch file

**Comment by willward12212** [comment]
The game and files assume nothing is wrong

**Comment by LukeRoss00** [comment]
OK, then please follow the directions that I gave in #108 and attach your log files

**Comment by willward12212** [comment]
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/4531339/asiloader.log)

**Comment by willward12212** [comment]
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/4531342/ScriptHookV.log)

**Comment by willward12212** [comment]
[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4531354/RVRLog.zip)

**Comment by LukeRoss00** [comment]
Your logs show that your game settings are not as the mod expects, which means that either you didn't run the batch file as explained in step 4 of the Quick Setup instructions, or the batch file failed to find your Documents folder. Or you tweaked the settings yourself afterwards. The logs also show that you're running other mods together with mine, which I do not recommend until you are sure that VR works.

Have you tried the batch file that I provided in hotfix 4.2?

**Comment by willward12212** [comment]
Ye I think the game restarted in safe mode changing a few settings

**Comment by willward12212** [comment]
last night i did a reinstall of gta ran the mod again, and now works fine along with racing wheel mod thank you very very much

**Comment by willward12212** [comment]
<3
