### ISSUE TITLE
It don' work

### ISSUE THREAD

**Issue by DankBong420** [LukeRoss00/gta5-real-mod#165]
So like I deleted all my mods from installation folder and only mod installed is this one. 

This mod also makes my game boot in a weird resolution, 1024 by something, looks so squished and bleh. 

Second of all it crashes all the time, but again, you say not to have other mods installed so I removed and tried again. Now it seems to crash again at loading up story mode and left eye is black and my monitor has a black square on the left side of the screen. 

I am using 1868.1 and found out that this mod may not be updated, but your releases tabs begs to differ. 

I use a Rift S and never had this issue a month ago when I tried, and that was before updating 1868.0 to 1868.1

Thanks in advance, I don't mean to sound too critical, you've done a fantastic job when I first tried, and really made it where I am the character lol. 
Stay safe, friend.

**Comment by DankBong420** [comment]
Also only mod I really use is menyoo trainer. 

That's about it, I don't do like graphic changes, like turning the blimp to the millennium falcon

**Comment by DankBong420** [comment]
GL.

**Comment by DankBong420** [comment]
Still don't work

**Comment by LukeRoss00** [comment]
v1.0.1868.1 works fine for everybody else. Just make sure that the updated Script Hook V is installed correctly and that the batch file doesn't report any errors when you configure the settings.

**Comment by DankBong420** [comment]
It don't report errors
Menyoo works fine for me on 1868.1 

And I always have latest scrip hook because I have Rockstar version and forced to update and can't downgrade like you can on Steam.

**Comment by LukeRoss00** [comment]
I can take a look at your logs if you wish. Follow the directions that I already gave many times in other issues (for example #108)

**Comment by DankBong420** [comment]
Ok I'll look and report back, thank you and I apologize if I came off rude or anything, my intentions weren't so 😦

**Comment by DankBong420** [comment]
Ok I found the instructions, but like when story mode loads, I don't have control, game frozen on screen and the "app stop working" box is in the middle of screen, invisible to the human eye but the cursor can see it. I haven't tried editing the files like I found in that issue, since it does this all the time with this. 

Could spend the 3hrs to redownload GTA

**Comment by LukeRoss00** [comment]
You should have some logs anyway, even if the game crashes right at the start. If you decide to download again, make sure that you completely remove the game folder beforehand, because files left over from previous (perhaps modded) installations are often the cause of problems like yours

**Comment by DankBong420** [comment]
Hi sorry for the long wait, I had other issues with my PC which resulted me in reinstalling Windows. 

I tried the log thing as soon as a fresh new installation of GTA 5, with the latest scripthook. 

This time I don't a black screen in one eye and a frozen game, GTA 5 now crashes back to Rockstar and Rockstar says game unexpectedly quit. 

I think I did the logs right, there was a line called Stereo = 1 and I put the code right under that, but here is my RVRLog file. 
(Creating hyperlinks not working for me)

https://drive.google.com/file/d/184dp61ghMpqbTWDHFdA0_UHrZpsrDzYm/view

**Comment by DankBong420** [comment]
Did I do anything wrong?

**Comment by DankBong420** [comment]
Because it still don' work

**Comment by LukeRoss00** [comment]
Your log file shows that you are running the game with graphics settings that are incompatible with the mod (e.g., 1920x1080 resolution, no frame scaling, ...). Did you even look at the README, specifically the [Quick Setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) part?

Since you have totally wrong settings, either you didn't even run my batch file that would fix them for you, or it reported errors that you didn't pay attention to.

**Comment by DankBong420** [comment]
Hi, I am so sorry for not replying, I really am. This covid shit man, now one of my family members got it, but seems like the road she's during now is the road to recovery, so I'm just hoping she doesn't make a wrong turn, y'kno?

I'm glad you're still doing well. I just want to say that using the bat file worked, and I can play the game. I couldn't really get a chance to test it until I got back home this morning. 

Just a couple of questions, is there a way I can see thru the scope of the guns? I know in FPS non VR, I press R-Stick and I can see thru it, I can't in VR. Also, is there a quick file or two I can edit the name so I can load up GTA v without having to reopen the file and see which files to delete? 

Again, I am so sorry if it felt like I neglected this issue.

**Comment by LukeRoss00** [comment]
Hi, very sorry for your family member, I hope that she'll get well soon.

In GTA V you look through scopes with the same command that you use for aiming (Left Trigger). In the game menus there are diagrams for all the bindings.

As for turning the mod on and off, see the nice work done by users in issue [63](https://github.com/LukeRoss00/gta5-real-mod/issues/63#issuecomment-587206495)
