### ISSUE TITLE
headbob on even when turned off (nausea inducing)

### ISSUE THREAD

**Issue by brentjohnston** [LukeRoss00/gta5-real-mod#168]
First off I want to thank luke for this incredible mod.  Just some feedback, I notice that headbob is on even if you turn it off in the menu.  In the crayfishery mod he found a way to disable it completely even with it disabled.

Some people think there is headbob in real life so it should be like this in VR, but I can tell you it creates aweful nausea in myself a lot of users (not everyone of course) I would love to see an option to remove it if possible since it makes it the game unplayable for me to play.

I actually have major issues in half life alyx with smooth locomotion for a similar reason. They did not smooth out collision of objects on the ground and the world is ultra detailed soo.. everytime you walk over an object the camera bounces up and down.. So I am forced to teleport in alyx. I've been using VR since the DK1 days and the only thing that gets me sick is headbob basically.

Edit: In additional another thing I noticed. On the index with the wider fov the characters left shoulder is always sort of noticeable in perhiperal vision. Especially if you are looking left or a 20 degree angle downwards (Even with recentering F11 then / )

**Comment by LukeRoss00** [comment]
I'm sorry but I have to close this issue as "won't fix" :-(

The residual head bobbing, the weird position of your character's body with the left side pushing forward (they call it the "combat stance"), and the fact that at times (especially indoors) your character seems to have the shakes like Tonya, are all aspects of Rockstar's first person implementation that we have to deal with. crayfishery did not correct them: he simply used a scripted camera to replace the actual gameplay camera (which unfortunately leads to a plethora of other issues) and removed the player's model. It's not something I'm willing to do, although if you're interested he has a pre-alpha version he's been working on for some time now.
