### ISSUE TITLE
Shake your head reset the view for Pimax Headset

### ISSUE THREAD

**Issue by Aikimaniak** [LukeRoss00/gta5-real-mod#169]
Hello Luke,
first of all let me thank you for your absolute piece of art. I have the time of my life playing GTA V this whole new way, it is just amazing!!!!
I am playing it with Other mods on, so with a force feedback wheel a Hotas and a bike controller, just sick!!!
Unfortunately I have a little issue maybe you can help me fix:
When I play with my Pimax (Steam VR supported headset, not oculus) the reset the view option by shaking your head doesn’t work. This option is absolutely hassle free it is so natural when I switch from my wheel to my hotas with rudder positon to just shake my head and continue flawlessly the gameplay...
It works fantastic with the oculus but not on the Pimax.
I really enjoy the purity of the image of the Pimax and it is hard to trade the large FOV of the Pimax for the Oculus...
Are you aware of this issue? Would it be hard to fix it? Can you tell me how I could do it or could you check that in your next update?
It would be lovely!!!

PS: I’ve managed to make your mod work with REDUX, it wasn’t easy but man!!!!!!! It is absolutely pure magic, the image is cristal clear and the depth of view is x10 time better, it was a pain in the S because I am new into the modding world but I found the file that makes your mod goes glitchy inside Redux and changed it... if you are interested you can message me privately...
Cheer from France
Daju

**Comment by LukeRoss00** [comment]
Great, thanks for the appreciation and I'm very glad that you're having so much fun with the mod!!

Unfortunately if the shake gesture doesn't work it's because the Pimax headset doesn't report its angular velocity to the SteamVR runtime. WMR systems have the same problem. It's one of those little-used functions that developers never seem to get around to implement.

**Comment by Aikimaniak** [comment]
Hi, 

Thanks again for this Marvel that you happened to come up with, 
I am telling I am really having the best VR experience and so far my best video game experience ever !!! I am 40! I almost started black and white...

Little suggestion if I may just to make things even greater.!!!

Do you think that it would be possible for you (or even for me if you explain me how) to add something in the ini file to set a keyboard hotkey assigned for the reset of the view for cases like this one...?

Let me explain why...
That way the player could hit the key any moment or even better ask voice attack to do it!!!! Wouldn’t it be great ???

« Please reset the view »
Then bimm 
View is reset!!!

Hope the idea could be a seed that you could grow !!! 

Your mod is fantastic 
Again,
You re my new hero!!!!!!!
Daju

**Comment by LukeRoss00** [comment]
You must have missed my edit, or I don't get what you're asking... The recentering is already bound to `NUMPAD /`

**Comment by Aikimaniak** [comment]
Whaou great news I will try my voice command and post it here just in case it could help anybody else...
This is just gigantic !!!

**Comment by Aikimaniak** [comment]
After setting things up with voice attack, I figured that the hotkey you are referring at doesn’t do anything. It is blank... or am I missing something?...
In your RealVR.ini file we can see 2 num pad related key but not the slash key numpad /...
Did I miss understand something?
I guess I have...

I am using a French keyboard do you thing there is something to do with the issue?

Thank for your kind help on this one!!!

**Comment by LukeRoss00** [comment]
The ini file only contains options you can set, while recentering is a command. Remember that to enable my mod's hotkeys you have to press `F11` (just once to enable them, not every time you use a hotkey)

**Comment by LukeRoss00** [comment]
If you prefer hotkeys to be active right from the start, that's what the `Hotkeys` option is for, just set it to `Hotkeys = 1` in the ini file

**Comment by LukeRoss00** [comment]
Did you fix your issue? For more information about the mod hotkeys, see https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys

**Comment by Aikimaniak** [comment]
Hi Luke,

Issue absolutely fixed and working!!!
So if anyone is interested the trick works!!!

In voice command you can add orders like :

Activate VR Menu - 
And then order 
Press F11
+ say VR Menu activated

Resest VR view
And then order
Press Numpad /
+ say VR view reset

Just beware not to open multiple sessions of voice attack like I accidentally did this would suck out 99% of your CPU workload (I play with a Ryzen 9 3900X)

It works like a charm but now that I have solved this issue (which is already great)

I figured out more inconveniences playing with the Pimax so I turned back to the Oculus which is way more hassle free...

Despite the graphics clarity and the large FOV I could list below some problems (seen in other posts elsewhere in the issue section of your github for some of them)

-When you enter or go out of a vehicle the 3D gets glitchy during the sit in/sit out animation only
-When you aim with a weapon in a vehicle  you got the 3D in each eye. (Similar to parallel retro projection issues seen in other games) that totally breaks the immersion and is the main reason I turned back to Occulus...
-When you aim on foot the aiming is unprecise (maybe the problem is also present on oculus,I think I saw somewhere that we may twitch something in a menu to set the left or right as dominant eye)

May I also report a glitch in one mission that I have played so far... (played with oculus when it happened)
Just after the yellow submarine mission Mickael, Trevor and Franklin ride an heli. You can then switch character to Franklin when you do Franklin is shooting with a sniper rifle, that particular part of the gameplay was glitchy it was impossible to get a good image ( I don’t know if someone else reported this issue or not) you could only see a flat image but impossible to get the scope if I remember well, anyway I finished the mission by switching back to the pilot)
Another one that may have no relation to the headset: the character in game is slightly turned on the right so that we can see ahead our left shoulder when on foot.
Same goes when you are in a vehicle you are not 100% facing the road seems slightly turned on the right I think like 5 degrees.

Overall the only thing missing now is a booster for the refresh rate, that would change the mod to a native VR game...

I know for having read elsewhere that you can’t put the mod on RDR2 due to the excessive demanding of the game itself...
What about older game like GTA4? Would love to re do the game many years after with this build in mod added... would be crazy too... (vorpx is to low quality...) 

Anyways absolutely blasting crazy experience you gave us with this mod, I know I am repeating myself but it is my best VR experience so far I told you... It completely blows away the other VR games right now, the whaou effect works everytime!!!

Hope you continue improving it!!!

Conclusion:
Pimax VR: Crazy graphics clarity, large FOV but some gameplay issues.
Oculus: Lower clarity (actually not so bad makes the textures a little less fake), smaller FOV, but absolutely hassle free thanks to you and your mod!!!

**Comment by mikededo4** [comment]
> You must have missed my edit, or I don't get what you're asking... The recentering is already bound to `NUMPAD /`

For some reason this doesn’t work for me.
