### ISSUE TITLE
How do I edit the cutscene FOV?

### ISSUE THREAD

**Issue by keem85** [LukeRoss00/gta5-real-mod#17]
I've read the documentation, but when I open settings.xml I can't find any pitch option or FOV option. Which option is supposed to be changed, and to what FOV should that option be set to?

**Comment by Akimya49** [comment]
You can press F11 in game, then "." on your numpad to have a larger FOV in cutscene but you will have a lot of visual glitches. 

See "Cutscenes" and "Advanced tweaking and hotkeys" in the readme section.

**Comment by keem85** [comment]
Thank you! Yeah, but I was wondering if I can set it permanently in the setting file. I'm usually launching the game from my living room and don't have my keyboard with me. And also a way so that I don't have to do that every time I launch the game :)

**Comment by LukeRoss00** [comment]
For the moment mod settings are not stored in a file, sorry

**Comment by keem85** [comment]
Actually it's not working. Nothing happens when I click the hotkeys... Any idea why?

**Comment by Gilderdale96** [comment]
> Actually it's not working. Nothing happens when I click the hotkeys... Any idea why?

Best way to test is to stand in the street, get your mobile phone out (in game). It should zoom in initially so press 'F11' (should hear a little beep sound), then press '.' Key 3 times. After 2 pressed the zoom will fix but it is not on the right setting as cut scenes will zoom, so press '.' A third time and zooming will no longer happen

**Comment by Gilderdale96** [comment]
Saving settings isn't really a big problem, on each startup you can quickly press F11 then '.' 3 times really quick and you're already initialized.

**Comment by keem85** [comment]
> Saving settings isn't really a big problem, on each startup you can quickly press F11 then '.' 3 times really quick and you're already initialized.

Yeah it's a big problem. Every time the game crashes or something happens, I'd have to get up from the bean bag, take off my headset, enter my computer room, recenter the view in the headset, pressing the hotkeys, taking off the headset again, going out to the lilving room, readjusting my bean bag, sit myself down, recenter the view again and then play. Only to do the same again the next time.

I will try your mobile trick when I get home

**Comment by Gilderdale96** [comment]
Yeah true having the settings save would be great. And a quick way to recenter is to shake your head left and right rapidly then stop.

**Comment by keem85** [comment]
> Yeah true having the settings save would be great. And a quick way to recenter is to shake your head left and right rapidly then stop.

Yeah but it's not a must have. I can live with the zoom :) I'd much more prefer for someone to solve the 80fps stereoscopic injection issue. That's actually the only thing I'm truly missing from this wonderful mod

**Comment by Gilderdale96** [comment]
What do you mean by that? It's unable to break 80fps? I haven't broke 80fps yet, currently running at around 60/70 with max settings with 1080x1080 res.

**Comment by keem85** [comment]
My game is running 80fps at all times, but this VR mod renders picture on each eye seperately, meaning it is reduced to less than 80fps constant on each eye. That's why you get the blurring effect. If/when they are able to render GTA 5 at full 80fps in to each eye (or anything above 40fps on each eye) we will be able to take advantage of the very much needed ASW function in Oculus runtime

**Comment by Gilderdale96** [comment]
I understand, that's why on monitor the view bounces from eye to eye, wouldn't it need to be 160 fps for it to view at 80fps then?

**Comment by keem85** [comment]
> > Actually it's not working. Nothing happens when I click the hotkeys... Any idea why?
> 
> Best way to test is to stand in the street, get your mobile phone out (in game). It should zoom in initially so press 'F11' (should hear a little beep sound), then press '.' Key 3 times. After 2 pressed the zoom will fix but it is not on the right setting as cut scenes will zoom, so press '.' A third time and zooming will no longer happen

Nothing happens when I do this.. I think these hotkeys are all wrong in the readme here. Author should have a look at the issue.

About the fps, yeah 160
