### ISSUE TITLE
Does anyone have ideal setting recommendations for Oculus Rift S?

### ISSUE THREAD

**Issue by dantharp** [LukeRoss00/gta5-real-mod#170]
I know this is a mod and not a port and from what I understand, this won't ever look as perfect as a full port would have looked, but it's still pretty damned amazing!  (IMHO)
However, there are definitely times when rotating fast or certain things are taking place in the game that the issue of a faint double-image crops up and it's a little bit of a bummer.
Nothing major....I'm certainly not complaining.
But it makes me wonder if I'm running my game at the most optimal settings.  I have a killer powerful rig so I'm not at all concerned about it not being able to handle it, but I'm not familiar with what settings should be set in the game to make it as good as it could possibly be for an Oculus Rift S.
Does anyone have any recommendations?
Thanks much in advance!   
Dan

**Comment by LukeRoss00** [comment]
The double image when things are moving laterally is normal (https://github.com/LukeRoss00/gta5-real-mod#faq). According to how powerful your rig is, you'll want to start from Low/Medium/High settings and then perhaps tweak something as explained in https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys
