### ISSUE TITLE
LA noire full game in first person vs VR case files

### ISSUE THREAD

**Issue by fuiop2000** [LukeRoss00/gta5-real-mod#172]
i think it would be really cool to see the full game of LA Noire in first person VR not just a few select case files as in the PS VR version...any hope here

L.A. Noire: The VR Case Files Trailer | PS VR
https://www.youtube.com/watch?v=dj3_NdIp21M

**Comment by LukeRoss00** [comment]
It would be great, but it's a completely different engine and apparently not very mod-friendly. Sorry but there's little hope that the full game will ever be converted to VR
