### ISSUE TITLE
Issues with windows mr device

### ISSUE THREAD

**Issue by fangzhangmnm** [LukeRoss00/gta5-real-mod#173]
I'm using windows mr device, and when I move my head I found the scene shattering. I feel it like sort of Motion Smoothing. however, I cannot turn off windows mr's Motion Smoothing in steam vr setting

**Comment by LukeRoss00** [comment]
Unfortunately it's a known issue, and I can't do anything until Microsoft and Valve come together to fix it. See https://www.reddit.com/r/WindowsMR/comments/gatwy0/can_i_run_gta_5_with_vr_mod_on_my_mr_helmet/ and https://www.reddit.com/r/WindowsMR/comments/f1yb7t/windows_mixed_reality_for_steamvr_beta_updated/fh9mqu0/.
