### ISSUE TITLE
Using Oculus Quest with Virtual Desktop and can only see the HUD in VR

### ISSUE THREAD

**Issue by BenCearlock** [LukeRoss00/gta5-real-mod#174]
I'm using the Oculus quest with virtualdesktop to run my VR. When I run the game, I only see the HUD elements and loading screens in VR. I can play the game in a small window on my desktop, but none of the HUD elements are showing, and it's not 3D or anything.

This is with the latest game release from May 14th, and the latest mod files.

I did have to delete the script hook V thing in order to get it to run because of a version mismatch error. That might be the issue.. 

... I found issue #162, so I'm pretty sure this is the script hook issue since I don't have that file.  Any ideas on when the update will come?

**Comment by LukeRoss00** [comment]
See #175, it usually takes a few days

**Comment by caffeinum** [comment]
@BenCearlock sorry for unrelated issue, but how did you launch it using Virtual Desktop? Did you use downgraded version of Virtual Desktop?

**Comment by chiefkeef99** [comment]
I Have the same issue on a gp76 leopard

on low graphics i have only my hud and in the background my screen is black ?!

Can someone help me please
