### ISSUE TITLE
Epic Games Store version working with modified ScriptHookV

### ISSUE THREAD

**Issue by LukeRoss00** [LukeRoss00/gta5-real-mod#175]
I'm creating this issue myself so hopefully it won't get duplicated a dozen times.

My mod relies on Alexander Blade's Script Hook V, which needs to be updated every time a new game version comes out. At the moment Script Hook V (http://www.dev-c.com/gtav/scripthookv/) supports up to version 1.0.1868.1, while Epic's version of the game is 1.0.1868.**4**. Alexander Blade usually releases his update in a matter of days, so be patient!

**Update: mod appears to be working correctly with modified Script Hook V, scroll down to https://github.com/LukeRoss00/gta5-real-mod/issues/175#issuecomment-633212165**

**Comment by matthewrbrooks** [comment]
Thanks Luke, I'm new to the VR mod and thought I had done something wrong!

**Comment by Ranimate** [comment]
Hey matthewrbrooks, I am new to the whole VR mods as well, I am of course blown away by it. I also tried modding and it failed, I am now re downloading from Epic and I will wait patiently for Luke's sorcery skills for an updated mod. 
Meanwhile, have you tried playing Alien: Isolation?

**Comment by LukeRoss00** [comment]
No need to download again if you want to remove the mod temporarily, just delete the files that you extracted from the .rar (see #63)

**Comment by Ranimate** [comment]
Too late, gulp... I am downloading (15 gig out of 94 already down) now, no biggie :)
Thank you Luke :)

**Comment by alistairgd** [comment]
Waiting for Alexander Blade's Script Hook V update...

**Comment by Ranimate** [comment]
> update...

You mean this one? : 
https://www.dropbox.com/s/bw5dql1ba47sy39/ScriptHookV_1.0.1868.1.zip?dl=0

Someone posted this on my comment in ‘Virtual Reality Oasis’ YouTube video that explains about Luke’s mod

**Comment by Ranimate** [comment]
Not sure if it works or not 🤷🏻‍♂️

**Comment by dantharp** [comment]
I suspect this is the same issue those of us who use modded versions of Skyrim/Fallout4 experience where the script extenders provided by silverlock.org are used, but they expect a specific version of the game EXE.  So, when Bethesda pushes out an update, you either have to wait for silverlick.org to update their script extender or go find an old version of the EXE (via something like steamdb.info).

ScriptHookV seems to be doing the same thing with regards to the version of the GTA5.exe.
In my case, I'm running version 1.0.1868.**1** of the GTA5.exe.  The current version of ScriptHookV (ScriptHookV_1.0.1868.**1**) is looking for that same version of the GTA5.exe so it won't work if someone has the free EPIC version of the game, which I _believe_ is 1.0.1868.**4**.  So you either need to wait until the ScriptHookV folks generate a new version that will work with version 1.0.1868.**4** _(and hopefully also 1.0.1868.**1**, so those of us with the slightly older version aren't cut out)_, or you could try getting ahold of a version 1.0.1868.**1** GTA5.exe and then use the ScriptHookV version 1.0.1868.**1** as well.  I'm betting that would work.

Here's my 1.0.1868.**1** version of the GTA5.exe (zipped up): 
https://www.dropbox.com/s/9l9azkffnsk32z6/GTA5.zip?dl=0

Here's my 1.0.1868.**1** version of the ScriptHookV mod:
https://www.dropbox.com/s/6v4b46kmjkxk6h0/ScriptHookV_1.0.1868.1.zip?dl=0

These two are functioning perfectly fine on my machine.
Understand, I have the 1.0.1868.**1** version I bought a while back, downloadeded from Rockstar....NOT the free version.  Again, I believe the free version is 1.0.1868.**4**.

Note: Backup/save your files.
Note: You're on your own after this.  I can't be responsible for what mixing EXEs on your machine will do.  I'm just offering a possible solution.  You'll need to be able to implement it and back out if needed.  (Sorry.)

Mr Ross: If me offering these files is some kind of violation of intellectual property rights or something like that and you need to delete this post, I perfectly understand.  I don't want anyone to get into trouble--especially me! :)

I'd be curious to find out if this works for you or not.
Good luck and enjoy!  :)

**Comment by Ranimate** [comment]
Thank you 🙏 I think the best and safest thing to do is to just wait. I’m going to

**Comment by MaximiliumM** [comment]
@dantharp Unfortunately, it didn't work. The .1 version doesn't know how to authenticate the game with the Epic store, so Social Club just says your game isn't activated.

It was worth trying anyway :P

**Comment by alistairgd** [comment]
> Not sure if it works or not 🤷🏻‍♂️

No that .1, we need .4 to work with the latest version of the game.

**Comment by cercata** [comment]
> My mod relies on Alexander Blade's Script Hook V, which needs to be updated every time a new game version comes out. At the moment Script Hook V (http://www.dev-c.com/gtav/scripthookv/) 

The site has been down for several days ... but it was ok when GTA offer launched on EGS, I wonder what's happening.

**Comment by TuskedSalmon366** [comment]
> you could try getting ahold of a version 1.0.1868.**1** GTA5.exe and then use the ScriptHookV version 1.0.1868.**1** as well. I'm betting that would work.

I tried using your attached GTAV.exe version 1.0.1868.1 by just replacing the exe and not worrying about the mod yet but it doesn't work.
From what I understand, either Epic Games has associated the 1.0.1868.4 version with my account *or* that the 1.0.1868.4 version has been associated with my Rockstar Social Club account, which I think is more likely. When I tried booting the game, it told me the game was unverified and asked me to input my verification code saying that this copy of the game would be permanently associated with my Rockstar Social Club account. 

Whatever it is, trying to use the 1.0.1868.1 version of the game causes an authentication error which won't allow you to play the game at all. Fortunately, this is easily fixed by just replacing the GTAV.exe version 1.0.1868.1 with my original GTAV.exe version 1.0.1868.4. When I did this, the game booted fine and normally as it had done before.

It looks like we'll just have to wait for the updated Scripthook - although as of this writing (May 19 at 12:09 pm) the site has been down every time I checked these last couple days so who knows when that'll be.

**Comment by Ranimate** [comment]
@TuskedSalmon366 , you are braver than me my friend :) I am worried to attempt the replacement of the EXE file for some reason, maybe because it connects online. I'd just wait until a working mod comes out, hopefully it'll be sooner then later...

**Comment by cmcosta81** [comment]
The 404 page for dev-c.com has been updated, they are moving to a new server. Hopefully the script hook update will be available soon.

**Comment by Ranimate** [comment]
Yassssss!!! That’s great! 🥳

**Comment by dantharp** [comment]
Possible workaround until ScriptHookV 1.0.1868.**4** is available????
https://youtu.be/EUxega_gRUQ

I haven't tried it myself (I have GTA 5 version 1.0.1868.1)....but the video looks like it might be worth a shot.

**Comment by irreal** [comment]
@dantharp  I just tried that workaround on my epic games (.4) version.

Not getting it to work.
Game always runs normally, nothing on the VR headset.

I tried placing the real mod files in the fivem plugins folder and alongside the gta5.exe, neither worked.

**Comment by dantharp** [comment]
Bummer.  :(
Sorry about that....thought maybe we might have gotten lucky.
Thanks for giving it a try and letting us know how it went.   :)

**Comment by Ranimate** [comment]
> @dantharp I just tried that workaround on my epic games (.4) version.
> 
> Not getting it to work.
> Game always runs normally, nothing on the VR headset.
> 
> I tried placing the real mod files in the fivem plugins folder and alongside the gta5.exe, neither worked.

Damn it... so close but yet...

**Comment by dantharp** [comment]
Yeah, sorry guys.  It was kind of a shot in the dark.  Thanks for trying it out though.  
Hopefully ScriptHookV 1.0.1868.4 will come out soon.

**Comment by NikPaso** [comment]
Hello guys. I downloaded the epic games version and would like to use it on Oculus rift s. It gave me the 'unrecognized version' error and I solved it by removing the hook script from the root folder and checking the game on the epic launcher. Now it starts, I see the menus, but when I enter the story mode I can see the map, the health and the various menus but I don't see the image in the VR. I have a black screen in the oculus but on the monitor I can see everything. Is it always a problem related to the version of the hook script to update or can I solve it? I hope you help me, thanks in the meantime!

**Comment by LukeRoss00** [comment]
The mod cannot function without Script Hook V. As you noticed, only the HUD will be visible in the headset.

**Comment by NikPaso** [comment]
Ok thanks for the reply. So I guess I understand that the only way is to wait for the updated hook script, right?

**Comment by Ranimate** [comment]
Hey guys, I just saw this online, it is using Luke's mod but there is a new .dll I have not yet tried this - 
https://stylistme.com/vr-ar-jeu-tuto/gta-5-vr-tuto-mod-real?fbclid=IwAR162GqfTY5ct2xtfMN6WTBG14bC33ynhkjw8B7iZQNd6Wcup3UfaeY3alM

**Comment by carlosgalveias** [comment]
That worked :)

**Comment by irreal** [comment]
Oh, I got so excited for a moment. With that new .dll it boots in vr mode, I enter story mode, I get the opening text about events taking place 9 years ago, then as soon as the first frame needs to render it crashes and exits the game :(

Any idea what the issue could be? The log files show nothing unusual, it logs that the .asi file was loaded and started, nothing about the crash.

**Comment by irreal** [comment]
So, pretty much out of despiration, I tried re-running the RealConfig.bat and choosing the LOW profile (Was on medium before). This solved the crash, but we are right back to 2 FPS, which sounds exactly like #184 

@carlosgalveias  when you say that worked, is it running well, good FPS ?

Looks like we're back to waiting for the new script hook version :(

**Comment by Ranimate** [comment]
@carlosgalveias Does it run smoothly for you? its loading in VR, yes but definitely not playable at all... it's what @irreal says, it runs at very low frame rate and not really working... :(

**Comment by carlosgalveias** [comment]
sorry guys, was too excited as it started without error...
FPS is like 2... terrible...

**Comment by Ranimate** [comment]
@carlosgalveias I knowwwww.... when I put the headset on and saw that it was running I was so excited! then... Boom... yuck!
I guess we will wait for Luke's magic

**Comment by alistairgd** [comment]
Can confirm, in does launch in VR but unplayable regardless of which quality setting is selected.

**Comment by KaynKyden** [comment]
Im not seeing the new scripthook. Im guessing it isnt released yet?

**Comment by cmcosta81** [comment]
> Im not seeing the new scripthook. Im guessing it isnt released yet?

The one people have tried using is actually openvhook and not quite compatible.

**Comment by LukeRoss00** [comment]
Excellent news, guys! A slightly modified version of Script Hook V surfaced on the web. I've just tried it with the Epic Games Store version and it appears to work perfectly. No frame rate issues, no version conflicts. It seems legit, as only a few bytes here and there were modified in offset tables and version checks, so it should be safe. I'm putting it here for convenience, although it's understandable if you want to wait for Alexander Blade's official update.

[ScriptHookV_1.0.1868.4.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4673315/ScriptHookV_1.0.1868.4.zip)

Do not use the FiveM "workaround" or the buggy OpenVHook with it. Just treat it as a replacement for the original Script Hook V and put the modified `ScriptHookV.dll` in `C:\Program Files\Epic Games\GTAV` or wherever you installed the Epic Games Store version of GTA V.

**Comment by irreal** [comment]
I tried out the modified file, and it works. The frame rate is normal, the game runs good.

I did loose sound, for some reason. I can hear the sound in the opening video and in the menu, but when the game loads up it's silent. I'll try later today to play with audio settings and report back.

Thanks @LukeRoss00 !

**Comment by LukeRoss00** [comment]
Audio works for me. Which headset are you using?

**Comment by irreal** [comment]
I was using the oculus virtual adapter. Switching to my headphones in windows audio settings works fine, just played the first couple of missions wearing both thr quest and my headphones on top :)

**Comment by Ranimate** [comment]
Works beautifully Luke, thank you so much!
The sound does come out of the speakers and not from the rift-s like I pointed it to but its all good, I use headphones anyway.
Again, thank you!!!

**Comment by ilancueto** [comment]
Working like a charm for me

**Comment by tahacan** [comment]
it works perfectly, i shouldnt get banned as long as i dont click online right? i think it connects to rockstar online services and stays connected even if you dont play online.but i hope its ok as long as you dont click online, right?

**Comment by Ranimate** [comment]
Just play Story mode and you will be fine

**Comment by rgferreira** [comment]
Just arrived here. It really works! I have to tweak some things since everything is quite stuttering (no hw issues here, running 2080ti). Any guide for tuning this awesome mod?

**Comment by jmke79** [comment]
> Excellent news, guys! A slightly modified version of Script Hook V surfaced on the web. I've just tried it with the Epic Games Store version and it appears to work perfectly. 

registered here to say SUPER! Thank you for taking the time to make this modification and clear instructions on how to use it.

Keep up the good work man, exploring virtual LA is quite a thing, even fictional :)

**Comment by alistairgd** [comment]
Awsome, the new file works a treat, game runs great iin VR now.

Now I need to go find some of these GFX mods I keep hearing about...

**Comment by cazman321** [comment]
Worked for me as well!  @huangt04 - check the new updated scripthook posted by LukeRoss.
Link to the forum for reference: https://gtaforums.com/topic/717612-v-scriptnative-documentation-and-research/page/39/?tab=comments#comment-1071221925

**Comment by huangt04** [comment]
@cazman321  thanks for remind me this. It tired this morning already and it is working for me. Though I find the double image and low refresh on quest with link (even with one eye closed) is too much for me. Tried to virtual desktop streaming it see if it get around that, but revive injector is blocking rockstar launcher, so I gave up.

**Comment by LukeRoss00** [comment]
@rgferreira Unfortunately, as I mentioned in the release notes, WMR headsets do not support alternate eye rendering and will work with my mod only in monoscopic mode. See https://www.reddit.com/r/WindowsMR/comments/ewtd6s/to_the_wmr_devs_please_solve_the_gta_vr_problem/ for some context.

**Comment by joakimraz** [comment]
Hey guys, I have the latest version from Epic and ScriptHookV_1.0.1868.4. The game start normally on the screen but only oculus home displays on the headset. Any help please.

**Comment by joakimraz** [comment]
> 
> 
> @dantharp I just tried that workaround on my epic games (.4) version.
> 
> Not getting it to work.
> **Game always runs normally, nothing on the VR headset.**
> 
> I tried placing the real mod files in the fivem plugins folder and alongside the gta5.exe, neither worked.

I have the same issue, what did you do to make it work?

**Comment by rgferreira** [comment]
> @rgferreira Unfortunately, as I mentioned in the release notes, WMR headsets do not support alternate eye rendering and will work with my mod only in monoscopic mode. See https://www.reddit.com/r/WindowsMR/comments/ewtd6s/to_the_wmr_devs_please_solve_the_gta_vr_problem/ for some context.

Thanks, perfectly understood. Is there any workaround for forcing run the mod through Revive, using the Oculus API?

**Comment by irreal** [comment]
> > @dantharp I just tried that workaround on my epic games (.4) version.
> > Not getting it to work.
> > **Game always runs normally, nothing on the VR headset.**
> > I tried placing the real mod files in the fivem plugins folder and alongside the gta5.exe, neither worked.
> 
> I have the same issue, what did you do to make it work?

This was when I was trying out a different script hook.

To get it to work, I removed all custom files from everywhere, then just pasted in the .rar archive from this repo, and then over that pasted the patched .dll that LukeRoss provided above.

The game then always starts in VR mode as expected.

**Comment by hornet900bcn** [comment]
At least (thxxxxx)..i have the gtav (epic store)working via link on my oxulus quest.. is there any chance that it works via Virtual Desktop?

**Comment by cmcosta81** [comment]
> Excellent news, guys! A slightly modified version of Script Hook V surfaced on the web. I've just tried it with the Epic Games Store version and it appears to work perfectly. No frame rate issues, no version conflicts. It seems legit, as only a few bytes here and there were modified in offset tables and version checks, so it should be safe. I'm putting it here for convenience, although it's understandable if you want to wait for Alexander Blade's official update.
> 
> [ScriptHookV_1.0.1868.4.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4673315/ScriptHookV_1.0.1868.4.zip)
> 
> Do not use the FiveM "workaround" or the buggy OpenVHook with it. Just treat it as a replacement for the original Script Hook V and put the modified `ScriptHookV.dll` in `C:\Program Files\Epic Games\GTAV` or wherever you installed the Epic Games Store version of GTA V.

Sorry, Luke, I couldn't figure out how to contact you directly. I was wondering if I could link directly to this modified ScriptHookV in an instructional blog. I know some people do not like having files directly linked, and prefer mirrors or not sharing at all.

**Comment by LukeRoss00** [comment]
You can certainly link directly. Please note that I am NOT the author of the modified ScriptHookV though, so perhaps it's best if you link to this forum post: https://gtaforums.com/topic/717612-v-scriptnative-documentation-and-research/page/39/?tab=comments#comment-1071221925

**Comment by LukeRoss00** [comment]
> > @rgferreira Unfortunately, as I mentioned in the release notes, WMR headsets do not support alternate eye rendering and will work with my mod only in monoscopic mode. See https://www.reddit.com/r/WindowsMR/comments/ewtd6s/to_the_wmr_devs_please_solve_the_gta_vr_problem/ for some context.
> 
> Thanks, perfectly understood. Is there any workaround for forcing run the mod through Revive, using the Oculus API? I unsuccessfully tried to inject the exe into Revive.

The API is not the problem. The issue is with Microsoft's driver for WMR, which does not allow for two independent eye poses.

**Comment by E66666666** [comment]
Please don't directly link the file, but prefer referring to the [GTAForums post](https://gtaforums.com/topic/717612-v-scriptnative-documentation-and-research/?do=findComment&comment=1071221925).

There's background info, the forums are publicly accessible and it'll help against creating an unsourced series of articles or videos that just refer to other unsourced posts.

**Comment by LukeRoss00** [comment]
@E66666666 Cheers ikt, thanks for stopping by! Love your mod :-)

**Comment by cmcosta81** [comment]
> At least (thxxxxx)..i have the gtav (epic store)working via link on my oxulus quest.. is there any chance that it works via Virtual Desktop?

Works great on my Oculus Rift, but I'm having trouble trying to get it running properly on my Quest. 

I'm using [Radeon Relive VR](https://github.com/GPUOpen-LibrariesAndSDKs/Radeon-ReLive-VR) (AMD's own baked in solution to virtual desktop and pc VR streaming). I can hear the game, and see the HUD in the headset, but the game only shows on the PC monitor, as was the issue with an earlier scripthookv on rift. The thing is, I did see 1 or 2 frames pop in the headset while moving around. I believe it could be some issue with refresh rate? Default is 72 Hz for Quest.

**Comment by AhmedHussein12** [comment]
Hey @LukeRoss00  Can you help me? I tried your modified scripthookv but everytime I enter the game, it crashes (As task manager states running,suspended,running,suspended,....)but no error messages appear just loading.... I tried removing the dotnet script files but that doesnt work ..

**Comment by NaimAhmed** [comment]
Anyone know if I can also install **Menyoo** as well and if so how would I go about installing it? Thanks

**Comment by NaimAhmed** [comment]
Also, I'm preparing for the first heist mission and anytime I go near the van to steal it the game keeps crashing but works perfectly fine elsewhere. I have even tried it on Safe mode but it still keeps crashing. Also, I don't think it's my PC as it seems to work perfectly fine (and I'm running on a gaming PC) and doesn't crash if I am not doing the mission. Does anyone have any idea for a possible fix? I know it's not related to ScriptHook but I don't know where to ask

**Comment by LiamVengeace** [comment]
So i'm completely new to modding and stuff, I downloaded the scripthook and put it with the gta files, all I wanna do is have cool mods on my GTAV, what else do I need to download? I used F4 to try and bring up the menu in game and It did nothing, someone please help?

**Comment by chienvegan** [comment]
So , i tried installing AddonPeds , but when i launch the game with the mod installed , the game crashes. How can i fix it?

**Comment by KaynKyden** [comment]
First off thank you for this mod and the additional files and all the work you and others have done. That said, I am having same issue as rgferreira in that I'm getting some graphical stuttering and jittering that's not cause by hardware being overworked. I feel like its something that could be adjusted somehow if I knew how to do this type of thing. Its still very much playable and great frame rate. I am more or less just putting this up in case someone else figure out how to fix this.

**Comment by cazman321** [comment]
The official Script Hook V has been updated: http://www.dev-c.com/gtav/scripthookv/

I'm guessing it's best to use that one instead of the RandomModder version, as I see a lot of differences between the two files.

**Comment by LukeRoss00** [comment]
Thanks for the heads-up! I updated the release notes and the README, so I'll be closing this issue now

**Comment by sparkey1523** [comment]
It's blurry for me.
