### ISSUE TITLE
Link not working

### ISSUE THREAD

**Issue by Thomas12356** [LukeRoss00/gta5-real-mod#177]
![image](https://user-images.githubusercontent.com/65460259/82125182-34844f00-979c-11ea-9d21-e21a827b40bf.png)

this link does not work ?

**Comment by LukeRoss00** [comment]
Works for me

**Comment by laurens94** [comment]
I also get a 404 error when opening the link, it seems the website is offline: https://downforeveryoneorjustme.com/dev-c.com

**Comment by laurens94** [comment]
I was able to download it from this page: https://gta5mod.net/gta-5-mods/tools/script-hook-v-native-trainer-1-0-1737-0/

**Comment by LukeRoss00** [comment]
[ScriptHookV_1.0.1868.1.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4640220/ScriptHookV_1.0.1868.1.zip)

**Comment by sneakyjoeru** [comment]
While it's down, can you please update manual step 3?

**Comment by LukeRoss00** [comment]
Done
