### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by benjoeben117** [LukeRoss00/gta5-real-mod#178]
Hey Man,
   The other night I had the mod working perfectly for my version on Steam. 
The only changes I made since is I decided to download Epic Game Launcher to download the free version of GTA V to be able to still play pancake mode.
The other change would be, last night while using other apps on my oculus (ran by link) my oculus pc program got an update.
Later last night I attempted  to Play GTA V in VR, now when I go to load it up. It loads just fine to the choice menu where you choose to play Story Mode, once it hit Story Mode it attempts to load it but freezes up, I get black in my headset and the PC says the program stopped working.

I haven't really tried any trouble shooting because I have no idea what I'm doing or what to look for. I really appreciate you reading my issue, thank you.

**Comment by LukeRoss00** [comment]
You probably just need to reapply the VR settings (run `RealConfig.bat` again). Crashes when loading Story Mode are usually caused by graphics settings which are incompatible with VR.

**Comment by benjoeben117** [comment]
You're Amazing! Thank you for the reply. I'll try the in a little bit.
