### ISSUE TITLE
black screen in hmd under linux via SteamPlay/Proton

### ISSUE THREAD

**Issue by frostworx** [LukeRoss00/gta5-real-mod#179]
hi,
there's probably not much you can do about it, but it might be interesting, that the mod "almost" works on linux via SteamPlay/Proton (5.0-7). The game starts and works normally, renders normally on the small desktop window, but the hmd is going black directly from the rockstar intro video, so the hmd is at least detected correctly. the two logs ScriptHookV.log asiloader.log don't look so bad as well
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/4639021/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/4639022/ScriptHookV.log)
probably the d3d11.dll from the mod has compatibility issues with the d3d11,dll from dxvk (shipped with proton).

**Comment by LukeRoss00** [comment]
I agree with your diagnosis; the logs look fine but probably the `d3d11.dll` file (which is a modified version of [3Dmigoto](https://github.com/bo3b/3Dmigoto)) is not compatible with Proton.

**Comment by frostworx** [comment]
thank you very much for your interest and mentioning 3Dmigoto (I recently stumbled over it while reading about helixmod, I guess I can forget that too for now :)). I hope your mod works one day under linux, the videos look amazing!

**Comment by LukeRoss00** [comment]
I googled this for a bit and couldn't find a definitive answer as to whether 3Dmigoto (or 3D Vision itself) is compatible with Proton/DXVK. Maybe there are some forums or Discord servers where you could ask?

In the meantime, if you like the genre, you could check out my older R.E.A.L. mod for No One Lives Forever 2 (https://github.com/LukeRoss00/nolf2-real-mod) which doesn't need 3Dmigoto!

**Comment by frostworx** [comment]
oh, thank you very much for trying to help! I googled as well and only found my own how to get sidebyside games working on linux vr reddit thread :)
thanks for pointing me to nolf2. A longer time ago I even tried it under linux and it did not work
(https://github.com/LukeRoss00/nolf2-real-mod/issues/5). It would be a great idea to try it again, but unfortunately ReVive doesn't work with proton as well.

**Comment by LukeRoss00** [comment]
Haha, sorry for not recognizing you! A pity that Revive still doesn't work on Proton... Have you considered installing Windows 10 in a dual boot config?

**Comment by frostworx** [comment]
hehe, no problem. I never used windows and never will because I don't like it, even if that means that I can't use every cool software and mod :)
Thank you for your friendly communication! :)

**Comment by frostworx** [comment]
Not that much changed, but for future reference it might be interesting that the apparently only problem is
`fixme:vrclient:ivrcompositor_submit_dxvk Unhandled flags 0x8`
which is written again and again while gta is running with black hmd.

The exact same error also occurs in other "official games" - f.e. L.A. Noire, where I opened a bug before once.
The dxvk author thinks that it is a Proton VR bridge error:
https://github.com/doitsujin/dxvk/issues/1538#issuecomment-605633584
but my Proton bug is unfortunately still ignored:
https://github.com/ValveSoftware/Proton/issues/3701
and at least publically vrclient_x64 didn't get much love the last 5 months:
https://github.com/ValveSoftware/Proton/commits/proton_5.0-next/vrclient_x64

Meanwhile I switched to amd (Radeon VII) and mesa, so at least it is not a nvidia(-driver) problem.

Somewhere in between I also played a bit with 3dmigoto
https://github.com/bo3b/3Dmigoto/issues/128
which works via proton, but for side-by-side, which was my goal it requires Nvidia 3D-Vision, so I'm out for now.

Still hoping Vk3DVision will work one day without 3D Vision, it was nice to see that you are/were active in the thread as well :)

**Comment by LukeRoss00** [comment]
Hey! Unfortunately the unhandled flag that the message reports (0x8) corresponds to `Submit_TextureWithPose`, which means that the main idea behind alternate eye rendering (using two different poses for the two eyes) is not supported by this code path.

As @doitsujin said, the missing implementation appears to be on Valve's side :-(

**Comment by frostworx** [comment]
Hi there,
thank you very much for having taking an extra look into it! With some luck they will fix it one day :)

**Comment by frostworx** [comment]
Hello! :)
Yesterday a new proton RC was released which fixed functionality for Assetto Corsa Competizione VR and also for Summer Funland (great game). Now I just tested your mod with gta, once with my previous settings using OpenXR and once with reconfiguring from scratch using OpenVR. With both attempts the game starts fine AND
all 2D graphics (title,menu, hud, map, settings) are shown correctly in the HMD, but the actual game graphics seem to consist of only 2 pixels (the color of the pixels react to the head movement, so I assume they are part of the real scenario).
The game window on the desktop draws correctly.

asiloader.log and ScriptHookV.log don't look very suspicious:

**asiloader.log**
```
// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\windows\system32\dinput8.dll" => 00007F86CE150000
API: "DirectInput8Create" => 00007F86CE164670
API: "DllCanUnloadNow" => 00007F86CE164F40
API: "DllGetClassObject" => 00007F86CE164F50
API: "DllRegisterServer" => 00007F86CE165320
API: "DllUnregisterServer" => 00007F86CE165340
LOADER: Loading *.asi plugins
ASI: Loading "Z:\media\ssdeam\SteamLibrary\steamapps\common\Grand Theft Auto V\asi\RealVR.asi"
     "RealVR.asi" => 00000000014D0000
LOADER: Finished loading *.asi plugins
```
and **ScriptHookV.log**
```
// GTA V SCRIPT HOOK (build Sep 12 2020, v1.0.2060.1)
//     (C) Alexander Blade 2015-2020
[17:17:07] INIT: Started
[17:17:07] INIT: Success, game version is VER_1_0_2060_1_STEAM
[17:17:07] INIT: Registering script 'RealVR.asi' (0x00000000014DA310)
[17:17:19] INIT: Pool 1 extended
[17:17:19] INIT: Pool 2 extended
[17:17:19] INIT: Pool 3 extended
[17:17:19] INIT: Pool 4 extended
[17:17:24] INIT: GtaThread collection size 189
[17:17:24] INIT: wnd proc 0x00000000FFFF002A
[17:17:24] INIT: IDXGISwapChain 0x00000000304AD960 (0x00000000302958B0)
[17:17:24] INIT: IDXGISwapChain set
[17:17:24] INIT: DX init started
[17:17:24] INIT: DX feature level B000
[17:17:24] INIT: DX init succeeded
[17:18:12] CORE: Requesting thread creation
[17:18:12] CORE: Creating threads
[17:18:12] CORE: Started control thread, id 31 active 1
[17:18:12] CORE: Started thread 'RealVR.asi' (0x00000000014DA310), id 32 active 1
[17:18:12] CORE: Launching main() for 'RealVR.asi' (0x00000000014DA310), id 32
```
The proton log has multiple
`vrclient:ivrcompositor_submit_dxvk Unhandled flags 0x8`
no idea if this related.

Do you maybe have a hint what I could try? TBH I never haven't played any GTA yet, but it is a bit mean to see that it is almost working in VR on linux :)

**Comment by LukeRoss00** [comment]
Unfortunately the fact that the compositor error is still present means that my [comment](https://github.com/LukeRoss00/gta5-real-mod/issues/179#issuecomment-669298666) of Aug 5 remains relevant: until Valve extends their implementation to cover `Submit_TextureWithPose`, the mod will not work

**Comment by frostworx** [comment]
Yeah, sorry for the noise, I just didn't want to delete my whole post, as at least **something** works now!
Thank you for your reply!
