### ISSUE TITLE
RDR2 support

### ISSUE THREAD

**Issue by cercata** [LukeRoss00/gta5-real-mod#18]
The MOD is perfect, I have some small issues, but I guess they are from the base game ;)

Can you make it work with Red Dead Redepmtion 2 ? In case ScriptHook gets released for RDR2 of course :)

**Comment by LukeRoss00** [comment]
Hahaha, we'll see! I certainly look forward to playing that game in VR too, but it's highly unlikely that this mod will work for RDR2, as the engine must have undergone major changes during these years

**Comment by cercata** [comment]
Mr Zelnick should hire you as supervisor for VR developments ... for example your methon for the HUD is better that what we see in Borderlands 2 VR.
And regarding LA Noire VR, OMG, on launch that was the most immersion thing I have seen, they have fixed some things on the PSVR version, I hope they bring that to PC soon. Have you played LA Noire VR ?

**Comment by LukeRoss00** [comment]
L.A. Noire was a fantastic game and I played it through twice, I still haven't found the time to play the VR version tbh!
