### ISSUE TITLE
Pimax Headset

### ISSUE THREAD

**Issue by emozio666** [LukeRoss00/gta5-real-mod#181]
Hi, I have 8K Plus, are Pimax helmets generally supported? In the game, I’m like in a sphere, there is no normal 3D, although everything is perfect on the Vive helmet.
Maybe advise some settings?

**Comment by LukeRoss00** [comment]
Pimax headsets are not supported for the moment, but some people managed to run the mod successfully in normal FOV (you should ask on their forums for more details as I don't have a Pimax headset myself)

**Comment by sneakyjoeru** [comment]
I'd like to learn if you manage to run it in pimax.
