### ISSUE TITLE
Image in either eye do not line up - Oculus CV1

### ISSUE THREAD

**Issue by sharkysi** [LukeRoss00/gta5-real-mod#183]
Hi (amazing mod by the way), I am having a problem with viewing things directly in front of me, the image in either eye do not seem to line up correctly and it is like I am seeing double.  When moving this can be very unsettling and even though I do not suffer from vr motion sickness it actually makes me feel a little disorientated.  Not sure if this may be the cause but I have to use an IPD of 70

**Comment by LukeRoss00** [comment]
These kinds of problems are usually caused by other conflicting mods, or wrong graphics settings. IPD is not a factor. Make sure that you don't have any other mod installed and that my batch file to configure the settings does not report any errors.

**Comment by sharkysi** [comment]
thanks, I'm running vanilla GTA (with scripthook and your mod only).  Have tried with all three settings options and they are all acting the same.  I would say may be its my hardware but i9 and 2080ti should be more than enough.  Should I do a complete re-install then?

**Comment by LukeRoss00** [comment]
When you say that the three graphics levels are all acting the same, do you mean that nothing changes when you select each of them, or do you mean that graphical quality changes (it is very visible, especially the resolution/pixelation) but the misalignment persists?

Also, have you tried switching to monoscopic mode (see https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys)?

**Comment by sharkysi** [comment]
The graphics quality does change but the misalignment remains. I haven’t tried monoscopic, I’ll give that a go

**Comment by sharkysi** [comment]
Just tried monoscopic mode and it solves the issue but is no longer in 3D. Tried monoscopic on your low, medium & high settings and all ok.  When playing on high settings in stereoscopic I get 90 frames a second so dont think it is that.  It is most obvious/exaggerated when a car or ped goes past your view from left to right (or vice versa) in front of your character

**Comment by sharkysi** [comment]
ah just seen the section in your FAQ about doubling, I'm guessing thats what I'm seeing?

**Comment by LukeRoss00** [comment]
Yes, that's what you're seeing. Most people (myself included) just get used to it, the brain filters it out after a while.

**Comment by sharkysi** [comment]
Hopefully my old brain will too 😀👍Thanks,  and again, great work
