### ISSUE TITLE
Super low FPS when use the epic store version with openvhook

### ISSUE THREAD

**Issue by huangt04** [LukeRoss00/gta5-real-mod#184]
I use this version
https://github.com/212antt/OpenVHook/releases

As people are reporting it works with other asi for epic store version.

When I launch with fresh install, the CPU is at 30% and I only get 1-2 fps. GPU utilization is 8%. I have 9900k and 1080ti.

The log show no error

// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\windows\system32\dinput8.dll" => 00007FFA9AFF0000
API: "DirectInput8Create" => 00007FFA9AFF8F80
API: "DllCanUnloadNow" => 00007FFA9B009EB0
API: "DllGetClassObject" => 00007FFA9B009F80
API: "DllRegisterServer" => 00007FFA9B013CB0
API: "DllUnregisterServer" => 00007FFA9B013F30
LOADER: Loading *.asi plugins
ASI: Loading "E:\EpicGame\GTAV\asi\RealVR.asi"
     "RealVR.asi" => 00007FFA9A9C0000
LOADER: Finished loading *.asi plugins

OpenHookV log also show no error
[13:23:04] Registering script 'RealVR.asi' (0x00007FFA9A9CA2E0)
[13:23:04] Initializing...
[13:23:05] Input hook attached: WndProc 0x00000000FFFF08BF
[13:23:05] Initializing ScriptEngine...
[13:23:08] Game version #-1
[13:23:08] Initializing Pools...
[13:23:09] Pool Init Finished
[13:23:09] Checking if game is ready...
[13:23:09] Game ready
[13:23:09] Registering script 'RealVR.asi' (0x00007FFA9A9CA2E0)
[13:23:09] Initialization finished
[13:23:49] Launching script RealVR.asi

The FPS is super good at loading screen and pause screen, but actual in game fps drop to 1-2 fps
I'm using oculus quest with link but get the same thing even when link is not connected. the small window on monitor also show 1-2 fps. In game shortcut F11 doesn't seems to working neither.

Is the OpenVHook not supported?

**Comment by LukeRoss00** [comment]
I developed the mod using Alexander Blade's Script Hook V and I cannot provide support for any other script loaders. If they work that's great, but if they don't you're on your own.

AB usually takes only a few days to update. Perhaps this time the wait might be a bit longer because he also happens to be moving servers for his website, but he always delivers :-)

**Comment by cazman321** [comment]
Hey huangt04, just wanted to say the same thing is happening to me too, so I think we'll just have to wait.  I'm using a Valve Index, so it's not just a Quest issue either.

**Comment by TuskedSalmon366** [comment]
Same issue on my Quest with link. I thought it was just me but I guess it's the script loader. We'll just have to wait for the Script Hook V. I wonder if we'll get an ETA or something? I can understand if he's moving servers for his website (good to know). It'd just be nice to hear something

**Comment by kyfounet** [comment]
same issue on my rift, everything launch super quickly (with epic games launcher), then once in the game after the loading screen the fps fall at 2 to 3 fps... Uninstalled the game, checked everything again, even that in the setting files it shows my graphic card as a 1080Ti when it is just a 1080 (I tried to edit that but nothing changed even in low sets). I guess we'll have to wait and see if updates come.

**Comment by LukeRoss00** [comment]
Solved in #175, please continue discussion there

**Comment by kyfounet** [comment]
ok, thanks a lot, the new script #175 works great! Your rock guys! Merci beaucoup!
