### ISSUE TITLE
Recentering gesture is not working

### ISSUE THREAD

**Issue by x-d-a-n** [LukeRoss00/gta5-real-mod#189]
I just got this VR mod working in the Epic Games version with the updated ScriptHookV that you posted in Issue #175 and it is fabulous, thank you so much for creating this!

Everything seems to be working well except for the recentering gesture with the headshake described here https://github.com/LukeRoss00/gta5-real-mod#recentering-your-view-in-vr

I can not, for the life of me, get this gesture to work and the only way that I have been able to get recentered is by hitting F11 to activate your keyboard shortcuts and then / on the numpad.

I'm not sure if this is related to it being the Epic Games version or something else with my setup. I'm using a Valve Index for the HMD.

**Comment by dantharp** [comment]
That head-shake thing works occasionally for me too...not always... maybe
(?) half the time.
I just press the Oculus button and choose to recenter the display (Oculus
Rift S).  Does the same thing, putting the map overlay back to where it
belongs.

**Comment by sheepdestroyer** [comment]
Same here : valve index, Epic Games version and ScriptHook posted in #175
Recentering is not working at all, never detected

**Comment by LukeRoss00** [comment]
The gesture used to work fine for Index users, and I very much doubt that the new Script Hook V could interfere with it (headshake is still detected normally on my CV1). Perhaps something has changed in recent versions of SteamVR that broke it.

I cannot test this myself, so let's hope that someone with an Index for whom the gesture still works sees this post and replies, so we can investigate further.

**Comment by skylinepower** [comment]
> The gesture used to work fine for Index users, and I very much doubt that the new Script Hook V could interfere with it (headshake is still detected normally on my CV1). Perhaps something has changed in recent versions of SteamVR that broke it.
> 
> I cannot test this myself, so let's hope that someone with an Index for whom the gesture still works sees this post and replies, so we can investigate further.

Hi Luke,1st time using a forum so I hope you see my question,amazing mod by the way,I desperately want to turn off the head shake recentering,it does it just when I look at something quickly and it’s very annoying,I’d rather just use R3 on controller as that does it anyway,is there something I can delete to remove the head shake gesture,thanks in advance mate

**Comment by LukeRoss00** [comment]
By "R3 on controller" do you mean pushing the right stick in? Because that is not equivalent to recentering. It's only a brief "look behind, look forward" that happens to reset the camera alignment when you're in a vehicle, and does not recenter the HUD in front of you.

**Comment by skylinepower** [comment]
Yes that’s right sorry,but I’m still happy to recenter the hud with the keybinding on the num pad you set,it’s just the headset look left and right briefly one I’d love to turn off,It keeps triggering when I don’t mean it to,Is that possible for me,thanks for the reply

**Comment by LukeRoss00** [comment]
Currently there is no easy way to disable the headshake detection. See https://github.com/LukeRoss00/gta5-real-mod/issues/70#issuecomment-581573122 for a workaround

**Comment by LukeRoss00** [comment]
Whoops, closed the issue by mistake

**Comment by skylinepower** [comment]
That’s perfect nice one,I’ll look into trying to do it,if not it’s still breathtakingly amazing to be in GTA in VR thanks to you,keep up the good work and thanks for replying to my questions
