### ISSUE TITLE
Broadcasting

### ISSUE THREAD

**Issue by DJBuZzCoLa** [LukeRoss00/gta5-real-mod#190]
Hey, I'm trying to broadcast the GTA VR mod but it's in a weird desktop screen so hard to capture. how do i change the resolution of how it looks on desktop

**Comment by dantharp** [comment]
I use OBS (https://obsproject.com/) for recording and streaming and that has the ability to capture the video display output of any EXE running.  IF you're using an Oculus headset, there's a utility called Oculus Mirror (https://developer.oculus.com/documentation/native/pc/dg-compositor-mirror/?locale=en_US) that basically simulates what you're seeing in the headset and that comes out nice.  I only have an Oculus (Rift S) so I'm not aware if there's a similar tool for other headsets...but it's worth a try.
