### ISSUE TITLE
No problem with anything

### ISSUE THREAD

**Issue by Jesusavesouls** [LukeRoss00/gta5-real-mod#191]
Actually it is running terrific.Would you be releasing anymore updates ? Possibly a super low setting for extreme FPS and a mega high for most detailed boast in res.My Pimax works in max fov normal which is fov 150 not the large at 170.In Pimax fov small its 130 and matches the 1080 x 1080 res settings.The normal Pimax fov of 150 I need to bump up the gta5 graphics res options to 1920 x 1200.So in every one of your mod’s settings of low,med and high none work with Pimax large fov of 170.But like I said in the fov normal 150 it only needs the gta5 graphics bump up res to work.Jesus loves you !

**Comment by LukeRoss00** [comment]
I have no further updates planned ATM. To increase the base window resolution beyond 1080x1080 (recommended only for GTX 1080 Ti and higher) see https://github.com/LukeRoss00/gta5-real-mod#even-more-advanced-resolution-tweaking

**Comment by Jesusavesouls** [comment]
Thanks for your work and all the updates to this point.You have added so
many options and the low to high setting range included is very fun to
tinker with looking for best res and fps.

**Comment by Jesusavesouls** [comment]
So I got a 2500  x 2500 in the gta5 command and your settings in
documents.I get the mega high maga file now.Thanks again
