### ISSUE TITLE
ENB / d3d11.dll conflicts

### ISSUE THREAD

**Issue by toxicFork** [LukeRoss00/gta5-real-mod#192]
Thank you for this awesome mod!

I'm trying to use the new version of NaturalVision which seems to have ENB as a dependency, and in its installation has a copy of d3d11.dll. The R.E.A.L. mod also uses d3d11.dll, so it seems I cannot have both working at the same time.

I have two questions:
- even if I managed to get it working, would ENB be compatible with this mod? (i.e. would it have similar issues to ReShade)?
- how do I get it working - is it possible for this mod to use something other than d3d11.dll, or if anyone knows, can I point ENB to use something other than d3d11.dll?

**Comment by E66666666** [comment]
You *could* try to have d3d11.dll chainloaded. ENBSeries.ini (or enblocal.ini, can't recall) allows for chainloading dlls.

**Comment by toxicFork** [comment]
I tried renaming the R.E.A.L. d3d11 to d3d11_other, and then tried this in ENB config:

```
[PROXY]
EnableProxyLibrary=true
InitProxyFunctions=false
ProxyLibrary=d3d11_other.dll
```

When I do this the game instantly crashes on launch unfortunately... 

I tried to have `InitProxyFunctions=true` and same thing. If I have `EnableProxyLibrary=true` only ENB loads and not `R.E.A.L.`.

**Comment by toxicFork** [comment]
Here is what happens if I don't have d3d11 loaded by proxy:
![image](https://user-images.githubusercontent.com/860717/83224534-21468b80-a16d-11ea-8006-899801cecac6.png)

**Comment by toxicFork** [comment]
After a bit of RE I found out the DLL is coming from https://github.com/bo3b/3Dmigoto - is it based off the master branch, or did you fork it? I think 3dmigoto may allow proxy dlls too from its side so I will do some research about that

**Comment by toxicFork** [comment]
I tried various combinations of 3Dmigoto proxying ENB, ENB proxying 3Dmigoto, them proxying each other, recursive proxying and so on, and all have resulted in either ENB not working, R.E.A.L. not working, or crashes 😓 I haven't tried all options so I will keep trying but going quite blind here.

I'd welcome any ideas from anyone :)

**Comment by LukeRoss00** [comment]
That's correct, the .dll is a custom build of 3Dmigoto. Unfortunately I don't think that 3Dmigoto and ENB can work together (at least I couldn't find any evidence of success in this direction over the web).

Even if you could somehow make the two libraries cooperate, there would be the issue that ENB is almost certainly working by intercepting the game main backbuffer (just like ReShade), which is not the one that gets sent to the VR headset. So you pay in frame rate to have a gorgeous game window on the monitor but see no graphical improvements in VR :-/

**Comment by LukeRoss00** [comment]
The old NaturalVision Remastered works beautifully with the R.E.A.L. mod if you don't use ReShade (see https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking). Can the new version be used without ENB?

**Comment by toxicFork** [comment]
Thanks for the answers, I am on NaturalVision Enhanced which seems to work without ENB. It looks pretty good, but with ENB it'd be even more spectacular :D

I sort of managed to get the DLL for ENB to load but it doesn't do anything graphically in VR unfortunately. I'm unsure if it's because it has not completely loaded, or because it may be using the backbuffer.

So I'll disable that to prevent performance loss.
