### ISSUE TITLE
Game Always Prompts to 'Hit Numpad 0 to Open VR Menu'

### ISSUE THREAD

**Issue by dakodeh** [LukeRoss00/gta5-real-mod#194]
Hi Luke, thanks so much for the work on this! I'm playing using an Xbox 360 controller, but everytime I start the game with the mod there's a message front and center on my screen that says something like 'Hit Numpad 0 to Open VR Menu'. 

Pressing the Numpad 0 key twice to toggle the menu on/off makes this message go away, but is there a way to disable it permanently? It's quite annoying, as my keyboard is usually far away from my VR playspace. Thanks for any help!

**Comment by LukeRoss00** [comment]
You must have followed some absurd tutorial on YouTube that made you install the mod from http://grandtheftvr.com/ together with mine. They're two different things and are not meant to work together. Please refer to the correct [setup instructions in my README](https://github.com/LukeRoss00/gta5-real-mod#quick-setup)

**Comment by dakodeh** [comment]
The only instructions I followed were from the root of your GitHub (this one on which I'm posting this), and I started from a clean install of GTA V. Does your mod not have a menu that comes up when you hit NumPad0 and allows for options like hitting 'Numpad 2' to swap rendering modes? that's what I'm talking about, and it definitely leaves a prompt on screen to hit Numpad0 until I open and close that menu at least once. I'll double check your readme, and I'll look to see there isn't some file leftover on my system from some long-abondoned attempt to run the grandtheftvr.com mod and will report back with my findings, but I'm unquestionably using your mod from this source.

**Comment by LukeRoss00** [comment]
Haha ok, but my mod doesn't have any on-screen menu. The Numpad 0 message definitely comes from the grandtheftvr mod, so yeah, the most likely explanation is that you have some leftover files from previous installations.

**Comment by dakodeh** [comment]
I'm so sorry, I'm an idiot. You're guidance on the grandtheftvr.com mod got me remembering that lonngggg ago I tried that mod. Apparently some of its source files were still in my GTA folder. I removed those and the problem went away entirely. My fault. Thanks for the great guidance and the awesome mod.

**Comment by LukeRoss00** [comment]
No problem, happy that you could fix your issue!
