### ISSUE TITLE
Epic Games Version and Oculus Setup

### ISSUE THREAD

**Issue by Kaleek76** [LukeRoss00/gta5-real-mod#195]
I'm confused as to how to get my Oculus headset to detect GTA V from the Epic Games store. I'm pretty sure I did everything right aside from the fact that it doesn't allow me to extract anything from the real mod download though I did put it in the GTA V area. I tried to click on the desktop area and it moves the in-game screen a little bit but I'm not necessarily seeing it in vr. I don't know if it's really an issue as it seems other people are pretty successful with the Epic Games version. Maybe there's something that I'm missing but i wouldn't know what it is.

**Comment by LukeRoss00** [comment]
> it doesn't allow me to extract anything from the real mod download though I did put it in the GTA V area

What do you mean by that?

**Comment by LukeRoss00** [comment]
Which extraction program are you using (WinRAR, 7-Zip, ...)?

**Comment by Kaleek76** [comment]
The mod file has .rar at the end. When I right click the mod in the Gta folder, I don't have the option to extract.

**Comment by Kaleek76** [comment]
Could that mean that it's already extracted?

**Comment by LukeRoss00** [comment]
No, it means that you don't have any extraction programs installed. You can use 7-Zip (https://www.7-zip.org/), it's good and free

**Comment by Kaleek76** [comment]
Ok so I downloaded it and converted the file and extracted it through the program. Is that what I was suppose to do? If so, how do I get the my oculus headset to show gta, or does it just automatically load in?

**Comment by LukeRoss00** [comment]
All the instructions are at https://github.com/LukeRoss00/gta5-real-mod#quick-setup

**Comment by Kaleek76** [comment]
oh ok thanks
