### ISSUE TITLE
I see a double screen in the viewfinder but it is not seen in VR.

### ISSUE THREAD

**Issue by cartmanrr86** [LukeRoss00/gta5-real-mod#197]
I have tried the mod in the rockstar version and in the Epic Games version and in both it happens exactly the same, the game starts in my oculus quest but it is not seen in VR, I see two screens in 2D, one bigger and another Smaller, any solution?.

**Comment by LukeRoss00** [comment]
Please double check that you followed the directions at https://github.com/LukeRoss00/gta5-real-mod#quick-setup exactly, especially point 4

**Comment by cartmanrr86** [comment]
I follow all the steps of the tutorial but I still see 2 screens in 2D, I will configure it to a friend and if it works on his PC, I do not understand where the problem may be.

**Comment by LukeRoss00** [comment]
Are you using the Link cable? Because Virtual Desktop does not work with my mod

**Comment by cartmanrr86** [comment]
yes i use link cable

**Comment by LukeRoss00** [comment]
What does the batch file report when you choose the settings? Any errors?

**Comment by cartmanrr86** [comment]
you mean the RealConfig file to select the quality L M H?

**Comment by cartmanrr86** [comment]
Now that I have noticed it says that the system cannot find the specified path. I have the game installed on a non-C: drive, can this have something to do with it?
