### ISSUE TITLE
Grand Theft Auto V exited unexpectedly... on game loading

### ISSUE THREAD

**Issue by qiangqiang101** [LukeRoss00/gta5-real-mod#198]
I have steam version GTA5 1.0.1868.1, Latest SHV 1.0.1868.4, Latest version of R.E.A.L, Removed all other mods, only Real mod running. No error on ScripthookV.log

Running on Lowest Settings, Tried Medium and High all crash

My Rig:
Intel Core i7 7th gen
32GB of RAM
Asus ROG Strix GTX1660 Ti GPU
Google Cardboard with iPhone 11 using iVRy

No problem on Startup screen, Loading screen, but crash on middle on loading.
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/4737318/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/4737319/asiloader.log)

https://www.youtube.com/watch?v=oQ273C4ZAnU&feature=youtu.be

**Comment by LukeRoss00** [comment]
Unfortunately I have no experience with iVRy. However [this](https://github.com/LukeRoss00/gta5-real-mod/issues/111#issuecomment-587860916) comment from a few months ago reported success... Perhaps you might find some more information posting on the iVRy forums?

**Comment by qiangqiang101** [comment]
well then keep this open until i found a solution

**Comment by LukeRoss00** [comment]
To what purpose? I have no additional info to give you
