### ISSUE TITLE
Can't Even Go In First Person

### ISSUE THREAD

**Issue by christheflappybird** [LukeRoss00/gta5-real-mod#2]
Rift Controllers Do Nothing And I'm Stuck In Third Person, Anyone Help Me Out?

**Comment by LukeRoss00** [comment]
This mod cannot be played with Touch controllers, as explained in the README. You'll need to use a normal gamepad or, if you prefer, keyboard and mouse.

**Comment by christheflappybird** [comment]
yeah but even when i go into first person i can still see my character in third person without a head

**Comment by Akimya49** [comment]
Did you try to reset the headset view? 

Stop moving your head, then you go left then right, like saying "no" with your head. It will reset the view and probably fix your issue.
