### ISSUE TITLE
Aliasing, Low GPU Usage - so-so framerate for my setup

### ISSUE THREAD

**Issue by cazman321** [LukeRoss00/gta5-real-mod#200]
Machine:
i5-4690K OC'd to 4.4Ghz on all cores (old I know)
1080Ti
16GB RAM 2400Mhz

GPU Usage around 45% max
CPU Usage 70's, spikes into the 80's or 90's

My goal was to try to get this to 120Hz on my Index...but some areas go down near 60FPS, and with my GPU only hitting around 45% max..I don't think that'll happen.  My CPU stays at like 70% usage, sometimes spikes to the 90's.   Wondering if this could be a CPU issue?

I've also tried this on my Quest + Link and get the same issues.

Here's some game recording with my settings, does this look right?  Doesn't seem as smooth looking as the other youtubers:

https://www.youtube.com/watch?v=QyVrYCqa_xs

You can see my settings are at 1080x1080 with 2.5X frame sampling.
No issues when using the bat file for settings.
I forgot if those settings were medium or high...but the same framerate issues/aliasing occur if I go to Low and change the res/multiplier.  I've even tried 600x600 with 2.0 multiplier, framerate isn't much better there either.

Also, here's the log you've asked people to grab.  See anything wrong?

[cAzRVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4740645/cAzRVRLog.zip)

Let me know if you think there's something wrong on my end, or if I should wait till I upgrade my CPU.  

Thanks!

**Comment by LukeRoss00** [comment]
Congrats for the excellent post! Most users don't bother to give any details about their configuration :-)

Sadly I don't have any miraculous answer for you. Nothing appears to be wrong from your log. Your CPU is most likely the bottleneck that prevents you from hitting higher frame rates, but even with a top-of-the-line CPU there are some areas (especially in the open country and the desert) where a 1080 Ti cannot sustain 120 fps with High settings.

To fight aliasing, please see https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking. Enabling MSAA 2x + TXAA should be very beneficial on your system, because it only adds load to the GPU without taxing the CPU.

What software are you using to measure GPU usage?

**Comment by cazman321** [comment]
Thanks.  All I did was search through your issues for solutions and noticed the questions you asked others.  :P

It's both good to know and disappointing that the log looked good.  I was hoping for a miraculous easy fix haha.

I did mess with MSAA + TAA and that did seem nice, I just figured my FPS would take a hit, but didn't compare much.  I'll go back to it.

I'm using MSI Afterburner.  I should have grabbed a screenshot of it in action, but never did.  I did notice that each core had the same usage spikes.  I never looked into that, but I figured each core would be doing different amounts of work.  I was wondering if maybe there's some different CPU settings for my processor through BIOS that could help for GTA specifically, but I doubt it.  No hyperthreading for me.

When I was messing around with 144Hz, there was a point in Franklin's house that I actually hit 144fps (basically moving around in front of a wall, lol), and it was so smooth and nice.  Guess I'll wait till next gen CPUs and 3080Ti to at least try to hit 120fps.

**Comment by LukeRoss00** [comment]
Yes, indoors the frame rate really soars :-P

We must be patient with the poor old GTA V: it's rendering so much more stuff than other games/engines, and that's part of what makes it so special. Games based on the Unreal engine very often use the trick of having enormously tall buildings right in your face to hide everything else in the world from view (thinking of the Bioshock and Dishonored series, for example, but even Half Life games are designed to always leverage walls to boost performance), whereas GTA V strives for realism and beauty.

The fact alone that we can guarantee a minimum of 60 fps in all game areas, with high graphics settings, is somewhat of a miracle. And unfortunately [no longer true](https://www.reddit.com/r/oculus/comments/dtwc9p/does_anything_think_red_dead_redemption_2_will/f71nl6t?utm_source=share&utm_medium=web2x) in Red Dead Redemption 2.

**Comment by cazman321** [comment]
I see.  Did you see the announcement of the re-re-release? Hopefully we see some solid optimizations...although we have to wait over a year (2H 2021).
