### ISSUE TITLE
what about rdr2

### ISSUE THREAD

**Issue by fuiop2000** [LukeRoss00/gta5-real-mod#203]
are you going to try rdr2 first person mod for vr

in an interview with Gameinformer Jake Kazdal (Space Channel 5, Galak-Z) said if you turn off head bob and increase the FoV it really blows your mind and he hints at a future Vr mod 

see this video at 15:00 when he describes it...includes Ryan Payton from MGS4 

Game Developers React To Red Dead Redemption II - Game Informer 
https://www.youtube.com/watch?v=uU21dtLATGw

**Comment by LukeRoss00** [comment]
Unfortunately there are technical reasons why it cannot be done now (see the discussion at https://www.reddit.com/r/oculus/comments/dtwc9p/does_anything_think_red_dead_redemption_2_will/). Perhaps in a few years!
