### ISSUE TITLE
reach out to rockstar

### ISSUE THREAD

**Issue by fuiop2000** [LukeRoss00/gta5-real-mod#204]
any chance you could reach out to rockstar by Telephone and get the adjustments done for you on their end for dx11/12 thing and the alternate eye,, since ur famous now...they could also do it themself for pointing the ship with REAL, just throw a hint.

“Please don’t take this to mean that the game is not “optimized” as kids on the forums love to say,” wrote Ross. “At 1080p, it pushes more than 80 fps (in other terms more than needed) while looking gorgeous.”

https://venturebeat.com/2019/11/16/dont-expect-a-red-dead-redemption-2-vr-mod-anytime-soon/

**Comment by LukeRoss00** [comment]
That's not the way corporations work. They don't put money and effort into something because you ask them nicely on the phone. They only do it if they expect tons of money in return, and with the PS5 announcement it's been made clear where R* expects to make lots of money :-)
