### ISSUE TITLE
Gun is stuck auto firing

### ISSUE THREAD

**Issue by Hawkeye3230** [LukeRoss00/gta5-real-mod#205]
After struggling to get rid of the shaky/vibrating view bug I finally managed to get the game started and it looked like it was running properly, at least visually. I am using the Oculus quest through virtual desktop and I have a PS4 controller that I am using that is connected to my headset via Bluetooth. For some reason my gun is stuck auto firing and the only way to stop shooting is to hold the left trigger. Has anyone else run into a similar issue?

**Comment by LukeRoss00** [comment]
Not that I know of. I do not modify controller inputs in any way... do you have other mods installed?

So now you have correct tracking when turning your head while using Virtual Desktop? Other users will be interested how you managed to do that. Is there a new version out? Or did you tweak something?
