### ISSUE TITLE
Path not found issue

### ISSUE THREAD

**Issue by Gunshine** [LukeRoss00/gta5-real-mod#206]
i used the hotfix to launch realconfig and when i choose my M settings it says
Error: "C:\Users\jonbo\OneDrive\Documents\Rockstar Games\GTA V\settings.xml" not found

i tried where you said to delete the user documents line and enter the desired path, not sure if im typing the right path or the command for the path properly for that matter. i would be very grateful to some help. ive been at this for a while.

**Comment by LukeRoss00** [comment]
Did you run the game at least once as explained at https://github.com/LukeRoss00/gta5-real-mod#quick-setup before launching the batch file?

**Comment by Gunshine** [comment]
I launched the game and changed the settings like the directions said. Then i exited the game. Was i supposed to launch the game to the opening mission?

I downloaded game,launched and changed setting,downloaded mod, replaced the script hook file, then executed the batch file.

when doing the script hook part, it says i need to install the asi loader. i am confused on this part and may not have done it right.
Do i take the dinput8.dll thats is with the script hook file and put it in the gtav folder?

**Comment by LukeRoss00** [comment]
> Was i supposed to launch the game to the opening mission?

No, that's not necessary.

> when doing the script hook part, it says i need to install the asi loader. i am confused on this part and may not have done it right. Do i take the dinput8.dll thats is with the script hook file and put it in the gtav folder?

No, just the `ScriptHookV.dll` file

**Comment by Gunshine** [comment]
so on the part where it says if you get the issue im having, it says if u moved or redirected the path to change it manually, i didn't move anything so i wouldn't think i need to do this, so i ran the 4.2 hot fix and it gave me the error in my first message.
i tried to put the path directly but im not familiar with writing paths on a computer and not sure if my attempt with it was correct

**Comment by Gunshine** [comment]
I GOT IT!
i wrote the destination path correctly and got it to launch. Thank you for your help.
