### ISSUE TITLE
Hey there

### ISSUE THREAD

**Issue by LlamaswithHands** [LukeRoss00/gta5-real-mod#210]
So I am loving the mod so much so far my buddy and I really want to use the coop mod with this but I require F9 in game to use it and pressing it  I can hear a menu pop up but nothing does for me. Other than that I have no issues. <3

**Comment by LukeRoss00** [comment]
I believe that the co-op mod doesn't work anymore. I haven't tried it myself, but no other users reported being able to activate it. See #146
