### ISSUE TITLE
Can't rin gta5 vr

### ISSUE THREAD

**Issue by Tgfkacalvinh0** [LukeRoss00/gta5-real-mod#216]
Hello there,

After installing gta 5 and the vr mod it says i'm running a non compatible version.
Even after adding the new scripthook.dll it stays the same. 
I've had it running a few months ago but had to uninstall it because my 1050ti couldn't run it properly, so after installing my rtx 2070 wanted to try it again bit to no avail.
Sincerely, 
Marinus

**Comment by LukeRoss00** [comment]
Please post an image of the error message that you get

**Comment by Tgfkacalvinh0** [comment]
I will do this tonight as i'm not at home right now

**Comment by Tgfkacalvinh0** [comment]
![IMG_20200707_212905](https://user-images.githubusercontent.com/67957320/86832837-fe2ac800-c098-11ea-84b4-ed7173f13bb8.jpg)

**Comment by Tgfkacalvinh0** [comment]
I get this on the steam version and on the epic games version both identical errors

**Comment by LukeRoss00** [comment]
As you can see from the error message, you have an old build of Script Hook V that only supports up to game version 1.0.1868.**0** (Steam is now at 1.0.1868.**1**, Epic at 1.0.1868.**4**). Which release of my mod did you download? You should be using the latest, Release 5

**Comment by Tgfkacalvinh0** [comment]
Hello,

Sorry for the bother, didn't download the new version thank you for your
fast response.
Gonna play the hell out of it now really thank you for making this great
mod.

Op di 7 jul. 2020 22:52 schreef LukeRoss00 <notifications@github.com>:

**Comment by LukeRoss00** [comment]
No problem, have fun!
