### ISSUE TITLE
black screen 

### ISSUE THREAD

**Issue by easytigerman72** [LukeRoss00/gta5-real-mod#217]
Hi wonder if you can help i have done the game load and the mod then when i start the game it loads up then i get a black screen then it turns off the game

**Comment by LukeRoss00** [comment]
Please post your `asiloader.log` and `ScriptHookV.log` files

**Comment by easytigerman72** [comment]
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/4885313/ScriptHookV.log)

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/4885316/asiloader.log)

**Comment by LukeRoss00** [comment]
The game is crashing very early: it's not even loading the mod script.

Using Notepad, add the line `RVRLog = 2` to the end of your `RealVR.ini` file, save it and try to start the game again. You should find an `RVRLog.txt` file in the game folder, please post it here too

**Comment by easytigerman72** [comment]
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4885491/RVRLog.txt)

**Comment by LukeRoss00** [comment]
As you can see from the log, there is a problem with your SteamVR setup:

```
ERROR: VR_Init() failed with error code 110 ("Installation path could not be located (110)")
```

Which headset do you have? Can you run other SteamVR games without problems?

A quick Google search turns up this page: https://steamcommunity.com/app/250820/discussions/0/361787186435224667/

**Comment by LukeRoss00** [comment]
Another day, another hit-and-run issue that I'm closing because the person asking for help cannot be bothered to reply

**Comment by easytigerman72** [comment]
Hi sorry not been in touch not been to well but thanks again for ur help I managed to sort it now
