### ISSUE TITLE
v5 still jittery with Oculus Quest via Virtual Desktop.

### ISSUE THREAD

**Issue by OneToo** [LukeRoss00/gta5-real-mod#218]
I just wanted to let you know that I tried your newest update with Oculus Quest and it's still jittery when I move my head.  The only mode that worked with OpenVR.  The game launched but did not show up in the Quest when using OpenXR or Oculus mode.   

I tried using '-vrmode oculus' launch parameters and I also tried launching the game from the Virtual Desktop Streamer.   I am using the latest SteamVR beta.

**Comment by LukeRoss00** [comment]
Virtual Desktop is probably not yet compatible with OpenXR. I have no idea if that's even in the works.

I made no changes to the OpenVR renderer from r4 to r5, so what you observed is expected.
