### ISSUE TITLE
Re-centre gesture not working on WMR / OpenXR 1909 Rockstar version (1868.1)

### ISSUE THREAD

**Issue by jcooray** [LukeRoss00/gta5-real-mod#219]
**Environment:**
Windows 10 1909
GTA V version: 1868.1 (Rockstar Store)
R.E.A.L. mod version 5
HMD: HP Reverb (WMR)
Xbox One Elite Gamepad connected via Xbox Wireless Adapter for Win 10
Intel 8700 (non-k) / DDR4 16GB 3200MHz / 2080Ti
Running with high settings (realconfig.bat)

**Behaviour:** 

- Game displaying in HMD with no issues (stereoscopic 3D, no judder) as resolved by OpenXR rendering.
- Head tracking appears to be 1:1 when viewing the environment (i.e. appears to have no issues)
- No issues with gamepad / movement / button mappings
- Playing with first person view
- Any roomscale movement (e.g. movement of game chair) offsets camera as expected, but re-centering gesture appears to have NO visible effect.

**Detailed description of re-centering gestures attempted:**

- head rotation from right to left shoulder and vice versa returning to centre at both at "normal" headshake speed and "slow motion"
- head rotation from right shoulder to centre (normal and slow-motion speed)
- head rotation from left shoulder to centre (normal and slow-motion speed)

**Comment by LukeRoss00** [comment]
Wonderful issue description, thanks! Are you a professional game tester? :-D

Slow-motion speed will never work (the gesture recognition is triggered only when the side-side rotation velocity exceeds a certain threshold). For the same reason, wide movements, i.e. shoulder to shoulder as you mentioned, will not work because it's too hard to do them at speed. Try with a sharper shake that is much narrower in breadth but faster, almost like a twitch: look ahead for a second or two without moving too much, then rapidly twitch to the right and forward again.

Once you get it working, you'll start getting a feeling for it. It shouldn't be painful at all BTW!

**Comment by jcooray** [comment]
I'm a technical product owner - I write test-driven requirements for software engineers.  I know how to write a proper bug report tho :-)

AAAANND... after all that rigour with the bug report I got impatient and uninstalled the Rockstar version and started to download the Epic version!!

(tbh there was another issue with losing all audio upon reloading a save from the game menu.. I'm sure I've tried installing grandtheftvr and several versions of your mod at some point, so I lost confidence in the integrity of the install.)

.. thanks for the advice with the gesture, I'll try that twitch gesture.  If still no dice I'll report back

btw I'm glad WMR juddering led to OpenXR implementation.... hopefully this will put OpenXR on the map for other devs...  Surprised this is working on OpenXR as well as it does - there's been no real world usage to provide feedback to MS devs until now!

**Comment by lazyletucce** [comment]
` there was another issue with losing all audio upon reloading a save from the game menu..`

either give the focus to the game by clicking in the window or lift the helmet and fold it down

**Comment by LukeRoss00** [comment]
For the audio issue, just set 'Mute Audio On Focus Loss' to 'Off' in the Audio options page of the game!

**Comment by xnkn** [comment]
same issue here, HMD is Odyssey+, tried everything, no response.

**Comment by jcooray** [comment]
**So I can confirm that it was user error with the re-centreing gesture**.  A flick of the head... pause... and the screen flicks off for the briefest of moments... and then flicks on.. centred!..  I will say there is a knack to it tho... but that's the case with gestures anyway so no complaints from me.

And thnx for the advice re the muting audio!  Again... user error, but (if the game menu option not muting audio on losing focus is not already in the readme **and** Reddit post then it may be worth adding it?

**Comment by LukeRoss00** [comment]
Great that you got it working in the end, and thanks for posting back!

@xnkn Does it work for you too with more of a "twitching" movement? Can I close the issue?

**Comment by xnkn** [comment]
I've managed to make it work, it's a bit tricky yeah haha
