### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by cristo860** [LukeRoss00/gta5-real-mod#222]
I get into the game and i can see menus, map and such, but the actual game is just black

**Comment by ODEH67** [comment]
there is already an opened thread about black screen u can check it out maybe it would be helpful 👇

https://github.com/LukeRoss00/gta5-real-mod/issues/217

**Comment by cristo860** [comment]
> there is already an opened thread about black screen u can check it out maybe it would be helpful
> 
> #217

I saw it but its not the same, my game runs fine, i can see it running in my pc, it just doesnt show on my oculus

**Comment by ODEH67** [comment]
what is your pc specs?

**Comment by cristo860** [comment]
i5 9300h, gtx 1650, 8gb ram 2400hz.
Its not the best in the world but it runs vr fine and gta v at 1440p

**Comment by ODEH67** [comment]
it is a laptop i guess right? is this problem came with the new release 5.0 of the mod or is it your first time installing it?

more details would be helpfull

**Comment by cristo860** [comment]
Yes its a laptop,lenovo l340. My setup is with a oculus quest running virtual desktop on the epic games gta v. This is the first time i try to run the game with the mod, i had no previous mods installed and only played a little bit of the story (trevor with brain on sole). I also replaced the scripthook as it says in the tutorial

**Comment by ODEH67** [comment]
i did not try the epic version yet, but as soon as i finish testing the steam version i will test the epic one and then we will see how it will go,,, generally it works with it @jcooray worked for him but with a WMR headset and a High end PC ... i would suggest as a beginning the LOW settings method,, the commandline.txt , settings.txt

> I also replaced the scripthook as it says in the tutorial

actually when u install the mod there should be no impact or replacement with other files in the game,,

did u do this as well?  the quick setup ... 2nd point 
https://github.com/LukeRoss00/gta5-real-mod

**Comment by cristo860** [comment]
Yes i did, maybe i deleted the wrong file? I replaced the scripthook.dll for the one on alexander blades page, was i not supposed to do that? I got an error when both were present on the file. Maybe i need an asi loader like alexander states on his site?

**Comment by ODEH67** [comment]
simply use the scripthook.dll that comes with the mod , it works ,,, 
I did not use any asi loader for this just simply extract the mod zip folder into your game folder and u r good to go... 
like I said I i will try the epic version soon to see if it will bring that black screen

**Comment by LukeRoss00** [comment]
> My setup is with a oculus quest running virtual desktop

Virtual Desktop still does not support alternate eye rendering, despite many users asking for it. You will need to use the Link cable if you want to run the mod on your Quest

**Comment by ODEH67** [comment]
after the last update of oculus quest for oculus link, the charging cable supports the link and it should be no problem.. 👍

https://www.youtube.com/watch?v=O3CfhT7qXxI&t=227s

**Comment by cristo860** [comment]
Ohh so all i need to do is run it with cable instead of virtual desktop? Nice, il give it a try and let you guys know if that solves it.

**Comment by cristo860** [comment]
Okay so, same problem when plugged in, 
![IMG_20200713_151233](https://user-images.githubusercontent.com/68204429/87308465-90a8ec80-c51b-11ea-86bc-53bb88f67c9d.jpg)
![IMG_20200713_151325](https://user-images.githubusercontent.com/68204429/87308470-9272b000-c51b-11ea-989f-cd744137a21e.jpg) and yes when i put first person mode same stuff happens, i just see black, i see the UI but not the game

**Comment by cristo860** [comment]
GUYS! I figured it out, a .dll file was missing, i prob deleted it by mistake, now everything works perfectly! Thanks to all who took their time to help me

**Comment by ODEH67** [comment]
so it worked by using the link method and not by the virtual desktop right

> GUYS! I figured it out, a .dll file was missing, i prob deleted it by mistake, now everything works perfectly! Thanks to all who took their time to help me

**Comment by cristo860** [comment]
Yes it did, i can try with virtual desktop later and post my results, i need a break now, fps while flying is really bad and now im really dizzy

**Comment by ODEH67** [comment]
in advance settings in game settings **turn the high detail streaming while flying off**, that make less details for the view but more fps to gain

**Comment by cristo860** [comment]
> in advance settings in game settings **turn the high detail streaming while flying off**, that make less details for the view but more fps to gain
> 
> > fps while flying

Yess thanks dude that made it way better, it was making me really dizzy when dropping under 30

**Comment by xnkn** [comment]
I'm having this exact same issue right now, I found out that the dinput8 file that comes with the mod makes my game crash around 5-10 minutes in-game, then I looked up the issue on Youtube and I got a solution, using the dinput8 file that's in my System32 folder makes my game run smoothly without the REAL mod BUT it gives me this problem when I install the mod :/  (black screen, icons don't make sense).
![20200714_042107_MixedReality](https://user-images.githubusercontent.com/48757089/87411120-db168180-c58c-11ea-83a7-04661a911afa.jpg)

So I'm either stuck with my game crashing every 10 minutes or my game straight up on a black screen. T_T

**Comment by ODEH67** [comment]
which headset do u have? pc specs? and which resolution did u choose from the mod H, M, L?

**Comment by cristo860** [comment]
> I'm having this exact same issue right now, I found out that the dinput8 file that comes with the mod makes my game crash around 5-10 minutes in-game, then I looked up the issue on Youtube and I got a solution, using the dinput8 file that's in my System32 folder makes my game run smoothly without the REAL mod BUT it gives me this problem when I install the mod :/ (black screen, icons don't make sense).
> ![20200714_042107_MixedReality](https://user-images.githubusercontent.com/48757089/87411120-db168180-c58c-11ea-83a7-04661a911afa.jpg)
> 
> So I'm either stuck with my game crashing every 10 minutes or my game straight up on a black screen. T_T

Hey dude, unpack the mod on a separate folder and check that all the files are present, i dont remember wich file was missing for me but it fixed the issue you describe

**Comment by xnkn** [comment]
Headset is Odyssey+
Ryzen 5 3600
GTX 1060 6 GB
16 GB RAM
W10
Game version is 1.0.1868.1
RealConfig settings: M
things I already tried:
-Verify files
-Clean install
-Downloaded the Epic version just to try a different launcher, same crashes.

I just tried extracting the files in a folder to see if I was missing a file or something but everything checks out.
I gotta say I have two game versions, a Rockstar launcher version and a pirated one that I use purely for intense modding, the pirated version does not seem to be crashing for some reason, only the legit ones have the dinput8 file issue

**Comment by ODEH67** [comment]
> RealConfig settings: M

I would suggest the L config in your case, If it works u can change the Width and height Values manually from 600 to 1000  In commandline and settings files as max in your case (try the best value for u untill having the best resolution without crash) .  i got same specs but with 2080 super (and reverb pro headset) and i use the Low config to get the game as smooth as possible.. 
I got the epic version and the pirated one too (which it uses steam vr btw) And im getting till now almost same results on both without tweaking anything yet.. 
(im still working on an intense Tests to get the best configurations and settings as possible to have the game enjoyable as possible..

**Comment by LukeRoss00** [comment]
> I found out that the dinput8 file that comes with the mod makes my game crash around 5-10 minutes in-game, then I looked up the issue on Youtube and I got a solution

Please don't use YouTube as your reference for finding "solutions". As you can see just by hovering over it with the mouse, the `dinput8.dll` file packed with the mod is the original GTA V *.asi plugin loader created by Alexander Blade, which is an essential component of his Script Hook V, which in turn is essential for my mod. If you "fix" it as YouTube recommends, no mods will work for you any longer, hence the black screen.

The crashes are **not** due to `dinput8.dll` which is just a loader. The possible causes for your crashes are the usual ones: GPU or CPU overheating, out of memory conditions, other mods or overlays interfering, etc.

Also guys, please no talk about pirated copies here. If you want to discuss that among yourselves, please do it elsewhere.

**Comment by ODEH67** [comment]
> please no talk about pirated copies here.

Removed

**Comment by LukeRoss00** [comment]
Thanks!
