### ISSUE TITLE
Cant move mouse to select "Story mode" 

### ISSUE THREAD

**Issue by Cassiegurly** [LukeRoss00/gta5-real-mod#223]
Hi,

Has anyone had the issue of not being able to move your mouse far enough to select story mode? Could it be the aspect ratio?

**Comment by ODEH67** [comment]
before the game launches you maybe opened something else , the game window is simply not activated , just click on the game at taskbar and the mouse should go further than the screen limit down there.. i prefer to use a joystick in this case ,,,, if it did not work u can adjust the height and width of the game from both files settings.xml and commandline to 1080 and it should be able to choose the in-game menu... but in this case u will loose the game quality ... i suggest u to try the first one it should absolutely work, let us know if it does

**Comment by ODEH67** [comment]
okayy?? @Cassiegurly

**Comment by Cassiegurly** [comment]
Changing the width and height worked. Thank you.
