### ISSUE TITLE
Game Crashes on Startup after Installing Mod

### ISSUE THREAD

**Issue by dgwdv666** [LukeRoss00/gta5-real-mod#224]
Steam VR and Rockstar Games Launcher start, then the game starts, and before the police sirens it crashes with no errors.

**Comment by ODEH67** [comment]
re-open it several times ..after few times it should work and after it launches , next time u will open it it will work directly
if it doesn't did u followed the guide steps of the mod or did u changed something in mod\game settings manually?

**Comment by dgwdv666** [comment]
> re-open it several times ..after few times it should work and after it launches , next time u will open it it will work directly
> if it doesn't did u followed the guide steps of the mod or did u changed something in mod\game settings manually?

It still crashes. I have no other mods installed and I did a clean install, and I only changed the game settings that I was supposed to change for this mod.

**Comment by ODEH67** [comment]
Use low settings from the mod even if your pc is a high-end PC...
What is your pc specs and headset?

**Comment by dgwdv666** [comment]
> Use low settings from the mod even if your pc is a high-end PC...
> What is your pc specs and headset?

GTX 1080 Ti - i7 7700 - 16GB RAM

I had an Index which isn't plugged in right now because the RMA is coming Monday or Tuesday. This might be the issue, but idk because I can still launch other Steam VR games including the unofficial DOOM 3 Fully Possessed VR mod.
If this is the issue though, I'm sorry for the trouble.

**Comment by ODEH67** [comment]
so u tried to launch the game with the mod with no headset connected?

**Comment by dgwdv666** [comment]
yes. I feel like an idiot now...

**Comment by dgwdv666** [comment]
I'll update you when it comes

**Comment by LukeRoss00** [comment]
I'm closing the issue for inactivity, feel free to reopen if necessary
