### ISSUE TITLE
Possible solution to ghosting/double vision

### ISSUE THREAD

**Issue by thmoas4** [LukeRoss00/gta5-real-mod#226]
Dear, I have a simple workaround to disable the ghosting which I don't know if it's tried yet. Show a black screen instead of the previous rendered image. How much flicker would that induce? It will cause at least only half brightness but GTA V has a brightness slider.

Shutter glasses work the same way, they shut off one eye at a time. Maybe with the low framerates this will cause too much flicker?

**Comment by LukeRoss00** [comment]
That could be a good idea in principle, and I did try it some time ago. Unfortunately, with the low-persistence displays that are used in VR, the flickering turns out to be intolerable.
