### ISSUE TITLE
Unknown game version

### ISSUE THREAD

**Issue by GCops99** [LukeRoss00/gta5-real-mod#227]
When I went to launch the game after adding the updated scripthook, it said there was an unknown game version. I'm not the greatest with computers so if anybody could provide a dumbed down version on what to do to fix this problem that would be great!

**Comment by LukeRoss00** [comment]
You're probably using an outdated version of the mod. Download it again from https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r5 and make sure to follow the quick setup instructions at https://github.com/LukeRoss00/gta5-real-mod#quick-setup

**Comment by GCops99** [comment]
After adding the update it still has the same message pop up. I deleted the old version and replaced it with the new one

**Comment by ODEH67** [comment]
Try to update your game and use the newest scripthook v That comes with the new mod release 5,, it been all said the mod guide  ... if you don’t wanna update or the game doesn’t update for some reason try an older version of the scripthook .. try this 👇

https://youtu.be/heKyWfV9qZE

**Comment by LukeRoss00** [comment]
@GCops99 Were you able to solve your problem? Do you have anything else to ask or should I close the issue?
