### ISSUE TITLE
HTC Vive Showing Two Screens

### ISSUE THREAD

**Issue by tandlar** [LukeRoss00/gta5-real-mod#229]
Hi Guys,

Hoping that I did something wrong and I just did something accidentally however I am getting two screens in VR on HTC Vive.  I am getting a smaller screen in front of a bigger screen.   So imagine playing fullscreen on a normal monitor and then having the exact same thing in a windowed screen right on top of it and that is what it looks like in VR.

Has anyone had this problem?

Thanks,

Todd

**Comment by LukeRoss00** [comment]
Did you follow all the instructions given at https://github.com/LukeRoss00/gta5-real-mod#quick-setup carefully, in particular point 4?

**Comment by tandlar** [comment]
Hi Luke,

I did but I had a 'different' version of GTA lets say.  I spent all night downloading epic version and verified it is working now thanks!

Todd

**Comment by LukeRoss00** [comment]
Great! Often "special" versions don't work so good ;-)
