### ISSUE TITLE
Grand theft auto V does not support VR. it will apear on your desktop and may affect Vr performance

### ISSUE THREAD

**Issue by Boycie456** [LukeRoss00/gta5-real-mod#23]
Im using a dell mixed reality headset.
I followed each step perfectly.
yet steam just gives me this message.
plz help.

**Comment by cercata** [comment]
I works only for Oculus at the moment

**Comment by Jesusavesouls** [comment]
Only oculus.I did everything too and it didn't work on my odyssey then I read all the info and saw it now at the moment only works on oculus.
