### ISSUE TITLE
Free mouse aiming (horizontal + vertical) in first person view?

### ISSUE THREAD

**Issue by mejo13** [LukeRoss00/gta5-real-mod#230]
Hey, is there a setting to have free mouse aiming?

**Comment by ODEH67** [comment]
did not try that yet but I think u will get motion sickness if u try to do so

**Comment by LukeRoss00** [comment]
@mejo13 My mod doesn't specifically support mouse aiming. I find that it detracts from immersion: in real life you don't see a floating crosshair, and if you actually want to hit something with your gun you aim down the sights, so you shoot where you're looking at and vice versa. GTA V and my mod offer full support for aiming down sights, and I also made sure that you can choose your dominant eye for perfect gun alignment. That being said, user @coru182 reported that mouse aiming worked for him when on foot by setting `HeadingControl = 2` and `PitchControl = 0` in the `RealVR.ini` file.

**Comment by mikededo4** [comment]
hey im currently trying to unlock y axis mouse for aiming as well. I looked in the RealVR.ini file but this most recent version doesnt include the PictControl line and it doesn't unlock by just changing the HeadingControl line. 

any thoughts?

**Comment by coru182** [comment]
Here's the RealVR file i'm using, hope it helps

; GTA V R.E.A.L. mod Release 7

[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 0

; 0           Select stereo mode in cutscenes (normal, dynamic, flat
screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left,
right) - right at start
DominantEye = 2

; Y           Select heading control (always, only when aiming, never) -
always at start
HeadingControl = 2

; U           Select pitch control (always, only when aiming, never) -
always at start
PitchControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut
relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 1

; End         Activate gyro stabilization of view in vehicle - off at start
GyroVehicle = 0

;             Select universal FOV fix (never, only cutscenes, only aiming,
always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always
except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 0

;             Select VR API to use (autodetect, Oculus, OpenVR, OpenXR) -
autodetect by default
VRAPI = 3

**Comment by mikededo4** [comment]
ahh thank you for that. I copied and pasted your file into mine and I did get y axis movement, but only of my player's arm. my crosshair doesnt actually follow along like it does horizontally.

thanks for the help tho

**Comment by coru182** [comment]
Np. I'm not entirely sure what you mean about your issue tho.
Using the config that I pasted, I'm able to free aim using the mouse while
looking in a different direction with my headset. Is that what you are
trying to achieve?
Feel free to add me on Discord Coru#0451 for further help, so that we don't
keep spamming here.. :)

cheers.

**Comment by mikededo4** [comment]
just touching back on here for anyone else.

the config @coru182 provided works and allows free aim, its just that the crosshair doesn't follow. if that can be changed that would be more than amazing. 

nonetheless thanks for the mod, having a lot of fun

**Comment by sycspysycspy** [comment]
> 
> 
> just touching back on here for anyone else.
> 
> the config @coru182 provided works and allows free aim, its just that the crosshair doesn't follow. if that can be changed that would be more than amazing, but for now gonna learn how to aim without a crosshair
> 
> nonetheless thanks for the mod, having a lot of fun

Crosshair would never work for "3D" games.
