### ISSUE TITLE
My game crashes when it loads!

### ISSUE THREAD

**Issue by RUNETHERABB1T** [LukeRoss00/gta5-real-mod#233]
As simple as the title! I get as far as Ludendorff 9 years ago and then the game crashes!

I have completely reinstalled the game. And removed the documents thing with savefiles! I don't know what more I can do! I also followed the setup guide 2 a T

Thanks!

**Comment by LukeRoss00** [comment]
Who ever told you to "remove the documents thing with savefiles"?!?

What you _can_ do if you want us to be able to help you is provide some details on your system: CPU, GPU, which headset are you using, which game version, which release of the mod, which settings did you choose (H/M/L) when running the batch file, etc.

**Comment by osterman2** [comment]
I have the exact same issue, crashes in the same spot. 
I installed last night, completely clean install, never been run on this machine before. 
My machine: i7-8700k, 1080ti, 64GB, Pimax 5K+.
I tried High settings first, then Med, always crashes in the same spot regardless. Is there a way to turn on debug logging?

**Comment by LukeRoss00** [comment]
Yes. Add the line `RVRLog = 2` at the end of your `RealVR.ini`; run the game until it crashes. After the crash, there will be a new `RVRLog.txt` file in the game folder: please attach it here.

**Comment by osterman2** [comment]
Trying to create a log file made the issue more obvious, looks like it was permissions. I moved the installation folder out of Program Files and it started fine. Thanks for making such a great mod!

**Comment by LukeRoss00** [comment]
You're welcome! Thank you for replying with how you solved your issue, I always appreciate it when people take the time to post their solution so that it might help others 👍
