### ISSUE TITLE
Batch file is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Soapmactuna** [LukeRoss00/gta5-real-mod#234]
![image](https://user-images.githubusercontent.com/69070309/89096010-f3a8e780-d426-11ea-941c-3438b090fbd2.png)
Getting this error when running the batch file

I followed every step in the install process. Not sure if it helps but my game is installed in E:\\

**Comment by LukeRoss00** [comment]
As you can see from the error report, it's not the batch file which is not recognized, but the internal 'CHOICE' command which should be present in all Windows versions since Vista.

What Windows version are you running?!?

**Comment by Soapmactuna** [comment]
That's weird, I'm running a Windows 10 Pro. Any idea how to fix?

**Comment by Soapmactuna** [comment]
Weird, running the batch file as administrator sort of fixes the issue but now it shows a new issue.
![image](https://user-images.githubusercontent.com/69070309/89099599-9cb20b00-d444-11ea-9a6d-785038f3076b.png)

**Comment by Soapmactuna** [comment]
Fixed it by adding System 32 and WindowsPowershell to my 'Path' in Environment Variables. 
![image](https://user-images.githubusercontent.com/69070309/89099904-d4ba4d80-d446-11ea-938f-67b05fb9bac8.png)

**Comment by LukeRoss00** [comment]
Thanks for providing details about your solution! However, both `%SystemRoot%\system32` and `%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\` should always be already present in your global PATH (under System variables). The fact that they weren't there in the first place suggests that your Windows installation has somehow become corrupted.
