### ISSUE TITLE
It’s keeps closing right before I load in 

### ISSUE THREAD

**Issue by purple-urkle** [LukeRoss00/gta5-real-mod#238]
My game closes every time when I’m about to load into the world and nothing pops up like saying I crashed or anything. How do I fix this??

**Comment by LukeRoss00** [comment]
The more details you can provide on your system, the better we'll be able to help you:

- CPU:
- GPU:
- VR headset model:
- game version and build:
- release of the mod:
- did you follow all the steps in https://github.com/LukeRoss00/gta5-real-mod#quick-setup carefully, in particular step 4?
- which settings did you choose (H/M/L) when running the batch file `RealConfig.bat`?
- did the batch file report any errors?
- did you change the graphics settings manually?
