### ISSUE TITLE
Let's work together to see whether this mod can be ported to SteamVR

### ISSUE THREAD

**Issue by LukeRoss00** [LukeRoss00/gta5-real-mod#24]
Many people would like to play GTA V in VR on their non-Oculus system. However, Revive and/or SteamVR appear to offer limited/no support to alternate eye rendering, causing the mod to have severe ghosting issues.

Since the source code to the mod is very large and complex, I have decided to reduce the problem to its core, by making a very small repro case that can be used by developers to test the issue and (hopefully) work out a solution.

Follow these easy steps to repro the problem:
1. [Download ](https://github.com/LibreVR/Revive/releases) and install Revive.
2. [Download](https://developer.oculus.com/downloads/package/oculus-sdk-for-windows/) the Oculus SDK (current version is 1.41.0) and unpack it somewhere, say in `C:\Devel\ovr_sdk_win_1.41.0`.
3. Open the `Samples.sln` solution from `C:\Devel\ovr_sdk_win_1.41.0\Samples\Projects\Windows\VS2017` (there are also versions for VS2013 and VS2015 if you're not up to date).
4. In Solution Explorer, within the folder `OculusRoomTiny (Advanced)`, right click on `c. Simple Alternate Eye` and set it as the Startup Project; also, expand the project and double-click on `main.cpp`.
5. Scroll to the end of the file and insert the following two lines just before the line containing `SimpleAlternateEye app(hinst);`:
```
	LoadLibrary("C:\\Program Files\\Revive\\Revive\\x64\\openvr_api.dll");
	LoadLibrary("C:\\Program Files\\Revive\\Revive\\x64\\LibRevive64_1.dll");
```
6. Change the platform to `x64` and build the solution.
7. Run the project.

The test application should load in SteamVR, and you will be inside a simple room with a floating cube orbiting around you. Move your head, and you should see no ghosting effect. Now enable alternate eye rendering by holding down '1' (on the main keyboard, not the numpad; also it's important to keep it pressed, not just press it once) and as you move your head you should be seeing the same weird ghosting effect that appears in the R.E.A.L. mod when running with SteamVR.

If you can get rid of this ghosting effect (without disabling alternate eye rendering of course) by making tweaks to Revive, and/or by changing the way that the eye poses are submitted to SteamVR, I will test your changes and if they work correctly I will integrate them in the mod.

**Comment by Jesusavesouls** [comment]
Let's get this up and going.Sounds good and me too want to play this mod on a non oculus vr with steamvr.

**Comment by brentjohnston** [comment]
CrossVR just said this on reddit:

Just want to note that the biggest problem right now is that Revive itself doesn't support it. While it's true that SteamVR doesn't fully support it, there's no telling yet how much of a problem that is.

This part needs to be updated: https://github.com/LibreVR/Revive/blob/7d520882fe83f3b05c3f081ea764ae9b9ea4f544/Revive/TextureBase.h#L32

We can probably get rid of Submit() altogether and just remember the last committed image in SubmitIndex.

**Comment by Jesusavesouls** [comment]
I will just have to wait for the quest link pc update to try it.I have a quest and odyssey 1st gen.Got rid of my cv1 to get a inexpensive high resolution headset like the odyssey.

**Comment by LukeRoss00** [comment]
> Let's get this up and going.Sounds good and me too want to play this mod on a non oculus vr with steamvr.

> I will just have to wait for the quest link pc update to try it.I have a quest and odyssey 1st gen.Got rid of my cv1 to get a inexpensive high resolution headset like the odyssey.

Please let's limit this to technical discussion, thanks

**Comment by Jesusavesouls** [comment]
If the guy from grand theft auto vr mod and this mod from lukeross work together we could have a full working in vr mod with full motion controls in vr on gta5 but without a injector needed like vorpx.

**Comment by Jesusavesouls** [comment]
Thanks for this mod I haven't tried it yet but it's free and works.Praise Jesus!

**Comment by brentjohnston** [comment]
I've got no build errors anymore now after installing some missing components with the visual studio installer (such as Windows Universal CRT SDK) It builds successfully.

The problem I have though is I still can't get it to start, it gives an error "the operation could not be completed. Unspecified error."

**Comment by brentjohnston** [comment]
Uhh, when holding 1 down and checking out the ghosting effect is waaay more tolerable than when I test with revive and GTA V directly. It's like glitching out everywhere in GTA V. (even if you set your mod to monoscopic mode) If it was only ghosting like this tiny room demo I think that would actually very playable.

**Comment by Jesusavesouls** [comment]
Keep at it and you will reap rewards for your labor.

**Comment by LukeRoss00** [comment]
> it's moving all around in GTA V even with head still

I cannot test that myself because I don't have an Index, and nobody at Valve has volunteered to donate one for the mod :-P, but that doesn't seem to happen to other users (several reported that the 3D is perfect with the R.E.A.L. mod and Revive if they keep their head still).

**Comment by Jesusavesouls** [comment]
So what exactly are you doing to get it to boot up and work on revive ?

**Comment by tomreason** [comment]
Hi Luke! I looked at the game in my Pimax 5k Plus helmet, it works on the VIVE basis and here's what I can say. Perhaps I realized what the problem is. I’m not quite a programmer, but maybe the image is projected in both eyes the same thing, that is, in one eye the image is for both the left and the right, that's why it ripples like that, it calculates as 4 images, not two, because which clones on both eyes at once two images.

**Comment by Jesusavesouls** [comment]
Now quest link pc update is out any chance you will update your mod to work on it ?

**Comment by LukeRoss00** [comment]
@brentjohnston I sent you a PM on Reddit (assuming I got your username right)

**Comment by LukeRoss00** [comment]
In the end I did the porting myself, so I'm closing this issue. Please refer to #44 for reporting success or problems with the new release
