### ISSUE TITLE
Crashes on startup - Scripthook V error

### ISSUE THREAD

**Issue by Mulbin01** [LukeRoss00/gta5-real-mod#240]
CPU: i7 4790k
GPU: GTX 1080
VR headset model: Oculus Rift S
game version and build: - 1.0.2060.0
release of the mod: Release 5
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No

Getting a Scripthook error on launch. fresh install of game and mod, latest steam version.

"FATAL: Unknown Game Version"

**Comment by VRWulff** [comment]
New update in GTAV did the same to mine.
2 options, wait for a update form here, or we have to roll back GTA to older version

**Comment by Mulbin01** [comment]
Looks like bad timing on my part. I just bought the game today to try this mod... I had no idea there was a new patch!

Trying to roll back, but now fighting controller config errors so may just have to wait for an update to script hook :(

**Comment by LukeRoss00** [comment]
Yes guys, it seems that Rockstar updated the game again, once more breaking all script mods. It usually takes a few days for Alexander Blade to update Script Hook V to match a new game version, we'll just have to wait!

**Comment by Jon6206** [comment]
If you don't want to wait you can downgrade GTA 

https://www.youtube.com/watch?v=r-x7JWt_3Wg

**Comment by alphanumeric-characters** [comment]
Same here. I downloaded this mod the other day and was playing it last night. Tried to play it today and keep getting the Script Hook error.

**Comment by commychung** [comment]
i have ps4 GTA already , Because VR mode ~ some day ago i buy steam GTA, but cannot play now ~~, VR mod can support crack GTA version?

**Comment by alphanumeric-characters** [comment]
> i have ps4 GTA already , Because VR mode ~ some day ago i buy steam GTA, but cannot play now ~~, VR mod can support crack GTA version?

@commychung I had it working the other night. As per comments I believe there was an update to GTAV sometime in the last 24 hours that has rendered the current version of ScriptHook obsolete. We will have to wait for ScriptHook to be updated before this mod will work again. But rest assured that the mod does work.

**Comment by iliakulikov** [comment]
> If you don't want to wait you can downgrade GTA
> 
> https://www.youtube.com/watch?v=r-x7JWt_3Wg

Unfortunately didn't help, the app asks for the update.

**Comment by VRWulff** [comment]
I tried the downgrade thing. Was able to downgrade but the game will not boot without updating from launcher. So I tried downloading the NoLauncherMod.exe - that did not work either, gave me a register error and then I gave up.  Im using the rocketstar launcher version

https://www.youtube.com/watch?v=qW1584OJ18Q              Downgrade video for steam version
https://www.youtube.com/watch?v=Sn_KQZOZstI&t=1s       Downgrade video for Epic games

Does anyone know where we can keep an eye out for an Scropthook update?

**Comment by LukeRoss00** [comment]
> Does anyone know where we can keep an eye out for an Scripthook update?

On the official page: http://www.dev-c.com/gtav/scripthookv/

**Comment by brankia** [comment]
Someone solved this?

**Comment by Johnnyprim3** [comment]
My issue is I downloaded the lastest version of script hook and the game is now so slow, it's virtually unplayable. Anyway to solve this?

**Comment by JonathanTurnock** [comment]
Same issue for me as above, 7 FPS with Medium Settings from Bat config, Followed the Install Guide Twice and changed nothing other than dropping in the new ScripthookV dlls.

i5-9600K, RTX-2070 Super and HP Reverb using OpenXR

**Comment by VRWulff** [comment]
Installed latest version of scripthook and the game will boot up. but it runs at something that feels lik 2fps - it is unplayable.
Working just fine before the last GTA update with old scriphook version.

CPU: i7 8700k
GPU: GTX 2080TI
VR headset model: Oculus Rift S
game version and build: - 1.0.2060.0
release of the mod: Release 5
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Tried all 3 and its the same.
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No

**Comment by LukeRoss00** [comment]
@VRWulff Probably some signature(s) have changed with this latest update. Could you do me a favor? Add the line `RVRLog = 2` at the end of your `RealVR.ini` file and run the game until you get control of your character, then quit. You should find a new `RVRLog.txt` file in your game folder, could you please zip it and attach it here?

**Comment by Jms10391** [comment]
Having the same problem, and did the log dump.  Hopefully this helps!

CPU: i7-9700K
GPU: RTX 2070
VR Headset: Rift S
Game Version: 1.0.2060.0
Mod Release: 5

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5081222/RVRLog.txt)

**Comment by VRWulff** [comment]
> @VRWulff Probably some signature(s) have changed with this latest update. Could you do me a favor? Add the line `RVRLog = 2` at the end of your `RealVR.ini` file and run the game until you get control of your character, then quit. You should find a new `RVRLog.txt` file in your game folder, could you please zip it and attach it here?

Here you go :)
[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5081232/RVRLog.zip)

**Comment by LukeRoss00** [comment]
Thanks. Two code signatures used to set the camera FOV have indeed changed. Looks like I will have to work at a new release of the mod :-/

**Comment by SaxoFr** [comment]
Hello,

Here is the file 

[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5081301/RVRLog.zip)

**Comment by VRWulff** [comment]
> Thanks. Two code signatures used to set the camera FOV have indeed changed. Looks like I will have to work at a new release of the mod :-/

:( To bad man. I was really enjoying the mod - only got to try it once before the update.

**Comment by jgiroux** [comment]
I really appreciate all the work on this, it's truly legendary!  I recently learned about your mod just a few days after the most recent update, and no manner of downgrading has worked, so I'm still dreaming of GTAVR.  I was so excited when the new Scripthook came out and was all ready to go, then struggled a long time with the mod because I thought I installed it wrong.  It's reassuring in a way that it's a real issue.  Thanks!

**Comment by VRWulff** [comment]
> I really appreciate all the work on this, it's truly legendary! I recently learned about your mod just a few days after the most recent update, and no manner of downgrading has worked, so I'm still dreaming of GTAVR. I was so excited when the new Scripthook came out and was all ready to go, then struggled a long time with the mod because I thought I installed it wrong. It's reassuring in a way that it's a real issue. Thanks!

ye I got same problem. Cant seem to downgrade my game cause I have the rocketstar version.
If you have the steam or epic game version you should be able to downgrade it

**Comment by jgiroux** [comment]
I have Steam version as well, but nothing I've tried so far has worked to downgrade, and I've tried a lot.

**Comment by Johnnyprim3** [comment]
My issue is I downloaded the lastest version of script hook and the game is now so slow, it's virtually unplayable. Anyway to solve this?

**Comment by jgiroux** [comment]
@Johnnyprim3 -- this issue is discussed up-thread.  the mod will need an update

**Comment by VRWulff** [comment]
> I have Steam version, but nothing I've tried so far has worked to downgrade, and I've tried a lot.

https://www.youtube.com/watch?v=qW1584OJ18Q Downgrade video for steam version
These guys in the comment section claims this is working - unsure if you tried this fix :)

**Comment by jgiroux** [comment]
Thanks, I tried most of that except for pre-opening the launcher and game online, then switching and re-opening.  That just sends me to Activation Required screen though, even if I just activated the game a moment before.  Just guessing, but I'm thinking that since I bought it after 2060 came out, it won't have a record of me activating 1868 so it won't let me downgrade.

**Comment by LukeRoss00** [comment]
Game version 1.0.2060.0 should now work fine with [Release 6](https://github.com/LukeRoss00/gta5-real-mod/releases). As always, your feedback is welcome!

**Comment by Johnnyprim3** [comment]
Thanks Luke, It works!!! Your efforts are highly appreciated.

**Comment by Johnnyprim3** [comment]
I know this is slightly off topic... But isn't there a way to use this Mindbending plugin with GTA online? That would be like entering the Matrix. I know mods aren't allowed, but there has to be a way to mask it from detection.
(A genius mind like yours can do ANYTHING)

**Comment by alphanumeric-characters** [comment]
> Game version 1.0.2060.0 should now work fine with [Release 6](https://github.com/LukeRoss00/gta5-real-mod/releases). As always, your feedback is welcome!

Legend

**Comment by LukeRoss00** [comment]
@Johnnyprim3 Trying to sneak past Rockstar's online defenses would only lead to them banning the mod altogether and/or making me take it down with legal action. Sorry but online is never happening unless they specifically ask me for it (which is also never happening, ha-ha)

**Comment by Johnnyprim3** [comment]
@LukeRoss00 you're right. Thanks all the same for your dedication and sacrifice and for making Los Santos a city one can be a part of.
