### ISSUE TITLE
Feedback on gta5-real-mod V6

### ISSUE THREAD

**Issue by VRWulff** [LukeRoss00/gta5-real-mod#242]
Thank for the update dude - you are a champ!

The frame issue is gone, the game seems to be running at a steady good framerate.
What I noticed right away was when moving right and left, I am seeing alot of noise/double image. If you open up the phone and turn right and left, its really bad, this is the same with NPCs or vehicles moving left/right from the camera view. 
I read the FAQ (/Q. Mmmhhh... When I drive at speed and look sideways, or if I strafe in front of a brick wall, everything looks sort of double... Did I smoke too much weed?) What I am experiencing happens in both right and left eye. (close one eye, its  there, close the other its still there)

CPU: i7 8700k
GPU: GTX 2080TI
VR headset model: Valve Index
game version and build: - 1.0.2060.0
release of the mod: Release 6
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Tried all 3 and its the same.
did the batch file report any errors? No
did you change the graphics settings manually? Yes - after trying H/M/L I turn on your recommented adcanved gfx tweaking MSAA 2x +TXAA
are you using any other mods? No

I created a log where all I did was boot up the game, open my phone and turn right and left if that is any help. 

[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5090660/RVRLog.zip)

**Comment by LukeRoss00** [comment]
What you are seeing should just be the normal artifacts of alternate eye rendering. To double check, you can toggle monoscopic mode: press `F11` to activate the mod hotkeys, and then `NUMPAD2`. The double image should disappear when monoscopic mode is used.

Back to stereo 3D mode, make sure that motion smoothing is off in the SteamVR settings. With the Index, you can make the artifacts a lot less visible by choosing a high refresh rate (say 120 Hz) and lowering the game graphics settings a bit until you can achieve a stable frame rate.

**Comment by VRWulff** [comment]
I tried lowering the setting to Low before and that did absolutly nothing to the double image, it was just as bad in Low as in High. I tried turning off motion smoothing in SteamVR and I did not see any changes at all. My index is always running 144hz - but doing the F11 + NUM2 completly removed the issue, I dont see any changes in graphics, other than it looks 99% smoother.

Thanks again dude - much appreciated

**Comment by LukeRoss00** [comment]
Something seems wrong from your log. You say that you're running at 144 Hz, but the game is actually rendering at ~72 Hz, which might indicate that for some reason your SteamVR settings are forcing motion smoothing to be always on. This means that every other frame will be interpolated instead of rendered, which will make alternate eye rendering look terrible.

You might try turning on the mod frame counter (`N` hotkey) to monitor what is happening. If you lower the GTA V graphics settings enough, with your video card there is no reason why you shouldn't be able to reach 144 Hz (perhaps not in the desert which is very demanding, but at least in the city).

**Comment by VRWulff** [comment]
Well - im not running 144 fps, I just always have my index set to 144hz. 
Choosing the Low settings will give me 80-90 fps in the city. I was wondering how I am not able to squeeze out more when I have a 2080ti, but I figured it was due to the VR mod being very heavy on the GPU. - but yes it looks very terrible when I use stereo rendering, even on Low.

**Comment by foocanidiot** [comment]
I get home in a week cant wait to try out your mod!

**Comment by MilkyShakester** [comment]
I seem to be getting a similar issue to VRWulff's, the framerate seems pretty stable but looking around, specifically side to side, is a bit jittery, almost like the image is vibrating side to side when I turn my head. It's also still mirroring my view on the desktop, which I assume is what turning off Desktop Game Theater is supposed to avoid. Motion Smoothing is also turned off in Steam VR for GTA 5, however I couldn't find a global setting for the Oculus-specific option.

    CPU: Ryzen 5 3600
    GPU: Radeon RX5700 XT
    VR headset model: Oculus Quest through Virtual Desktop
    game version and build: 1.0.2060.0
    release of the mod: V6
    did you follow all the Quick setup steps carefully, in particular step 4? Yes
    which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Medium
    did the batch file report any errors? No
    did you change the graphics settings manually? No
    are you using any other mods? No

**Comment by LukeRoss00** [comment]
@MilkyShakester Virtual Desktop doesn't (yet?) support alternate eye rendering. You need to use the Link cable

**Comment by MilkyShakester** [comment]
@LukeRoss00 Gotcha, figured it was probably something simple that I overlooked. I'll give it a shot with the link cable when I get home tonight. Thanks.
