### ISSUE TITLE
Game crashes on loading story

### ISSUE THREAD

**Issue by emozio666** [LukeRoss00/gta5-real-mod#244]
CPU: i7 6700K
GPU: 2070 rtx super
VR headset model: HTC VIVE
game version and build: last
release of the mod: last (r6 i believe)
did you follow all the Quick setup steps carefully, in particular step 4? - yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? - H
did the batch file report any errors? - no
did you change the graphics settings manually? - no (i play half year with this graphic settings)
are you using any other mods? - natural vision (also use this mod half year)

i update last version GTA5 and update last ScriptHookV - game crashes on loading story
PS
By the way, a week ago I downgraded the version of the game to play and blocked access to the Internet, it worked perfectly. Could this somehow affect?

**Comment by LukeRoss00** [comment]
Everything looks in order from the log. However, the script part of the mod (`RealVR.asi`) is not being loaded: the game crashes before the .asi has even had a chance to start. It might have something to do with your downgrading the game, I'm not sure.

Could you also attach your `asiloader.log` and `ScriptHookV.log` files?

**Comment by emozio666** [comment]
Sure
[asiloader.log](https://yadi.sk/d/w_21v8Czx4YVsA)
[ScriptHookV.log](https://yadi.sk/d/SlmpT1KTzxWfHA)

**Comment by LukeRoss00** [comment]
Your `asiloader.log` shows that you're still using `GTAVLauncherBypass.asi`. That's probably what's crashing your game.

**Comment by emozio666** [comment]
I probably overlooked in the video that after updating to the latest version of the game, the bypass will need to be removed. Is it enough to just delete this file?

**Comment by LukeRoss00** [comment]
I guess. Downgrading is always a bit dicey though: that's why I never suggest it even as a temporary remedy. If simply deleting the fake launcher doesn't work, I would suggest reinstalling from scratch. Please post back with your findings so that other users who have fallen into the same trap may find your solution!

**Comment by emozio666** [comment]
Removal GTAVLauncherBypass did not help, I had to remove the game completely.
