### ISSUE TITLE
Detecting R.E.A.L. / Camera-related question

### ISSUE THREAD

**Issue by E66666666** [LukeRoss00/gta5-real-mod#246]
Recently, I've had people complaining my Manual Transmission script broke R.E.A.L. - this was due to the custom camera implemented in my script being active by default.

For my next release, I plan to make it more compatible, but still offer the best out-of-the-box experience. So my question regarding this is: Is there a good way to detect RealVR being *active*? Initially I could detect the asi being loaded, though I don't know what other operating modes RealVR uses. Does it expose something I can read, or is assuming a loaded .asi == VR good enough?

Additionally, not related - would you mind sharing how exactly you set the camera rotation (and position)? I'd like to use the same method for my custom camera, as it would solve a few issues with regards to NVE and excessive motion blur.

**Comment by LukeRoss00** [comment]
Hi!

I think that detecting `RealVR.asi` being loaded should be good enough: my mod cannot work without it, and I have no "off" switch ATM (so if the .asi is loaded, the game will always try to go into VR mode).

Re: the code for adjusting the camera position and rotation, it is unfortunately rather complex and a core part of my mod, and I'm not ready to open-source it just now :-(

**Comment by E66666666** [comment]
Ah thanks, I'll just check for the module then. Not running any of my camera code should be good enough to ensure compatibility.

No problem about the camera thing :) I'll close the issue then.
