### ISSUE TITLE
Mod is causing my FPS to be locked at 4?

### ISSUE THREAD

**Issue by XPMitcheLPX** [LukeRoss00/gta5-real-mod#247]
Hello! 
CPU: I5-9400f
GPU: GTX 1070 ti
VR headset model: HTC Vive Original
Gta 5 version: Steam
Mod version: Latest
Scripthook: Latest
Config setting: I've tried each one, and it's made no difference.

Sorry for creating an issue, I couldn't find anyone else having the same issue. When I play the game originally, I run the game between 60-120fps, but every time I install the mod for some reason I get locked at 4 frames. During the time I've spent trying to fix this, I noticed I get stuck in this 3rd person view which I was guessing was the extra camera. And it's as if it was in first person view, but out of place. Like a few metres back. If I look left or right the camera doesn't move and my player follows as if it was first person. I
![help](https://user-images.githubusercontent.com/70375368/91554687-87d37500-e927-11ea-9738-0b223093c2b3.PNG)

**Comment by LukeRoss00** [comment]
- did you change the graphics settings manually?
- are you using any other mods?

Does "latest" mean that you are using Release 6 of the mod?

**Comment by XPMitcheLPX** [comment]
I haven't changed the graphics from what the realconfig set it to.
I am not using any other mods.
And Yes I am using Release 6.

**Comment by LukeRoss00** [comment]
Let's see the log files: add the line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get control of your character. After quitting the game, there will be a new `RVRLog.txt` file in the game folder: please attach it here together with your `asiloader.log` and `ScriptHookV.log`.

**Comment by XPMitcheLPX** [comment]
Thank you so much for your time!

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5142254/RVRLog.txt)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5142256/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5142257/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
As I suspected, you're not actually using Release 6 of the mod :-)

You might have done something wrong when unpacking the new .rar file (perhaps didn't overwrite existing files?)

**Comment by XPMitcheLPX** [comment]
I'm such a dumbass, Thanks for your help it's completely fixed.

**Comment by LukeRoss00** [comment]
No problem!
