### ISSUE TITLE
Game locked to 60 fps

### ISSUE THREAD

**Issue by Hamad-other** [LukeRoss00/gta5-real-mod#249]
CPU: i7 7700K
GPU: GTX 1080 Ti
Ram: 16 GB 3600 MHz
VR headset model: Valve Index (set to 120 fps)
game version and build: 1.0.2060.0 
release of the mod: R6
did you follow all the Quick setup steps carefully, in particular step 4? Yup. 
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? M 
did the batch file report any errors? Nope.
did you change the graphics settings manually? Nope. (I did after, set refreshrate=120)
are you using any other mods? No, Fresh install. I am using a downloaded 100 % save game but it was placed before the mod.

- The game appears to be locked at 60 fps, v-sync is off in game and in geforce settings. My monitor is 100 Hz so the 60 fps lock makes no sense, plus the headset is 120 Hz. Motion smoothing is off. My monitor has G-sync but I doubt that is relevant. 

- In the settings.xml file, refreshrate_value=60 so I changed it to 120. It kept changing back to 60, so I set it as read-only (prob a bad idea). I also tried adding '-framlimit 0' to the commanline file (before setting settings as read-only).

- I am out of ideas, looking it up online, the solution in all threads is to just turn off v-sync, which is off. I also tried to turn v-sync on then load the game and then turn it back off with no luck. 

- I tried uninstalling the entire game and deleting the GTA V folder in Documents and trying everything again but I am seeing the same issue. I did not touch any graphics settings at first (other than instructions in step 4), I then messed around a bit and tried the RealConfig.bat High settings as well, still locked at 60 fps.

- The 60 FPS reading is both through the mod hotkey and I checked it through fpsVR. I have attached RVRLog and settings.xml (as txt) if it helps. I also realize this may be a game issue than a mod issue but I am out of ideas.

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5177931/RVRLog.txt)

[settings -.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5177932/settings.-.txt)

Cheers.
Geforce settings:
![image](https://user-images.githubusercontent.com/70801880/92303527-4e7db380-ef7e-11ea-9a0f-c26b1b17feb8.png)
![image](https://user-images.githubusercontent.com/70801880/92303565-b16f4a80-ef7e-11ea-9c97-59c3058d1ccb.png)
![image](https://user-images.githubusercontent.com/70801880/92303570-bc29df80-ef7e-11ea-9fa5-2a67b6fc90ab.png)

SteamVR settings:
![image](https://user-images.githubusercontent.com/70801880/92303679-f8aa0b00-ef7f-11ea-9b33-23a535d03e5e.png)

GTA 5 ingame settings (settings.xml shows the same):

![image](https://user-images.githubusercontent.com/70801880/92303778-d369cc80-ef80-11ea-98be-e99b9e04992c.png)
![image](https://user-images.githubusercontent.com/70801880/92303777-cf3daf00-ef80-11ea-9ffd-eeae03d813af.png)
![image](https://user-images.githubusercontent.com/70801880/92303786-e381ac00-ef80-11ea-9fa7-f870fbc85a9a.png)

**Comment by LukeRoss00** [comment]
Hey, thanks for providing so much detail!! The log indicates that SteamVR is throttling the application AND using motion smoothing, despite the global setting "Motion Smoothing = off" that can be seen from your posted image. That's probably the reason for the 60 fps cap (never mind the `<RefreshRate value="60" />` entry in the `settings.xml` file, that's not used by the game in windowed mode).

You should check the per-application settings, which might be overriding the global settings (the application-specific settings are visibile in SteamVR only when GTA V is running). It might also be something left over in your `steamvr.vrsettings` file...

**Comment by Hamad-other** [comment]
and fixed! Thought global would include per-application settings but it was set to Force always-on for some reason and I forgot to check. 
Thanks a million.

For future reference, while the game (GTA 5) is running in VR:
Settings then video then this:
![image](https://user-images.githubusercontent.com/70801880/92304192-5f312800-ef84-11ea-91cd-b5e329b60ea2.png)
If its force always-on, global settings don't affect it:
![image](https://user-images.githubusercontent.com/70801880/92304202-7f60e700-ef84-11ea-9b1c-495fa09a0ab1.png)
So set it to Disabled (better) or use global settings:
![image](https://user-images.githubusercontent.com/70801880/92304214-999ac500-ef84-11ea-81f4-7085017ed235.png)
