### ISSUE TITLE
Double image in same eye (one eye closed)

### ISSUE THREAD

**Issue by tbonge** [LukeRoss00/gta5-real-mod#25]
With the alternate eye rendering I understand that there will be a ghost effect since one eye lags behind the other and shows a frame behind. I figured I could close one eye for a few seconds if the ghosting makes me dizzy but I still see the ghost image on objects moving from left to right with one eye closed. Shouldn't it be showing the same frame twice? Where is the ghost image coming from then? The image is solid with F11 then num 2 to turn off 3D. I would expect the same solid image with one eye closed. Do I have something set up wrong? This is on rift S.

**Comment by Polyamid1978** [comment]
I have the same problem with my Rift S. Every object moving sideways has a ghosting both to the left and to the right even with one eye closed.

**Comment by LukeRoss00** [comment]
That might be due to ASW kicking in. The keyboard shortcuts Ctrl+NUMPAD1 to Ctrl+NUMPAD4 change the behavior of ASW in the Oculus runtime (see for example [What are the keys for ASW?](https://forums.oculusvr.com/community/discussion/50711/what-are-the-keys-for-asw)).

Could you guys try using those 4 combinations while the mod is running, and report back whether there is at least one of them that makes the ghosting go away when you keep one eye closed?

**Comment by tbonge** [comment]
1 and 4 look the same, they have the ghost image in one eye. 2 and 3 have the ghost images twice as far apart and much more noticeable and it is very jittery, looks like 15 fps.  I tested this by looking at a white car against a dark wall and walking side to side. There is a very obvious double image of the car in only one eye when moving but not when standing still and it is not there with stereo turned off. There is no noticeable ghosting when moving towards and away from the test car, only side to side.

**Comment by Polyamid1978** [comment]
I already tried to force ASW off by tray tool. ASW is not the problem. I use rift s with RTX2080. A friend with rift s and RTX2070 also has the same problem. Another friend with old rift still does not recognize the effect. 

Could this be a problem with the slightly higher resolution of the rift s? Rift uses 1080 resulution and so you configured the settings file. Rift S uses 2560x1440. Is the problem eventually a setting problem of the resolution with the alterned eye rendering?

**Comment by LukeRoss00** [comment]
Okay, then what you're seeing is not actually ghosting, but the normal effect that low frame rates have on the human vision system. People use a variety of different names for this effect, the most common being jerkiness, judder, strobing, or sometimes jittering. Basically the brain tries to interpret the strobing image as a continuous movement, and in doing so reconstructs "phantom" object positions that are never really displayed.

For a demonstration that doesn't require VR, see the [UFO Test](https://www.testufo.com/). Observe how the low frame rate stripes exhibit the strobing effect, and phantom images of the UFO start to appear.

I suspect that the phenomenon is made particularly evident by the lower refresh rate of the Rift S as opposed to the CV1, and possibly by the fact that the Rift S employs an LCD display.

So, sorry but there's nothing that I can do :-(

**Comment by Polyamid1978** [comment]
But if this is the Rift framerate, why is there anywhere else such an effect. You do not see such a blurry effect in any game. Also my hardware is easy able to easy show the 80 fps, my rift is able to draw.

**Comment by LukeRoss00** [comment]
Because with stereo enabled in the mod the frame rate per eye is halved to 40 fps.

**Comment by tbonge** [comment]
I understand what you mean about the low frame rate effect. But I don't think that is it. Because when the FPS is locked to 40 in the tray tool each eye gets 20 fps with stereo on and 40 fps with stereo off. And at 80 fps with stereo on each eye gets 40. So 40 FPS with stereo off should have the same effect as 80 fps with stereo on (effective 40). But it's not even close. 40 FPS with stereo off has no double image that I can see. In fact with the normal 80 fps and stereo on with one eye open or both eyes open have just about the same ghosting. This is very easy to see if you go the the car wash south of Franklin's house. There is a building with a white tile wall. Strafing along the wall you can clearly see the wall is doubled and one eye open or both the double effect is the same.

![IMG-4111](https://user-images.githubusercontent.com/4255666/68086253-bbcd2f00-fe17-11e9-88c2-94c616d905eb.PNG)

Here is a picture I took though the lens on the left eye. The graffiti and tile are double when moving sideways. It took a few tries to catch it because it seems to alternate between the double image and non double image. Like every other frame has the double image. If this is a low frame rate vision optical effect, the camera would not be able to see it.

**Comment by Polyamid1978** [comment]
![IMG_20191103_133223](https://user-images.githubusercontent.com/57312761/68086559-b8549a80-fe4d-11e9-9fa9-c5779fa53d6e.jpg)

**Comment by LukeRoss00** [comment]
> [...] the camera would not be able to see it

That is some in-depth analysis, thank you! You're definitely on to something weird. I always assumed that the double image came from the two eyes not matching perfectly, but it's not that (or at least not just that).

Could you please try with this small [test](https://github.com/LukeRoss00/gta5-real-mod/files/3801655/c.Simple.Alternate.Eye.zip)? I compiled it straight from the Oculus SDK, it's the sample that shows how to perform alternate eye rendering. Look especially for the moving cube, or you can also strafe near a wall like you did in GTA (movement in the sample is done with WASD and the cursor keys). If this sample shows the same behavior in the camera then we'll know for sure that it doesn't come from the mod, or from GTA itself, but it's an artifact introduced by the Oculus runtime.

I would love to investigate this further, thanks again for your deep delving!

**Comment by Polyamid1978** [comment]
Your flying Cube from the test file shows the same problem as shown in the mod. It is also possible to see its ghosting with one eye closed

**Comment by tbonge** [comment]
There are two overlapping cubes flying around and the same double image on the walls. 

![IMG-4128](https://user-images.githubusercontent.com/4255666/68087638-d8706380-fe25-11e9-9fb1-3cbe334d3a62.PNG)

**Comment by Polyamid1978** [comment]
exactly

**Comment by LukeRoss00** [comment]
Yep, that also matches what I see :-(

It might be a subtler form of ASW that kicks in automatically when only one eye is updated, and that cannot be disabled by the user. Anyway, guys, thank you for the analysis, but it really seems that there's nothing more we can do

**Comment by LukeRoss00** [comment]
For me the same behavior occurs with the R.E.A.L. mod: laterally-moving objects appear doubled in each eye in the headset, but not in the Oculus mirror. So it's either something that happens in the final composition stages, or a persistence effect as I was speculating above.

BTW, I can sometimes capture the double cube with my camera set to 1/90 s shutter time, but if I go down to 1/180 s shutter the cube always comes out as a single image. So, even the camera captures might not be telling the whole story: perhaps the photos showing the double image simply happened to be taken across a frame change.

**Comment by tbonge** [comment]
Is it possible to use a black frame (the way shutter glasses work) instead of the same frame twice to see how it looks? Maybe ASW does not expect the same frame twice when the image is moving so it is trying to add a frame and gets it wrong?

**Comment by Polyamid1978** [comment]
Also I notice strange behaviour when forcing ASW to on with oculus tray tool. After that fluid playing is no longer possible. Looks like ASW is incompatible with the Mod rendering.

**Comment by flexy123** [comment]
It even says in the description of the SDK demo that there are double images. So guessing that timewarp/ASW does this and it's intended (?) interpolation of what's 45fps (eg. odd/even frames per each eye) to the 90hz refresh of the displays. The question is whether it would it look worse if ASW wouldn't insert these frames?

**Comment by Polyamid1978** [comment]
But ASW is off in the SDK demo with the cube and in the Gta mod. You can see the ASW status in overlay if the tray tool.

**Comment by flexy123** [comment]
It's probably not even ASW *per se*, but the timewarp part of it. Eg. frame doubling.

**Comment by LukeRoss00** [comment]
Were you guys able to capture the effect on camera when using an exposure time of 1/180 s or less? At this point I'm pretty convinced that the double image is just strobing, and that there's nothing at all that can be done in software to get rid of it (apart from black frame insertion, which is unacceptable in VR because it flickers horribly).

**Comment by tbonge** [comment]
I recorded a video at 240fps. I watched it frame by frame. It shows the following pattern of frames...

1. Two identical frames in a row.
2. Two black frames.
3. The next two identical frames.
4. Two black frames.

There are no two overlapping frames or ghost images. The pattern of two frames then two black frames are probably because the capture frame rate is so high and these really just the same frame captured twice.  The black frames could be actual frames inserted or could be the refresh rate of the HMD screen.

I am going to record the same 240 fps video with stereo turned off to see what the difference is to try to get a clue as to why stereo shows the ghosting in a singe eye and mono doesn't, given that the we would expect to only see double image in stereo with both eyes. Stereo at 80hz should be the same as mono at 40hz however there is no double image in mono at 40hz that stereo at 80hz has.

Is this effect exclusive to the Rift S that runs at 80/40hz LCD or do the OLED 90/45hz head sets look the same? 

[IMG_4110.m4v.zip](https://github.com/LukeRoss00/gta5-real-mod/files/3825108/IMG_4110.m4v.zip)

**Comment by Polyamid1978** [comment]
Strange... If this effect cannot be seen on  single frames and is not a type of image
retention. Couldn't it be possible that the render engine sends frames to each eye panel with wrong angle or in wrong order? This could also cause the oculus ASW to make problems because frame spaces cannot be filled with new frames correctly.

**Comment by conman588** [comment]
Hey folks, is there any more information on this topic? Am having the same exact issue on my Rift S (1080ti, R5 3600), adjusted settings so I get a solid 80 FPS constantly but with this effect stereo is really hard to play, especially when driving. Thanks for all the hard work and hope so badly you guys can find some sort of fix for this.

**Comment by dabinn** [comment]
Same issue here. Rift S, ASW off, 70~80fps.
When turning camera even very slowly, obvious double image in one eye appears. But it did not show any ghost on desktop game window of a 60HZ monitor.

**Comment by dabinn** [comment]
Update:
Tested with 1/200s exposure time of still image, not ghost found. And then tested 1/125s+120fps video recording, still no ghost. And the frame rate for single eye is also fine at 40fps (3 same images in the 120fps recording). Objects in the recording also did not seems to go back and forth.
All seems fine, but it really feels very strange than other games.
https://www.youtube.com/watch?v=thk3WN2pewQ

**Comment by sheepdestroyer** [comment]
I see the exact same thing on Valve Index, event when set and stable at 120fps 
I tried with and without reprojection, 90fps and 120 fps
laterally moving objects have gosts,
Also there is a very clearly visible ghosting when holding the phone and turning with the mouse

**Comment by rossmassey** [comment]
I was able to fix this

I have a 2080ti and Valve Index, and even though I had turned off the stereo rendering everything was double

In addition to disabling Motion Smoothing, **Use Legacy Reprojection Mode** needs to be **off** as well (I had assumed since motion smoothing was disabled this setting wouldn't do anything, but it does)

**Comment by LukeRoss00** [comment]
Thanks for posting, this should be helpful for other people with the same problem
