### ISSUE TITLE
GPU not utilized?

### ISSUE THREAD

**Issue by anymorn** [LukeRoss00/gta5-real-mod#250]
CPU: AMD Ryzen 7 1700x

GPU: NVIDIA RTX 2070 SUPER (founders)

VR headset model: Oculus Rift CV1
game version and build: latest

release of the mod: latest

Q: did you follow all the Quick setup steps carefully, in particular step 4? 
A: Yes

Q: which settings did you choose (H/M/L) when running the batch file RealConfig.bat? tried one each
     did the batch file report any errors?
A: Tried every config once, never got errors

Q: did you change the graphics settings manually?
A:  Tried to play with defaults made by config, tried lowering settings after low performance to no avail

Q: are you using any other mods?
A: No

I have tried re-installing the game, re-installing the mod, and using different versions of scripthook. Nothing has worked, and I noticed that my GPU was not going above 10% at any time before and after launching GTA. Menus work fine, but rendering the 3D world is a no go.

**Comment by LukeRoss00** [comment]
What do you mean by "rendering the 3D world is a no go"?

Please attach your `asiloader.log` and `ScriptHookV.log` files.

**Comment by Eddie557** [comment]
GTA 5 UPDATED AGAIN    :(

**Comment by anymorn** [comment]
Woops, didn't realize how vague I was about the actual problem :p 1 FPS on all settings I tried, low GPU usage, rest of my computer had noticeable slowdown (I think it was using just CPU?)

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5206111/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5206139/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
Add the line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get control of your character. After quitting the game, there will be a new `RVRLog.txt` file in the game folder: please attach it here.

**Comment by SilentChill** [comment]
I have the exact same issue, the image is awesome the VR is working great apart from it running at 1fps with my 2080ti using about 5%.

Im using WMR HP Reverb everything works as it should just the GPU is just not being used at all

**Comment by LukeRoss00** [comment]
See my previous comment

**Comment by SilentChill** [comment]
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5250243/RVRLog.txt)

The hotkeys dont seem to work either ??  I enabled them them using F11 but didnt seem to do anything at all

**Comment by SilentChill** [comment]
Turned my IGPU off just incase it was trying to use that but it made no difference.

**Comment by SilentChill** [comment]
![image](https://user-images.githubusercontent.com/28492034/93686443-36458280-faae-11ea-88ca-96efa38b181c.png)


Thats with the game running GPU just isnt wanting to play with the game lol

**Comment by SilentChill** [comment]
Ive tried setting it to use OpenVR instead of OpenXR and its just as bad,  

Strange never had this issue when going through steam vr.  I just had the ghosting issue like everyone else never 1-3fps

GPU usage just hovers around 5%

**Comment by LukeRoss00** [comment]
@SilentChill You're not using the latest release of the mod! Just upgrade to Release 6, then update Script Hook V, and everything shall be well

**Comment by SilentChill** [comment]
ohhhhh lol thought I had latest version !!    doh !
