### ISSUE TITLE
game crashes before loading up

### ISSUE THREAD

**Issue by mikededo4** [LukeRoss00/gta5-real-mod#251]
CPU: i7 9700k 
GPU: Geforce GTX 1060 6GB
VR headset model: Oculus Quest
game version and build: 1.0.2060.0
release of the mod: r6
did you follow all the Quick setup steps carefully, in particular step 4?: yes 
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? M
did the batch file report any errors? - honestly idk where to find this
did you change the graphics settings manually? - no 
are you using any other mods? - no 

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5198364/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5198366/ScriptHookV.log)

ya game was working for version 1.0.18 whatevr was before this. I upgraded and then it took me to the latest version today of 1.0.2060.1.

then I downgraded back to 1.0.2060 and uninstalled the mod and everything was working fine.

then I reinstalled the mod and even redid scripthook separately and now the game crashes as soon as the 1080 by 1080 screen pops up.

**Comment by michaelnjays** [comment]
I was having this problem until I thought about re-running RealConfig.bat 

I had already run it once, so I'm not sure why that fixed it.

**Comment by mikededo4** [comment]
@michaelnjays ahh thanks for the reply but ive ran it already multiple times.

gonna try again.

**Comment by Eddie557** [comment]
1.0.2060.1 yep hookscrip  not working a New Update  From Rockstar Games Today 👎

**Comment by michaelnjays** [comment]
I was able to get the mod working again by putting it in offline mode and downloading the game files for my format (Make sure you get the Epic games or Steam specific files) and then re-running the config.

**Comment by mikededo4** [comment]
how did you put it in offline mode exactly @michaelnjays

**Comment by LukeRoss00** [comment]
If you have the Steam version of the game, [this](https://www.youtube.com/watch?v=p98pI1svTJE) video shows exactly how to revert to the previous build until Alexander Blade manages to update Script Hook V.

**Comment by mikededo4** [comment]
@LukeRoss00 thats exactly what ive done before installing ur mod today as a new version was released by rockstar. 

i am on the downgraded version and it just closes right after launch

ill see a second of black 1080 x 1080 then close

**Comment by mikededo4** [comment]
might uninstall and then just do a full clean install. the issue is not making any sense. when I uninstall and do everything the game runs fine but as soon as I reinstall the mod, it goes back into closing on launch..

backing up the profile file in the documents is the way to go to save the game data?

**Comment by LukeRoss00** [comment]
Uninstalling/reinstalling the game will not mess with your saves (which are in the `Documents\Rockstar Games\GTA V\Profiles` folder).

By any chance do you have the game configured to start in online mode? Script Hook V will close the game if it detects an attempt to go online, to prevent you from getting banned.

**Comment by mikededo4** [comment]
i believe i tried it in both online and offline mode. 

can you please tell me how to try it with offline mode.

the only way I was able to do it in offline mode was to 

a. ad -scOfflineOnly to a shortcut of "gta5"
b. turn off my ethernet adapter to force offline

both times the problem still persisted.

could you tell if theres another way to launch it in offline mode

also currently reinstalling game, if problem still persists ill try and provide like a mini vid if that helps.

**Comment by mikededo4** [comment]
https://www.youtube.com/watch?v=4KRIZB2dMdM&feature=youtu.be&ab_channel=lanre

**Comment by LukeRoss00** [comment]
Thanks for the video, it's funny :-) I did notice a weird thing: in the first attempt, you crashed with a 1080x1080 resolution, as confirmed by the contents of the `settings.xml` file.

Then you manually (and correctly) removed the mod, but didn't touch `settings.xml`. So the game should have started up windowed, still at a resolution of 1080x1080. Instead it went full screen and with a 16:9 aspect ratio, which makes me think that somehow the game is fetching its settings from somewhere else.

Perhaps try removing the `pc_settings.bin` file from your profile in the `Profiles` folder? Make a backup copy of it first in case anything goes horribly wrong...

**Comment by mikededo4** [comment]
@LukeRoss00 since its a fresh install there isnt a pc_settings.bin in there,

there is one in my backup however that i made prior to the video

**Comment by LukeRoss00** [comment]
After reinstalling the mod, add the line `RVRLog = 2` at the end of your `RealVR.ini`; run the game until it crashes. After the crash, there will be a new `RVRLog.txt` file in the game folder: please attach it here.

**Comment by mikededo4** [comment]
ooh here
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5202719/RVRLog.txt)

**Comment by LukeRoss00** [comment]
I see from the log that you're trying to use the mod in SteamVR mode, but you don't seem to have a valid SteamVR installation (look at the second line of the log).

You should be using the normal Oculus runtime (with the Link cable)

**Comment by mikededo4** [comment]
how do i fix this?

or switch it to normal oculus runtime?

**Comment by LukeRoss00** [comment]
Unless you changed the `VRAPI = 0` line in the `RealVR.ini` file, the mod will automatically default to the Oculus runtime.

For autodetection to work, your Oculus software must already be running (which it will always be, unless you messed with the service settings) and your Quest should be connected to your PC using the Link cable.

**Comment by mikededo4** [comment]
lollll you see thats crazy how I never thought to plug in the oculus this time. 

at least now I know.

Oculus must be running in order for game to run

(i was just rushing to test out if the game finally ran with the downgrade)

ty this can be closed now I think.

**Comment by michaelnjays** [comment]
In the command line file I added one line

“-scOfflineOnly” without quotation marks

**Comment by michaelnjays** [comment]
In the folder where GTAV is installed (eg: C:/ProgramFiles/Rockstar/GTAV) there’s a file called commandline that has some settings (including HMD resolution). Instead of adding -scOfflineOnly to a shortcut, try adding it to this document using a text editor (not Word. More like notepad++ or MS Notepad)
