### ISSUE TITLE
Rollovers

### ISSUE THREAD

**Issue by Subveil** [LukeRoss00/gta5-real-mod#254]
This line:
tied the roll (lateral tilt) of the rendering camera to the headset's roll, relative to the vehicle roll when the player is in a vehicle

and this line:

End         Toggle gyro stabilization of view in vehicle - off at start

Seem like the two are referring to actually being upside down during a rollover in a vehicle and being able to toggle that gyro stabilazation that would require on and off. Even if I change the .ini file so the default for the gyro is on, it has no affect. Ive been in a vehicle rollover and this is the main thing i was excited to experience in this far more immersive version of GTA and the previous version did allow for a violent rollover in VR and I would love it for this feature to be togglable or I will have to use an older version to get it the way I want. Unless Im totally crazy and theres another toggle somewhere that fixes this. Thanks! Amazing work BTW!!!!

**Comment by LukeRoss00** [comment]
Yes, the feature you're referring to can already be toggled on and off using the `End` key (the mod hotkeys must have been activated before that using `F11`). For more details see https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys

**Comment by Subveil** [comment]
I'm saying the toggle isn't working. Every other toggle does work though. I
tried changing it in the ini

**Comment by Subveil** [comment]
To answer your other questions. I installed the mod clean on a fresh
install of the game. I'm running a 2080ti. I out on only two mods
afterwards, simple fuel which uses F9 as a mod menu key and a manual
transmission mod gears which uses b+RB to access it's mod menu, so there
should be any conflicts with F11 key being able to activate the END key to
remove the gyro in the rollover. The forward slash to recenter works. I
can't figure out why the END toggle won't work. The only thing left for me
to try is removing simple fuel and gears and see if the toggle still
doesn't work for me, I was just pretty confident their menues shouldn't
collide. Does the .ini also let me change what the default keys are so I
can try a different key than END or F11?

**Comment by LukeRoss00** [comment]
Are you sure you're using Release 6 of my mod? The `End` hotkey was not active in previous releases.

I'm not sure, but I seem to gather from your first post that what you want is the old behavior (i.e., the camera rolling together with the vehicle) and you _don't_ want the camera to be gyro stabilized (i.e., the camera always being level with the horizon). In this case, what you want is to leave `GyroVehicle = 0` unchanged, and not to press the `End` key.

**Comment by LukeRoss00** [comment]
One additional idea: the Manual Transmission mod has a custom camera that might be causing the behavior you're observing. Make sure that custom camera is set to off.

**Comment by Subveil** [comment]
It is definitely version 6. And yes I want the old behaviour. Ill try both
those things this evening and then removing mods before I bother you again
with a result lol. Thanks for the quick response!

**Comment by Subveil** [comment]
Your right! I thought that manual transmission had not seen any updates since I used it with your 4th version of this mod, but it definitely added a camera that had to be disabled in the .ini and now everything is tickity boo! Would you like to remove this issue or should we leave it as an example to everyone to read everything everywhere lol

**Comment by LukeRoss00** [comment]
Great that you solved your issue! The update of Manual Transmission that was just released should take care of disabling the custom camera automatically when RealVR is detected :-)
