### ISSUE TITLE
Version update and scripthook update needed 

### ISSUE THREAD

**Issue by slikk66** [LukeRoss00/gta5-real-mod#255]
Just an FYI the included version of script hook is out of date.
I'm not too familiar with modding GTA5 so my first install and test ended up with a big error message saying version mismatch.
I went to the scripthook page and got the updated version and it launched.

**Comment by LukeRoss00** [comment]
It's already in the [release notes for R6](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r6)
