### ISSUE TITLE
Oculus Quest Virtual Desktop incompatibility

### ISSUE THREAD

**Issue by Bluscream** [LukeRoss00/gta5-real-mod#256]
CPU: [in msinfo.nfo.txt]
GPU: [in msinfo.nfo.txt]
VR headset model: [in 1600997374.json.txt]
game version and build:1.0.2060.1
release of the mod:r6 (with own dinput8 and scripthookv because the ones shipped are outdated)
did you follow all the Quick setup steps carefully, in particular step 4? yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
did the batch file report any errors? no
did you change the graphics settings manually? no
are you using any other mods? yes (but i also tried without anything else)

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5279752/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5279754/ScriptHookV.log)
[DxDiag.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5279755/DxDiag.txt)
[msinfo.nfo.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5279756/msinfo.txt)
[1600997374.json.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5279760/1600997374.json.txt)

**Comment by LukeRoss00** [comment]
Hey, you're gaming on a blade O_o

Thanks for the very good details! I see that your headset is a Quest: what are you using to connect with it? Only the Link cable (or a good USB cable) is working correctly that I know of, Virtual Desktop did not support the game last I heard.

If you're playing wired already, please add the line `RVRLog = 2` at the end of your `RealVR.ini` and run the game until it crashes. There will be a new `RVRLog.txt` file in the game folder that you can attach it here; it might tells us something about the cause of the crash.

**Comment by Bluscream** [comment]
Too bad to hear that VD isn't supported. May i ask what the reason is?

**Comment by LukeRoss00** [comment]
Very simple: ggodin hasn't yet gotten around to it. Unfortunately there's nothing I can do on my side

**Comment by AzureRok** [comment]
Looks like 1.0.2060.1 isnt supported: SCRIPT HOOK CRITICAL ERROR: FATAL: Unknown game version....

**Comment by LukeRoss00** [comment]
Make sure to have Release 6 and to update Script Hook V after installing the mod: https://github.com/LukeRoss00/gta5-real-mod/releases

**Comment by Bluscream** [comment]
@LukeRoss00 but how is it any different from any other SteamVR headset to your game/mod? Is it the quests weird refresh rate?

**Comment by Bluscream** [comment]
Also i am 100% certain that i used your mod with VD before, just on my local pc with 10fps instead of my shadow

**Comment by dantharp** [comment]
I don't know if this is the same issue or not, but mine would crash after trying to start a game.  I snagged the current version of ScriptHookV and then on the launcher, did a verify on the game files.  Those ended up needing to be updated and after that, no more crashes.  
Again, may be unrelated, but it's worth a try.  (Personally, I didn't know you could even do a "verify" on Rockstar games, just like you can on Steam games.)

**Comment by Bluscream** [comment]
Soo, i redid everything and this time i noticed the commandline.txt. My launcher was overwriting that's probably why it crashed.
So i got it working now and was even able to bump up the resolution to `-width 1440 -height 1600` (Quest native resolution) with 30+ fps. What confused me is the jittering that happened. The game ran at it's high fps but the screen was jumping around. Felt like someone enabled the opposite of motion smoothing. It made me quite sick after only a few seconds. I then retried with `Stereo = 0` and the artifacts were gone but the shaking was still quite noticable and i refuse to play like that. I tried VRAPI openxr in hopes steamvr would just make use of that but it didn't load in VR. Same with oculus (i tried tunneling the Link USB connection through shadow and the oculus software does actually recognize the quest but on the quest itself it doesn't realize it's plugged in anywhere.

This feels really weird to me because no other VR game/mod had rendering problems to this extend. not even ones using propietary engines like Alien: Isolation VR.

Also for the love of god i can't remember what  i did differently when had it running the last time where everything worked out of the box (even though it looked like crap back then resolution-wise)

P.S: I still don't get what VD would do differently then any natice SteamVR headset except it's own translation layer which shouldn't affect anything after the OpenVR layer

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5286224/RVRLog.txt)

**Comment by OneToo** [comment]
@LukeRoss00 do you think bumping Quest2 to 90hz when available will help with the jittering?  

@Bluscream VD once worked with v1.8 with some issues with the menu displaying.  Ingame was stable.  Something changed on their end when they implemented their Oculus home driver.

**Comment by LukeRoss00** [comment]
I'm not sure either, but my best guess is that Virtual Desktop is not using the eye poses that I'm submitting to SteamVR, replacing them with its own prediction instead. That is likely done in an effort to counteract the latency that comes from the wireless link, but it's a violation of the OpenVR API contract. Valve used to have a similar bug when my mod first came out, but they fixed it in a matter of weeks.

Most other games simply accept the default poses coming from the system and don't submit custom ones (because they don't do alternate eye rendering), which is probably why the issue only occurs with GTA V.

Guy Godin said to me that he would love for my mod's users to be able to play it with VD, and that probably after mid September he would have some time to look into the matter, so if you guys could politely remind him on his forums or Discord server it's probably the right moment to do so.

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/94348663-622caf00-003e-11eb-9b84-9271be5359ef.png)

I now wanna try to downgrade to the last version that worked with your mod for the time being.

On a sidenote: i would love to invite you to a discord where we focus on bringing pancake games into the 3rd dimension: https://discord.gg/djJMvR We have a ton of great modders in there (for example Dr. Beef who made all the amazing Quest ports for pc games like HL1, Quake, Wolfenstein and Doom and Nibre who made the Alien Isolation VR mod

**Comment by Bluscream** [comment]
![image](https://user-images.githubusercontent.com/3318223/94348663-622caf00-003e-11eb-9b84-9271be5359ef.png)

I now wanna try to downgrade to the last version that worked with your mod for the time being.

On a sidenote: i would love to invite you to a discord where we focus on bringing pancake games into the 3rd dimension: https://discord.gg/djJMvR We have a ton of great modders in there (for example Dr. Beef who made all the amazing Quest ports for pc games like HL1, Quake, Wolfenstein and Doom and Nibre who made the Alien Isolation VR mod

**Comment by Bluscream** [comment]
s

**Comment by Bluscream** [comment]
s

**Comment by Bluscream** [comment]
While this is unresolved, for anyone wanting to play it as badly as i do. you'll need to temporarily install [VD 1.8](https://drive.google.com/file/d/1HgGWT0EryTLfbmoprfXW_eMRR_W0vdDa/view?usp=sharing) on your PC and quest and block auto updates as described in the README.txt

**Comment by OneToo** [comment]
I just tried again recently with the Q2 and the 90hz SideQuest config, still stuttering when moving your head.

**Comment by DesktopMasters** [comment]
I have a Q2 and could not get it working.   Would crash on launch.  I also have an Oculus Rift.  And I am getting very bad FPS on that.  Like the game is supper laggy for some reason.  I did apply the patch mentioned on the release page.  I tried it in M and L resolution and nether helped.  It also hung when I tried to quit the game on M resolution.  I had to endtask it.  It did not hang on L resolution when I quit but for the first time ever my computer completely seized after the game quit.

**Comment by meklubba** [comment]
> I have a Q2 and could not get it working. Would crash on launch. I also have an Oculus Rift. And I am getting very bad FPS on that. Like the game is supper laggy for some reason. I did apply the patch mentioned on the release page. I tried it in M and L resolution and nether helped. It also hung when I tried to quit the game on M resolution. I had to endtask it. It did not hang on L resolution when I quit but for the first time ever my computer completely seized after the game quit.

you need latest ScriptHookV to make it stop crashing after the menu, but if you play through virtual desktop it will studder like hell and only the VD people can fix it, used to work on VD 1.8... man dont wanna but the link cable just for gta v

**Comment by Bluscream** [comment]
What about ALVR?

**Comment by OneToo** [comment]
> What about ALVR?

It has the same issue with stuttering.

**Comment by LukeRoss00** [comment]
> man dont wanna but the link cable just for gta v

You should be able to use a normal USB cable: https://www.androidcentral.com/oculus-link-now-works-cable-comes-your-oculus-quest

**Comment by Bluscream** [comment]
> > man dont wanna but the link cable just for gta v
> 
> You should be able to use a normal USB cable: https://www.androidcentral.com/oculus-link-now-works-cable-comes-your-oculus-quest

I think he meant any cable at all. VR with cables just feels restrictive if you've ever experienced it without

**Comment by LukeRoss00** [comment]
I read "but" as "buy", so I guessed he meant the rather expensive original Link cable. Anyway, I still hope that Guy Godin will find some time to extend VD one of these days so that it can support my mod!

**Comment by meklubba** [comment]
ye lots of typos there lol ... will try with a normal cable for the time being. the freedom of virtual desktop is great, really hope they fix it soon. thanks for the mod Luke :))

**Comment by Bluscream** [comment]
I can only second that thanks to you Luke :) I bow down for your work!

**Comment by banner90** [comment]
oculus quest 1 issue:
i connect VD，i can play and more better, but the game scene will shake when i turn my head left or right, it's not comfortable.
=========Hardware & Software
GTX1070TI
i5-7500
Oculus Quest 1
VD10.7.1
=========
"There was another mod out there that made them somewhat usable by removing your in-game character's body",i want to know what's the name of the mod?

**Comment by Bluscream** [comment]
Is this resolved?

**Comment by OneToo** [comment]
@Bluescream He mentioned in another post that he was working with the Dev.  I hope they are close to something.

**Comment by LukeRoss00** [comment]
Unfortunately the attempts to make Virtual Desktop work with the mod were unsuccessful. There are probably some limitations in the Oculus mobile SDK that make it impossible for third-party applications to support alternate eye rendering correctly. I have updated the README to indicate that a USB connection is needed for the Quest and Quest 2.

**Comment by OneToo** [comment]
@LukeRoss00 I know this issue is closed, but I'm wondering why it was able to work with 1.8 but can't now?   Were those changes to the SDK made after 1.8?

**Comment by LukeRoss00** [comment]
That's a good point. I'll try asking Guy Godin if he remembers what the old version was doing differently

**Comment by OneToo** [comment]
I posted on Discord and it was mentioned that 1.8 wasn't using the Oculus SDK, it was still the old SteamVR API \ OpenVR.
