### ISSUE TITLE
Can't play with Oculus Quest. Very low frame rate.

### ISSUE THREAD

**Issue by Mesteryl** [LukeRoss00/gta5-real-mod#257]
I am using the Oculus link to play with this mod but, when I start it, It's very laggy. Its at least 0.5 fps. My graphic card isn't the problem. I think I found the problem but can't fix it. When I look at Task Manager, it shows me that GTA V is using 0% of the GPU and 100% of the CPU and almost all of the memory. I reinstalled the mod and GTA V and it is still not working. When I play without the mod, the fps is normal. I have a GTX 1660. Please help me. I don't want to reinstall GTA again. Is this mod still supported? Thanks.

**Comment by LukeRoss00** [comment]
Please read #239
