### ISSUE TITLE
Doesn't work in the Oculus Quest. Frame rate is less then 1 fps.

### ISSUE THREAD

**Issue by Mesteryl** [LukeRoss00/gta5-real-mod#258]
I am using the Oculus link to play with it but, when I open it, the frame rate is almost 0 and the images flash a lot. I have reinstalled GTA V and the mod. I have also used a different version of the mod.

CPU: AMD Ryzen 5 3600 6-Core Processor (12 CPUs), ~3.6GHz
GPU: NVIDIA GeForce GTX 1660
VR headset model: Oculus quest
game version and build: Newest
release of the mod: Latest
I have followed all instructions
I used the Medium settings.
No.
No.
Only the native trainer that comes with the script hook.

It also tells me something bout the game version and crashes. So what I do is I just install the newest version of script hook.

I am using the steam version.

**Comment by LukeRoss00** [comment]
Low frame rate problems were caused by the Aug 11 Rockstar update and were solved in Release 6 of my mod. Make sure to update to the current version of the mod, and then also update Script Hook V from http://www.dev-c.com/gtav/scripthookv/
