### ISSUE TITLE
Not Working with GearVR and Epic Games...Expected?

### ISSUE THREAD

**Issue by StiffCookie** [LukeRoss00/gta5-real-mod#259]
Hi,

Thanks first off for the amazing work you've done on the mod, kudos.

So.. about my setup, should this be possible? 

I have the following:

- Own the Epic Games version of the game
- Installed the mod as directed
- Use a GearVR headset with Riftcat (Vridge)
- Launch the game from desktop shortcut

When the game loads, SteamVR pops up and does its thing (I didn't expect this to happen as I own the Epic Games version of the game). I get the 2D menu fine, then I press Story mode, right where I'm about to load in, it crashes to desktop.

Requested info:
CPU: Ryzen 5 3600
GPU: MSI RTX 2060 Super
VR headset model: GearVR (Galaxy S10+)
game version and build: 1.0.2060.1
release of the mod: r6
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? High and Medium
did the batch file report any errors? No, "1 file copied 1 file copied, press any key to continue"
did you change the graphics settings manually? Not touched a single thing apart from the 4 settings at the start of the guide.
are you using any other mods? None fresh install

Thanks so much in advance.

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5323898/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5323899/asiloader.log)
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5323901/RVRLog.txt)

**Comment by StiffCookie** [comment]
Never mind, I found the problem. I was searching for issues specific to GearVR. But in actual fact it was caused by outdated scripthook V. I updated to the new version as instruced here: [#252](https://github.com/LukeRoss00/gta5-real-mod/issues/252)

All is good now!

p.s. THIS MOD IS INCREDIBLE... LIKE DAMN... Best VR experience I've had yet

**Comment by LukeRoss00** [comment]
Great that you were able to quickly fix your problem! And yes, I'm thoroughly amazed that it works with dear old GearVR O_o
