### ISSUE TITLE
Crashes on loading screen of story mode and sends me back to steamvr home

### ISSUE THREAD

**Issue by Skyrdolla** [LukeRoss00/gta5-real-mod#260]
CPU: i7-8700 CPU
GPU: gtx 1070
VR headset model: HTC VIVE
game version and build: 1.0.2060.0. epic games build
release of the mod: r6
did you follow all the Quick setup steps carefully, in particular step 4? yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? first M and then L
did the batch file report any errors? at first but then i redid the thing and then it didnt
did you change the graphics settings manually? no
are you using any other mods? i tried to do the no cars limit mod to fix my issue
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5324609/asiloader.log)

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5324610/ScriptHookV.log)

**Comment by Skyrdolla** [comment]
nvm i fixed it

**Comment by reklawpeels** [comment]
> 
> 
> nvm i fixed it

Do you mind telling me what you did? I'm having the same problem but on Valve Index. It crashes to desktop while showing the "loading story mode" screen.

**Comment by Skyrdolla** [comment]
I went to older issues and found out that we might just have a old scripthookV. So i installed the new one and it worked!

**Comment by reklawpeels** [comment]
> 
> 
> I went to older issues and found out that we might just have a old scripthookV. So i installed the new one and it worked!

Wow thanks so much! This totally worked for me. I just grabbed the latest version of scripthookv and I was good to go.
