### ISSUE TITLE
Only showing my settings/hud

### ISSUE THREAD

**Issue by linkdaghanmer2** [LukeRoss00/gta5-real-mod#263]
im running quest 2 with cable link, 

1060 
i7 8700k

I installed it just like in the quicksteps with Rockstar launcher, and every time I opened it into story mode it crashed :)

so I decided hey maybe I'm dumb imma just do on steam, I do it exactly like the steps like 2 more times and get some message from steam that "GTA5 isn't compatible and it will show on desktop" something along that, amazing, and they are right I can only see the HUD on my Vr headset while gta5 Actual gameplay is just showing on my desktop. 

Before I was getting a script hook v error i fixed that took a couple of hours since this is the first time I ever done anything like this. it just had version compatibility errors.

Ive tried everything that ive seen maybe im missing something, I just love that i got like 3 different errors throughout this whole installation. but now i just have one error and I have no idea how to even begin fixing that but thank you if you actually fix this

Game runs fine im sure its nothing to do with hardware just some random issue that I got,

**Comment by linkdaghanmer2** [comment]
I saw that someone had gotten this fixed by manually changing VRAPI, Would anyone know how to change that :P

**Comment by LukeRoss00** [comment]
For Quest with the wired link you should not be using SteamVR, it's only going to mess up things. Be sure to follow exactly the steps outlined in the [release notes](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r6) and the [setup instructions](https://github.com/LukeRoss00/gta5-real-mod#quick-setup)

**Comment by RenatoLifestyle** [comment]
Also have the same issue. Blank screen only showing map and settings. Followed all the steps with Release 6 and I am not running SteamVR. 

I am on Oculus Quest 2 with cable link. 

 i7- 6700K 4GHz. 16Gb Ram. GTX 1080
I set RealConfig to- L

Perhaps its the new quest that it doesn't work with? Any help is very appreciated!

**Comment by RenatoLifestyle** [comment]
Never mind, I figured it out. I had to manually change the script hook v files. Extracting the RaR was not overwriting the old ones. New to this. Game play is awesome. Thanks for the mod!

**Comment by LukeRoss00** [comment]
Great that it was only a Script Hook V issue and that it now works with your Quest 2! With your GTX 1080 you should be able to use at least Medium config, if you don't mind some occasional frame rate drops

**Comment by nobodyspecial306** [comment]
Can someone tell me how to do this as I have tried getting this to work 5 times now
Cpu intel core i7 2700k 
Gpu GTx 1060 6gb 
Presets tried
Medium
And low

**Comment by LukeRoss00** [comment]
@nobodyspecial306 What exactly are you having trouble with? Also, please read #239 and provide the required information

**Comment by nobodyspecial306** [comment]
Hi Luke dw all fixed now :) only having issue with recentreing character now :)

**Comment by linkdaghanmer2** [comment]
yes i did exactly like in the steps, just tried a couple of time without ever opening steamvr , when i do that only the HUD appears On vr and the game on my pc

**Comment by LukeRoss00** [comment]
@linkdaghanmer2 Please attach here your `asiloader.log` and `ScriptHookV.log` files
