### ISSUE TITLE
NUMPAD 0    Toggle position tracking - on at start - Include in RealVR.ini?

### ISSUE THREAD

**Issue by Dark-CSS** [LukeRoss00/gta5-real-mod#264]
Hi, I would like to know if there's any way to include the "NUMPAD 0    Toggle position tracking - on at start" hotkey in the "RealVR.ini" file, so I can automatically start the game with it off instead of having to disable it manually everytime I start the game.

By the way, thanks for the mod, it's one of the best VR experiences available in the world today.

**Comment by LukeRoss00** [comment]
Thanks for your appreciation, it means a lot to me!

Yes, there is a way: just use a text editor like Notepad to add the line `PositionTracking = 0` to the end of the .ini file. The option will then default to off, although you'll still be able to turn it on with the hotkey.

**Comment by Dark-CSS** [comment]
Thank you so much! You're an awesome modder. I hope we get someone like you for the upcoming Cyberpunk 2077 soon!
