### ISSUE TITLE
Oculus Quest 1 game scene shake when i move

### ISSUE THREAD

**Issue by banner90** [LukeRoss00/gta5-real-mod#265]
oculus quest 1 issue:
i connect VD，i can play and more better, but the game scene will shake when i turn my head left or right, it's not comfortable.
>Hardware & Software
CPU:i5-7500
GPU:GTX1070TI
VR headset model:Oculus Quest 1
game version and build:v1.0.2060.1（Epic version）
release of the mod:Release 6
=========
"There was another mod out there that made them somewhat usable by removing your in-game character's body",i want to know what's the name of the mod?

**Comment by LukeRoss00** [comment]
For the moment the mod only tracks correctly if you connect the Quest to the PC with a USB cable, but I'm working together with the developer of Virtual Desktop to see if we can make it work wirelessly... Fingers crossed!

**Comment by banner90** [comment]
thank for responding.
i'm not sure if the issue only happen to me(Quest1).you can try it with other devices(the shake issue).can you send  me a play video on youtube and i will send my video to help you fix it.

**Comment by LukeRoss00** [comment]
It happens to everybody when using Virtual Desktop, thanks for the video offer but it's not needed because it's easily reproducible

**Comment by LukeRoss00** [comment]
Unfortunately the attempts to make Virtual Desktop work with the mod were unsuccessful. There are probably some limitations in the Oculus mobile SDK that make it impossible for third-party applications to support alternate eye rendering correctly. I have updated the README to indicate that a USB connection is needed for the Quest and Quest 2.

**Comment by jamie01** [comment]
That's a real shame, hopefully Oculus hurry up with 90hz support for Quest Link as I assume that will help reduce the doubling effect of the alternate eye rendering, given it's currently only 36fps per eye when limited to 72hz
