### ISSUE TITLE
instructions to install mvga mod

### ISSUE THREAD

**Issue by rikiwelche** [LukeRoss00/gta5-real-mod#267]
Good morning all,
I tried to install the MVGA mods after installing the ReAL mods (which works great with my RTX 2060 and my oculus rift), but the game did not launch anymore! crash "critical error can't find native xxxx
I followed a youtube tutorial but maybe you don't have to install everything so here are my questions:
-in what order should Real and MVGA be installed?
-Do you have to install scripthook 5 again?
-Do you just install the .oiv file from openIV?
-should you install reshad? I don't think so in view of Lukk's installation instructions
- do you have to install L.A vegetation, L.A roads and water4k?
-idem for simple trainer, but I don't think that creates any problems.
sorry for the translation, i'm french!
thank you

**Comment by LukeRoss00** [comment]
I'm not even sure that M.V.G.A. (which hasn't been updated in a while that I know of) still works with the most recent versions of GTA V. I would suggest trying only M.V.G.A. with the base game, i.e. without my mod, and if you can make it work reliably then add my mod later.

There is no need to install Script Hook V again, and ReShade should not be used because it's not compatible with VR at the moment. The other things (L.A. vegetation, roads and water) are not needed to run M.V.G.A., so I would suggest waiting to install them until you have everything else working.

**Comment by rikiwelche** [comment]
Ok thanks I will try this
Thanks!

**Comment by rikiwelche** [comment]
Hello,
before following your instructions, I gradually uninstalled the mods (those that could be) and came to the conclusion that it was the (native) trainer that crashed the game!
I still have everything re-installed in the recommended order and everything works very well, even with the evolution of the native trainer (enhanced native trainer).
as well as the LA roads LA vegetation and water 4k mods!
the only doubt is whether the mods are well supported by the game (apart from the trainer) because apart from the visual appreciation of the graphical evolution, I don't think there is a way to verify this (uninstall the files or move the mods folder or scriptthook files ...).
I hesitate to try the NaturalVision Remastered mods ... how did you go about testing all these mods one after the other? it is not obvious to uninstall one properly.
in any case, it's great work on VR, no worries on my oculus rift with an rtx 2060.
thank you

**Comment by LukeRoss00** [comment]
If you followed the recommendation that OpenIV gives to create a `mods` folder, it is actually very easy to uninstall a mod or temporarily "park" it out of the way: just rename the `mods` folder to some other name (for example `MVGAmods`), create a new empty `mods` folder, and install the other mod. Then you can switch between the two just by renaming the folders.

**Comment by rikiwelche** [comment]
ok thank you for this very simple advice after all!
All the best
