### ISSUE TITLE
Use mod with VorpX?

### ISSUE THREAD

**Issue by OneToo** [LukeRoss00/gta5-real-mod#270]
There was another GTA V VR mod that allowed me to use their implementation with VorpX.  I know that this wasn't the goal of your mod, but i can play GTA V wirelessly via VorpX  and Virtual Desktop with G3D or Z3D without the jitter.   Is it possible to add a mode that doesn't perform VR injection, but allows your general VR enhancements such as Cutscenes, HUD, FOV, Head Tracking?

**Comment by LukeRoss00** [comment]
Unfortunately the two aspects are not separable. Due to the way the mod was written, it's impossible to use a separate program for VR rendering.
