### ISSUE TITLE
Black Screen or Flat Normal Map

### ISSUE THREAD

**Issue by FoamHistory** [LukeRoss00/gta5-real-mod#272]
Hey, So I went through a lot of the black screen reports and haven't seen this exact issue. I am attaching all of my logs including the RVR log.

I have attempted a few reinstalls, each time carefully following the steps and have the video settings set to low on this last run (started with medium). I had issues similar to what a lot of people were reporting in the form of the black screen with just the menus and overlay appearing. In my most recent attempt at running the game, a few seconds after opening to a black screen and returning from the pause menu I had visuals like this appearing on a flat plane in front of me. From what I can tell, this looks like the games normal maps.

![20201116004811_1](https://user-images.githubusercontent.com/35437359/99231801-1b963e00-27bf-11eb-9f67-4f51c935766b.jpg)

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5545116/RVRLog.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5545117/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5545118/asiloader.log)

Edit: I am playing on the Rift S using the steam version of the game. 

Graphics: NVIDIA GeForce GTX 1060 3GB
Processor: Intel i7-8700 CPU @3.2

**Comment by LukeRoss00** [comment]
You are using a very old release of the mod. Please always make sure to run the last release (currently r6) and to update Script Hook V after reinstalling the mod

**Comment by FoamHistory** [comment]
Ah I see. The article that appears on google as the first result links to release 4 and I didn't notice. Works like a charm now. Thanks!
