### ISSUE TITLE
Seeing double EVERYWHERE...

### ISSUE THREAD

**Issue by Hanselljlh** [LukeRoss00/gta5-real-mod#274]
CPU = i7-9770 / 9970?
GPU = GTX-1080 x2 /w SLI
VR HM = Oculus Quest 2
Game ver = Steam version most recent build as of 11.20.2020 (not at PC to check)
R.E.A.L. Mod ver =  6
Follow instructions = yes
Rconfig = H - tried all
Errors = No
Change Graphics = yes/no - default or changing everything makes no change. 
Other Mods = No

Ok so I have read though everything and fixed my first issue that was I was only getting one eye then using the hotkey to toggle stereo rendering does move it from eye to eye and both. When it is on both it is not syncing left with right, e.g. close either eye and all is normal. It says that Stereo rendering is default so I am wondering if I have something not set right since I have to go in an hotkey it anytime I re run the realconfig file. Like I said I have tried everything I can think of as far as graphics setting in game. I have run realconfig on both High and Low and manually set everything to low so it isn't the PC in and of itself. 

Thanks for any help

**Comment by LukeRoss00** [comment]
Are you using the Link cable? Virtual Desktop doesn't work with this mod.

If you are already, I could take a look at your logs to check whether something else might be wrong with your config. Use a text editor like Notepad to add the line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder: please attach it here together with your `asiloader.log` and `ScriptHookV.log`.

**Comment by Hanselljlh** [comment]
Thank you for the reply here is your request:

I am using a USB 3.1 gen2 cable getting 2+gbs. 
Ok I am pretty sure I chopped up the RVRLog correctly. If you just need the start or end then all you need is 1 and 4. 

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5577278/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5577279/asiloader.log)

[RVRLog1.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5577291/RVRLog1.txt)
[RVRLog2.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5577292/RVRLog2.txt)
[RVRLog3.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5577293/RVRLog3.txt)
[RVRLog4.txt](https://github.com/LukeRoss00/gta5-real-mod/files/5577294/RVRLog4.txt)

**Comment by LukeRoss00** [comment]
The log indicates that you have lots of missed frames. Also, it seems that you are using MSAA 4x, which is completely overkill and will destroy your frame rate.

You can use the `N` hotkey to toggle an fps indicator in the lower right corner of the VR image. Make sure that you are getting a high enough frame rate for a smooth experience.

Finally, I see that you have a SLI system. The mod has never been tested with SLI, and it might be causing the artifacts that you're seeing. Did you run the game with SLI on or off?

**Comment by Hanselljlh** [comment]
Well we now know that the SLI is fully incompatible!!! When I turn on the FPS I stay at (M or A) 51-59. Don't see any smoothness difference but still seems frame droppy.
