### ISSUE TITLE
Choppy gameplay (even on low).

### ISSUE THREAD

**Issue by QQQQQQ2000** [LukeRoss00/gta5-real-mod#276]
Hi Luke. 
First thanks for great work!

I have some problem to enjoy the game.
In my opinion game is using my internal video card instead of my GTX. Why? Because i'm monitoring the performance and my GPU is not even warm and way below 20% usage.

I started "RealConfig.bat" and something went wrong so i manually changed settings.xml 

<ScreenWidth value="1080" />
<ScreenHeight value="1080" />

and additionally i changed VideoCardDescription to match my card
old value: ...1080
new value:  <VideoCardDescription>NVIDIA GeForce GTX 1060 3GB</VideoCardDescription>

The file "commandline.txt" in main game folder is:
-width 1080
-height 1080
-ignoreDifferentVideoCard

I also tried low settings but it didnt help - extremely choppy (even first cutscene)
I don't know what else can i do :(

My specs are:
CPU: i5-9600k
GPU: Gtx 1060 3gb
VR headset model: Quest2
game version and build: 1.0.2060.1
release of the mod: "GTAV_REAL_mod_by_LukeRoss_r4"
did you follow all the Quick setup steps carefully, in particular step 4? Yes. I have epic version so N/A
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? M and also tried L
did the batch file report any errors? Yes
"
The system cannot find the path specified.
The system cannot find the path specified.
        0 file(s) copied.
        1 file(s) copied.
"
did you change the graphics settings manually? Yes
are you using any other mods? No

**Comment by QQQQQQ2000** [comment]
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5602716/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5602720/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
Please always use the latest release of the mod which currently is [Release 6](https://github.com/LukeRoss00/gta5-real-mod/releases)

**Comment by QQQQQQ2000** [comment]
I was blind i didn't see it:) Thanks man and have a good day!
