### ISSUE TITLE
Crashes when loading into story

### ISSUE THREAD

**Issue by ColonelCoon** [LukeRoss00/gta5-real-mod#278]
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5617497/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5617498/asiloader.log)

The game loads into the menu just fine, then I load into the story for about 10 seconds then it crashes. I've tried redownloading the game but it hasn't worked.
CPU: I7 7700
GPU: GTX 1070
VR headset model: Oculus Rift S
game version and build: 1.0.2060.1 on Epic Games
release of the mod: r6
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Yes
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No

**Comment by LukeRoss00** [comment]
You need to update Script Hook V from http://www.dev-c.com/gtav/scripthookv/ (you have version v1.0.2060.**0** but need v1.0.2060.**1**)

**Comment by SmokeyVH** [comment]
> You need to update Script Hook V from http://www.dev-c.com/gtav/scripthookv/ (you have version v1.0.2060.**0** but need v1.0.2060.**1**)

Sadly this is wrong, even after having updated scripthook the game immediately crashes 10 seconds into loading in. Very similar specs to OP. Game works fine without the VR mod but the moment it along with the latest scripthook is installed the game crashes.
