### ISSUE TITLE
Game locked at 6 fps

### ISSUE THREAD

**Issue by RealSkyr0** [LukeRoss00/gta5-real-mod#279]
When I start it the menu is fine until I'm actually loaded into the game. At that point the game is stuck at 6 fps and each eye is flickering/blinking. I'm using the Oculus Rift CV1 and I have an RTX 2060 OC along with a Ryzen 5 3600x, so performance is not the issue. Game normally runs at 110-120 fps.

**Comment by LukeRoss00** [comment]
Very low frame rate usually means that you are using an outdated version of the mod. Please update to Release 6 and then download the latest Script Hook V from http://www.dev-c.com/gtav/scripthookv/

**Comment by RealSkyr0** [comment]
Thank you, that fixed it, but I still feel pretty dizzy after playing for 30 min, which is mostly due to the alternating rendering of each eye, but I don't think you can change that.

**Comment by LukeRoss00** [comment]
To get yourself used to the mod (which also has smooth turning and involuntary camera movements) you might want to try monoscopic mode first. You can toggle it using the `NUMPAD2` button after activating the mod hotkey with `F11`.

Also, if you find yourself getting queasy it is very important that you keep a consistent high frame rate (use the `N` hotkey to check) and that you take frequent pauses _before_ getting sick.
