### ISSUE TITLE
3FPS in game after installing the mod

### ISSUE THREAD

**Issue by TheApexDevil** [LukeRoss00/gta5-real-mod#281]
so i installed the mod but only get 3fps whats the deal here

**Comment by LukeRoss00** [comment]
The deal is that Google keeps sending people to an old release which is almost a year old and which has been made unusable by Rockstar's game updates.

Update the mod to [Release 6](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r6) and then also update Script Hook V from http://www.dev-c.com/gtav/scripthookv/
