### ISSUE TITLE
does this not work anymore? scrithook error

### ISSUE THREAD

**Issue by Battletoad08** [LukeRoss00/gta5-real-mod#282]
I wanted to try the VR out but everytime I load the game it says scripthook not right version or something. I go to his page and download the latest but get the same error.

Is it because I am trying to use a vive headset?

**Comment by LukeRoss00** [comment]
It does work. You might have extracted `ScriptHookV.dll` to the wrong folder. Check that it is in the same folder as `GTA5.exe` (not for example in a `bin` subfolder) where the game can find it, and make sure by hovering on it with the mouse that it is the correct version 1.0.2060.1.

**Comment by Battletoad08** [comment]
Thanks for the reply, I put the files in the correct places atleast 3 times before I got it to work. It wouldnt work when I would click play from steam on my desktop. For some weird reason I started it by mistake directly from the exe in the game folder and it worked all of the  sudden.

**Comment by Battletoad08** [comment]
Well, I installed MVGA and the included enb and now the game wont launch in VR lol. The smaller screen pops up like it is in VR but my VR headset is just showing steam VR home. :(

**Comment by LukeRoss00** [comment]
Please make sure to check out the [README](https://github.com/LukeRoss00/gta5-real-mod). M.V.G.A. is very good and compatible with my mod but you should not use ENB, ReShade or other 3rd party mods that capture the game backbuffer, because that breaks VR.

**Comment by Battletoad08** [comment]
Thanks. Im trying to figure it out.
Now I am getting scripthook error CORE :an exception occurred while executing RealVR.asi id44

**Comment by Battletoad08** [comment]
Dont mean to bug you here. I got it working by just redoing it all but just one quicl question. The graphics seem to jutter looking side to side, like side stepping. Sort of like the screens over lap each other. Can I fix that? I have a Fast pc. Ryzen 3700x and a 2070super.

**Comment by LukeRoss00** [comment]
Some image doubling when you strafe is normal with AER, see the first two entries in the FAQs: https://github.com/LukeRoss00/gta5-real-mod#faq
