### ISSUE TITLE
Offtopic: Cyberpunk 2077 R.E.A.L. Mod

### ISSUE THREAD

**Issue by VR-Punk** [LukeRoss00/gta5-real-mod#283]
Are you going to mod Cyberpunk 2077, too ? The performance with deactivated rtx but activated performance mode of DLSS is very good ! Is it possible to use alternate rendering in dx12 in the foreseeable future ?

**Comment by LukeRoss00** [comment]
It's a little early to tell. What figures are you referring to? The benchmarks I found are still preliminary, and from what I've seen it seems that only RTX 3090 cards are capable of running the game at resolutions and frame rates that come somewhat close to what would be needed in VR, even with alternate eye rendering.

Considering the price of the cards and the fact that it is exceedingly hard to even get your hands on them at the moment (except if you're a scalper or a YouTuber), I believe that very few people would be able to take advantage of a mod.

But who knows, perhaps in a few months?

**Comment by VR-Punk** [comment]
I will send you detailed benchmarks with screenshots after they rolled out the drm free final day one patch tonight. Is a Resolution of 2160x2160 still the best choice for your needs ? The most important thing to get very high fps is to activate the ultra performance mode of DLSS 2.0, but deactivate Raytracing completely ! You can't find such benchmarks in the web until now.

**Comment by VR-Punk** [comment]
hi, in 2160x2160 (!) and a FOV 100 in medium settings and DLSS Ultra on and RTX off i got global average 80fps, the minimum frames are average 60 fps with a RTX 3080. For RTX 2000 Cards 1080x1080 is a better choice. Is that enough for alternate eye rendering ?

**Comment by LukeRoss00** [comment]
Well, it might be enough for some users, although the game appears to be far more taxing than GTA V.

For reference, on my GTX 1080 Ti, GTA V runs at the same frame rates that you are mentioning with an internal resolution of 3000x3000 (without any DLSS upscaling of course, it is the true native resolution), and the lowest settings that I package with the mod achieve an internal resolution of 1200x1200, which looks very pixelated in the headset despite being more than what you propose for RTX 2000 cards.

**Comment by Jesusavestill** [comment]
I played it on my 1080ti and vorpx. It seemed to work fine. Would really like to see a lukeross real mod for it.

**Comment by Jesusavestill** [comment]
Game is trash and full of garage. Explicit billboards and ads everywhere,even with the nudity censor. I returned it.

**Comment by VR-Punk** [comment]
whimsical
