### ISSUE TITLE
Game Memory Error on inital load

### ISSUE THREAD

**Issue by Yatzii93** [LukeRoss00/gta5-real-mod#288]
CPU: i7 - 8700K CPU
    GPU: 2080Ti
    VR headset model: Vive Pro
    game version and build: latest
    release of the mod: latest
    did you follow all the Quick setup steps carefully, in particular step 4? Yes
    which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Tried them all
    did the batch file report any errors? No
    did you change the graphics settings manually? No 
    are you using any other mods? No

Fresh GTAV aside from playing a bit of online.

Everything is up to date I have the lastest scripthook and I'm using the temp fix using a older version of the exe due to scripthook not being on the lastest version yet.

Everything loads fine until I press Storymode. It starts loading then errors out with the popup here before crashing completely. I've tried a number of things to resolve it to no avail. The only thing I haven't tried is completely fresh install but it seems unneccesscary considering I haven't used mods on this client.

![image](https://user-images.githubusercontent.com/47720837/102353774-74651c00-3fa1-11eb-8a83-9a6965ce2d6d.png)

Any help would be great. Thanks

**Comment by Yatzii93** [comment]
Going to try a fresh install anyway just to rule it out. Will report back

**Comment by LukeRoss00** [comment]
Never seen this one. From a quick Google search, it seems that this kind of heap allocation error usually occurs if you install too many add-on cars. You could check out https://www.gta5-mods.com/tools/heapadjuster

**Comment by Yatzii93** [comment]
Ye it's odd I havent got any mods installed. I'm downloading it fresh now so we'll see if it comes up again. I did go online with the old client so who knows  ¯\_(ツ)_/¯

**Comment by Yatzii93** [comment]
Seem's I'm stuck on this issue, completely fresh install. Installation as stated and the error still appears after pressing "story mode". So odd.

**Comment by coru182** [comment]
Try running a memtest. I was getting similar errors and it turns out one of my ram dimms was bad. Once I replaced it, it was all good. You can always remove the bad one if you have more than one and play with less ram in the meantime or if short on cash.

**Comment by Yatzii93** [comment]
Ahhh I had a feeling it was related to using the old exe. The game runs fine without the mods as a fresh install so I was pretty confident it was to do with the mod or atleast the current process.

**Comment by Yatzii93** [comment]
This issue has been resolved by the new scripthook update. Closing.
