### ISSUE TITLE
[Valve Index] Stuttering both inside and outside GTA after loading my save file

### ISSUE THREAD

**Issue by celowsky** [LukeRoss00/gta5-real-mod#289]
### Summary
I've been having a similar issue to @Faburden #286. What's particularly interesting to me is my entire PC seems slow to respond to any input after GTA V loads my story mode save, and even affects other programs outside the game (e.g. delayed key presses and mouse movements). However, Windows Task Manager indicates my CPU usage is somewhere between 36-39% and the GPU usage is between 6-8%. It also says memory usage is around 60%, and my PC doesn't sound like it's working too hard. Also, when I enter the pause menu all my applications, including GTA V, become much more responsive. The save file I'm loading starts with Trevor near the safehouse at the Strawberry / Elgin Ave intersection, so it's not the most active part of Los Santos. 

#### PC Specs:
- GeForce Game Ready Driver Version 460.89
- Nvidia RTX 2070 (default)
- Nvidia GTX 1060
- Intel Core i7 8700k
- 16GB RAM
- Two displays other than the Valve Index. Both are 1080p but one is newer and supports a
  GSYNC'd 144Hz refresh rate (not sure if GSYNC would be an issue here, but I figured I
  should include it just in case).

#### Headset Specs:
- Valve Index
- SteamVR **1.15.12**
- Using one base station, instead of two, for convenience and also because the mod is meant to be played sitting down.
##### Global SteamVR settings
- Refresh Rate is **80Hz**
- Render Resolution is **Custom** with the Resolution Per Eye set to **2016 x 2240 (100%)**. _Note: The issue does not improve if I reduce this to the minimum value_.
- Motion Smoothing is **off**

#### Mod Installation: 
I start by uninstalling GTA V from Steam interface. Then I deleted the folder <SteamLibrary>\steamapps\common\Grand Theft Auto V\, and reinstalled GTA V via Steam. Before running the RealConfig.bat file, I booted GTA once to set the settings instructed in Step 2 of this repo's Quick Setup section in the readme. Subsequently, I optimized GTA V using the Nvidia GeForce Experience tool. Afterwards, I navigated to GTA V's installation directory, ran RealConfig.bat, and chose option H. No errors were reported by the script. I did not change the game's graphics settings at any point after this, and I am not using any other mods.

#### Game Info
GTA Version: 1.0.2060.1
Mod Version: GTAV_REAL_mod_by_LukeRoss_r6.rar
Here's my settings.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>

<Settings>
  <version value="27" />
  <configSource>SMC_AUTO</configSource>
  <graphics>
    <Tessellation value="3" />
    <LodScale value="0.500000" />
    <PedLodBias value="0.200000" />
    <VehicleLodBias value="0.000000" />
    <ShadowQuality value="1" />
    <ReflectionQuality value="2" />
    <ReflectionMSAA value="0" />
    <SSAO value="2" />
    <AnisotropicFiltering value="16" />
    <MSAA value="0" />
    <MSAAFragments value="0" />
    <MSAAQuality value="0" />
    <SamplingMode value="9" />
    <TextureQuality value="2" />
    <ParticleQuality value="2" />
    <WaterQuality value="2" />
    <GrassQuality value="3" />
    <ShaderQuality value="2" />
    <Shadow_SoftShadows value="3" />
    <UltraShadows_Enabled value="false" />
    <Shadow_ParticleShadows value="true" />
    <Shadow_Distance value="1.000000" />
    <Shadow_LongShadows value="false" />
    <Shadow_SplitZStart value="0.930000" />
    <Shadow_SplitZEnd value="0.890000" />
    <Shadow_aircraftExpWeight value="0.990000" />
    <Shadow_DisableScreenSizeCheck value="false" />
    <Reflection_MipBlur value="true" />
    <FXAA_Enabled value="false" />
    <TXAA_Enabled value="false" />
    <Lighting_FogVolumes value="true" />
    <Shader_SSA value="true" />
    <DX_Version value="2" />
    <CityDensity value="1.000000" />
    <PedVarietyMultiplier value="1.000000" />
    <VehicleVarietyMultiplier value="1.000000" />
    <PostFX value="3" />
    <DoF value="false" />
    <HdStreamingInFlight value="false" />
    <MaxLodScale value="0.000000" />
    <MotionBlurStrength value="0.000000" />
  </graphics>
  <system>
    <numBytesPerReplayBlock value="9000000" />
    <numReplayBlocks value="36" />
    <maxSizeOfStreamingReplay value="1024" />
    <maxFileStoreSize value="65536" />
  </system>
  <audio>
    <Audio3d value="false" />
  </audio>
  <video>
    <AdapterIndex value="0" />
    <OutputIndex value="0" />
    <ScreenWidth value="1080" />
    <ScreenHeight value="1080" />
    <RefreshRate value="60" />
    <Windowed value="2" />
    <VSync value="0" />
    <Stereo value="0" />
    <Convergence value="0.950000" />
    <Separation value="31.999695" />
    <PauseOnFocusLoss value="0" />
    <AspectRatio value="0" />
  </video>
  <VideoCardDescription>NVIDIA GeForce GTX 1080 Ti</VideoCardDescription>
</Settings>
``` 

I also started playing with the RealVR.ini file, since I couldn't determine whether an **F11** press followed by **n** or **N**(shift + n) was displaying the FPS. After using this modified file, I saw M8 show up in turqoise in the bottom left corner of my headset's display.
```ini
[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 1

; 0           Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left, right) - right at start
DominantEye = 2

; Y           Select heading control (always, only when aiming, never) - always at start
HeadingControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 1

; End         Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 0
```

Also here's what fpsVR looked like while I was walking around Elgin Ave:
![fpsvrForGta](https://user-images.githubusercontent.com/5439675/102475521-94d3bb80-401f-11eb-8bc1-8f3cf594f031.gif)

#### Logs
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5708675/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5708679/asiloader.log)

Any advice on how I could improve my FPS?

**Comment by LukeRoss00** [comment]
Thank you for providing so much detailed information!

Let's see if the mod's own log tells us anything. Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder: please attach it here.

**Comment by celowsky** [comment]
@LukeRoss00 I'm not sure I'm looking in the right path. I'm checking in <STEAM_LIBRARY>\steamapps\common\Grand Theft Auto V, but I'm not seeing a file in there called RVRLog.txt after following your instructions.

**Comment by LukeRoss00** [comment]
That is the correct folder. Could you check its permissions to make sure that the directory is writable from your user? Although Steam usually gives the user full control of the game's directory...

**Comment by celowsky** [comment]
You're correct about the permissions. They were already set properly. I was trying to replicate the problem again by spending more time in Los Santos than before, and I have encountered an error state. I can see parts of the GTA world faded into parts of the steam grid overlay, and I'm unable to control my character. I'm going to give it a little bit to see if it crashes. Otherwise, there does now appear to be an RVRLog.txt in my GTA V directory.

**Comment by LukeRoss00** [comment]
I'm beginning to think that the workaround to return to the previous game version is not working correctly. Perhaps it's best to just wait a few days for the updated Script Hook V to come out :-)

**Comment by celowsky** [comment]
Agreed, but for future reference here's that RVRLog.txt.
[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5709979/RVRLog.zip)
I had to compress it to fit Github's file size limit.

**Comment by LukeRoss00** [comment]
OK, the log indicates that you are using Release 4 of the mod, so that explains the low frame rate. You should update to Release 6. I know that you wrote in your original post that you used `GTAV_REAL_mod_by_LukeRoss_r6.rar`, but there must have been a mistake somewhere along the line (it's understandable, because Google keeps pointing people to the old release)

**Comment by celowsky** [comment]
[Doh!](https://giphy.com/gifs/season-3-the-simpsons-3x12-l0G18G3m69vQCOddm)
The mod is working now at a normal speed and everything looks good. Thanks for your work on this project. It looks great!
