### ISSUE TITLE
Compatibility with Rockstar Games Launcher version of GTAV?

### ISSUE THREAD

**Issue by Enyakk** [LukeRoss00/gta5-real-mod#29]
Instead of a GTA5.exe I have a PlayGTAV.exe and GTAVLauncher.exe. The VR mod doesn't seem to engage with this version. Can compatiblity be added?

**Comment by masher42** [comment]
I have the Rockstar Games Launcher version and it works. Are you sure you don't have GTA5.exe ? It should be in the same folder as the other two.

**Comment by Enyakk** [comment]
I just double-checked. I am positive. That's quite weird I don't know why there should be a difference.
