### ISSUE TITLE
RTX3090 and Cosmos Elite stutter on head turning

### ISSUE THREAD

**Issue by Teledougie** [LukeRoss00/gta5-real-mod#294]
Hi Luke. Firstly thank you so much for your work on this. I am blown away with how good it looks. The problem i am having is severe judder when turning my head. I have read this is something to do with motion smoothing but I can't turn this off in steamvr as global isn't available and the game isn't in the vr settings game list. Any ideas?

**Comment by LukeRoss00** [comment]
Other users had trouble with the Cosmos in the past. There seem to be some issues in its runtime that cause problems with alternate eye rendering. I don't think that a solution was ever found, but you might try reading through #202 to see if you get any useful hints :-/

**Comment by Teledougie** [comment]
Thanks for your feedback. Using vorpex now. Not as good as the mod but at least I can play it. Keep up the good work. Cheers.
