### ISSUE TITLE
Mod not work with Oculus link

### ISSUE THREAD

**Issue by Temka193** [LukeRoss00/gta5-real-mod#295]
I copied the mod to the game folder, launched RealConfig.bat and selected High. Then I just start the game on Steam, it starts in a small window in the center of the computer screen.
At this point, I have Oculus Link running on my Oculus Quest 2 device, nothing else happens on the headset.
What am I doing wrong?

CPU: Intel Core I9 9900
GPU: Geforce GTX 1080 Ti
VR headset model: Oculus Quest 2
game version and build: steam version, build 2189
release of the mod: 7
did you follow all the Quick setup steps carefully, in particular step 4?
yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat?
yes
did the batch file report any errors?
no
did you change the graphics settings manually?
yes
are you using any other mods?
no

**Comment by anasfizazi** [comment]
@Temka193 Add GTA v to your oculus library then launch it from there

**Comment by Temka193** [comment]
@anasfizazi I added, the game is still not displayed

**Comment by LukeRoss00** [comment]
@Temka193 Please attach here your `RealVR.ini`, `asiloader.log` and `ScriptHookV.log` files so I can take a look at them

**Comment by Temka193** [comment]
@LukeRoss00 
[logs.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5732215/logs.zip)

**Comment by LukeRoss00** [comment]
The last line in the `ScriptHookV.log` file is odd. Just 40 seconds after loading the mod, Script Hook V is unloading it.

Are you trying to go online perhaps? Modding is supported only for Story Mode, not for GTA Online.

Also, you wrote in your first post that you modified the graphics settings manually. What changes did you make?

**Comment by Temka193** [comment]
I am trying to enter story mode. game menu should show on oculus device?
I changed the camera and gamepad settings in accordance with the instructions. 
also, before installing the mod, I changed the graphics settings for my computer, I no longer remember which ones

**Comment by LukeRoss00** [comment]
Yes, the menus and (once finished loading) the in-game world should be displaying on the VR headset automatically.

Did you make sure that "Use Desktop Game Theatre while SteamVR is active" is **unchecked** in the GTA V Steam properties page?

**Comment by Temka193** [comment]
> Yes, the menus and (once finished loading) the in-game world should be displaying on the VR headset automatically.
I can't even see the menu

> Did you make sure that "Use Desktop Game Theatre while SteamVR is active" is unchecked in the GTA V Steam properties page?
yes

**Comment by LukeRoss00** [comment]
Let's see if the mod's own log tells us anything. Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder: please attach it here.

**Comment by Temka193** [comment]
added a line in the config and miraculously everything worked :)
the resolution is small and everything jittering when moving, it is not very comfortable to play, is that how it should be?

**Comment by LukeRoss00** [comment]
What line did you add?

**Comment by LukeRoss00** [comment]
Closing for lack of feedback, feel free to reopen if you have new information

**Comment by uyizz** [comment]
it keeps on saying unknown game version 

![2022-03-22](https://user-images.githubusercontent.com/102196387/159601425-abee6fe3-023c-4ac1-b387-17ebe5ce1340.png)

**Comment by uyizz** [comment]
![2022-03-22 (1)](https://user-images.githubusercontent.com/102196387/159601651-765583d6-990c-452b-a18d-75d5b080a4ea.png)
