### ISSUE TITLE
HP Reverb G2

### ISSUE THREAD

**Issue by Goresh** [LukeRoss00/gta5-real-mod#296]
Just got this headset and tried to get it going, no luck.
I was hoping it would go as it claims compatibility with WVM and Steam but no go. 
I have a Nvidia GTX 1070 card so it will run at half resolution if it does.

Thanks for creating this. Hope to use it some day soon :-)

**Comment by LukeRoss00** [comment]
Sorry for the late reply. The HP Reverb G2 works, as confirmed by several other mod users. Please post the information listed in #239

**Comment by ODEH67** [comment]
@Goresh  minimum specs for the G2 is 1080 or rtx 2070, if u mean that the headset is not running at all .. well mine doesnt run smoothly, it acts like it been foreced to run , so under pressure the headset will stop running . that has nothing to do with the mod .. it works actually with it better than steam games  @... im sending it back immediately, 5 months of waiting for a piece of garbage..

**Comment by Goresh** [comment]
> The HP Reverb G2 works, as confirmed by several other mod users. Please post the information listed in #239

Thanks for the reply. Yes, for some unknown reason I tried again yesterday and it worked just fine.

**Comment by Goresh** [comment]
> im sending it back immediately

Actually I am pretty happy with the HP Reverb G2. Even at half resolution.
