### ISSUE TITLE
Happy New Year Luke

### ISSUE THREAD

**Issue by Jesusavestill** [LukeRoss00/gta5-real-mod#297]
Thanks for a terrific mod,the updates and replies.

**Comment by Jesusavestill** [comment]
Would it be infringement on your mod if you could look at the www.grandtheftvr.com mod. It won’t work with oculus software but did on my pimax.I would just drop it into the gta5 directory and I had the option to activate and use motion controls or turn it off and use yours.It wouldn’t work without yours. Again it won’t work with oculus software.

**Comment by LukeRoss00** [comment]
Thanks and happy 2021 to you!

As you know, [I don't think](https://github.com/LukeRoss00/gta5-real-mod#keyboardmouse-controller-aiming) that motion controls are a good fit for GTA V. Also, mixing the two mods has never been a supported configuration, and crayfishery's mod doesn't work with the Oculus runtime, as you mentioned.

That said, you might try forcing my mod to render in SteamVR mode by setting `VRAPI = 2` in the `RealVR.ini` file.

**Comment by Jesusavestill** [comment]
It works,thanks so much.

**Comment by Jesusavestill** [comment]
I notice when going through steamvr after changing VRAPI 0 to 2...I get lower FPS.Going back to default and straight oculus runtime,I get the 90fps. Thanks for this info and option to use.

**Comment by LukeRoss00** [comment]
You're welcome! As you noticed, unfortunately, using an Oculus headset through SteamVR leads to worse performance than the native Oculus SDK. That's just the way it is with most (if not all) games, and GTA V is no exception.

**Comment by Jesusavestill** [comment]
Well thanks,I wouldn’t be able to play it without your software.
