### ISSUE TITLE
Stereoscopic view is uncomfortable when rotating camera via in-game

### ISSUE THREAD

**Issue by colthreepv** [LukeRoss00/gta5-real-mod#298]
I have reinstalled GTA5 just for this mod 😃 
So I have this:
- latest GTA5 from Steam
- Oculus + Oculus Link + Quest2
- Disabled ASW from Oculus Tray Tool
- Release 7 Mod

hardware high, but not special, 8700K + 1080ti

The game looks smooth and also turning the head while playing is smooth, but turning the camera, or when the camera follows the car when driving, it gives an uncomfortable feeling

I am not sure this can be recorded in a video, I will try tho

EDIT:  
Attached google public video, on recording it shows much less than in VR, but it's still noticeable.  
This was taken from Oculus Mirror
https://drive.google.com/file/d/1JWs6RZSDpbqqeH8U3cfChJmIP11PBSvT/view?usp=sharing

Capture n2:  
https://drive.google.com/file/d/1dvx5vxSIRvE5z8DUkmOQ6cUi5WeJQG1b/view?usp=sharing

**Comment by LukeRoss00** [comment]
You seem to have lots of hitches / missed frames. Check your frame rate with the `N` hotkey (after enabling the mod shortcuts with `F11`, see https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys)

**Comment by colthreepv** [comment]
You are right. I cranked MSAA up and it hit framerate hard.

With 90fps there is still a difference between turning head and turning the camera, the camera gets much more blurred, but with high framerate doesn't make myself dizzy

I suppose it's just the game.  Great work Luke, I am astonished at the quality of this work
