### ISSUE TITLE
Game crashes with exit code 0xc0000005 (STATUS_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by JandyGambe** [LukeRoss00/gta5-real-mod#299]
When I load the game, it crashes just before entering story mode with exit code 0xc0000005.

**CPU:**
Ryzen 5 2600X
    **GPU:**
GTX 1650 Super
    **VR headset model:**
Oculus Quest (through steamvr)
    **game version and build:**
Rockstar Games Launcher, version 1.0.2189.0
    **release of the mod:**
r7
    **did you follow all the Quick setup steps carefully, in particular step 4?**
Yes
    **which settings did you choose (H/M/L) when running the batch file RealConfig.bat?**
L
    **did the batch file report any errors?**
No
    **did you change the graphics settings manually?**
No
    **are you using any other mods?**
No

Logs:

```
[2021-01-04 16:47:03.831] [DISPLAY] [18844] [gamelaunch] Launching game...
[2021-01-04 16:47:03.831] [DISPLAY] [18844] [gamelaunch]  Path: D:\Games\Rockstar Games\Grand Theft Auto V\GTA5.exe
[2021-01-04 16:47:03.831] [DISPLAY] [18844] [gamelaunch]  Command Line: "D:\Games\Rockstar Games\Grand Theft Auto V\GTA5.exe" @commandline.txt -rglLanguage=en-US
[2021-01-04 16:47:03.831] [DISPLAY] [18844] [gamelaunch]  Working Directory: D:\Games\Rockstar Games\Grand Theft Auto V
[2021-01-04 16:50:40.241] [DISPLAY] [18844] [gamelaunch] Game exited with code 0xc0000005 (3221225477)
[2021-01-04 16:50:40.248] [DISPLAY] [18844] [crashdetection] Game left no exit file.
[2021-01-04 16:50:40.248] [ ERROR ] [18844] [crashdetection] Exit code 0xc0000005 indicates a fatal game exit (reason: STATUS_ACCESS_VIOLATION)
```

RealVR.ini:

```
; GTA V R.E.A.L. mod Release 7

[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 0

; 0           Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left, right) - right at start
DominantEye = 2

; Y           Select heading control (always, only when aiming, never) - always at start
HeadingControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 0

; End         Activate gyro stabilization of view in vehicle - off at start
GyroVehicle = 0

;             Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 1

;             Select VR API to use (autodetect, Oculus, OpenVR, OpenXR) - autodetect by default
VRAPI = 0
```

I can't find my `asiloader.log` and `ScriptHookV.log` files.

**Comment by LukeRoss00** [comment]
What do you mean by "Oculus Quest (through steamvr)"? Are you using Virtual Desktop? If not, you should not need SteamVR

**Comment by JandyGambe** [comment]
I am using ALVR, which is a free application that I believe is similar to Virtual Desktop.

**Comment by LukeRoss00** [comment]
Although it might not be the root cause of your crash, ALVR is not supported with my mod. The only supported configuration for the Quest is through Oculus Link. Could you try with a wired configuration and without SteamVR?

**Comment by JandyGambe** [comment]
The same exact thing happened through Oculus Link. I would also like to mention that with ALVR, the Quest is treated like an Oculus Rift running through SteamVR.

**Comment by LukeRoss00** [comment]
Thanks for trying with Link. It must be something specific to your system then, because many users have reported success with the Quest (and Quest 2) via Link.

The `asiloader.log` and `ScriptHookV.log` files should always be found in the game folder (where `GTA5.exe` is). If they're not there, either something went wrong with your game installation, or your Windows user account does not have permission to write to the game folder. Could you check if it's just a permission problem? Otherwise a full game reinstall (with a full delete of the game folder) might be in order...

**Comment by JandyGambe** [comment]
I changed some permissions of the entire GTA folder and it worked.
