### ISSUE TITLE
Big distortion in Cutscenes.

### ISSUE THREAD

**Issue by kgian** [LukeRoss00/gta5-real-mod#3]
The game in first person seems good but the cutscenes seem kinda flat and with great distortion when I I move my head. Like they are greatly zoomed in. Is it how it is supposed to be?

**Comment by LukeRoss00** [comment]
Yes unfortunately, check the README [here](https://github.com/LukeRoss00/gta5-real-mod#cutscenes) for an explanation

**Comment by kgian** [comment]
Yes, I read the README about the cutscenes. If I had to just use a word for how they look it would be "flat". Squashed. I do not get sick or anything as I am a VR veteran but they are pretty unwatchable.

**Comment by cercata** [comment]
> If I had to just use a word for how they look it would be "flat"

Zoom in VR flattens things. Have you tried the hotkeys for removing the zoom from cutscenes ?

**Comment by kgian** [comment]
I tried the "." hotkey and it makes the cutscenes much more comfortable but of course there are weird glitches all over the place.

Also I did some performance testing. Low settings with 1080x1080 give me average 90fps on cv1. High settings give me around 60-70fps.  So it is low for me.
1080Ti and 7700K.

**Comment by sycspysycspy** [comment]
Close on of your eyes if the cut scenes make you uncomfortable.
