### ISSUE TITLE
RealConfig Closing not running 

### ISSUE THREAD

**Issue by Szklarski2012** [LukeRoss00/gta5-real-mod#300]
I cant open RealConfig the file right away closes, i followed every step to the letter and my game version is 1.0.2189 i changed game settings on fresh install then closed game copied the mod into game directory tried to run realconfig but it closes right away as i run it with out any prompts i got it on steam and i have steam vr settings like explained in the mod install readme, need some help thanks

**Comment by LukeRoss00** [comment]
There is a `PAUSE` command at the end of the batch file, so it should never close without asking for confirmation.

Maybe something on your system is preventing it from running altogether? Like an overzealous antivirus? Could you try running the batch file from a command (DOS) prompt?

**Comment by Szklarski2012** [comment]
how would i word the path in powershell i cant figure out commands in this thing the path of the batch file is C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V i cant seem to figure out the proper wording to type so it starts the .bat file

**Comment by LukeRoss00** [comment]
If you can't open CMD itself, it definitely means that your Windows installation is corrupt. You might ask someone knowledgeable with computers who lives near you to help you fix your PC, or you might try reinstalling Windows.

**Comment by Szklarski2012** [comment]
lol kind of though that might be the case with the CMD not turning on, ill contact windows i pay there bull crap 150 a year for there protection and remote repair services let them fix there crappy OS lol but thank you for your time and help i cant wait to play your amazing mod brother keep up the good work man you rock, i tried your mod already at a buddies and its killer man great work !!

**Comment by Szklarski2012** [comment]
and just a quick question after i get it working i got and i9 and rtx2070super with 32gb of memory can i run this on high you think once i set it up ?

**Comment by LukeRoss00** [comment]
Yes, it should run on High on your system without problems
