### ISSUE TITLE
Mission bugged?

### ISSUE THREAD

**Issue by virtualmisterl** [LukeRoss00/gta5-real-mod#301]
Hi luke

I'm having trouble on a strangers & freaks mission for trevor.
The mission is called exercising the demons.
It involves a bike race with a woman & is located at the top of a hill.
I've tried the mission several times & after the initial few seconds of cut scene it stops leaving my character unable to move & the next cut scene will not start.
The game does not freeze but just leaves the character in limbo.

I did get it to work by chance when pressing random  buttons & bringing up a menu & manually moving trevors character towards the couple on bikes but then I could not figure out how to disable the menu I somehow launched.
Is this your menu? Or maybe it was a menu from the trainer I have installed.
So I dont know for sure if this bug is due to using your vr mod but this is definitely not an issue on the normal flat version of the game which I have previously played.

It just seems that somehow the character needs to be moved toward them for the next cutscene to begin which then triggers the bike race 

My pc specs
8700k 
Rtx2080ti
32gb 3466
Valve index

Over 60 hours In with your vr mod

I have 2 mods installed
Brittish police vehicle pack
Advanced trainer

**Comment by LukeRoss00** [comment]
Hi! I just tried the mission with the latest game version (Steam) and I only have one cutscene at the beginning, where Trevor punches Mary-Ann's boyfriend and then they both climb on bicycles. At the end of the cutscene Trevor is already on the bike and the race starts.

So, I think it must be the other mods. Could you temporarily remove them to check?

**Comment by virtualmisterl** [comment]
Yes thats the one.
For me the camera at the start pans to them I believe & shows them arguing but then it wouldn't progress to the actual cutscene where trevor punches her boyfriend.
Thank you for looking into this.
I think you are right & it must be one of the mods.
I also noticed last night that there is a police vehicle in the compound behind the start location of this mission so maybe that is affecting it somehow.
I'll find out how to remove the mods & will report back once I've done it.
I'll close this issue as it seems this isn't related to your vr mod.
