### ISSUE TITLE
Closes loading in to Story Mode

### ISSUE THREAD

**Issue by Raging-Beard** [LukeRoss00/gta5-real-mod#303]
No error message or anything, just closes. I am using release 7 and ran realconfig again. It used to work perfectly. Thanks.
[Grand Theft Auto V.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5819806/Grand.Theft.Auto.V.zip)

i9 10900k
3090
Reverb G2
Rockstar version, 1.0.2189.0
Release 7
Steps followed, chose H, no errors
Using Natural Vision Remastered, Manual Transmission and realistic Driving 5

**Comment by LukeRoss00** [comment]
Hi, thanks for including the logs! Looking at them I noticed that your `ScriptHookV.log` terminates abruptly, before the mods are even launched (see [here](https://github.com/LukeRoss00/gta5-real-mod/files/5820909/ScriptHookV.log) for an example of how the log should appear).

That makes me think that your GTA V installation has become corrupted somehow, which is preventing Script Hook V from working correctly. I would advise a complete reinstall, adding the mods one by one to see if one of them is creating problems.

**Comment by WatYouNeed** [comment]
Hi LukeRoss,

I encountered a similar issue.

I never had any MOD installed on my Steam GTA5.  I extracted your r7 release into the main folder. Then I extracted the ScriptHook rar into the main folder. When unzipping I was prompted to overwrite ScriptHookV.dll and dinput8.dll.  I clicked Replace all.

When I launch the game from Steam.  A  warning message appeared saying "GTA5 does not support VR. It will appear on your desktop and may affect VR performance"

The intro game loads, then the main loading screen appears, I go to Story Mode using keypad, press Enter, and then the game starts to load (as I can see at the bottom of the screen "Loading Game...")... then it suddenly shuts down.

I will attach the files for you to see.
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5849831/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5849832/ScriptHookV.log)

RealVr.ini

**Comment by WatYouNeed** [comment]
> Hi LukeRoss,
> 
> I encountered a similar issue. First, I have an HTC VIVE
> 
> I never had any MOD installed on my Steam GTA5. I extracted your r7 release into the main folder. Then I extracted the ScriptHook rar into the main folder. When unzipping I was prompted to overwrite ScriptHookV.dll and dinput8.dll. I clicked Replace all.
> 
> When I launch the game from Steam. A warning message appeared saying "GTA5 does not support VR. It will appear on your desktop and may affect VR performance"
> 
> The intro game loads, then the main loading screen appears, I go to Story Mode using keypad, press Enter, and then the game starts to load (as I can see at the bottom of the screen "Loading Game...")... then it suddenly shuts down.
> 
> I will attach the files for you to see.
> [asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5849831/asiloader.log)
> [ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5849832/ScriptHookV.log)
> 
> RealVr.ini
> 
> ; GTA V R.E.A.L. mod Release 7
> 
> [Defaults]
> 
> ; F11 Activate hotkeys - off at start
> Hotkeys = 0
> 
> ; 0 Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
> StereoInCutscenes = 1
> 
> ; T Select dominant eye for aiming down sights (none, left, right) - right at start
> DominantEye = 2
> 
> ; Y Select heading control (always, only when aiming, never) - always at start
> HeadingControl = 0
> 
> ; J Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
> CutscenePitchMode = 2
> 
> ; N Show FPS counter - off at start
> ShowFPS = 0
> 
> ; End Activate gyro stabilization of view in vehicle - off at start
> GyroVehicle = 0
> 
> ; Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
> UniversalFOVFix = 3
> 
> ; NUMPAD. Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
> ZoomOverride = 0
> 
> ; NUMPAD2 Activate stereo rendering (alternate eyes) - on at start
> Stereo = 1
> 
> ; Select VR API to use (autodetect, Oculus, OpenVR, OpenXR) - autodetect by default
> VRAPI = 0

Actually... I fixed it... I went into Steam's GTA5 properties and then Local Files and then Verify Integrity. After that, the game reinstalled itself, and everything worked out fine.

Was able to load in High, MEdium,  and Low settings.

Thanks for the awesome work and allowing me to enjoy my game in VR!

**Comment by LukeRoss00** [comment]
Great! Hopefully verifying the game files integrity should work for the other users who had the same problem too. I'll close the issue now, feel free to reopen if there is new information

**Comment by gusflanagan** [comment]
> Great! Hopefully verifying the game files integrity should work for the other users who had the same problem too. I'll close the issue now, feel free to reopen if there is new information

How can I do this if I don’t have the game on steam?

**Comment by LukeRoss00** [comment]
Both the Epic and Rockstar game launcher have similar functions

**Comment by gusflanagan** [comment]
> Both the Epic and Rockstar game launchers have similar functions
My game isn’t on epic either. I just have the Rockstar launcher

**Comment by gusflanagan** [comment]
> Both the Epic and Rockstar game launchers have similar functions

I was able to figure out how to verify the game file integrity through the Rockstar launcher, but the game still crashes while loading story mode and gives me the Scripthook pop up about the error loading RealVR.asi

**Comment by LukeRoss00** [comment]
@gusflanagan Please read the [quick setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) instructions carefully. If you're still stuck after that, see #239 and open a new issue

**Comment by gusflanagan** [comment]
> @gusflanagan Please read the [quick setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) instructions carefully. If you're still stuck after that, see #239 and open a new issue

Updating to version 7 fixed it for me. Thanks so much for your help, and for creating this mod in general!
