### ISSUE TITLE
Visual glitch in cutscenes when the camera changes angle

### ISSUE THREAD

**Issue by importedturtle** [LukeRoss00/gta5-real-mod#305]
CPU: i7 10700k
GPU: RTX 3090
VR headset model: Valve Index
game version and build: 1.0.2189 (Latest Steam Update)
release of the mod: Latest (7) 
did you follow all the Quick setup steps carefully, in particular step 4? Yep.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H.
did the batch file report any errors? Nope
did you change the graphics settings manually? Added 2x MSAA and TXAA
are you using any other mods? Manual Reload, Euphoria Overhaul, and Dynamic Radar and HUD

**Comment by importedturtle** [comment]
Hey! Thank you for your great work on this mod, it really is incredible. My issue is essentially that in cutscenes when the camera angle changes the entire headset (Both eyes) flashes white or gray for a brief moment (couple of frames or so I'd say). This doesn't occur every single time the angle changes, but I'd say maybe 1 in every 3 or 4 camera angle cuts it does this flash. Is this just inherent to the mod or is it something on my end? Not the biggest issue but it takes me out of things a bit during cutscenes. Any help would be much appreciated :) Thank you for your time

**Comment by importedturtle** [comment]
Tried uploading the three files you specified in the "Please read before posting" but each is saying "We don't support that file type" when I try to upload them.

**Comment by LukeRoss00** [comment]
Nobody ever reported this issue, and lots of people are playing with the Index, so I suspect that it might be related to the other mods you're using. The Euphoria one seems the most likely.

Could you try removing the other mods temporarily to see whether the problem goes away?

**Comment by importedturtle** [comment]
I did a clean install with just your mod and I still seem to be getting the issue. Reinstalled nvidia drivers too but nothing. If this isn't something you're able to diagnose then don't worry, it's all good. The mod is still amazing!

**Comment by importedturtle** [comment]
Also tried all of the graphics presets and the issue still persists regardless.

**Comment by LukeRoss00** [comment]
Is the flashing visible only in the headset, or does it show in the game window on the monitor too? If it shows in the game window, could you upload a brief video so I can take a look at it?

Also, if you replay a cutscene, does it always occur at the same camera cuts, or is it more of a random occurrence?

**Comment by LukeRoss00** [comment]
Closing due to no feedback, feel free to reopen if there's new information

**Comment by importedturtle** [comment]
zsc

**Comment by importedturtle** [comment]
Hi there! Sorry for not replying to this sooner. So the "flashing" seems to be the camera jumping to another position for one frame or the characters/assets in the shot disappearing for one frame before transitioning to the next shot. I have uploaded examples of this on imgur, in the format: Shot 1 - "flash" - Shot 2. Check it out [here](https://imgur.com/a/SfXQx3W) and also [here](https://imgur.com/a/csYl0wb).

It seems to be a random occurence or it only happens in one eye. I noticed when playing back the recorded footage that the "flashes" occured at different times to when I remember them happening, so they must be occuring only in one eye at a time.

**Comment by LukeRoss00** [comment]
That is very weird! Indeed it looks as if for one frame only the camera is jumping to another, more or less random position.

I'm sorry but I have no idea what could be causing the issue. As I mentioned, nobody else reported it, and I never witnessed it on my system :-/

**Comment by LukeRoss00** [comment]
It does remind me of a similar issue that I know of, which however is only present in cutscenes that take place in closed environments. Sometimes the designers put the camera so close to a wall that when you play the cutscene in VR one of the two eyes ends up actually outside the room, thus seeing a blank space that can give you the impression that the assets have not loaded.

The issue I'm describing can usually be fixed by recentering the view, and/or leaning forward just a little to make sure that both eyes are "inside" the environment you're seeing.

**Comment by importedturtle** [comment]
No worries man, thank you for the incredible mod regardless. It is probably the coolest VR game I've played, it works incredibly well. I can't wait to see what you do in the future with other games. Thanks for responding to this :)
