### ISSUE TITLE
VR Jitter then Turning Oddity

### ISSUE THREAD

**Issue by morg106** [LukeRoss00/gta5-real-mod#306]
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5870140/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5870143/asiloader.log)

When the game loads up everything is kind of slow, jittery, i can move but its borderline unplayable.
I get on Franklins bike and slow ride down the road and after about 40 secs i hear an error noise on my computer which says
"Scripthook error

An exception occured while executing RealVr.asi
(0x00007FFD0BD7A2E0). id 36"

When i click ok all of  a sudden the game whizzes into normal speed, however the trade off here is that going straight fine
but if i get in a car and turn hard left, my head movement stays where it is and the car turns to the left, so i have to physically
turn my head and body to face that way, if im walking i can usually see the headless body and turning in circles using the left thumbstick, this is also used for aim too, the bits i do get to play by just trying to go straight is so much fun that i would really love to get this sorted so i can play it properly.

Cheers.

CPU:Intel Core I7-3370 CPU @ 3.40 GHz
GPU:Nvidia Geforce GTX 1060
VR headset model: Oculus Quest 2 via Link Cable
game version and build:1.0.2189.0
release of the mod:Release 7
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? tried all of them
did the batch file report any errors? 
did you change the graphics settings manually? No
are you using any other mods? No

**Comment by LukeRoss00** [comment]
You're describing the exact symptoms that Release 6 of the mod used to have after the latest game update, and before I put out Release 7. Are you 100% positive that you're using Release 7?

**Comment by morg106** [comment]
i thought i was, i will try redownloading the mod reinstalling just to be sure.

Whats the best way of going about uninstalling please?

Regards

Phil

________________________________

**Comment by LukeRoss00** [comment]
Uninstalling requires no special steps, just delete the files and folders that you extracted from the .rar file

**Comment by morg106** [comment]
Ok thank you, could i also just extract the new ones in and select replace all files?

Regards

Phil

________________________________

**Comment by LukeRoss00** [comment]
Sure
