### ISSUE TITLE
View warper in WMR Best visual quality mode

### ISSUE THREAD

**Issue by AWarringa** [LukeRoss00/gta5-real-mod#308]
Hi, when I set WMR to Best Performance mode everything works great but I get the terrible motion smoothing. 
When I switch to Best visual quality as adviced, my view is warped. 
When the loading screen appears it doesn't stay in place, it moves around when I move my head. In the game the fov is not correct, when I look upwards the buildings also stretch upwards. And I see the edge of a black box around me. 

    CPU: I9 9900
    GPU: 2080 Super
    VR headset model:  G2 Reverb
    game version and build: Steam 1.0.2189.0
    release of the mod: release 7
    did you follow all the Quick setup steps carefully, in particular step 4? yes
    which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
    did the batch file report any errors? No
    did you change the graphics settings manually? not that I can remember, was using it with my Quest a couple of months ago
    are you using any other mods? no

Files:
[GTA.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5897032/GTA.zip)

**Comment by LukeRoss00** [comment]
Did you quit the game before switching to Best visual quality? I don't think it can be done seamlessly without restarting the game.

Also, your logs show that you are using a launcher bypass, which might cause problems. Could you remove it from the game folder?

**Comment by AWarringa** [comment]
Hi Luke, yes I restarted after switching to Best quality, the first loading screen (the plain text) is already warped after starting GTA 5. 
I removed that Gtalauncerbypass files from my folder (not the log says I didn't use that bypass) but unfortunately still warped. 
Now I installed the mod a few months ago with another headset, the Quest 1. Maybe that is causing issues and it would be best if I now would reinstall everything from scratch?

**Comment by LukeRoss00** [comment]
The mod doesn't save the headset FOV, so I don't think that having used it with the Quest 1 in the past could be the cause of your problem.

Let's see if the mod's own log tells us anything. Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder: please attach it here.

**Comment by AWarringa** [comment]
Done, here it is:

[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5897878/RVRLog.zip)

**Comment by LukeRoss00** [comment]
Thanks for the log! So, your problem seems due to a bug in the Microsoft runtime. You must have used the "OpenXR Developer Tools for Windows Mixed Reality" to set a Custom render scale. That shouldn't warp the image obviously, but apparently there's some issue with their implementation.

Anyway, the mod selects its own rendering resolution for the headset and doesn't care about the render scale suggested by the driver, so what you should do is leave the Custom render scale to its 100% default.

**Comment by AWarringa** [comment]
That's it!! I had set the scaling in OpenXR to 50% for FS2020. Unchecking the custom scaling fixed the fov issue. 
And GTA 5 now looks GLORIOUS with the G2. Thank you SO much!!

**Comment by LukeRoss00** [comment]
I just posted a bug report on the WMR subreddit, let's hope someone from Microsoft sees it. They're not particularly fast in fixing these kind of issues though, so for the moment you will have to turn the Custom render scale off and on according to what game you want to play :-(
