### ISSUE TITLE
Feature Request: Optional Blinders

### ISSUE THREAD

**Issue by cercata** [LukeRoss00/gta5-real-mod#31]
Would it be posible to add optional blinders to the MOD ?
I guess you know what I mean, dynamic FOV reduction while moving and/or turning.

Some VR players are confortable with cockpit games, but not with FPS games. 
Blinders is an option that reduces motion sickness, and also helps people to develop virtual legs.

I think adding blinders would make GTA VR more mainstream. BTW, how many people downloaded it ?

**Comment by LukeRoss00** [comment]
The R.E.A.L. mod is not intended for people who get sick from VR. Although blinders might be helpful somewhat, the forced camera movements (which cannot be eliminated) would be a blocking issue anyway.

That being said, if someone wants to experiment with helmets, which might provide a helpful [frame of reference](https://www.purdue.edu/newsroom/releases/2015/Q1/virtual-nose-may-reduce-simulator-sickness-in-video-games.html) linked to the head, [this mod](https://www.gta5-mods.com/scripts/helmet-control) might be what you're looking for.
