### ISSUE TITLE
The game launches but not in VR

### ISSUE THREAD

**Issue by Sparadok71** [LukeRoss00/gta5-real-mod#310]
I am having a similar issue the game launches but not in VR. I have social club version, the game doesn't show in Oculus app anywhere, the sound comes through Oculus headset but can only see in cinema view. Saw the vrapi = 0 comment but I am not sure what this setting is, sorry new to mods and pc gaming.

_Originally posted by @Sparadok71 in https://github.com/LukeRoss00/gta5-real-mod/issues/245#issuecomment-774263067_

**Comment by LukeRoss00** [comment]
With the Rockstar Social Club version, the most likely problem is that your user doesn't have sufficient permissions to write to the game directory, so the installation of the mod doesn't happen correctly.

Could you try giving your user full control of the game folder, and then performing the steps described in the [Quick Setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) all over again?

**Comment by Sparadok71** [comment]
Thanks I eventually got it sorted.
