### ISSUE TITLE
Hotkey to disable vr looking for mod compatibility

### ISSUE THREAD

**Issue by Shibbyz** [LukeRoss00/gta5-real-mod#313]
Hey! This mod is amazing. I've been having so much fun with it. Thank you for your work.

I was wondering if it's possible to add a hotkey for pc and controller to temporarily disable or enable looking around with the HMD. I've been downloading some JulioNib mods like ironman and superman scripts and trying them out in VR. It works surprisingly well! In 3rd person it works as expected and no problems there. But in first person, when you fly in these mods, the HMD looking interferes with it and causes a bunch of jitter and weirdness that makes it unplayable. If there was a quick way to disable/enable that and the controls of looking around goes solely to how the game is out of VR (with joystick or mouse) then all those mods would work even when flying. And that would be really cool. 

Even better would of course be some kind of collaboration between yourself and JulioNib to make all the mods work well in VR but a hotkey would be the next best thing :)

**Comment by LukeRoss00** [comment]
Hey! I'm not sure if I get what you're looking for. What you wish is a toggle that disables all head tracking, so that when you turn your head the world image no longer stays fixed in space but turns with your head? That would be nauseating for a lot of users, but most importantly it would make turning your head having zero effect whatsoever on what you see... so at that point aren't you better off just keeping your head still when you're flying?

Not trying to make fun of you, just can't understand how it could possibly work.

**Comment by Shibbyz** [comment]
That sounds like a nightmare haha... Well what I mean is when you look around with the HMD its directly connected to where the character looks in-game and thus the direction you move. I don't think thats the case when using 3rd person with your mod, then the controls are basically like playing on flat screen. 
I've tried keeping my head perfectly still while flying but it still causes this jittery/glitchy camera movements. I've also tried only using the HMD for steering which works better but too difficult to control, and also you can't really turn around in-game without spinning in your chair and mummifying yourself in cables. 

So what I mean is a way to have the HMD direction not affect the characters movement similar to how it is in 3rd person. Basically with the HMD being like a flat screen and the characters looking direction being affected only by mouse/joystick. It would be even better if we (the user) can still look around with the HMD without the characters in-game direction being affected. Though this feature would only be useful if it's easy to turn off/on because being able to look around with the HMD is obviously the best part of VR. It would be used just for certain mods while in the air. 

I'm not a modder though so I have no idea if this is even possible. And if it's not possible this is still an amazing mod. Maybe having a bunch of other superhero mods is just overkill :)

**Comment by Shibbyz** [comment]
Sorry if that was confusing. Basically a toggle that disconnects the HMD from the characters looking direction/crosshair.

**Comment by freekanimal** [comment]
Exactly what I was after to get round the sniper thing

**Comment by LukeRoss00** [comment]
The `Y` hotkey controls heading (see https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys). Did you try it already?

**Comment by freekanimal** [comment]
I did mate and it works perfectly -just not with the scope, has no effect-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 08/02/2021, 09:20 LukeRoss00 <notifications@github.com> wrote:

   
  The Y hotkey controls heading (see https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys). Did you try it already?
