### ISSUE TITLE
Wide screen spectator window

### ISSUE THREAD

**Issue by freekanimal** [LukeRoss00/gta5-real-mod#314]
Is there a way to make the window on my monitor full screen so others can view what I'm laying better? I usually just use 'Display VR View' in Steam VR but when I click full screen and the gta window loses focus, I no longer have control with either m+kb or game pad until I bring the square gta window into focus and on top of the steam view...
Thanks in advance

**Comment by LukeRoss00** [comment]
GTA V won't take KB/M input if its window is not in focus, but it _will_ accept gamepad input, so you can play using a gamepad even if the VR View window is in front and fullscreen.

In case you lose audio, make sure that `Mute Audio On Focus Loss` is set to `Off` in the Audio options page of the game

**Comment by freekanimal** [comment]
As I thought, though my xbox pad won't play ball till it's in focus, i wonder if it's something to do with x360ce...-- Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 08/02/2021, 11:21 LukeRoss00 <notifications@github.com> wrote:

   
  GTA V won't take KB/M input if its window is not in focus, but it will accept gamepad input, so you can play using a gamepad even if the VR View window is in front and fullscreen. 
  In case you lose audio, make sure that Mute Audio On Focus Loss is set to Off in the Audio options page of the game

**Comment by freekanimal** [comment]
Hey Luke, confirmed - it was x360ce.
I removed it and can now use my gamepad without gta v in focus and steam vr in full screen on top
