### ISSUE TITLE
Epic games version

### ISSUE THREAD

**Issue by Believe-ConfessJesus2Bsaved** [LukeRoss00/gta5-real-mod#316]
So it’s my first time trying your mod on epic games. I did the downgrade patch and your version 6 release. Crashes on start.

**Comment by LukeRoss00** [comment]
You should be using [Release 7](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r7) of the mod, not 6. Does the game run normally after the downgrade if you don't install my mod?

**Comment by Believe-ConfessJesus2Bsaved** [comment]
I used 6 and it works. Had to use the proper scripthook too. I had a
downgraded .01 patch not .0 , that may of hindered it.
