### ISSUE TITLE
Stuttering with QU2 and remote desktop

### ISSUE THREAD

**Issue by lauke1010** [LukeRoss00/gta5-real-mod#318]
I use my quest 2 with virtual desktop to play pc vr. I play halfy life, sim racers, vivecraft, and elite dangerous. in all those games, tracking works fine, but it's really shaky in this game. it got mentioned in the V7 description, but that was for wmr headsets, so i am a bit confused.

(My info)
Cpu: Core i5-8600K oc to 4.2ghz
Gpu: 1660ti oc edition from gigabyte
Headset: Quest 2
Game build: Epic games version 1.0.2215.0, but i tried with the rockstar launcher with my alt and that also gave the same effect
Release: r7, ofc with scripthook v1.0.2215.0 (the 12 feb release)
I went through quick setup
I chose h, m and low and none of them worked
The batch file didn't return errors
I didn't chane any settings
I reïnstalled the entire game to a clean install, then installed the mod. 
[Logs.zip](https://github.com/LukeRoss00/gta5-real-mod/files/5976563/Logs.zip)

**Comment by LukeRoss00** [comment]
Hi, unfortunately Virtual Desktop doesn't support my mod (see point 6 in the [Quick Setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) instructions
