### ISSUE TITLE
Move or minimise the game window.

### ISSUE THREAD

**Issue by kgian** [LukeRoss00/gta5-real-mod#32]
I want to know how to move the game window. I want to have oculus mirror fullscreen so anyone watching on screen does not get a headache from the alternate reprojection of the game window. Unfortunately if the game window loses focus the game has no sound. 
At least I would like to be able to put the game window to the bottom almost out of the screen.

**Comment by LukeRoss00** [comment]
> For streaming Twitch or YouTube video, another idea is capturing the output of the Oculus mirror; in that case you'll want to set 'Mute Audio On Focus Loss' to 'Off' in the Audio options page, to be able to have the mirror on top of the game window without losing audio
