### ISSUE TITLE
Old GTAs

### ISSUE THREAD

**Issue by cercata** [LukeRoss00/gta5-real-mod#320]
Hey lukeross00,
Did you know this engine for old GTA games ?
https://github.com/GTAmodding/re3

Just in case you are bored ;)

**Comment by LukeRoss00** [comment]
Hi @cercata!

I didn't know about this project. I watched one video, and I have to say that GTA III and Vice City look really primitive when seen with today's eyes, and not with nostalgia-tinted glasses :-)

That said, I'm quite busy right now, but if nobody else expands the project with a VR conversion, I might take a look at it in the future. No promises though!

**Comment by cercata** [comment]
Nice, I see your eyes are tinted with Nostalgia. XD

STAR WARS™ Jedi Knight - Jedi Academy™ also looks very outdated and I enjoyed it a lot in VR.

I hope you are making a lot of money with that "busy" status ;)
