### ISSUE TITLE
RealVR.asi error with Scripthook

### ISSUE THREAD

**Issue by ForrestD17** [LukeRoss00/gta5-real-mod#321]
For some reason I get this error when loading up GTA V. I did what one forum said and it was to download the latest version of ScriptHookV and put only the .dll file in the main directory. I did that and it's still not working.
What am I doing wrong?

**Comment by ForrestD17** [comment]
Also here are my logs
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/5993270/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/5993271/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
Please see #239 before opening new issues
