### ISSUE TITLE
Controller Connected to PC Not Working !!

### ISSUE THREAD

**Issue by Anonymous0080** [LukeRoss00/gta5-real-mod#325]
I have an AntEsports GP300 pro v2 controller. It is having a usb reciever due to which i cannot connect to my phone as I am using a Gear VR which requires mobile phone port to be connected with VR. I am using ALVR to connect to my pc and use steam vr. 

So, my usb receiver is plugged into the pc and when i try to use the controller it does not take input but when i use keyboard and mouse it works fine ..... So, is there any way i can control the game with the controller connected to pc ?

I am using Samsung Gear VR
Latest Version of GTA 5 
Epic Games Version
CPU: Ryzen 7 3800x
GPU: RTX 2060 Super
VR headset model: Gear VR Samsung
game version and build: Latest (Epic Games)
release of the mod: Latest
I choosed "L" in Realconfig.bat

**Comment by LukeRoss00** [comment]
I'm sorry but I'm not familiar with that controller, and have no idea whether GTA V supports it. Be assured however that the VR mod doesn't change anything in the way the game reads input from the controller, so if a specific controller works with GTA V it will still work with the VR mod

**Comment by Anonymous0080** [comment]
GTA 5 Supports that controller because it works fine without the mod. It is dected as an Xbox controller So there is no issues while using it but in VR Mode, It disables the controller. 
Also my controller is connected to pc (not vr) So, as keyboard and mouse input, it should work by default but it is not ....

**Comment by LukeRoss00** [comment]
It might be that the controller is intercepted by ALVR, or SteamVR itself. I know for a fact that Xbox controllers work fine with the mod, even in SteamVR mode, but I have no experience either with ALVR or your specific controller model

**Comment by Anonymous0080** [comment]
Ok, thanks for your help !!
Btw This is a great mod 
I will continue to play with mouse and keyboard

😊😊😊 Once Again thanks for your help :-)
