### ISSUE TITLE
Exception Occurred while executing 'RealVR.asi'

### ISSUE THREAD

**Issue by scgtam** [LukeRoss00/gta5-real-mod#326]
CPU: Intel(R) Core(TM) i7-1065G7 CPU
GPU: eGPU GeForce 1070
VR headset model: Quest 2 (Link Cable)
game version and build:  EPIC 1.0.2215.0 , build 1.53
release of the mod:  Download it today 02/25 at your github page, the link said R7,so release 7?
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? no

I follow all the quick step. Connect Link cable, installed oculus app, oculus app detected quest 2. While loading into game, it has a pop up giving error Exception Occurred while executing 'RealVR.asi'
I wasn't able to see find asiloader.log nor scripthookv.log at the root directory of the game. Please help.

**Comment by LukeRoss00** [comment]
If you cannot find the logs, it's possible that your user doesn't have sufficient permissions to write to the game folder, which can mess up the mod installation. Try giving yourself full control of the game folder and then reinstalling the mod; after the game runs, you should be able to see the logs.

**Comment by scgtam** [comment]
I was able to give permissions to the folder. Now I can see the log, however, it gave me the same error. Please see logs.
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6051785/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6051786/asiloader.log)

**Comment by scgtam** [comment]
Thank you for your help, reinstall everything fixed it thanks!
