### ISSUE TITLE
Shuddering when looking around

### ISSUE THREAD

**Issue by Johnboywalt** [LukeRoss00/gta5-real-mod#328]
Hi,

I have shuddering when looking around, I have tried adjusting some settings but what ever I do its the same.

If i don't move my head its fine, any suggestions would be great appreciated. 

(I have seem similar shuddering to this before when i tried to up the super sampling to much on Elite Dangerous)

Operating: Windows 10 Home 64-bit 
Processor: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
Memory: 16384MB RAM
Graphics: Geforce RTX 2080 Ti
VR Headset:HP Reverb G2 (running through steam vr)
Game version: 1.0.2215.0
Build id: 6154203 or 2215
Release of mod: Release 7
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H (tried all of them)
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No

**Comment by LukeRoss00** [comment]
Thank you for providing all your details! With the G2 (or any other WMR headsets) you need to use OpenXR: see the [Release notes](https://github.com/LukeRoss00/gta5-real-mod/releases)
