### ISSUE TITLE
Gta V Real mod working speedometer?

### ISSUE THREAD

**Issue by GorrakTheOriginal** [LukeRoss00/gta5-real-mod#332]
Hi, loving the mod and would like to have a speedo, mainly to tell me what gear I am in so I can use the Manual Transmission mod in sequential. I have tried NFS, LeFix and another couple and cannot get any of them to display properly with a skin that shows me my gear. Some seem like a transparent square when I reposition or change the size.....I am wondering what might be going wrong and If anyone has a working solution.
Thanks

**Comment by LukeRoss00** [comment]
Doesn't the Manual Transmission mod put that information directly on the game HUD?

**Comment by GorrakTheOriginal** [comment]
Does it? I am not aware of it if it does

**Comment by LukeRoss00** [comment]
I'm almost sure it does. Try to look in its settings, there should be options to enable the various display elements

**Comment by GorrakTheOriginal** [comment]
You are right, I have tried the Manual Transmission speedo before and I just did again.
While I can get the gear and speed to display no problem the rmp is hidden and I really dont know why or how to fix it. After activating it I have tried moving the location and size but it is nowhere on the screen.
Obviously this is not an issue with this mod anymore, but I am still open to suggestions. Thanks LukeRoss00 , and thanks even more for REAL

**Comment by GorrakTheOriginal** [comment]
Ok, I discovered that I can see the rpm meter....but only when I am aiming with a gun in the car!!
Then it appears normally but goes away again as soon as I stop. It does not matter where I place it, as soon as I lower my weapon it disappears so I think it must be linked to the view change that happens when going from driving to driving and aiming/shooting.
Any ideas?

**Comment by GorrakTheOriginal** [comment]
E66666666 fixed this for me.
The solution was to disable the custom first person camera. (Manual gearbox ingame menu/Misc options)
