### ISSUE TITLE
Scripthook V Error running RealVR.asi upon loading game

### ISSUE THREAD

**Issue by esqueer** [LukeRoss00/gta5-real-mod#336]
Intel I-7 9700k
NVidia RTX 3070
Oculus Quest 2
Steam version 1.0.2215.0
R.E.A.L. Mod Release 7
did you follow all the Quick setup steps carefully, in particular step 4? Yes.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No

It works fine until I click story mode and load the game. Scripthook V has an error stating that there was an exception running RealVR.asi. The error code is (0x0007FFBC60A2E0) id 33. When the game loads after clicking out of the error, the hud is visible from the VR headset but nothing else is. I've reinstalled the game clean twice and reinstalled the mod seperately carefully following the steps. Unsure what to do at this point. Picture of error prompt below. 

![image](https://user-images.githubusercontent.com/80416163/110670190-1ceadc80-819b-11eb-8167-df3abce3a646.png)

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6117749/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6117755/asiloader.log)

**Comment by LukeRoss00** [comment]
Thanks for posting the Script Hook V logs and everything! The error that you're reporting used to occur with older releases of the mod after recent game updates, so first you could double check that you actually have Release 7 installed (look at the first line of your `RealVR.ini` file).

If you're still stuck, I could take a look at your full log, which you can obtain as follows: add a new line `RVRLog = 1` at the end of your `RealVR.ini` and run the game until you get the exception, then quit. There will be a new `RVRLog.txt` file in the game folder: please zip and attach it here.

**Comment by Pyromaniac91** [comment]
Hi, I am experiencing the exact same error as described by @esqueer. 


Intel I-7 4790K
AMD RX 5700XT
Oculus Rift S
Rockstar version 1.0.2215.0
R.E.A.L. Mod Release 7
did you follow all the Quick setup steps carefully, in particular step 4? Yes.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? No

**Comment by DeadPixels1** [comment]
Thanks for the prompt reply Luke. Here is the log as requested. Yeah that potential solution didn't work realconfig.bat isn't having problems carrying out it's commands and generates the xml file as expected.

[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6134838/RVRLog.txt)

**Comment by LukeRoss00** [comment]
@DeadPixels1 Although you wrote in your info that you're using Release 7 of the mod, your log shows that you're actually on Release 4 (which is the one Google is in love with and keeps sending people to). Release 4 unfortunately no longer works with the current game version, even if you have the latest Script Hook V.

You should download Release 7 and use it to overwrite the older files. Sometimes people have trouble with the Epic Games store version because it protects the game folder: if WinRAR gives you errors when overwriting the older files, give yourself full control of the folder before retrying.

**Comment by DeadPixels1** [comment]
Hmmm that's weird I used the link to the file in the quick setup page and it was version four the other day. Ok i'll give version 7 a go and let you know.

**Comment by jmote** [comment]
@LukeRoss00 please make obvious somewhere in the past releases that they are past releases, it took me 2 hours trying to troubleshoot this to finally find this thread - I waso nr4 as you say google loves sending people to. bout to go try it out for real this time!

**Comment by LukeRoss00** [comment]
@jmote Done. Let's hope people see the warning :-)
