### ISSUE TITLE
Quest 2 troubles. Stuck at 50-60fps with 13-30% GPU and CPU usage

### ISSUE THREAD

**Issue by aVolnov** [LukeRoss00/gta5-real-mod#338]
[logs.zip](https://github.com/LukeRoss00/gta5-real-mod/files/6133122/logs.zip)
    CPU: Intel 10700K
    GPU: RTX 3070
    VR headset model: Quest 2 using link, attempted both SteamVR and Oculus runtimes
    game version and build: **1.0.2215.0**
    release of the mod: **7**
    did you follow all the Quick setup steps carefully, in particular step 4? **Yes**
    which settings did you choose (H/M/L) when running the batch file RealConfig.bat? **M**
    did the batch file report any errors? **No**
    did you change the graphics settings manually? Yes but nothing changed
    are you using any other mods? **No**

Hi, so it seems my game is refusing to run at a proper framerate. This system can run GTA at 90-120 fps at 4k but refuses to run it in VR at more than 50-60fps (as reported by the game), which is obviously very stuttery and nauseating, given that it's basically 25-30fps per eye. During this, the CPU is utilized 30%, the GPU 3D section is at 13% and Encode is at 30%. This is all while using Link via cable, no other mods installed, fresh install with a fresh settings file.

Any ideas would be appreciated.
![OculusScreenshot1615584209](https://user-images.githubusercontent.com/52963000/111001135-4b7fd780-8394-11eb-9035-449a0f834e67.jpeg)

**Comment by LukeRoss00** [comment]
Hi, thanks for posting the logs and all the relevant information!

From the logs it looks like you have ASW turned on: it should be off when running the mod, because it's not compatible with alternate eye rendering. You can force it off either by pressing `Ctrl + NUMPAD 1` on the keyboard, or by using the Oculus Tray Tool.

If you still have frame rate issues with ASW forced off, please attach your new `RVRLog.txt`

**Comment by aVolnov** [comment]
That worked great, thank you! Only worked when I set the global switch for it though, doesn't seem to work with Tray Tool's profiles, although maybe I need to point it to GTA's main executable and not the one from Oculus library.

Another question I had, since this mod is running alternate eye rendering, would it be possible to run the game at 180fps so that we get a full 90hz per eye?

**Comment by LukeRoss00** [comment]
I have it working with Tray Tool's profile system, but as you said the profile needs to be tied to `GTA5.exe`.

In my testing no system can run GTA V at a stable 180 fps, not even with an overclocked RTX 3090. The game doesn't seem to take full advantage of all CPU cores. Also, you'll probably find that your 35% GPU utilization is a measurement error. I guess that you're using Task Manager to get that figure, but it doesn't seem to be reliable. MSI Afterburner is the tool I use to get accurate results.
