### ISSUE TITLE
Any plan/is it possible to add support for fivem, or know of a way to get it working?

### ISSUE THREAD

**Issue by TwizAu** [LukeRoss00/gta5-real-mod#34]
Hey Luke,

When running the fivem multiplayer mod it doesnt run mods located in the gta5 folder as the mod is seperate from the game. I tried installing the vr mod in the fivem folder but the game ended up crashing. I spoke to the fivem team and they said that for a mod to work it needs specific suport added by the mod developer.

Just wondering if you plan on adding support or if it is even possible?

Would be super cool to play gta 5 rp in vr!

Thanks,
Ethan

**Comment by cercata** [comment]
> I spoke to the fivem team and they said that for a mod to work it needs specific suport added by the mod developer.

Is there any documentation about that ?
I tried also putting the REAL mod on the pluggins folders, and it crashed. The looking for information on plugins/mods for FiveM, I didn't found anything clear, someplaces was stated it wasn't supported, somewhere else it said yes ...

It would be great some GTA V Multiplayer on VR

**Comment by LukeRoss00** [comment]
This is not something that really interests me (I'm not into multiplayer gaming), but if it's a simple matter of adding a call to the mod or anything like that, I'll do it.

Since you're in contact with the team, could you ask for a reference page on what I'm supposed to do?

**Comment by cercata** [comment]
> I spoke to the fivem team and they said that for a mod to work it needs specific suport added by the mod developer.

Did you tell them was what the mod about ?
I see here that .asi mods where allowed only before they added support for server side client scripts:
https://forum.fivem.net/t/request-plugins-check-signature/6510

And I have seen this, for making some customizations in the client:
https://docs.fivem.net/scripting-reference/client-functions/

But for making a VR mod it seems you need deeper access to GTA V. You must tell them that we need an ScriptHook asi loaded in the client side

**Comment by TwizAu** [comment]
Hey, contact with the team was just through their discord so nothing formal. I asked about some reference material for getting your mod working and one person said to try checking the docs. https://docs.fivem.net/

I managed to get fivem to attempt to run the mod, but only got as far as an error message.

If you think this is possible, and worth your time I can tell you what I know but I also completely understand if you dont want to undertake this project.

Cheers

**Comment by LukeRoss00** [comment]
I guess that cercata is right, and that client-side .asi mods are disallowed (which makes total sense because allowing client mods in multiplayer games is a recipe for rampant cheating).

So there's nothing I can do, and I'm closing the issue: feel free to reopen if you have positive confirmation from the devs that client-side .asi mods are allowed **and** they tell you how to get them working.

**Comment by cercata** [comment]
I have found that scripthook can be allowed by the servers:
https://docs.fivem.net/server-manual/setting-up-a-server/

```
# This allows players to use scripthook-based plugins such as the legacy Lambda Menu.
# Set this to 1 to allow scripthook. Do note that this does _not_ guarantee players won't be able to use external plugins.
sv_scriptHookAllowed 0
```
Also launching Fivem with -sp paremeter ("FiveM.exe -sp"), launches it in single player mode, and ScriptHook is allowed. I'm gonna try it later.

**Comment by TwizAu** [comment]
Yeah, @cercata, just got confirmation of the same thing from the fivem team.

"You can load client side plugins on servers that have scripthook enabled.
And yes, .asi should work."

So sounds like setting up a vr mod server may be possible.

There's still the issue of getting the vr mod asi to not crash, although that could just be me doing something wrong. 

Lemme know how you go @cercata. Would be great to see if we can get this working.

**Comment by cercata** [comment]
Game over :(

It seems that fivem is hooking d3d11.dll, and LukeRoss used a wrapper from d3d11.dll, so FiveM and RealVR are incompatible.

**Comment by cercata** [comment]
@TwizAu did you try Rage Multiplayer https://rage.mp/  ?
It launches on VR, but doesn't connect

**Comment by TwizAu** [comment]
Ah, that's a shame. Thanks for investigating and helping though :)

Havent tried rage multiplayer, but ill look into it at some point and see if I can get it working. 

Unfortunately populated servers seem to only be located in russia and germany which is no good for me. Might be able to host a server for the vr and english speaking community though if theres interest.

**Comment by E66666666** [comment]
To have it active globally within FiveM, you'd need to integrate your mod with FiveM itself. It'd be a massive task though, so I doubt it's a reachable goal.

**Comment by Alde1980** [comment]
Hi, I'm veri interested into have REAL mod working with FiveM, AFAIK scripthook mods in clientside work if enabled on server.cfg, IE the Manual trnasmision mod works. What is the difference with REAL mod then, the dll hooks? cannot be those renamed or changed in any eay so they load when mod loads? I have a fivem Server for testing but Fivem has a SP client too so it can be really interesting even for not multiplayer games
