### ISSUE TITLE
downloaded and installed natural vision and it wont load the game in VR 

### ISSUE THREAD

**Issue by acedredlo** [LukeRoss00/gta5-real-mod#341]
How do i fix this problem? it was working fine in the vanilla set up but once i installed natuaral vision it wont load

**Comment by LukeRoss00** [comment]
ReShade and ENB presets are not compatible with VR (see https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking). If you want to use my mod together with graphics overhaul mods, you need to skip the ENB and/or ReShade installation steps.

**Comment by acedredlo** [comment]
Ahhhh perfect. I do have another question. I noticed with the my graphics card i can beef up significantly, I have a RTX 3090 24gb, and what I’m seeing is it’s amazing stand still but gets distorted and kinda staggered like a warping motion when I run or drive. 

I have MSAA at like 8x
TIAA and FXAA active. 

Like I said graphics are insane with that overhaul mod just wish I can get it to where it stops warping on me. Is it a resolution sizing? 



Thanks, 
Ryan Dodson
Owner and Managing Partner/President 
AceDredlo LLC
www.acedredlo.com
Fraternal Order Of The Donkey Inc. 
3039317595
Text or call anytime!

“Ace is on the Case!”

**Comment by acedredlo** [comment]
Also I can’t get the police mod to work with NVE and REAL VR 

I CAN GET NVE + REAL VR to boot. (I just need to find the best settings so the game doesn’t feel like a 3d movie) I’m new to this so any guidance on this stuff would be helpful to transfer this vanilla game into a beefed up awesome dynanic experience. 



Thanks, 
Ryan Dodson
Owner and Managing Partner/President 
AceDredlo LLC
www.acedredlo.com
Fraternal Order Of The Donkey Inc. 
3039317595
Text or call anytime!

“Ace is on the Case!”
