### ISSUE TITLE
Script Hook V Critical Error

### ISSUE THREAD

**Issue by steveo69g** [LukeRoss00/gta5-real-mod#342]
Hope someone can help on this one!
Im getting Script Hook V Critical Error box on start up showing unknown game version

It lists the supported versions
1.0.335.2
1.0.350.1/2
1.0.372.2
1.0.393.2/4
1.0.463.1
1.0.505.2
1.0.573.1
1.0.617.1
1.0.678.1
1.0.757.2/4
1.0.791.2
1.0.877.1
1.0..944.2
1.0.1011.1
1.0.1032.1
1.0.1103.2
1.0.1180.2
1.0.1290.1
1.0.1365.1
1.0.1493.0/1
1.0.1604.0/1
1.0.1737.0/6
1.0.1868.0/1/4
1.0.2060.0/1
1.0.2189.0

I initially used the latest script hook 1.0.2215.0 as per the mod and then tried 1.0.2189.0 with the same issue
My version is a fresh install from steam march 2021 and any help is greatly appreciated

**Comment by LukeRoss00** [comment]
Yes, apparently the game was updated AGAIN today.

**Comment by LukeRoss00** [comment]
People with the Steam version of the game can temporarily downgrade (while waiting for Script Hook V to be updated, which usually takes a few days) by following the tutorial [here](https://www.youtube.com/watch?v=P8Beh-xPdGc)

**Comment by steveo69g** [comment]
Thank you so much for your reply and creating the mod, works perfectly now

**Comment by LukeRoss00** [comment]
New version of Script Hook V is available from Alexander Blade's page (http://www.dev-c.com/gtav/scripthookv/)
