### ISSUE TITLE
Game Crashes

### ISSUE THREAD

**Issue by Dan-Veinberg** [LukeRoss00/gta5-real-mod#346]
The game opens up in Oculus as an app but then crashes after pressing story mode. What do I do?

CPU:  Intel Core i7-10700KF
GPU:Nvidia RTX 3070
VR headset model: Oculus Rift S
game version and build: BUILDID: 6337558
release of the mod: downloaded 3/21/2021
did you follow all the Quick setup steps carefully, in particular step 4: yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat: High
did the batch file report any errors? idk
did you change the graphics settings manually? no
are you using any other mods? no

**Comment by LukeRoss00** [comment]
See #239 before opening new issues
