### ISSUE TITLE
I have no idea why this happened. it is like the game cant load the textures in VR?

### ISSUE THREAD

**Issue by acedredlo** [LukeRoss00/gta5-real-mod#347]
![what](https://user-images.githubusercontent.com/80606923/112420377-54549f80-8cea-11eb-85d9-e4e7c73c6ab6.png)

AMD Ryzen 9 3950X 16-Core Processor 3.50 GHz
64.0 GB of RAM
RTX 3090 24 GB
64-bit operating system, x64-based processor
Up to date on VR MOD and SCRIPTHOOK and GAME

**Comment by LukeRoss00** [comment]
Actually it looks more like your camera is under the game world. It's probably a conflict with other mods, or the game installation might have become corrupted. What other mods are you using?

**Comment by acedredlo** [comment]
LSPDVR and a billboard texture with make visuals great again. 



Thanks, 
Ryan Dodson
Owner and Managing Partner/President 
AceDredlo LLC
www.acedredlo.com
Fraternal Order Of The Donkey Inc. 
3039317595
Text or call anytime!

“Ace is on the Case!”

**Comment by LukeRoss00** [comment]
Those mods change _lots_ of game files, and in your other thread you also mentioned that you tried NVE. The most likely explanation is that your game installation has become corrupted. I'd advise deleting the game folder (the one where `GTA5.exe` is, not the one under Documents that contains your saves) and reinstalling the game from scratch with only the R.E.A.L. mod. Then, when everything works again, you can add one more mod at a time until either you get to the configuration you want or you identify the mod that causes conflicts.

Please refer to the [README](https://github.com/LukeRoss00/gta5-real-mod) and to issue #78 for additional information.

Let us know how it goes, so the info can benefit other users who might have the same problem.

**Comment by acedredlo** [comment]
No problem I will thanks man 



Thanks, 
Ryan Dodson
Owner and Managing Partner/President 
AceDredlo LLC
www.acedredlo.com
Fraternal Order Of The Donkey Inc. 
3039317595
Text or call anytime!

“Ace is on the Case!”
