### ISSUE TITLE
Error when launching with WMR

### ISSUE THREAD

**Issue by LucasNiles** [LukeRoss00/gta5-real-mod#348]
![image](https://user-images.githubusercontent.com/24360615/112739342-a7745f80-8f41-11eb-964a-dfffa1ba90cf.png)

AMD Ryzen 5 2600 6-Core Processor 3.40 GHz
16.0 GB of RAM
GTX 1070 8 GB
Windows 10
64-bit operating system, x64-based processor
HP Windows Mixed Reality
Chose H on the .bat config 
Epic Game Store GTA 5 ver. 1.0.2245.0 Mod r7 No errors in logs (unless I missed something)

When launching with "VRAPI = 0" the game is just a stuttery mess
When launching with "VRAPI = 3" the game gives this error but still launches but not through headset
OpenXR is installed and default

[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6216688/ScriptHookV.log)

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6216689/asiloader.log)

[RealVR.ini.zip](https://github.com/LukeRoss00/gta5-real-mod/files/6216691/RealVR.ini.zip)

**Comment by LukeRoss00** [comment]
Hi Lucas, thanks for providing all the requested information. There seems to be a problem with your OpenXR runtime for WMR. Unfortunately they tied it to both the Microsoft Store and Windows Update, which makes it exceedingly hard for non-Microsoft people to diagnose installation problems.

You could try installing the OpenXR Developer Tools for WMR: https://www.microsoft.com/en-us/p/openxr-developer-tools-for-windows-mixed-reality/9n5cvvl23qbt . From there you can check whether their demo scene runs, and perhaps it might tell you if you need to update something.

**Comment by LucasNiles** [comment]
Thats the thing, I have it installed OpenXR Developer Tools for WMR and am able to run the demo scene and it still gives the error.

**Comment by LukeRoss00** [comment]
Do you have other mods, or overlays, that might be hijacking `dxgi.dll`? My mod does not use `DXGIGetDebugInterface1` at all, so the problem must be somewhere else

**Comment by LucasNiles** [comment]
I do have GTA REDUX on for graphics quality but did think it would effect openxr. Gonna try it without gta redux and see if that fixes it. But does that mean I won't be able to apply any gfx mods to the game while using vr?

**Comment by LucasNiles** [comment]
So do you know if the others are still compatible? Seems like a while ago this was written so I feel I should ask before going in blind.

**Comment by LukeRoss00** [comment]
I believe you should find the most up-to-date info in issue #78, which is always open exactly for this kind of discussion. Maybe other users may be still monitoring that thread and may give you advice. I'll close this issue now as it's no longer a WMR-related problem, and I have not personally followed the evolution of other graphics overhaul mods recently.
