### ISSUE TITLE
Choppy rotation

### ISSUE THREAD

**Issue by Loginno** [LukeRoss00/gta5-real-mod#349]
Sorry if this is a known issue, but I searched high and low and did not find any solution. 

The problem is choppy rotation. When the camera is stable, everything is dandy, but when there is a slight movement of the entire surroundings - things get choppy/stuttery. The background is starting to appear as two different images, and rotation is not smooth, but "jumps" as if in very low FPS.
It happens all the time, as soon as the camera is dynamic. In a situation where the camera angle doesn't change - all is good.
The problem persists with all settings: low, med and high, and both with Oculus Rift CV1 and Quest 2 via link.

Turning off stereoscopic mode (hotkey keypad num2) the game flows perfectly. Also on the 2D rendering on the computer screen - all is perfect.
In FPS debug mode (hotkey N) there isn't any significant drop in FPS. It's ranging between 50-70+ which should be ok.
I don't have any other mods. The mod was copied on a fresh installation. All setup instructions were followed to the letter.
ASW was disabled, first by using the Oculus Tray Tool, then the Oculus Debug Tool, without solving the issue. Have to say the I have no way of knowing that the ASW is actually off.
AMD driver was updated to the latest driver: 21.3.2
I found somewhere that hotkey "B" may help. Didn't in my case. I tried many different setup tweaking without any success for this specific issue.
Also tried forcing OpenXR in the RealVR.ini file, since I saw that in a recommendation somewhere.

Appreciate it if you can give me some more leads to check.

Additional requested info not covered:
CPU: AMD Ryzen 5 3600X
GPU: AMD Radeon 5700 XT, 8GB
RAM: 16GB
VR Headset: Quest 2 via Link
Game version: running directly from Rockstar Launcher. v.1.0.2245.0
Mod version: 7
No errors in the batch file

Log and config files attached:
[RealVR.ini.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6251450/RealVR.ini.txt)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6251445/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6251448/ScriptHookV.log)

**Comment by Loginno** [comment]
This wouldn't hurt too I guess. From Documents\Rockstar Games\GTA V

[settings.xml.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6251489/settings.xml.txt)

**Comment by LukeRoss00** [comment]
Hi, thanks for providing such detailed information!

> The background is starting to appear as two different images

That is normal with alternate eye rendering when there is lateral movement. It's not actually a doubling (in fact it cannot be captured on video): it's an optical illusion triggered in the brain by the fact that the headset is strobing the same image twice.

> rotation is not smooth, but "jumps" as if in very low FPS

That is not normal though, and it's what we should try to diagnose. Do you play in first person or third person? Does the choppiness happen _a._ only when the game is rotating the camera itself, like in scripted animations or cutscenes, or _b._ also when you rotate the camera manually with the mouse or the right controller stick, or _c._ even when you rotate the camera automatically by turning your head to look around?

To make sure that ASW is off, the easiest way is to use in-headset debug HUD provided by Oculus, that can be activated either with the Tray Tool or the Debug Tool. For instance in the Tray Tool window, under Game Settings, set Visual HUD to "ASW Status".

**Comment by Loginno** [comment]
Cool! Some answers I know already, and some will come after testing.

I play exclusively third person. Seems weird for me to play GTA in first :) Now that you mention 3rd/1st, I do get a bug sometimes (actually very frequent), coming out of situations where the character model is not controlled by a controller (i.e. changing clothes or a cutscene) - wherein I get stuck in a kind of a first-person view, but very weird, where the camera is disassociated from the player, but I shake shake shake and it jumps back to centered 3rd person (great shortcut BTW).

Re choppy rotation, it is very distinctive to *any* camera movement that changes the background, whether by me rotating the gamepad stick, or turning the car around while driving, or a cutscene with a dynamic camera. They are all choppy. 

Turning my head to look creates 0 choppiness and is super smooth, so I guess the answers would be "yes" to a, b and partly c: in the mode where the head also controls the camera (it happens with one of the hotkeys, don't remember which...). In the default settings - turning the head to look around while the camera angle is fixed is smooth.

I want to try two things:
1. Turning on the in-headset debug HUD provided by Oculus to make sure ASW is off
2. Playing the game in first person to see if there any change

Can do these only later today. Let me know if there is anything else I should try.

**Comment by LukeRoss00** [comment]
> kind of a first-person view, but very weird, where the camera is disassociated from the player

Yes, that's a bit annoying, but the workaround you found (just shake to recenter) is the same one I use, and almost nobody plays in 3rd person in VR anyway, so I never got around to trying to fix the issue ^_^

In 1st person I apply an extra correction (in technical jargon it's known as "yaw folding") to the alternate eye rendering poses to take the camera rotation into account and get better motion compensation. Unfortunately it's only possible when the camera is the center of rotation, which is the case in 1st person but not in 3rd where when you use the stick the camera rotates around the character.

I think that your best bets (apart from double-checking that ASW is off) are either playing in 1st person, which is the preferred mode for the mod, or lowering your settings, especially the resolution, a bit to make sure that you are getting a stable 90 fps.

**Comment by Loginno** [comment]
So I tried to play ad nauseum with 1st person, 3rd person with unstable results. When the background seemed fine, some close objects were super jumpy, and vice versa. Stable close objects, but back to choppy background.

One thing I've noticed is that the first minute of the game gets me to 70+ FPS, but the more I play - the worse it gets. Drops down very fast to 50+, then 30-50.

BTW never got to 90+ FPS - even in the lowest of settings.

The prime suspect here is the ASW, and the Oculus tweak in general. For some reason, I can't get the dev HUD running to make sure it is off (with neither Oculus Tray Tool, or the Oculus Debug Tool), and if I can't get that - I can't vouch for any other tweak, including turning the ASW off.

So I'm off to reinstalling the Oculus Driver and try my best to get the HUD running at least. If you have any tips for forcing the HUD - that would be great.

Attaching screenshots of the configured tools.

![Screenshot 2021-04-04 190821](https://user-images.githubusercontent.com/25033884/113515324-7963d080-957c-11eb-99f8-91d3b7f9bb79.png)
![Screenshot 2021-04-04 190911](https://user-images.githubusercontent.com/25033884/113515325-7c5ec100-957c-11eb-834b-c406f8a30fb6.png)

**Comment by Loginno** [comment]
OK I got it (no one said anything about changing the setting AFTER link has established. Sheesh...) and made a video. I guess you can both see the performance layer and maybe even combine the mirror to see the choppiness? 

The settings are default LOW with two changes: 960 X 960 pixel resolution instead of 600 X 600 (changed both command.txt and settings.xml), and refresh 90 instead of 60.

ASW confirmed OFF.

Can you see something out of the ordinary in the video? https://youtu.be/2uvsqf4i6rk

BTW I can repeat that for 1st person, but it's basically the same in terms of performance indicators.

Settings used:

[settings.xml.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6255206/settings.xml.txt)

**Comment by LukeRoss00** [comment]
I've seen the video, and the choppiness there is definitely not normal.

Firstly, with your video card and graphics settings, you should easily be able to keep a constant 90 fps through most areas of the game. Unfortunately I don't have a sample of your specific card to test with, but it's only slightly less powerful than the NVIDIA 1080 Ti which was the card I used to develop the mod, so I would expect _much_ better performance than you're getting.

Secondly, and perhaps more importantly, the drop in frame rate as you keep playing, from 70 down to 50 or even 30, is a strong indicator that something is wrong with your configuration. Often this behavior is observed when there is a memory leak. However, I am 100% sure that there are no memory leaks either in the game or my mod, because I have never experienced that kind of issue, nor has anybody else using my mod ever mentioned it.

So, the leak must be somewhere else. The most likely suspects are overlays, global hooking programs, gaming HUDs, streaming software, RGB lighting crapware... Anything that might be attaching itself to the game and causing the slowdowns due to sloppy programming, as if often the case with RGB lighting or other bloatware that comes with the motherboard or the video card, or due to unexpected interactions, as can happen with overlays and other software that grabs the game output.

**Comment by Loginno** [comment]
Eloquently speaking: sh************t

This, sir, is a challenge. You say "gaming crapware", and I hear "Gigabyte AORUS f-ing edition where you pay more for bonus memory leaks".

I'm going to go in a two-prong approach:
a. run the game in as clean an environment as possible (minimum services. even safe mode if I can). See if we filter the disease
b. install the specific AORUS driver and utilities, update the firmware, etc. See if this was a known, patched issue.

A hunch tells me b would produce results.

And I would probably say goodbye to AMD because that was the last straw with their cards...

Thank you for your patience

**Comment by Loginno** [comment]
Did someone say LED?

![image](https://user-images.githubusercontent.com/25033884/113565466-af07c880-9613-11eb-8ed7-74df5d310344.png)

**Comment by LukeRoss00** [comment]
Did you get to the bottom of it?

**Comment by Loginno** [comment]
Sorry, did not have a lot of time to work on it. I want to stop a lot of services and run it. Couldn't find the time.

Another option is to install the card-specific driver from the manufacturer which is about 2 years old.

**Comment by LukeRoss00** [comment]
Yeah, it can be one of the nastiest problems to debug. I had a similar issue some time ago, and IIRC not even stopping services would get rid of it, because the RGB utility that the motherboard had kindly installed without even asking me was so nasty that it kept respawning new instance of the service as fast as I could kill them. I had to hunt it down and remove it from the system. Good luck!

**Comment by Loginno** [comment]
Just tried to close as many services as I could. No luck. Please see this service export. I have noted which are running and which are not. Any potential perps?

[ServiceList.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6291427/ServiceList.txt)

**Comment by Loginno** [comment]
@LukeRoss00 I gave up and sadly reverted to pancake. Don't know if I can still play since it's really not the same thing anymore...

**Comment by LukeRoss00** [comment]
We can try one last thing if you're up for it. Download Process Explorer (https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer). Then, with the game running in VR, select the game executable in Process Explorer from the list on the left, so that the .dlls loaded by the game process are shown in the bottom pane. Press Ctrl+A in Process Explorer (short for Save As), and attach the resulting file here.

Perhaps the list of .dlls loaded by the game will show one or more potential culprits.

**Comment by Loginno** [comment]
Wow! Thanks! here it is:
[GTA5.exe.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6296515/GTA5.exe.txt)

**Comment by Loginno** [comment]
sdk_legacy_led_x64.dll ??? Logitech??

**Comment by LukeRoss00** [comment]
That could be a suspect, yes. I have a similar entry on my system but in my case it's "C:\Program Files\Logitech Gaming Software\SDK\LED\x64\LogitechLed.dll", without the "legacy" part.

Also, another thing that strikes me as odd is the presence of the Windows Compatibility DLL (C:\Windows\System32\AcGenral.dll) in your list. I don't have it. It seems that at some point in time Windows decided to apply some compatibility fixes to your game, which might be a symptom of erratic behavior but it might also be a cause.

**Comment by Loginno** [comment]
I'll uninstall the Logitech S/W and let you know. Anything I can do re the Compatibility DLL? Make sure that the .exe is not running in compatibility mode?

**Comment by LukeRoss00** [comment]
It requires some tinkering, see here for example: https://superuser.com/questions/309582/how-can-i-remove-compatibility-settings-that-are-not-editable-from-the-compatibi

**Comment by Loginno** [comment]
Thanks. Found this and removed it:
![image](https://user-images.githubusercontent.com/25033884/114418955-abe47d80-9bbb-11eb-8638-a8315b47e343.png)

**Comment by LukeRoss00** [comment]
Mmm... doesn't look like it's very important. However, I noticed from your list that you're using Google Drive File Stream. Is your G: drive a local SSD?

**Comment by Loginno** [comment]
Indeed. A local SSD.

**Comment by Loginno** [comment]
@LukeRoss00 just to compare (and potentially to replace if no solution is found), I bought VorpX to see if there is a difference. In VorpX everything works perfectly (in Immersive mode. For some reason DirectVR is not supported here). No choppy rotation. I also realized how slick your mod is compared to VorpX, with every little detail customized for good gameplay. Just sucks that I can't get it to work.
If you have no other leads we can close this topic with great sadness...

**Comment by LukeRoss00** [comment]
Unfortunately I'm almost out of ideas :-( No other user has ever encountered this exact problem, and it's quite hard to diagnose.

How many minutes of gameplay are needed for your frame rate to grind down to 30-50 fps?

**Comment by Loginno** [comment]
It's only a few minutes if I'm active and changing sceneries. If I keep to a static environment (i.e. stay in the same apartment etc.) it doesn't drop.

**Comment by LukeRoss00** [comment]
So it's almost certainly a streaming-related problem. That's why I was suspicious when I noticed Google Drive File Stream on your process list. When the game needs to stream in a lot of new geometry and textures from disk and through PCI to upload them to the video card, something breaks down somewhere.

I'm sorry but I don't see an easy solution. If this were an official support line, my script would probably be at the "Try reinstalling Windows from scratch" part ^_^

I won't actually suggest that to you though. I'll close the issue now, feel free to reopen if you have any news!
