### ISSUE TITLE
Low quality image and low GPU usage

### ISSUE THREAD

**Issue by satyaloka93** [LukeRoss00/gta5-real-mod#35]
It seems my GPU is not being taxed (5-6%), CPU hovers around 40-50%. I edited the description to be exactly what's in my device manager "NVIDIA GeForce GTX 1080". I have gone so far as deleting the settings.xml, letting the system re-create, and manually editing all other settings to mirror the low/high mod files (I've tried both). My Windows install is only a couple weeks old, on a new build of AMD 3600, Crucial ballistic 16gb (3200), ASRock Steel Legend B450-tried XMP and auto already-and GTX 1080. CPU and 1080 are stock speeds. The image seems to be 'shimmery' with more pixelation than I think others are experiencing, and the low GPU usage leads me to believe something is going wrong. Also, no onboard video is detected, ingame settings lists correct VRAM (8GB). In game settings are all per mod.

**Comment by LukeRoss00** [comment]
What frame rate are you getting? You can see it in the lower right corner if you press F11 and then N.

Other users found that similar issues were caused by non-default settings in the NVIDIA control panel, especially game-specific 3D settings, custom resolutions/scaling etc.

**Comment by satyaloka93** [comment]
> What frame rate are you getting? You can see it in the lower right corner if you press F11 and then N.
> 
> Other users found that similar issues were caused by non-default settings in the NVIDIA control panel, especially game-specific 3D settings, custom resolutions/scaling/DSR etc.
The fps counter seems to be flickering quickly, I think it is between 80 and 90 fps. The nvidia control panel is almost at defaults,aside from turning off desktop resolution scaling.the The rest is application controlled. My Windows 10 installation is only a couple weeks old from my computer rebuild, so drivers and software is all up to date as well.

**Comment by LukeRoss00** [comment]
Then you might try pushing up the resolution a bit, that would increase GPU occupancy and reduce the pixelation. What is your Windows desktop resolution? Also, does the game appear as a borderless square window on the monitor?

**Comment by satyaloka93** [comment]
I had it at 1200x1200, 2.5 scaling. My desktop resolution is 1920x1080, and yes gta is windowed borderless.

**Comment by LukeRoss00** [comment]
GTA will never create/use a window that is larger than the screen. If your desktop resolution is 1080p, you must limit the resolution in the settings file to 1080x1080, which is what I put there because I know that most users have a 1080p monitor.

**Comment by satyaloka93** [comment]
That was the issue! It is still very odd I use low GPU, but it is much less jittery now. For some reason when I use the cell now I go headless and I see wheels in the sky, odd.
