### ISSUE TITLE
Reoccurring error

### ISSUE THREAD

**Issue by zaoc1** [LukeRoss00/gta5-real-mod#350]
SCRIPT HOOK V ERROR

Core: An exception occurred while executing 'RealVR.asi'
(0x00007FFDABB0A2E0), id 34

Sometimes the id is 41. The scripthook error always appears at the exact point during loading single player.
I'm using release 7 on a clean install with the latest scripthook version because the one that came with release 7 had an error about being too old.

**Comment by LukeRoss00** [comment]
Please see #239 when opening new issues

**Comment by zaoc1** [comment]
Hmm ok, I was hoping perhaps it just needed to be updated with the latest release of GTA but I'll get all that info for you now.

MSI MPG Z490 Gaming Carbon WiFi
Intel i9 10900k All cores @ 5.1GHz
32GB (2x16) G.Skill Trident Z Neo @ 3600MHz
8GB MSI GTX 1080 Gaming X
Valve Index
Release 7
Epic Games (Build 2245 Online 1.54)
ScriptHookV_1.0.2245.0
I did step 4 and first tried High and have since tried Medium with the same error.
No error reports in the batch file and I have not manually changed anything.
No other mods are running, I didn't even include the native trainer that comes with scripthook.

After I click OK on the error, I have a black screen with audio and I can hear my game but I see nothing (through the headset).
When I take the headset off and look at my PC, I can see the game and interact with it.
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6331018/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6331020/ScriptHookV.log)

RealVR.ini wouldn't upload (unsupported file type) so I'll copy and paste it here.


[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 0

; 0           Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left, right) - right at start
DominantEye = 2

; Y           Select heading control (always, only when aiming, never) - always at start
HeadingControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 0

; End         Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 1

**Comment by LukeRoss00** [comment]
Thanks! According to the info you posted, the most likely explanation is that you're not actually using Release 7 of the mod. Did you download the mod from the GitHub [Release page](https://github.com/LukeRoss00/gta5-real-mod/releases) or from some other website?

Make sure to use the file at https://github.com/LukeRoss00/gta5-real-mod/releases/download/r7/GTAV_REAL_mod_by_LukeRoss_r7.rar, and also check that your user has write access to the game directory. It appears that sometimes users with the Epic Games version have trouble writing the mod files to the game folder because of overly strict permissions.

**Comment by zaoc1** [comment]
Oh, well this is embarrassing. Umm, you passed the test? lol now I feel like a complete idiot. I'm sure I did download it from this website, but yeah it wasn't release 7. Awkward. Release 7 is actually working fine with the latest scripthook, no errors. Thank you Sir for not roasting me a new one for being a dumbass.

Man I was so sure I downloaded 7....
