### ISSUE TITLE
Slight up and down movement still present in 1st person on foot

### ISSUE THREAD

**Issue by palappapap** [LukeRoss00/gta5-real-mod#353]
Thank you for your work in advance!
version 1.0.2245.0. epic games store, Rift Cv1, mod r7

I searched the web and asked in reddit; the people guided me to your direct contact.
I even tried reinstalling the mod, but there is still head bobbing aka up and down movemnt when walking or running in VR.
Is this a problem with my install or is there still some movement left even with head bobbing disabled?

**Comment by LukeRoss00** [comment]
No, there's nothing wrong with your setup! The 1st person gameplay camera is located where the character's head would be, so when walking or running there is a slight, natural movement just like there would be in real life. That's what the designers of GTA V chose for the game, and I have to say that I personally enjoy it. I never quite liked the artificial "gliding on glass" effect that Half-Life games always had, for instance.

That said, if you want the steady-cam feeling, you can play in 3rd person. The 3rd person camera is fully stabilized by the game.

**Comment by palappapap** [comment]
Ahhh; ok, thx! but why is it that I don't see any difference when turning headbobbing on or off?

**Comment by LukeRoss00** [comment]
Actually, you should be able to see some difference. It's quite visible for example when sprinting: head bobbing will be much more pronounced if it's turned on in the menus. Although it's not a night and day difference: see [this video](https://www.youtube.com/watch?v=xu1Xq6A5pKk).

But to be honest, the real reason why it should be turned off with my mod is not this difference, but the fact that it messes with the character heading control when running if it's left on :-D

**Comment by palappapap** [comment]
thank you very much for the detailed explanation; maybe I find a config. or mod for the rest little camera movement. 

But when it is connected with the player rig it might not work. Although, there is tweaking already in the code; otherwise there would be no head bobbing option. so it might be possible!
