### ISSUE TITLE
Fivem Support

### ISSUE THREAD

**Issue by RootingInLoad** [LukeRoss00/gta5-real-mod#354]
Hello, first I'd like to thank you for all your work, because the mod you created is very neat, and I enjoy it a lot ! But there's one thing that I'd like above all, could you make it work for Fivem, I know this has already been requested somewhere, but I wish I could play with my friends on Fivem, with your mod, I already tried to put all of the files you provide, but it make crashes the game, so I with you could me, and help everyone who wants to get your mod working on Fivem, that'd be amazing ! Thanks

**Comment by LukeRoss00** [comment]
As far as I know, for the moment no one has been able to make any form of multiplayer (official or unofficial) work in VR. See issue #34 for more details.

**Comment by massreklaw** [comment]
> As far as I know, for the moment no one has been able to make any form of multiplayer (official or unofficial) work in VR. See issue #34 for more details.

I got it too work using singleplayer co op mod but not sure if it will work with fivem

**Comment by RootingInLoad** [comment]
> > As far as I know, for the moment no one has been able to make any form of multiplayer (official or unofficial) work in VR. See issue #34 for more details.
> 
> I got it too work using singleplayer co op mod but not sure if it will work with fivem

If you're able to make it work on FiveM could you tell me please ? I'd really like to play on FiveM in VR 😀

**Comment by abuneo** [comment]
any updates? 

> > As far as I know, for the moment no one has been able to make any form of multiplayer (official or unofficial) work in VR. See issue #34 for more details.
> 
> I got it too work using singleplayer co op mod but not sure if it will work with fivem
