### ISSUE TITLE
Oculus Quest Air Link

### ISSUE THREAD

**Issue by OneToo** [LukeRoss00/gta5-real-mod#355]
I know this isn't an issue, but for as long as GTA V  Real has existed, I've been attempting to play wireless with the Quest and Virtual Desktop or ALVR with no luck.   Finally, GTA V is working flawlessly with Oculus Air Link which was released officially yesterday.   It only officially supports the Quest 2, but there is a way to easily enable Air Link on the Quest 1 with a sideloaded APK called [AirLinkConnector](https://www.reddit.com/r/OculusQuest/comments/mwy223/app_airlinkconnector_connect_with_airlink_without/).   Try it out for increased immersion.  Playing without the wire is amazing and feels really free.   You should note that this is a compatible way to play in the mod notes.

**Comment by LukeRoss00** [comment]
Thank you @OneToo, that's wonderful news!!! I was looking forward to this.

I'll go and update the README right now :-D

**Comment by Jesusavesouls** [comment]
Thanks and will try out. I was actually leaving a issue, not issue but request for airlink or virtual desktop to be updated to work with this mod.
