### ISSUE TITLE
Slow-motion bug

### ISSUE THREAD

**Issue by krizzzgaming** [LukeRoss00/gta5-real-mod#361]
I get this weird slow-motion when playing with Real VR mod, I think the slow-motion starts when I hold the left thumbstick down but I'm not sure, also everything speeds up back to normal when you hold up on the D-pad but as soon as you release it there's slow-motion again. Does someone know a fix to it, how to turn off the slow-motion or what is causing it?

**Comment by LukeRoss00** [comment]
See #81 😄
