### ISSUE TITLE
Paetron question

### ISSUE THREAD

**Issue by dantharp** [LukeRoss00/gta5-real-mod#363]
Hi Luke,
I've been a long time fan of your work (GTA 5 VR and No One Lives Forever 2 VR) and I discovered you have a Paetron out there which offers paid access to these VR mods as well as your recent Red Dead Redemption 2 VR mod (which I'm incredibly interested in).
My question is this: Is donating to your Paetron at $10 per month the only option for getting these mods?
I'm not trying to be a cheap ass or anything, but $10 a month is $120 a year and year after year that stacks up.
Personally, I'd easily pay $60 for access to your RDR2 mod, on top of the $60 or so for the game itself.
Your VR mods are that good!     :)
Can I pay you (either through Paetron or some other means) a lump sum or perhaps $5/month instead of $10 to get access to that mod?
Again, I'm not trying to be a cheap ass--(OK, well maybe I am)--but my point is I'm 110% willing to compensate you for access to the VR mods....I'm just wondering if there's a more reasonable option?
Thanks,
Dan Tharp
dantharp@gmail.com

**Comment by LukeRoss00** [comment]
My GTA V and NOLF2 mods will continue to be freely available on GitHub. For RDR2, which is in early access, you don't need to stay subscribed. You can pledge for as long as you feel comfortable with, and when you leave my Patreon the mod will keep working.

**Comment by dantharp** [comment]
Thanks Luke.  MUCH appreciated!
Your mods are amazing and I'll definitely subscribe to your Patreon.
I'd encourage everyone to subscribe to Luke's Patreon here: https://www.patreon.com/realvr

**Comment by cercata** [comment]
If we remain suscribed to patreon, maybe he'll be able to work on future mods full time ;)

Taking into accound this is the third MOD he released, and I enjoyed all them a lot, that deserves at least one year of patreon.

**Comment by LukeRoss00** [comment]
Cercata, you're the best, thank you so much for all your support through these years!

Re: your question about fast traveling with the train, it does work for me. However, I also find that RDR2 is much more crash prone than GTA V. GTA V never crashes for me, literally never, whereas RDR2 especially likes to crash around Valentine and when loading new areas (so for instance when fast traveling and when galloping fast with your horse between cities). My advice is to create plenty of manual saves whenever possible (i.e., in free roam), especially before taking a trip ;-)

**Comment by cercata** [comment]
Thank so much to you for allowing us to play the best games in the world in REAL VR :)

Regarding crashes in RDR2, after 25h it only crashed once for me, in Valentine. I have trevalled a lot, but I'm still in chapter 2 ... it's maybe related to chapters ?

The fast travel thing was weird, I didn't know it it was a crash, or the game running without showing graphics.

**Comment by LukeRoss00** [comment]
Usually for me it doesn't crash to desktop, but hangs with a frozen screen (most times a black screen, since it tends to happen while loading) and the ambient sounds/music still playing but the game not responding to commands. When it gets in that state it needs to be killed from Task Manager, which also reports that the game is not responding. 🤷 I've tried waiting but it never gets out of its guru meditation, so after 5 seconds of black screen I've learnt just to kill it and reload
