### ISSUE TITLE
Gta v vr oculus quest black screen not full vr

### ISSUE THREAD

**Issue by Coyotewall** [LukeRoss00/gta5-real-mod#364]
I am using new script hook V with v7 mod, I also have followed different YouTube videos and I have got it to get inside the game but when I do go into gameplay there is a black screen and I'm moving on my monitor screen but not on my headset
i have a medium end system so I chose the medium setting,

some of my pc specs are
intel i7 7700hq
Gtx 1060 6gb
16 gb of ram
I am running on a laptop and that could be the reason
I'm using an oculus quest does it not work on it?
I followed the oculus quick steps and I have searched on the web for hours
I do not change the graphics settings manually but fx setting don't work good and also VSync so with the low settings present you made it turns them off,
The batch file doesn't report anything as far as I see the only thing I'm running into is my headset just shows a black screen and only sound and I (can) go into the menu.
Im not using any other mods just your vr mods.
I am using oculus vr, is there maybe a setting that makes it go into full vr?

sometimes what happens is my vr shows what my monitor sees and so i play the game in my monitor and not actually using vr, and it just acts weird.

**Comment by LukeRoss00** [comment]
> I'm using an oculus quest does it not work on it?

The Quest works for other users.

> I do not change the graphics settings manually but fx setting don't work good and also VSync so with the low settings present you made it turns them off
> I am using oculus vr, is there maybe a setting that makes it go into full vr?

I don't understand what you're saying, sorry

> my headset just shows a black screen and only sound and I (can) go into the menu.

Usually that is caused by wrong graphics settings.

Could you attach your `RealVR.ini`, `asiloader.log` and `ScriptHookV.log` files so I can take a look?

**Comment by Coyotewall** [comment]
My laptop doesn't really work good with vr, main cause is overheating. 
Thank you for trying to help me though
