### ISSUE TITLE
New to this so bare with me

### ISSUE THREAD

**Issue by karlmemphis87** [LukeRoss00/gta5-real-mod#367]
hi have done done exaclty what insutions are showing but having this issue any help

Oculus quest 2

On my monitor I see the game without any hud

On my headset I see the hud without any game

any help would be greatly appreciated

**Comment by LukeRoss00** [comment]
Please see #239 and provide the required info

**Comment by karlmemphis87** [comment]
CPU i9 10900k
GPU RTX 3080 
VR Headset Oculus quest 2
Mod is new version 7
GTAV Steam 

Followed setup several times
and i have tried with both H/ M 
not using any other mods as was from fresh install

problem i have is all ok loading up and when have Headset on my monitor is showing the main screen ie the carter outside world etc and my VR set i can only see HUD,Menu,etc i can see what i can see on my screen if that makes any sense

i haven't had any error reports since replaced them with new one

**Comment by karlmemphis87** [comment]
[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 0

; 0           Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left, right) - right at start
DominantEye = 2

; Y           Select heading control (always, only when aiming, never) - always at start
HeadingControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 0

; End         Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 1

**Comment by karlmemphis87** [comment]
asi loader log


// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\windows\system32\dinput8.dll" => 00007FFD5E310000
API: "DirectInput8Create" => 00007FFD5E312230
API: "DllCanUnloadNow" => 00007FFD5E325220
API: "DllGetClassObject" => 00007FFD5E325330
API: "DllRegisterServer" => 00007FFD5E334740
API: "DllUnregisterServer" => 00007FFD5E3349C0
LOADER: Loading *.asi plugins
ASI: Loading "C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\NativeTrainer.asi"
     "NativeTrainer.asi" => 00007FFD5E220000
LOADER: Finished loading *.asi plugins

**Comment by karlmemphis87** [comment]
script hook log


// GTA V SCRIPT HOOK (build Mar 20 2021, v1.0.2245.0)
//     (C) Alexander Blade 2015-2021
[20:02:54] INIT: Started
[20:02:54] INIT: Success, game version is VER_1_0_2245_0_STEAM
[20:02:54] INIT: Registering script 'NativeTrainer.asi' (0x00007FFD5E22A3C0)
[20:02:59] INIT: Pool 1 extended
[20:02:59] INIT: Pool 2 extended
[20:02:59] INIT: Pool 3 extended
[20:02:59] INIT: Pool 4 extended
[20:03:05] INIT: GtaThread collection size 189
[20:03:05] INIT: wnd proc 0x00000000FFFF01F7
[20:03:05] INIT: IDXGISwapChain 0x00007FFCF63E49E0 (0x00007FFCF62151E0)
[20:03:05] INIT: IDXGISwapChain set
[20:03:05] INIT: DX init started
[20:03:05] INIT: DX feature level B000
[20:03:05] INIT: DX init succeeded
[20:03:59] CORE: Requesting thread creation
[20:03:59] CORE: Creating threads
[20:03:59] CORE: Started control thread, id 32 active 1
[20:03:59] CORE: Started thread 'NativeTrainer.asi' (0x00007FFD5E22A3C0), id 33 active 1
[20:03:59] CORE: Launching main() for 'NativeTrainer.asi' (0x00007FFD5E22A3C0), id 33

**Comment by LukeRoss00** [comment]
Your .ini file shows that you are in fact NOT using Release 7. Please make sure to download the latest release and use it to overwrite the one you have installed. Also, you didn't extract the mod to the correct folder. You should put the mod in the game folder where `GTA5.exe` is, not into a subfolder.
