### ISSUE TITLE
Reshade

### ISSUE THREAD

**Issue by tomreason** [LukeRoss00/gta5-real-mod#37]
Hi @LukeRoss00 ! I recently tried the Reshade function for GTA 5. Is it possible to somehow add depth to the helmet on HTS VIVE using it? All the functions that I used were added only on the screen, the picture in the helmet changed completely, but there are many functions associated with 3D stereo. I'm not selenium in programming, but can I use it to start a normal depth display?

**Comment by LukeRoss00** [comment]
No, the "fake 3D" introduced by Reshade cannot be used for proper VR rendering
