### ISSUE TITLE
Judder When Turning Head

### ISSUE THREAD

**Issue by munkyonline** [LukeRoss00/gta5-real-mod#370]
Hi LukeRoss00,

My system:
AMD Ryzen 9 5900x OC to 4.65Ghz
32GB RAM
Windows 10 Pro 64-bit Version 21H1
Geforce 3800 RTX Suprim
Nvidia Drivers 471.11
HP Reverb G2
GTA V Steam Version Build ID 6337558
SteamVR beta 1.18.3 with Motion Smoothing Off
Yes been though the steps
I chose H, no errors
No changes to settings manually (this time)
No other mods currently

First of all - thank you for this mod, it's bloody brilliant! 

I initially tried pushing it as far as I could by setting everything on max settings, and the resolution to 1650 x 1650 (any higher and the headset crashed) but the FPS was very low, and with the judder it was unplayable. I also had a couple of other mods installed at the time. I tried adjusting the settings but couldn't fix it, so this evening i've reinstalled the game and started from scratch.

Now when I load the game up (with no other mods or manual adjustments to the settings) I can still see visual juddering when turning my head, and when things are moving in game. I don't experience this in other VR games - Half Life Alyx for example is completely smooth. 

I can run Modern Warfare and other similar titles at 170+ FPS on max settings, so I would have thought I could set the graphic settings quite high on this. I read that you said MSAA eats FPS so I lowered it to 4x with NVIDIA TXAA ON and get around 60-70 FPS, which seems quite low to me? The more I improve the visual quality, the more visible the judder. 

SteamVR and OpenXR seem to be quite buggy and crash quite often too (although it seemed to be more stable before I recently upgraded from a 1080 GTX to the 3080 RTX). I've tried OpenXR set to SteamVR and WMR.

I'm not sure what else I can try, any assistance you can provide will be greatly appreciated. Thanks!

**Comment by LukeRoss00** [comment]
Hi! Could you post your `RealVR.ini` file? You can drag it here if you make a copy and rename it to `.txt`

**Comment by munkyonline** [comment]
Sure no problem: [RealVR.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6703790/RealVR.txt)

Thanks

**Comment by LukeRoss00** [comment]
You did not select the OpenXR renderer (see the [Release notes](https://github.com/LukeRoss00/gta5-real-mod/releases)). Edit the `RealVR.ini` file with a text editor like Notepad (do not use anything fancy like Word) and change the line `VRAPI = 0` to `VRAPI = 3` in order to have the mod render using the OpenXR backend. The OpenXR active runtime must be set to WMR.

The reason for this is that the WMR driver for SteamVR is buggy and doesn't support independent eye poses correctly. So, with WMR headsets, you want to keep SteamVR out of the equation completely.

**Comment by munkyonline** [comment]
Ah OK, I honestly had tried setting that to 3 on the previous attempt but the game crashed to desktop after loading. Will give that a try now. Thanks

**Comment by munkyonline** [comment]
Yep that sorted it thank you. I must have had the OpenXR set to SteamVR when I last tried it.

Looking forward to now playing this all again in VR :)

Do you think 60-70 FPS is about right for my system, or is there something else I need to tweak? I can only get solid 90 FPS when I run the RealBat and set it to H, and then not change anything else.

**Comment by LukeRoss00** [comment]
It is about right. Especially MSAA is a performance killer with GTA V, I'd advise to keep it no higher than 2x. Some jaggies are unavoidable with this game, it's never been known to have good antialiasing even in 2D
