### ISSUE TITLE
Scripthook not working

### ISSUE THREAD

**Issue by Tgfkacalvinh0** [LukeRoss00/gta5-real-mod#371]
Hey Luke,

First of all you did a great job on the mod really liked it a few months ago.
But now when i install the game and add the files to the game including the new scripthook it keeps telling me that the scripthook version is wrong.
I've tried everything i found online but to no avail.
I'm sure i dowloaded the latest version as it was from march 2021.
I hope you could help me out because this time my pc is much better so the experience would be even better then a few months ago.

Sincerely,

Marinus Emmers

**Comment by LukeRoss00** [comment]
Could you attach your `ScriptHookV.log` file?

**Comment by Tgfkacalvinh0** [comment]
I'm currently at work but will do it when i get home thanks for the fast respond.

**Comment by Tgfkacalvinh0** [comment]
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6712446/ScriptHookV.log)

I also looked at the file and it says build Dec 18 2020 although on the site where i downloaded it it says it was released at 20 march 2021.

**Comment by LukeRoss00** [comment]
The correct place to download from is http://www.dev-c.com/gtav/scripthookv/

When you extract the new `.dll`, be sure to place it directly in the `GTA5.exe` folder and not in a subfolder like `bin`

**Comment by Tgfkacalvinh0** [comment]
Ok i will try that.
At least i got the right scripthook i will keep you posted

**Comment by Tgfkacalvinh0** [comment]
Hey there Luke,

this solved the problem thanks for your help.
It was not the scripthook itself but the fact that it copied into the bin file.
I've allready played a little and now it just really amazing with my new pc no more screen tearing.
Certainly gonna buy rdr2 and have a look at your vr mod for that.
keep up the good work with delivering what triple A companies won't do.
