### ISSUE TITLE
Simeon

### ISSUE THREAD

**Issue by Anarasha** [LukeRoss00/gta5-real-mod#372]
<<I'm assuming anyone reading this played the game before, but just in case, this issue contains early game spoilers>>

    **CPU:** AMD Ryzen 3700
    **GPU:** GTX 970 
    **VR headset model:** Oculus Quest 2 running Link through a cable 
    **Game version and build:** I could not find this info, but I installed the game a few days ago, so newest version 
    **Release of the mod:** Release 7 
    **Did you follow all the Quick setup steps carefully, in particular step 4?:** Yes I did 
    **Which settings did you choose (H/M/L) when running the batch file RealConfig.bat?** M
    **Did the batch file report any errors?** At first it did, but I ran it as administrator and then it finished perfectly with no errors 
    **Did you change the graphics settings manually?** No
    **Are you using any other mods?** No

So, I just started playing the R.E.A.L mod, and I love it so far! I did run into one issue though. 
During the part where Michael pulls a gun on Franklin and makes him drive the car into Simeon's den of fraudulent shitbaggery, the camera is vastly buggered. First off, you don't get to play that part in VR, which is a bit of a shame because that might be more powerful. But driving is also a bit of an issue because you have to rely on cinematic cameras and such. 

But the kicker that made me start this issue came when actually driving into the dealership. The camera went off to.... who knows where? I could not actually see the car unless I stood up and looked down, and the car was gone again as soon as I started driving. This made me take someting like 5 tries to hit the dealership, and I was afraid I was gonna fail a pretty much unfailable mission. 

It's not a huge issue, but it seems like something you might have an idea on how to handle :-)

**Comment by LukeRoss00** [comment]
[Title modified. No swearing needed.]

Yes, it's very easy: when the camera seems to point in the wrong direction (mostly during scripted transitions from 1st to 3rd person and vice versa), just shake your head to recenter.

**Comment by Anarasha** [comment]
> [Title modified. No swearing needed.]
The decision to remove swearing for a mod for a game about murderous bank robbers seems quaint - but I respect your distaste for it :D 

>  just shake your head to recenter. 
That seems reasonable :D Thanks, I'll give that a shot if I do another playthrough or encounter similar issues
