### ISSUE TITLE
HUD position

### ISSUE THREAD

**Issue by Anarasha** [LukeRoss00/gta5-real-mod#373]
**CPU:** AMD Ryzen 3700
    **GPU:** GTX 970 
    **VR headset model:** Oculus Quest 2 running Link through a cable 
    **Game version and build:** I could not find this info, but I installed the game a few days ago, so newest version 
    **Release of the mod:** Release 7 
    **Did you follow all the Quick setup steps carefully, in particular step 4?:** Yes I did 
    **Which settings did you choose (H/M/L) when running the batch file RealConfig.bat?** M
    **Did the batch file report any errors?** At first it did, but I ran it as administrator and then it finished perfectly with no errors 
    **Did you change the graphics settings manually?** No
    **Are you using any other mods?** No

This may be more of a suggestion than an actual issue, but here goes. 

I play the mod and am a huge fan. However, the HUD to me is a bit too far to the edges. I realize that most people might enjoy it like this due to immersion, but I have a hard time keeping an eye on my HP, where I'm going and my special ability bar. 
So what I would like is the option to reposition the HUD, or several HUD versions. That, or at least having the HP/Armor/special bar moved to a discreet middle of the screen thing :-) 

I hope this suggestion is useful to you, and I do hope you will eventually implement it as I would truly love that :-)

**Comment by LukeRoss00** [comment]
IIRC there are several other mods around the web that allow you to redesign the HUD, moving stuff around. I suggest trying to mix my mod with one of those, so that you can adjust the HUD elements to your liking!

**Comment by Anarasha** [comment]
Do you happen to know the name for any of these mods? Because I tried looking and couldn't find any, but modding GTA V is pretty new to me :-)

**Comment by LukeRoss00** [comment]
Here are 14 pages ^_^ full of them: https://www.gta5-mods.com/all/tags/hud/

**Comment by Anarasha** [comment]
Oh, I gotta admit I thought that was a scam website when I found it. 
Thank you! :-) I really appreciate it
