### ISSUE TITLE
Support for FidelityFx Super Resolution ?

### ISSUE THREAD

**Issue by coru182** [LukeRoss00/gta5-real-mod#374]
Hey Luke,

Any chance you can make your mod compatible with FidelityFx Super Resolution? (https://github.com/NarutoUA/gta5_fsr)
If you can make it work i'm sure your mod users will appreciate the extra performance.

Thanks!

**Comment by LukeRoss00** [comment]
On first look, it doesn't seem like it would work. The mod you linked to uses FSR to recover from a Frame scaling which is less than 1 (they list 1:2 to 5:6 ratios) with a better quality than GTA V internal upscaler can provide. My mod uses Frame scaling to make the game natively draw an image with a higher resolution than the output window: no upscaling is ever involved.

**Comment by LukeRoss00** [comment]
(The name "Frame scaling" given to the option is perhaps a bit misleading: it's really more of an "Internal resolution multiplier", as no upscaling or downscaling is involved when the internal buffer is drawn)

**Comment by ASchneiderBR** [comment]
Hello guys! Just to let you know that I've tried yesterday OpenFSR with your mod and it works great! I can now set the config bat to high, FSR to 80% its resolution and get a steady 90hz with my Quest 2 (1.5 render quality). This is just amazing! Running with a Ryzen 9 3900x, 2080ti, 32gb DDR4 3600.

**Comment by coru182** [comment]
Can you post instructions how you made It work and your game settings file?
I was not able to make it work myself when I tried.

Thanks!!

**Comment by ASchneiderBR** [comment]
> Can you post instructions how you made It work and your game settings file? I was not able to make it work myself when I tried. Thanks!!

Hey there! No problem. I'm using this great app: https://github.com/tappi287/openvr_fsr_app

It can install open_fsr mod automatically with an user interface, works great. The only problem is this software is not digitally signed so Windows Defender keeps flagging as a virus. If you don't feel comfortable to use it, you can always apply the mod manually. The latest version of this app, lets you add a custom path, if you are like me and bought GTA from Rockstar, not Steam.

These are my settings:

![image](https://user-images.githubusercontent.com/25224882/133357117-b59fb0ed-b604-4ccc-aba3-f379c85a8f4a.png)

Let me know if you need any help.

**Comment by coru182** [comment]
Thanks for the quick reply. However, i'm still unable to make it work.
Can you post your realVR.ini file and your settings.cfg file from documents
and settings?

Thanks,

**Comment by ASchneiderBR** [comment]
Hello @coru182, I have not changed any of those files. I've unpacked the provided 7zip file into the game folder, updated the scripthook files, fired up the bat config file and then applied open fsr dll using the UI from the above app (running as admin).

**Comment by coru182** [comment]
No worries. I was able to make it work by switching to openVR rather than
OpenXR. Unfortunately I’m using a WMR headset which works like crap on
OpenVR, so it actually runs smoother with OpenXR and FSR disabled.

Thanks for your time and help tho. Not sure if FSR can be made compatible
with OXR, but that would be sweet.

**Comment by ASchneiderBR** [comment]
Hello. No, currently, this FSR mod does not work with OXR. The first game I've tested was the most needed Flight Simulator 2020 with no luck, because it uses OXR only.
