### ISSUE TITLE
Game won't start in VR with OpenXR api

### ISSUE THREAD

**Issue by 3DArtistExtreme** [LukeRoss00/gta5-real-mod#377]
To launch a game on WMR headset such as HP Reverb G2 is still an issue.
Game won't start in VR mode with OpenXR set to ON, in the config file.
Game starts in VR mode only with Steam VR or Oculus api's.
Starting game with Steam VR on WMR headset causes immense tearing and stuttering, making it unplayable.

**Comment by LukeRoss00** [comment]
Please see #239 when creating new issues

**Comment by 3DArtistExtreme** [comment]
CPU: Intel 6800k
GPU: Gigabyte 3080Ti Vision OC
VR headset model: HP Reverb G2
game version and build: 2245
release of the mod: R7
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Tried all of them
did the batch file report any errors? No
did you change the graphics settings manually? Yes, but only after trying presets
are you using any other mods? No

**Comment by 3DArtistExtreme** [comment]
I have deleted all the files in the root of the game folder exceptfor the data and did the integrity check, redownloaded it all. In all of the sudden everything works now! Issue is solved :) Anyway thank you for your assistance :)

**Comment by LukeRoss00** [comment]
Great, glad that you got it working in the end!!

**Comment by 3DArtistExtreme** [comment]
Thank you! :)
