### ISSUE TITLE
Incompatible version?

### ISSUE THREAD

**Issue by pinguluk** [LukeRoss00/gta5-real-mod#378]
_Issues_: 
So I'm using the GTA 5 Steam version, which currently is to the latest version (1.0.2372.0 / 1.57).
I've downloaded the Release 7 and placed the files and downloaded the latest ScriptHook (ScriptHookV_1.0.2245.0) and placed the files too in the GTA 5 root folder and I ran the RealConfig.bat and configured it to M.

The first issue is that the ScriptHook is not currently updated to the latest version and I need to downgrade GTA to at least 1.0.2245.0.
I've followed this tutorial https://www.youtube.com/watch?v=QZ7mE3hFcVY, downgraded the game and the ScriptHook is working again.

Now for the second issue is that the app runs, but it crashes at launch.
![Screenshot_299](https://user-images.githubusercontent.com/16257821/126511409-2eef36e3-bdb3-4444-8434-cde2d22b2de4.png)
After trial and error by deleting every .dll from the ScriptHook & R.E.A.L. mod, I think I found the culprit: d3d11.dll.
After deleting it, the game runs. BUT, again, I get an error related to the R.E.A.L. mod while loading the story mode.
![Screenshot_300](https://user-images.githubusercontent.com/16257821/126512028-0027451b-2793-45c8-9130-44b7da7eff22.png)
If I continue, the game continues fine and the other mods (NativeTrainer in my case) work. So I guess the error is related to the deletion of the d3d11.dll file. Ok, then I tried to replace the .dll with another .dll from here: https://github.com/bo3b/3Dmigoto, hoping it will fix something. But I get just another exception with a different id.

In brief, I think the mod is outdated and it needs to be fixed (?).

_More info_:
**CPU**: Intel i7-7700K
**GPU**: GeForce GTX 1060 6GB
**VR headset model**: Valve Index Headset
**game version and build:** 1.0.2372.0 / 1.57
**release of the mod**: Release 7
**did you follow all the Quick setup steps carefully, in particular step 4?**: Yes
**which settings did you choose (H/M/L) when running the batch file RealConfig.bat?**: M and L
**did the batch file report any errors?**: no
**did you change the graphics settings manually?**: no
**are you using any other mods?**: no, just the ScriptHook (ScriptHookV_1.0.2245.0) with the included NativeTrainer

_Logs_:
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/6856656/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/6856657/asiloader.log)
[RealVR.ini.txt](https://github.com/LukeRoss00/gta5-real-mod/files/6856736/RealVR.ini.txt) - _can't upload .ini, so I made it .txt_

**Comment by pinguluk** [comment]
So I tried it out again, downloaded the last GTA version and downgraded it.
What was really the issue? I didn't have my headset connected, resulting at crashing at startup.
I tried with the headset connected & configured before running the game and now it's working fine.
I'm such an idiot 🤦‍♂️

**Comment by LukeRoss00** [comment]
Thanks anyway for sharing details about the downgrade process that is needed until a new version of Script Hook V comes out, it will help other users!!
