### ISSUE TITLE
Contributing to fivem source

### ISSUE THREAD

**Issue by Hamy-os** [LukeRoss00/gta5-real-mod#379]
Hello i know you got a lot of requests to make this work for fivem but woudnt it be better to contribute straight to the source code? the main dev has tried and so have others but as they lack the care and equippment they havent done any progress. It would be amazing if you could integrate this to the fivem source as that would expose your work to over 500k people. please think about it and let me know.

**Comment by LukeRoss00** [comment]
To be honest I didn't get "a lot" of requests. The mod has been out for almost two years now, and I'd say no more than a dozen people (out of more than 100k downloads) manifested interest in making it work with FiveM.

I personally have zero interest in multiplayer, and have no plans to make my mod open source for the moment. So sorry but that's not happening.
