### ISSUE TITLE
Head position reset does not work

### ISSUE THREAD

**Issue by dborosev** [LukeRoss00/gta5-real-mod#38]
First off, great work on this mod.  But for me, its unplayable since the HUD is never in sight.  I've tried every way of shaking my head side to side to get it to reset.  I'm on a rift S.  Slow, fast, following your instructions, nothing works.
Might be ok for someone on a couch, but I stand and use roomscale turning myself around. 
Can this be fixed?  It would be perfect.

**Comment by LukeRoss00** [comment]
You can also use the normal ["Reset view in app"](https://support.oculus.com/200305533724698/) command from the Oculus menu!
