### ISSUE TITLE
The game doesn't work on DX10

### ISSUE THREAD

**Issue by tahawael** [LukeRoss00/gta5-real-mod#381]
I'm switching to DX10 because I'm having a lot of stuttering and FPS issues with DX11 but the game won't show on DX10 only the map and the menu.

CPU: Ryzen 3 3100
GPU: GTX 1050 GB
VR headset model: Quest 2
game version and build: Last version
release of the mod: 7
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Low and Medium
did the batch file report any errors? No
did you change the graphics settings manually? I've tried to change it from the game and commandline.txt file 
are you using any other mods? just ManualTransmission and it works fine with DX11

**Comment by tahawael** [comment]
![image](https://user-images.githubusercontent.com/62266433/126960680-336011e3-4002-487a-b9ba-546a74277d2a.png)
its probably the same as this one

**Comment by LukeRoss00** [comment]
@tahawael This is by design. The mod only works with DX11. Switching to DX10 would not help your frame rate in any way, even if it were possible. How many fps do you get with DX11 on Low and Medium?

**Comment by tahawael** [comment]
it's all about the juddering i'm getting when I move my head it's like ghosting but 10 times more, I'll try to record the headset and send it to you

**Comment by tahawael** [comment]
https://user-images.githubusercontent.com/62266433/127066003-e8473790-74be-4a11-88b8-e1a4c669275c.mp4

**Comment by LukeRoss00** [comment]
Thanks, the video shows the problem very clearly. However, it's not supposed to be like that. DX11 should be perfectly fluid too.

Let's see if the mod log shows anything out of the ordinary. Run `RealConfig.bat` again and select Medium, don't change anything in the settings manually after that. Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and play the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder, which you can zip (it might be quite big) and attach here.

**Comment by tahawael** [comment]
sry for not replying I just saw it, I've fixed it by installing Oculus software because I was using ALVR, Thanks for trying to help I really appreciate it ❤️

**Comment by LukeRoss00** [comment]
Awesome, enjoy!
