### ISSUE TITLE
Is there a way to disable the head shake recenter view? I hate it with a deep burning passion - 

### ISSUE THREAD

**Issue by Musashi-** [LukeRoss00/gta5-real-mod#385]
I love this mod so so so very much, but there are a few things, that I hate with an infuriating rage at times, especially because I am playing with a racing cockpit setup, wheel, petals, shifter, e brake, flight stick hotas setup, all attached to 1 racing cockpit setup for GTA V VR. Biggest grip, when driving and looking around and sliding around corners and what not, that stupid head shake features changes my camera all the time throwing my view sideways and what not. Makes me wanna smash something lol, especially in the heat of the moment being chased or doing a mission!! Its so annoying having to sit there and shake your head to get it to register, I much rather it sit there and have it not move at all, and I can just open steam vr and hit recenter view and bam done. I absolutely HATE the idea of having the camera jump around do to shaking/turning your head. Having the ability to disable this would be incredibley satisifying. Also, what happend to the heads? They are gone now in cutscenes and what not, thats not cool, also, SUPER annoying.. and also, a way to turn off the glasses in VR mode? That is another incredibley stupid annoying feature that is frustrating to deal with. Features in settings to enable/disable that stuff would be sooooooo nice. Anywyay I can contribute I would gladly accept as I too wander the language of code and modification. All that aside hope all is well!!

**Comment by Musashi-** [comment]
I did find this mod on the LCPDFR site, might be able to combine w/your mod
https://www.lcpdfr.com/downloads/gta5mods/scripts/7939-overlay-away-hide-props-in-first-person/

**Comment by LukeRoss00** [comment]
Dude, you seriously need to chill out! Also, what's with closing and reopening the issue?

Missing heads in cutscenes: never heard of that from any other users, and I just checked on my PC and the heads are where they need to be. You might have other mods/scripts that are causing the problem.

Disabling the headshake gesture: very few users have problems with it triggering unwantedly, so it's not customizable via an option. However, you can permanently disable it in your copy of the mod by using a hex editor on d3d11.dll to change the byte at offset 2D6A93 from 3F to 4F.

**Comment by Musashi-** [comment]
Wasnt tryin to sound upset at you haha was just givin my feedback, yeah I
dunno why im missing heads, didnt used to last playthrough(played thru the
whole game already in VR, just playin a new game) but yeah, theres some
annoying things that are happening. That mod didnt work to remove glasses.
Im not sure why my camera resets all the time, but im guessing its just me
looking around, I look behind me all the time, left shoulder an right,
especially when pulling e brake and sliding, it triggers the camera reset
at times, def gonna throw in that hex change, thank you! Ill try to figure
out why im missing heads, ill send some screenshots if you want. Also,
didnt mean to even close, thought I hit commit, then saw it was closed I
was like wth? It said I was the one that closed it, so was just
missclicking.

**Comment by Musashi-** [comment]
For my setup, using manual transmission, an your vr mod, bunch of various
scrips and mods like stopPowercutting!, world of variety, real ca
architecture. La roads an all those, stuff like pull me over, better police
chases, illegal street races, not really anything that crazy that should
change it to having no heads. Didnt first time I used the mod last year.

**Comment by Musashi-** [comment]
Hmmm maybe I have a file issue? I dont have an offset 2D6A93 in my d3d11.dll

**Comment by Musashi-** [comment]
tried a diff hex editor and found 2D6A90, changed the 3F to 4F, worked as
far as disabling the head shake, but then I couldn't see the menu when
pressing start lol, gonna keep messin w/it. Thanks again.

**Comment by LukeRoss00** [comment]
> but then I couldn't see the menu when pressing start

Remember that even though the headshake gesture will be disabled, you'll still be able to recenter manually using the `NUMPAD /` hotkey or the VR runtime command

**Comment by Musashi-** [comment]
Yeah I got it figured out now, workin awesome, just need to figure out now
how to fix the missing head(only missing the head of the player im
controlling(like vr mode or something) an the glasses are floating an if
move my body/head around they are all over the place floating with no head.
Very obstructive of your view. Prob another setting/mod to mess with.

**Comment by Musashi-** [comment]
Oh also, I noticed when the game tries to auto orientate, its based off
your vr play area setup(I can actually use OVR settings to rotate play
area, and got it set up right to where the cam view always is lined up in
the right direction. (So far seemingly is working out well) biggest problem
was id be driving around, slide a corner or somethin and as im ebraking
around a corner, sometimes the cam shake feature would activate, an now im
drivin forward, but my cam view is nearly sideways in the car lookin toward
passanger, an id have to shake my head a lot to fix it after turns an what
not or intense crashes gettin spun around an tossed around. But after hex
edit, soo much better.

**Comment by Musashi-** [comment]
Here's my setup for GTA V VR

https://imgur.com/a/LAB6vsb

Mods used are -
R.E.A.L VR
Manual Transmission
Railroad Engineer
Stop Powercutting!
Lifelike Traffic Speeds
World of Variety
Better Police Chases
Clean Flashlight
LA_Billboards
LA_Roads
Louder Engine Sounds
Real California Architecture
Remove Action Replay
Real Ads
L.A.Vegetation
Pull me over
Fuel Mod
Aiming At Driver
Dynamic Hair Growth
Rob Banks and ATMs
More Random Events
Enhanced Taxi Missions
Illegal Street Races

**Comment by LukeRoss00** [comment]
I know that the Manual Transmission mod has a custom first-person camera that you should disable for VR, although I can't recall if it also replaces the character model with a headless one.

I'm not familiar with all the other mods you listed, but at first glance none of them looks like it should behead your character. Are you sure you don't also have First Person Cutscenes? That would be a possible suspect

**Comment by Musashi-** [comment]
The cutscenes I can see everything fine, mainly its the little side
missions with animation and when driving, if I lean over and move my body
and look at my character, theres no head, or when walking around. However,
was interesting when I was on a bike, and aiming, showed 3rd person cam,
everything looked fine, then back to first person, same thing as b4, no
head lol. Ill check around with settings in manual transmission and see if
I can find anything.

**Comment by LukeRoss00** [comment]
Okay, that's just normal then. The first-person model in GTA V is always headless during gameplay. The game only draws your head during cutscenes and when in third person.

**Comment by Musashi-** [comment]
I do notice at times when lookin around the car, even with the head shake
feature off, it sometimes still resets itself an gets off, but I noticed,
tapping my right joystick on my controller activating controller look,
seems to reset camera to auto center. I have yet to see more headless cut
scenes, main ones I saw was with michael, however, playing as trevor now, I
noticed sometimes his shadow is headless lol.

**Comment by mikededo4** [comment]
> > but then I couldn't see the menu when pressing start
> 
> Remember that even though the headshake gesture will be disabled, you'll still be able to recenter manually using the `NUMPAD /` hotkey or the VR runtime command

for some reason the hotkey doesnt work for me. does it need to be enabled somewhere?

**Comment by LukeRoss00** [comment]
Hotkeys are enabled with the F11 key: https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys
