### ISSUE TITLE
Only see the map and the city's / streets in the right corner.

### ISSUE THREAD

**Issue by Luigivhb** [LukeRoss00/gta5-real-mod#386]
Hi there , i just installed this mod with everything in it.
And i start gta vr  , i go in the game and  i only see my map and streets name very weird.
Could you please respond with what i have to do? Thanks.
Lowie

CPU: intel I7 10 th gen (10750h) or somthing?
GPU: geforce 1650 q max super
VR headset model: Quest 2 
game version and build: 1.0.231.0 thats all i find
release of the mod: Sorry i have to anser the latest cuz i cant find it.
did you follow all the Quick setup steps carefully,  Yes
which settings did you choose (H/M/L) L
did you change the graphics settings manually Yup
are you using any other mods No
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7038207/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7038208/ScriptHookV.log)

Logs

scriphook.log:
// GTA V SCRIPT HOOK (build Jul 23 2021, v1.0.2372.0)
//     (C) Alexander Blade 2015-2021
[11:39:06] INIT: Started
[11:39:06] INIT: Success, game version is VER_1_0_2372_0_NOSTEAM
[11:39:06] INIT: Registering script 'NativeTrainer.asi' (0x00007FFFA6E6A3C0)
[11:39:06] INIT: Registering script 'RealVR.asi' (0x00007FFFA380A350)

asiloader.log:
// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\WINDOWS\system32\dinput8.dll" => 00007FFFA6BD0000
API: "DirectInput8Create" => 00007FFFA6BD2230
API: "DllCanUnloadNow" => 00007FFFA6BE5220
API: "DllGetClassObject" => 00007FFFA6BE5330
API: "DllRegisterServer" => 00007FFFA6BF4740
API: "DllUnregisterServer" => 00007FFFA6BF49C0
LOADER: Loading *.asi plugins
ASI: Loading "D:\GTAV\NativeTrainer.asi"
     "NativeTrainer.asi" => 00007FFFA6E60000
ASI: Loading "D:\GTAV\asi\RealVR.asi"
     "RealVR.asi" => 00007FFFA3800000
LOADER: Finished loading *.asi plugins

Realvr.ini:
GTA V R.E.A.L. mod Release 7

[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 0

; 0           Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left, right) - right at start
DominantEye = 2

; Y           Select heading control (always, only when aiming, never) - always at start
HeadingControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 0

; End         Activate gyro stabilization of view in vehicle - off at start
GyroVehicle = 0

;             Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 1

;             Select VR API to use (autodetect, Oculus, OpenVR, OpenXR) - autodetect by default
VRAPI = 0

**Comment by LukeRoss00** [comment]
Hi! Your issue seems similar to #382, which unfortunately was solved only by reinstalling the game.

See my comment here: https://github.com/LukeRoss00/gta5-real-mod/issues/382#issuecomment-887785110

In your case too, Script Hook V is not working as it should
