### ISSUE TITLE
Black Screen - Tried other fixes and it didn't seem to work.

### ISSUE THREAD

**Issue by AmazonChitlin** [LukeRoss00/gta5-real-mod#387]
Hi Luke,

I installed your Real mod, and am having the black screen issue.  In VR the menus and HUD will appear, but the game itself won't.  On my desktop screen, it shows it working as it should.

I've included my Scripthook log.
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7148208/ScriptHookV.log)

The only way I've strayed from your instructions, and please tell me if I'm wrong here, is to manually correct the settings file after running the .bat.  I changed my video card in the settings; when I reviewed the new settings file, it stated that my video card was a 1080 Ti, however I have a 3070 in my system.  I did try it unmodified, and it made no difference.

Thanks for all your help!!

**Comment by LukeRoss00** [comment]
My psychic powers of debugging suggest that you might have a WMR headset, and that you're using it with SteamVR. Is that correct?

**Comment by AmazonChitlin** [comment]
Your powers are correct sir!  Reverb G2.

Is it incompatible?☹

**Comment by LukeRoss00** [comment]
It works very well, you just need to read the [Release notes](https://github.com/LukeRoss00/gta5-real-mod/releases) :-)

**Comment by AmazonChitlin** [comment]
Hi Luke!

Following those directions worked, thanks!!  

It has to be frustrating for you to have to tell people like me what to do over and over.  I apologize on all of our behalf.

**Comment by LukeRoss00** [comment]
No worries, I know it's a lot of information to keep straight :-) Enjoy the game!!
