### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by NicholasComm** [LukeRoss00/gta5-real-mod#388]
Hello Luke, Upon doing the steps, I did actually get into the game in VR, however there was a black screen. I looked at other issues here and your notes and saw the same common things, the asiloader.log and the ScriptHookV.log, I looked everywhere in my files but couldn't find them. Also, I use an Oculus Quest 2 and the Epic Games version of GTA 5, I hope that is compatible with this. I would appreciate if you could walk me through this. Thank you!

**Comment by LukeRoss00** [comment]
Please see #239 before opening new issues
