### ISSUE TITLE
2018 Dodge Durango SRT 

### ISSUE THREAD

**Issue by OzzyWunna** [LukeRoss00/gta5-real-mod#389]
I just recently bought Gold Supporter Membership, And purchased a Dodge Durango and every time I turn the car tips over and I have no control over the vehicle. Since I bought Gold Supporter Membership I thought there was more upgrades for the vehicle but turns out i can only change the color, tint, and wheels.

**Comment by LukeRoss00** [comment]
It seems that you posted this to the wrong GitHub?

**Comment by OzzyWunna** [comment]
Where would I report an issue like this?

**Comment by LukeRoss00** [comment]
What I mean is, I am not the author of the mod you seem to be using. This GitHub is for the VR mod, nothing to do with cars or Gold memberships or anything like that

**Comment by OzzyWunna** [comment]
I’m confused now because the link from my discord leads me to here and I see others report issues there having on vehicles.

**Comment by OzzyWunna** [comment]
La Noire
