### ISSUE TITLE
Game wont load

### ISSUE THREAD

**Issue by awszii1** [LukeRoss00/gta5-real-mod#391]
When I start loading the story mode it crashes and I receive an error
(0x00007FF9CC2BA2E0)
CPU: I5-10400
GPU: 1660S
VR headset model: Oculus Quest 2
game version and build:1.57
release of the mod: latest
did you follow all the Quick setup steps carefully, in particular step 4?: Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat?: H
did the batch file report any errors?: no
did you change the graphics settings manually??: No
are you using any other mods?: No 
I have just downloaded the game

**Comment by LukeRoss00** [comment]
Hey, can you please attach your `RealVR.ini`, `asiloader.log` and `ScriptHookV.log` files? Just drag them on the comment; for `RealVR.ini`, you'll need to make a temporary copy as `RealVR.txt` to make the comment system accept it

**Comment by awszii1** [comment]
thank you for replying but i fixed it appreciate this good mod
