### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by abuneo** [LukeRoss00/gta5-real-mod#396]
We need an update for 1.0.2372.2_0

**Comment by LukeRoss00** [comment]
Not really, no. You just need to update your Script Hook V, see the [Release notes](https://github.com/LukeRoss00/gta5-real-mod/releases)

**Comment by abuneo** [comment]
ive actaully done that. still dosent work. i might do a fresh install of
gtav and try it again

**Comment by LukeRoss00** [comment]
Make sure that the new `ScriptHookV.dll` file is extracted to the same folder as `GTA5.exe` and not for example to a `bin` subfolder. Also, if you attach your `ScriptHookV.log` I can tell you if there's something wrong

**Comment by LukeRoss00** [comment]
Yes, unfortunately my mod and FiveM don't mix. See the old discussions: https://github.com/LukeRoss00/gta5-real-mod/issues?q=is%3Aissue+fivem
