### ISSUE TITLE
Judder when objects move or moving

### ISSUE THREAD

**Issue by specuu** [LukeRoss00/gta5-real-mod#398]
Hi, LukeRoss00,

My system:
    CPU: Ryzen 5 5600X
    GPU: GIGABYTE RTX3070 ti
    VR headset model: Quest 2
    game version and build: 1.0.2372.2
    release of the mod: 7
    did you follow all the Quick setup steps carefully, in particular step 4? Yes
    which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H
    did the batch file report any errors? No
    did you change the graphics settings manually? Yes with no improvement
    are you using any other mods? No
    graphic driver: 466.77

The main problem is I see visual juddering when things are moving in game, turning my head and driving a car, etc. Every object is not clear to see. I have tried to change VRAPI=0 to VRAPI=1 and 3 with no effect. 

Steamvr games stutter at the begining, then are smooth, on the other hand Oculus games stutter all the time.
Downgraded graphic drivers because new released ones make steamvr stutter all the time.

I don't know what else to try, your assistance will be greatly appreciated. Thank you.

[RealVRtxt.txt](https://github.com/LukeRoss00/gta5-real-mod/files/7379269/RealVRtxt.txt)
[asiloadertxt.txt](https://github.com/LukeRoss00/gta5-real-mod/files/7379279/asiloadertxt.txt)
[scripthookvtht.txt](https://github.com/LukeRoss00/gta5-real-mod/files/7379286/scripthookvtht.txt)

**Comment by LukeRoss00** [comment]
After activating the hotkeys with F11, try pressing NUMPAD2 to toggle stereo off. If the judder disappears in mono, then it's probably just the effect of alternate eye rendering (although it should not be present when you turn your head in real life, only when objects in the game move laterally). If the judder is still there in mono, then it's something else and we'll investigate further

**Comment by specuu** [comment]
Thank you! It makes the game much more playable! Juddering is almost gone, only appear for example when I drive a car and look at stationary and moving things. Can I do something with it too?
