### ISSUE TITLE
Game Doesn't Launch in VR

### ISSUE THREAD

**Issue by blcklghtngvg** [LukeRoss00/gta5-real-mod#40]
Hello!
I followed the instructions exactly: I uninstalled and reinstalled the game, installed the mod, copied the settings file with the modified GPU line and set it to read-only. However, the game still won't display in my Rift S. All I see is the square window on my desktop while I'm sitting in the Oculus app.

**Comment by LukeRoss00** [comment]
Do you have any other mods that might be interfering? Or any hooking programs like vorpX?

**Comment by blcklghtngvg** [comment]
Nope. No vorpX, and it was a completely fresh install.

**Comment by LukeRoss00** [comment]
Please see what I just posted in issue #39 to create a log file, hopefully it will contain some useful information to try and understand what's happening on your system

**Comment by blcklghtngvg** [comment]
Here's the log:
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/3921156/RVRLog.txt)

**Comment by LukeRoss00** [comment]
As you can see from the very first lines in the log file, the game cannot find the Oculus runtime DLLs, so it is unable to initialize the VR system. Perhaps try a repair of the Oculus software? Are you using some non-standard configuration that might prevent applications from loading the Oculus DLLs?
