### ISSUE TITLE
Poor pefromance on EGPU

### ISSUE THREAD

**Issue by Homeboy08** [LukeRoss00/gta5-real-mod#401]
Hi, my spec:
HP Envy i7-11065G7
16GB Ram
Egpu HP Accelerator with RX6900XT.
I play a lot of different VR games on the highest settings (Half-Life Alyx, Warthunder, MS flight simulator (running ultra in non VR mode, in VR didn't try)
EGPU always was a bottleneck, but since Thunderbolt 4 released on my processor, perfomance become much better.
https://www.youtube.com/watch?v=42o5tPE1uFA&ab_channel=TallyHoTech
Issue:
When playing GTA V non VR version on ultra, i see like my rx6900xt running full throttle. [Most of time 90+%](https://yadi.sk/i/vuSu_VvcN_WRYw) under load,  GPU frequency more than 2400MHz, card become very hot and coolers running on 100%. FPS never drops less than 60 on maximum settings.
When using VR mod, my rx6900xt most of time [30-60% under load, GPU frequency less than 1500MHz](https://yadi.sk/i/WIc0SfZbn2SLpg), card not so hot and coolers about 30% i think. FPS drops to 45-30.
I tried minimum and maximum graphic settings, no effect. 
Any ideas?

**Comment by LukeRoss00** [comment]
Hi again, thanks for the details. Let's see if the mod log gives us any hints. Run RealConfig.bat again and select Medium, don't change anything in the settings manually after that.

Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and play the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder, which you can zip (it might be quite big) and attach here.

**Comment by Homeboy08** [comment]
> Hi again, thanks for the details. Let's see if the mod log gives us any hints. Run `RealConfig.bat` again and select High, don't change anything in the settings manually after that.
> 
> Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and play the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder, which you can zip (it might be quite big) and attach here.

Link is [attached](https://yadi.sk/d/VWk8egJ06u-ozg)

**Comment by LukeRoss00** [comment]
It looks as though you are using other mods. In #239 (which you apparently didn't read or chose to ignore) I explicitly ask for some specific information, including what other mods you are running.

**Comment by Homeboy08** [comment]
> It looks as though you are using other mods. In #239 (which you apparently didn't read or chose to ignore) I explicitly ask for some specific information, including what other mods you are running.

Sorry, forget to tell you. I use Natural vision remastered, carpack 2139, extended wanted level and additional mission pack (Mission maker).

**Comment by LukeRoss00** [comment]
Check out https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking. NVR could cause problems if you installed the ReShade presets. I'm not familiar with the other mods you mentioned.

GPU usage normally stays around 99% with the VR mod and High settings. Check that when you remove all the other mods, the flood of "Restoring slot #5" / "Preserving slot #5" lines disappears from the log. Also check that you don't have V-Sync forced on in the driver or anything like that.

**Comment by Homeboy08** [comment]
> Check out https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking. NVR could cause problems if you installed the ReShade presets. I'm not familiar with the other mods you mentioned.
> 
> GPU usage normally stays around 99% with the VR mod and High settings. Check that when you remove all the other mods, the flood of `Restoring slot #5` / `Preserving slot #5` lines disappears from the log. Also check that you don't have V-Sync forced on in the driver or anything like that.

Hi, looks like Natural vision remastered mod drops game performance.
Now GPU perfom at 70-87% average, also CPU MHz become much bigger.
Thank you for  help, not recommend to install other mods with VR
