### ISSUE TITLE
Game not displaying in headset

### ISSUE THREAD

**Issue by GrandNoodleLite** [LukeRoss00/gta5-real-mod#402]
I've been working on this for hours trying to find a solution to this, but basically I can't get the game to appear in my headset. It just sits in a borderless window on my desktop, but the keybinds mentioned in the mod work. The borderless window also appears to be a vertical rectangle, like a smartphone video, but the in game resolution is correctly set to 1080x1080. I must have launched GTA V at least 10 times now just sitting in Oculus Home waiting for the game to load, only to find it doesn't work and try something else. I have reinstalled the game, updated scripthook, launching it through steamvr instead of oculus home, and tried changing my graphics card name in my settings.xml file. That's not to mention all the comments I've seen on YouTube and other issues here on Github with no solutions. Any help you could give would be greatly appreciated. Literally installed Oculus Home and set up my rift again today after a year of not using it, but this is a real bummer.

CPU: i9-10900k
GPU: Nvidia RTX 3070
VR headset model: Oculus Rift CV1
game version and build: 1.0.2372.2
release of the mod: r7
did you follow all the Quick setup steps carefully, in particular step 4? YES, many times.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? M
did the batch file report any errors? I didn't notice any.
did you change the graphics settings manually? No
are you using any other mods? Nope

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7445267/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7445271/ScriptHookV.log)
[RealVR.txt](https://github.com/LukeRoss00/gta5-real-mod/files/7445272/RealVR.txt)

**Comment by LukeRoss00** [comment]
Hi, thanks for filling in the required information. Your problem is at the last line of `ScriptHookV.log` where it says:

```
[17:11:20] CORE: Launching main() for 'RealVR.asi' (0x00007FFFF4C2A350), id 33
[17:11:48] UNINIT: Unregistering script 'RealVR.asi'
```

just 20 seconds after the script was launched, Script Hook V is killing it (and thus the mod). I'm not sure why that should happen, I've never seen it from any other users. Don't you get any error message? Sometimes the dialog box with the error is hidden behind the game window and you have to Alt-Tab to it.

**Comment by GrandNoodleLite** [comment]
Never saw anything.

**Comment by LukeRoss00** [comment]
Let's see if the mod log gives us any hints. Run `RealConfig.bat` again and select High, don't change anything in the settings manually after that.

Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and play the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder, which you can zip (it might be quite big) and attach here.

**Comment by LukeRoss00** [comment]
Closing with no reply in over a week, feel free to reopen if still interested
