### ISSUE TITLE
GTA V vr mod (black screen issue) oculus rift s

### ISSUE THREAD

**Issue by Aploiter** [LukeRoss00/gta5-real-mod#404]
Hey...

I have such a problem ... I tried to install vr mod in GTA V, but after a long solution of problems with the outdated version, I finally managed to run, but when I run gta and connect to singleplayer I see darkness ... you can see the mini map and when I press ESC I see the settings, but the picture doesn't ... don't you know how to solve it?

Aploiter

**Comment by LukeRoss00** [comment]
See #387 , if it doesn't work see #239

**Comment by Aploiter** [comment]
THANK YOU SO MUCH its working now (: you really helped me
