### ISSUE TITLE
Mod not working inside VR

### ISSUE THREAD

**Issue by FireMasterGamer** [LukeRoss00/gta5-real-mod#405]
Hello!

I saw someone else have the same problem as me described like this: Upon starting Story Mode, an error pops up saying that Script Hook V had an error with the RealVR.asi File. And I sat there, waiting for something to happen, but once the game started, It was in Windowed Borderless mode, and not in a VR state. So I've been trying to fix it myself, and nothing happened.
Also here's some required info:

CPU: AMD RYZEN 5 2600X
GPU: GeForce GTX 1080
VR headset model: Oculus Quest 2
game version and build: Build ID: 7172076
release of the mod: June 15th 2021
did you follow all the Quick setup steps carefully, in particular step 4? Yes!
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? High
did the batch file report any errors? Unsure.
did you change the graphics settings manually? I think I might have...
are you using any other mods? Yes.

**Comment by LukeRoss00** [comment]
Hi and thanks for the details! I'm not sure what you mean by "release of the mod: June 15th 2021". My [latest](https://github.com/LukeRoss00/gta5-real-mod/releases) release is 7 from 19 Dec 2020, and the [latest](http://www.dev-c.com/gtav/scripthookv/) Script Hook V is from 23 Jul 2021. The error you describe usually comes from using an old version, so please double check that you have the right ones. If you can't sort it out, please attach a zip with your `RealVR.ini`, `asiloader.log` and `ScriptHookV.log` files

**Comment by FireMasterGamer** [comment]
Yes, I do actually mean December 19th, I'm not using an older version of the mod, is it possibly because of the new Script Hook? Here are my logs..
[Logs.zip](https://github.com/LukeRoss00/gta5-real-mod/files/7492364/Logs.zip)

**Comment by LukeRoss00** [comment]
Hehe, you do have lots of other mods! One or more of them is probably conflicting. I'm not familiar with some of them, so I'm not sure which. I'd start moving all other .asi files (and enbhelper.dll) somewhere out of the game folder, so Script Hook V cannot see them; if the error goes away, you can put the other mods back into place one by one to see who the culprit is.
