### ISSUE TITLE
implement it to fiveM

### ISSUE THREAD

**Issue by abuneo** [LukeRoss00/gta5-real-mod#406]
We have a server that is allowing scripthook. I have tried to implement the mod inside of the "C:\Users\PC\AppData\Local\FiveM\FiveM.app\plugins" folder but nothing. Where do i have to put it in to make sure it runs on my client?

**Comment by LukeRoss00** [comment]
I'm not sure that allowing Script Hook V will be enough. Anyway, all the mod files and the `ShaderFixes` subfolder must be in the same folder as the game executable, except for `RealVR.asi` that must be wherever Script Hook V can find it

**Comment by abuneo** [comment]
I will try that and update you.

**Comment by LukeRoss00** [comment]
Did it work?

**Comment by abuneo** [comment]
I was pretty busy these past days. I will be working on it on the next
days.

If you could find any time we could try it out together. You could add me
on discord or any other social media.

Discord: AbuNeo#8959

**Comment by LukeRoss00** [comment]
I'm sorry, I'm quite starved for time and also not personally interested in using FiveM. I was asking just to know what to do with the thread. Take all the time you need, I'll leave the issue open for now

**Comment by VixusFoxy** [comment]
That's extremely unfortunate; I too would love to see an implementation for FiveM and am even willing to donate to the cause for this to become a reality.

On behalf of all the VR simmers out there who have a platform that is incredibly immersive -AND- comes with multiplayer capability, we would all love you forever. From the roleplayers, to the drift racers with their racing wheels, to the truckers in Transport tycoon, to the virtual cops, we'd be blessed to see this come to fruition one day.

Name your price.

**Comment by abuneo** [comment]
Alright i have tried it on a server where scripthook v was activated. The game just starts without any errors on the pc but nothing happes on the headsets. 

Ive also tried it on Rage Multiplayer. There on the other hand the game starts like it supposed to on the headset. The only issue is that its not streching the view and also only showing a black screen. Theese are the information i could gater.
