### ISSUE TITLE
sorry to ask

### ISSUE THREAD

**Issue by 100Cookie** [LukeRoss00/gta5-real-mod#407]
So apparently i scanned it on virus total and it said there is a Trojan.Malware.300983.susgen i dont know if its a false detection. just to make sure is this safe? i really want to play it it looks fun.

**Comment by LukeRoss00** [comment]
I can guarantee there are no viruses or malware of any kind (BTW the release has been unchanged for almost a year). Who ever heard of this "MaxSecure" antivirus anyway :-D

**Comment by 100Cookie** [comment]
Okay thank you so much i will try it now, Have a good day/night.
