### ISSUE TITLE
Sniper bug

### ISSUE THREAD

**Issue by ZombiesFromPluto** [LukeRoss00/gta5-real-mod#408]
Hi. I am having trouble controlling the sniper in missions. The zoom amplifies the shake of the headset and makes it very hard to aim a sniper. (I spent a good three quarters of an hour to pass the nervous ron mission). I was wondering if you could disable head tracking whenever a sniper is aimed and make the player use the mouse or thumbstick.
I love this mod so much. Thank you for making it and I would appreciate a fix for this.
Thanks.

CPU:                                                                                                                                                i5 2500k
GPU:                                                                                                                                               GTX 1650
VR headset model:                                                                                                                         oculus quest 2
game version and build:                                                                                                                latest from epic games
release of the mod:                                                                                                                       7
did you follow all the Quick setup steps carefully, in particular step 4?                                        yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat?                 L
did the batch file report any errors?                                                                                              no
did you change the graphics settings manually?                                                                           I turned fxaa on
are you using any other mods?                                                                                                     no

**Comment by LukeRoss00** [comment]
Hi, excellent username! See #312 for a full discussion

**Comment by ZombiesFromPluto** [comment]
Alright thanks. My problem isn't that I can't pass the missions, it's just that using the sniper isn't enjoyable. Is it possible for you to just add a setting to disable head tracking when zoomed in? I don't know how hard that would be but I think that it would greatly improve the experience.

**Comment by LukeRoss00** [comment]
Have you tried the existing [hotkeys](https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys) already? In particular `Y`, `U` and `O`

**Comment by ZombiesFromPluto** [comment]
Yea that does fix it thanks. It's just kind of annoying to press the keys anytime I want to use the sniper. Do you think that you could make it automatically do it when a scope is aimed in the next mod release?

**Comment by LukeRoss00** [comment]
Unless Rockstar breaks the mod with one of their updates, the next release will be on my new framework. I'll certain consider adding the option, but it won't be soon, as my Patrons have voted for other things to do first ;-)
