### ISSUE TITLE
Incorporate openvr_fsr into your existing openvr.dll

### ISSUE THREAD

**Issue by Camrule** [LukeRoss00/gta5-real-mod#409]
Hey Luke! Love your work!

I recently got openvr_fsr to work by copying the openvr.dll into GTA V. However, I think it may have overwritten your setup and I can no longer re-center my camera. Could you please merge this into your openvr.dll file?

https://github.com/fholger/openvr_fsr

Sorry, I have no idea if this is possible. I just noticed how well it works and thought you might be fascinated by it too!

Cheers,
Cam

**Comment by Camrule** [comment]
I also think it may be messing up because of the alternate eye rendering setup.

I did set radius = 2 in the openvr_fsr file but that did not fix it

**Comment by SatarVR** [comment]
I did the same. That may explain why the head shaking does not work. :)

@Camrule I have no problem with the rendering. I use these settings:
    "renderScale": 0.77,
    "sharpness": 0.9,
    "radius": 0.4,
    "applyMIPBias": true,
    "debugMode": false

**Comment by LukeRoss00** [comment]
The `openvr_api.dll` file that is distributed with my mod is the original one from Valve, untouched, so there is no merging that I can do. Maybe there's another reason for the headshake not working. Which headset are you using?

**Comment by SatarVR** [comment]
I'm using a Pimax 5K+ and I've been trying different levels of shaking, but no dice.

**Comment by LukeRoss00** [comment]
Yes, unfortunately Pimax headsets do not report their angular velocity to SteamVR, so the headshake gesture won't work with them :-( You can still use the hotkey though

**Comment by Camrule** [comment]
> The `openvr_api.dll` file that is distributed with my mod is the original one from Valve, untouched, so there is no merging that I can do. Maybe there's another reason for the headshake not working. Which headset are you using?

Hey Luke,

Yea I seem to be getting more double imagery after applying this fsr implementation. 

I'm using a hp reverb g2 and have the platform set to Open XR and using steam vr. 

Without the fsr openvr.dll I was using mixed reality opener as runtime, but this new openvr.dll doesn't let the game open that way, so I've switched to steam vr. 

Any idea why the image would be shimmering more now? 

Its like the double car image with rendering but it occurs everywhere now.

**Comment by Camrule** [comment]
> I did the same. That may explain why the head shaking does not work. :)
> 
> @Camrule I have no problem with the rendering. I use these settings: "renderScale": 0.77, "sharpness": 0.9, "radius": 0.4, "applyMIPBias": true, "debugMode": false

Hey thanks for sharing. So you don't get that double image lag with the cars but instead its everywhere?

**Comment by Camrule** [comment]
> I did the same. That may explain why the head shaking does not work. :)
> 
> @Camrule I have no problem with the rendering. I use these settings: "renderScale": 0.77, "sharpness": 0.9, "radius": 0.4, "applyMIPBias": true, "debugMode": false

Are you using open xr through steam? I can't seem to get it to run via mixed reality open xr runtime with my hp reverb g2

**Comment by LukeRoss00** [comment]
That's a different problem. The WMR driver for SteamVR is buggy and doesn't support alternate eye rendering correctly, hence the tracking jitters if you switch to SteamVR instead of using the WMR OpenXR runtime. They fixed it in a beta many months ago, but the beta introduced a new bug where the world appears completely black (only the HUD is drawn in the headset), and they never acknowledged or fixed this new issue, which is due to the fact that the driver enters an invalid state if the texture sizes for the two eyes are not identical.

**Comment by Camrule** [comment]
> Oh wow I had no idea about this. Do you have any idea why the openvr.dll wouldn't be opening gtav in WMR openXR runtime by any chance then? I'll try get it to work again, but it seemed as soon as I pasted this new dll in it just wouldn't load that way anymore.

**Comment by LukeRoss00** [comment]
As far as I know, openvr_fsr doesn't support OpenXR (https://github.com/fholger/openvr_fsr/issues/99)

**Comment by Camrule** [comment]
> As far as I know, openvr_fsr doesn't support OpenXR ([fholger/openvr_fsr#99](https://github.com/fholger/openvr_fsr/issues/99))

Could I use OpenVR runtime with my hp reverb g2?

**Comment by Camrule** [comment]
> As far as I know, openvr_fsr doesn't support OpenXR ([fholger/openvr_fsr#99](https://github.com/fholger/openvr_fsr/issues/99))

Oh I also am trying to get reshade to work in VR. I noticed it overwrites your d3d11.dll file. Anyway I could get around this issue? 

I ended up trying open_fsr with my quest 2 and it works flawlessly. Very helpful for quest users.

**Comment by LukeRoss00** [comment]
ReShade won't work with my GTA V mod (explanation [here](https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking))

**Comment by Camrule** [comment]
> ReShade won't work with my GTA V mod (explanation [here](https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking))

Thanks Luke!

A guy over in the Flatscreen to VR Mod discord shared a reshade that he says is working. 

Thought you might find this interesting or want to comment on this here:

https://github.com/fholger/reshade/releases/tag/openvr_alpha2
