### ISSUE TITLE
Game Running in a Rectangular Window

### ISSUE THREAD

**Issue by balong** [LukeRoss00/gta5-real-mod#41]
Hi, after installing the game according to the directions (including adding my video card to the Settings file and setting it to read only) my game is running on my desktop in a rectangular window and having frequent stuttering when I play. My laptop has a RTX 2070, an 8th Gen i7 and 32 GB of dual channel ram, but only running a high of 60ish FPS that frequently dips into the 40s. I've also tried running on the low Settings file, but it also seems to run in the same rectangular format (just a smaller one) and also has issues with stuttering.

Let me know if there's any more info you need!

**Comment by LukeRoss00** [comment]
Some frame drops are probably to be expected with a laptop. If you want to follow the instructions that I gave [here](https://github.com/LukeRoss00/gta5-real-mod/issues/39#issuecomment-561308882) and post a zipped log file, I can take a look and see whether something seems wrong

**Comment by jeq1** [comment]
Is there anyway to launch game on fullscreen while playing or does it allways affect resolution?

**Comment by LukeRoss00** [comment]
Please don't hijack closed (and mostly unrelated) issues! Anyway, fullscreen would kill your performance, but you can work around your problem by temporarily moving the taskbar to the left of the screen when you play (https://www.onmsft.com/how-to/how-to-change-taskbar-position-windows-10)
