### ISSUE TITLE
GTA IV mod support

### ISSUE THREAD

**Issue by Camrule** [LukeRoss00/gta5-real-mod#410]
Hey Luke,

Could GTAIV utilize this same mod?

Vorpx really cannot do a good job...

**Comment by LukeRoss00** [comment]
No, sorry. My mods are tailor-made to specific games. Even when the engine is the same (like with my mods for Mafia:DE and Mafia III:DE) there are many subtle changes from one game to the next that need to be individually addressed and fixed.

But don't worry, perhaps in ten years we'll have an official version of GTA IV VR running exclusively on the Quest 7 []-D

**Comment by Camrule** [comment]
Hahaha thanks Luke appreciate the reply.

I guess I'll just pray to the gods that you update the GTA V Mod in the near future ;)
