### ISSUE TITLE
Running at like 5fps on any settings, but without the vr mod it runs at 90+fps

### ISSUE THREAD

**Issue by SpreeV** [LukeRoss00/gta5-real-mod#411]
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7611629/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7611630/ScriptHookV.log)

CPU: i5 4570
GPU: GTX 1070
VR headset model: Oculus Quest 2
release of the mod: 7

**Comment by LukeRoss00** [comment]
Something must have gone wrong with installation, because you have two copies of the `RealVR.asi` file. Did you move the files around manually? You're supposed to just unzip the mod archive into the executable folder and then run `RealConfig.bat`. Delete `D:\SteamLibrary\steamapps\common\Grand Theft Auto V\RealVR.asi` and leave only `D:\SteamLibrary\steamapps\common\Grand Theft Auto V\asi\RealVR.asi`

**Comment by SpreeV** [comment]
> Something must have gone wrong with installation, because you have two copies of the `RealVR.asi` file. Did you move the files around manually? You're supposed to just unzip the mod archive into the executable folder and then run `RealConfig.bat`. Delete `D:\SteamLibrary\steamapps\common\Grand Theft Auto V\RealVR.asi` and leave only `D:\SteamLibrary\steamapps\common\Grand Theft Auto V\asi\RealVR.asi`

Thanks, that helped, but now I am facing a new issue, when I load into singleplayer I can only see my hud and I can only access the options. I will try to search around the closed issues to find how to fix it so I don't bother you, thanks for your help again. If I can't find anything I'll post here again.

**Comment by SpreeV** [comment]
Hello, sorry for bothering again, but after following the instructions at the release notes, my game crashes after the loading screen. Thanks in advance

**Comment by SpreeV** [comment]
Ok I fixed the crashing and everything, the performance is good, maybe like 10fps less than what I usually play on. Just one question. Is there a way to fix the stutters when I turn on msaa?

**Comment by LukeRoss00** [comment]
Hey, glad it works correctly now! The 1070 is probably not powerful enough to run the game at VR resolutions with MSAA. Check your frame rate with the `N` hotkey, you need at least a stable 60-70 fps to enjoy the mod properly

**Comment by SpreeV** [comment]
> Hey, glad it works correctly now! The 1070 is probably not powerful enough to run the game at VR resolutions with MSAA. Check your frame rate with the `N` hotkey, you need at least a stable 60-70 fps to enjoy the mod properly

Hey, the mod is truly amazing and immersive. When I turn on MSAA it doesn't start lagging or stuttering but I just don't know how to explain it. Basically when I turn my head with MSAA I see black parts of the screen. I cant really explain it better, sorry.

**Comment by LukeRoss00** [comment]
The black bars at the sides are visible when the game frame rate is too low
