### ISSUE TITLE
One eye black screen / sync issues

### ISSUE THREAD

**Issue by rqjimmy** [LukeRoss00/gta5-real-mod#414]
A little bit of backstory because my issue is sort of hard to explain and I was loving playing with this mod and would really like to get it working again. I was running it flawlessly (albeit with stereo rendering off as it was noticeable and hurt my eyes) on my previous hardware configuration but frames were somewhat low so I switched CPU/motherboard and added a second GPU in SLI as GTA V is one of the few games that plays well with SLI. I switched from Intel to AMD and thus had to do a clean install of Windows 10 in the process. I installed Steam, Oculus Link,  GTA V, then installed the R.E.A.L mod and ScriptHookV the exact same as I had done when I originally installed it on my old hardware. Made sure the desktop game theatre option was turned off, changed the necessary GTA settings before installing the mod, ran the batch file; everything exactly how I did it on my old build and how the readme tells you.

When I start the game up it seems to be working just fine during the menus and load screen but the problems start once I actually load into the game world. For some reason the game world is only displayed for my left eye, the UI (mini-map, in game phone, pause menu) etc. is displayed for both the left and right eye but if I close my left eye (the one the game world is being displayed on) it's nothing but UI with black screen behind it. If I hit F11 and then NUMPAD2 to toggle stereo rendering off the right eye starts displaying the game world and continues to even after I turn stereo rendering back on. However at that point it only looks okay if I'm completely stationary, if I move the character at all or move my head at all to look around the images for each eye are horribly desynced almost like the "blurring" you can notice with stereo rendering on but 1000x worse.

I've tried reinstalling chipset and graphics drivers, GTA V, steam, the mod, ScriptHookV, rerunning the config batch file, the Oculus software, just about everything I can think of but to no avail. Any help would be greatly appreciated, this mod is the only thing that got me back into GTA V after years and it's quickly became my favorite game again.

CPU: AMD Threadripper 1920X
GPU: MSi GTX 1070 Seahawk (x2 in SLI)
VR headset model: Oculus Quest
game version and build: whatever the most up to date version as of December 2nd 2021 is
release of the mod: 7
did you follow all the Quick setup steps carefully, in particular step 4?: Yes, multiple times.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat?: All of them multiple times.
did the batch file report any errors?: Not that I can tell.
did you change the graphics settings manually?: No.
are you using any other mods?: PackFileLimitAdjuster, HeapAdjuster, NativeUI, iFruitAddon2, OpenIV, ScriptHookVDotNet, NativeTrainer; but the problem happens even with nothing but R.E.A.L and ScriptHookV installed and on my old build R.E.A.L was working flawlessly with all the listed mods and many more

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7653526/asiloader.log)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7653528/ScriptHookV.log)

github won't let me upload RealVR.ini but it's all default values.

**Comment by LukeRoss00** [comment]
I'm so sorry, @rqjimmy, I wish you had asked me before doing the upgrade. While it's true that GTA V makes good use of SLI when playing flat, the SLI configuration won't work at all in VR. Hence your problems with the new system.

The issues come from two main reasons: 1. only one card is actually connected to the headset, so a system needs to be implemented in software to send the images rendered by the other card to the first one, and that has to be done for each frame with flawless timing without interfering with the VR compositor; and 2. GTA V and RDR2 completely change their rendering pipelines when using SLI, so large portions of the mod would have to be revised/rewritten.

With SLI basically dead (https://www.youtube.com/watch?v=i1dGQiNfCAc) the time and effort required to fix those two problems is sadly not justifiable for me.

Your best bets if you want to continue playing are either to disable SLI (of course that would get you back to the old frame rates, apart from the improvement brought about by the new CPU) or to sell the two cards in exchange for a single RTX :-|

**Comment by rqjimmy** [comment]
Ouch. Well I'm glad I just tried it out a card I had laying around in a different rig first and didn't pull the trigger on quad Titan XP SLI like I was thinking about. I'm getting okay frames with a single GTX 1070 (60-80), the main reason for adding the other card was to run it with the VisualV or NaturalVision mods (minus the ENB/ReShade of course) and still get good frames in VR. I guess I'll have to get a single higher end 20 or 30 series card for VR and retire the SLI to non-VR gaming and Nvidia Surround. Thanks for the incredibly prompt response, I was not expecting that and since disabling SLI it's working perfectly although I've definitely got to remove some of these graphics mods now lol.
