### ISSUE TITLE
I apear to be stuck on 60 fps 

### ISSUE THREAD

**Issue by DrDoomsLab** [LukeRoss00/gta5-real-mod#415]
Hi there, 

Thanks for a wonderful mod. I have been enjoying it massivly. So much so that I've only just noticed recently that i appear to be stuck at 60fps and can't get anything above that frame rate. I only realised that your mod had an ingame FPS indicator so i switched it on and im stuck at 60fps. I have looked though the issues and found one other person who had a simular issue but i am not running though steamVR with openXR. i'm using the direct openXR. If i use the openXR demo scean in the driver/developer thing i can see it running at 90hz.

CPU: i7 3770k @ 4.5ghz
GPU: 1070ti @ 2ghz
VR headset model: Dell Visor WMR
game version and build: 1.0.2545.0 (the latest)
release of the mod: R7
did you follow all the Quick setup steps carefully, in particular step 4? Yes indeed
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? M
did the batch file report any errors? nope
did you change the graphics settings manually? not origanally but i have done so since. although i have also reverted since editing.
are you using any other mods? Yes but i also can run without and it does the same thing.

I have tryed it in steamVR with openXR but like others i have the black screen bug with only the hud being rendered on the HMD. But while running in this mode i did try and edit the steam settings to make shore that screen scaling and motion handeling was off on the game profile and also universal. I have also tryed switch off the preview openXR drivers which changed some things but nothing changed with the frame rate. The settings for the WMD are set to 90hz and max everything. I did have some issues in game before hand but i removed all my mods and then have added a few back. Everything in games working fantastic other than im stuck at 60fps. Could it be just my pc is too slow? i would think i would be able to see at least 61fps. Any idears?

**Comment by LukeRoss00** [comment]
By any chance do you have V-Sync forced on (globally or for the game) in the driver?

**Comment by DrDoomsLab** [comment]
I checked the game and switch v-sync on and off but that changed nothing. i have just checked my nvidia settings and they are set to use the 3d app settings and thats also teh same for the GTA5 profile.

**Comment by DrDoomsLab** [comment]
oh but that makes me think...  i am using msi afterburner for my gfx card OC and that has revertuner. I'll close the program and test. That could be limiting it as i've only just started to use the oc a few weeks back

**Comment by DrDoomsLab** [comment]
Yes, sorry,  It was user error once again. It was MSI afterburner / revertuner that was locking the frame rate. Thank you for getting back to me and Sorry for wasting your time.  Cheers.

**Comment by LukeRoss00** [comment]
Haha no problem, I was just about to tell you to look into RivaTuner :-D
