### ISSUE TITLE
Can't find RealConfig tab to select high, medium or low settings for Gta 5 vr 

### ISSUE THREAD

**Issue by Alexofpeace** [LukeRoss00/gta5-real-mod#416]
i've searched my whole computer for the Realconfig.bat and nothing comes up when searching the whole PC

**Comment by LukeRoss00** [comment]
It's right there in the .zip file! Perhaps you have an overzealous antivirus software which is killing it as you extract the zip?

**Comment by Alexofpeace** [comment]
wow thank you for responding so quick :) ill try to look into that!

**Comment by Alexofpeace** [comment]
and by zip file do you mean the script hook?

**Comment by Alexofpeace** [comment]
soo for your mod file do i have to do anything special with it since its an RAR file? after downloading the LUKE ROSS MOD i just placed it into the Gta 5 folder but i can't extract it or anything if thats where the realconfig is placed in?

**Comment by LukeRoss00** [comment]
Sure you have to extract it! Please refer to the [Quick Setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) instructions
