### ISSUE TITLE
Wrong Read Me

### ISSUE THREAD

**Issue by pogrammerX** [LukeRoss00/gta5-real-mod#417]
The read me is wrong Virtual Desktop does work

**Comment by LukeRoss00** [comment]
As far as I know, Virtual Desktop hasn't been working correctly with alternate eye rendering for a long time. Do you have a link to a source confirming that it now does?

**Comment by pogrammerX** [comment]
I tested it and it works for me

**Comment by LukeRoss00** [comment]
That's great. However, all others (including the Virtual Desktop author on his Discord) say that it doesn't. So I'm not going to change the README unless you can provide an authoritative source.
