### ISSUE TITLE
Crashes immediately when story mode loads

### ISSUE THREAD

**Issue by CanYouMakeTheModWorkForMe** [LukeRoss00/gta5-real-mod#419]
Hi I used your mod in the past, I know which in-game settings to change and how to set the whole thing up, but it's not working after GTAV's Dec 2021 update as it crashes like the title says. 

I know I am using right scriphook, latest even. I use a mod called Menyoo which needs the Alexander one and the only one I know. 

I uninstalled Menyoo and tried again and still crashes. I think it's the update. 

If I can get help, that would be great. 

Great work on the mod!

**Comment by LukeRoss00** [comment]
See #239 before opening new issues. Are you using Release 7? If you are, please attach a zip with your `RealVR.ini`, `asiloader.log` and `ScriptHookV.log` files

**Comment by CanYouMakeTheModWorkForMe** [comment]
Where would the log files be? In the GTA5 dir?

**Comment by CanYouMakeTheModWorkForMe** [comment]
Also I did see that issue thread. I did use release 7. Release seven says
it's an update for GTA v December 2020 update, so I created this issue.

Don't worry, I did read the issue saying see here before creating an issue,
I followed the rules.

Thank you.

**Comment by CanYouMakeTheModWorkForMe** [comment]
???

**Comment by LukeRoss00** [comment]
What's with the question marks? You said you read #239, and yet you didn't provide the requested information, which I'm still waiting for. I'm also waiting for the logs, which as you guessed are found in the `GTA5.exe` folder

**Comment by CanYouMakeTheModWorkForMe** [comment]
What do you mean what's with the question marks? I asked you a question, I
didn't get an answer, so I'm just checking in. You must be American cuz you
clearly have no common sense.

And yes, I did read and check those issues. I didn't usually seven, but
really seven says it's for December 2020, not December 2021. Do you not
know how to read? Especially your own words?


Ridiculous.

**Comment by CanYouMakeTheModWorkForMe** [comment]
I did use release 7** not usually seven

I would have liked to get some resolution from you but you are so selfish.

**Comment by LukeRoss00** [comment]
I'm closing this issue as not constructive. This is a free mod. If you want support from me or other users, you need to provide the information that we require in order to help you.

**Comment by CanYouMakeTheModWorkForMe** [comment]
Says the one who can't read his own fucking words
