### ISSUE TITLE
Wont launch in VR on Oculus quest 2

### ISSUE THREAD

**Issue by Fallos77** [LukeRoss00/gta5-real-mod#422]
CPU: i9 11900k
GPU: 3080ti
VR headset model: Oculus quest 2
game version and build: 1.0.2545.0
release of the mod: release 7
did you follow all the Quick setup steps carefully, in particular step 4? Yes
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? H and M
did the batch file report any errors? Nope
did you change the graphics settings manually? Nope
are you using any other mods? Nope

[RealVR.txt](https://github.com/LukeRoss00/gta5-real-mod/files/7865178/RealVR.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7865180/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7865181/asiloader.log)

Alright, so my issue is that after following the steps in the guide, i can start the game, but it launches windowed on "the screen in the headset" and when i look on the gamescreen in the headset the picture is bouncing all over the place and stops when i look outside the active gamewindow. It is like its working, but it wont load into VR, i hope you understand what i mean. 

*edit* Might add that im totaly new to VR since today, so it might be the simplest of fixes, something simple that im not aware of in settings or something. */edit*

Have a great day! =)

ps. 
I obviously made the realvr.ini a *.txt for this message.

**Comment by LukeRoss00** [comment]
Well, first of all cheers for a great first post <3

Second of all, as much as I like my mods, please BE CAREFUL if you're new to VR. My mods are super-intense experiences meant for people who have already built their "VR legs". Unless you have an iron stomach, you will probably get motion sickness (also called simulator sickness) if you begin your VR adventures with GTA V :-D

Thirdly, by the symptoms you described, it seems that you are launching the game from the Virtual Desktop in the Oculus App? Try leaving the Oculus App in its default state and launching the game from the ordinary Windows desktop. Also, are you using the Link cable, or Air Link, or...?

**Comment by Fallos77** [comment]
Wow, thanks for a fast reply! 

Im well aware of the mationsickness, and i am getting used to it slowly :P

I am using Air Link, and what i do is; connect the headset - activating the monitor from the headset hud - starting the game.

I am not using the app "virtual desktop" just the built in one.

**Comment by LukeRoss00** [comment]
Yes, the built-in Virtual Desktop is what I was talking about. Try not using it but starting the game from the ordinary Windows desktop instead (i.e., before donning the headset)

**Comment by LukeRoss00** [comment]
Mmm, where did the "no headset found" error message come from? Can you attach a screenshot?

**Comment by Fallos77** [comment]
Its from SteamVR.

I was looking at video guide, and he was just installing the mod and the hook, then went into the built-in virtual desktop, chose monitor 1 and started the game from there..

EDIT; for some reason it does work now, no idea what i did different

**Comment by Fallos77** [comment]
Holy shit this is awsome! :O

**Comment by LukeRoss00** [comment]
Haha, thank you! Glad you got it working in the end :-)
