### ISSUE TITLE
DLDSR greatly enhances Image Quality

### ISSUE THREAD

**Issue by tala11** [LukeRoss00/gta5-real-mod#425]
I've managed to get NVIDIA's DLDSR working with a 1:1 aspect ratio in GTAV. The image quality is greatly improved, I was really astounded.

Hope this information helps Power Users (be aware that CRU utility messes with EDID settings, you must know what you are doing and have a second monitor (or any alternate display) at hand if you cannot restart to Windows)

Step-by-step:
1. Create a 1300x1300@90hz resolution and set it as NATIVE (using CRU tool)
2. Eliminate all resolutions greater than 1280x720 (using CRU tool). This tricked NVIDIA's driver to use 1300x1300 as the base resolution for DLDSR
3. Activate DLDSR resolution of 1733x1733 in NVIDIA control panel
4. Change R.E.A.L. "High" settings files and set the new resolution 1733x1733 (commandline.txt and settings.xml)
5. Run Realconfig.bat
DONE!

For further tips and reference, I game on a AMD-5800X & RTX3080 & OculusQuest2 and In-game I use:
 - Frame Scaling 3/2 (I can't go any higher with this resolution without impacting framerate)
 - MSAAx2, TXAA (and MFAA in the drivers) and Motion Blur Max

**Comment by Mavrik89** [comment]
Would appreciate it if u could elaborate a bit more as I've never used CRU tool before. How do u set a resolution as the native in CRU? I launched restart64.exe but I'm using my HDTV monitor as the PC screen and it says the resolution is not supported, does that mean I can't continue with ur method? and how do you "Activate DLDSR resolution of 1733x1733 in NVIDIA control panel"? Do you mean set it as the current screen resolution?

**Comment by Mavrik89** [comment]
> Took me awhile to get this working properly but OMG the difference is amazing and frame rate is still stable. It looks incredibly clear and runs smoothly. I'm using a Pimax 8KX and using 1080x1080 with SamplingMode value="7" in the settings at 2.25x (1620x1620) I'll elaborate on how I got this working in a bit (using OPs resolutions).
> 
> Update: I was using driver 511.23 but it had a bug with 1.78x DLDSR (blank screen cursor only) so had to run in 2.25x mode. So I had set a resolution of 1080x1080 and it rendered up to 1620 with 2.25x. 511.65 work with 1.78x now though. Running on 5900x EVGA 3080 full custom loop.
> 
> 1. With CRU I had to play around as the resolutions wouldn't stick always.  (safer to have a 2nd screen in case you screw up)
> 2. If this happens, just run reset-all.exe which will return all the factory screen options to default and start over.
> 3. Delete all the standard resolutions, detailed resolutions, and click through everything in the extension block and delete all of them under hdmi, hdmi 2.0, tv resolutions.
>    ![0](https://user-images.githubusercontent.com/40308295/153537491-25edf8ca-03c9-42ce-b4fd-9eb4e1aaec33.jpg)
> 4. Add a single square resolution you want to set the base rendering from that will be scaled by 1.78x or 2.2.5x to the detailed screen and choose 'native (PC)" in the dropdown. shown here as 1300x1300 90hz like the OP.
>    ![1](https://user-images.githubusercontent.com/40308295/153536807-235f7bc4-937c-482a-b57c-d9e5e30f0365.jpg)
> 5. Close CRU.  Run restart64.exe
> 6. Open Nvidia panel.
> 7. Check your Change resolution tab to see only that one resolution + any lower ones you left in.
> 8. Go to Manage 3D settings and find DSR Factors, click it and select both 2.25 and 1.78x options (ignore the resolution listed here).  Click Apply.
>    ![2](https://user-images.githubusercontent.com/40308295/153537370-42de8a59-0e3c-4c7a-ac4f-05fea79cfc8b.jpg)
> 9. Go back to Change resolution tab and you should see 2 new options.  Check the one you want and hit apply.
>    ![3](https://user-images.githubusercontent.com/40308295/153537418-7a315325-f2f0-4dbb-9cf4-b12038204f03.jpg)
> 10. Update the High settings.xml file in the LukeRoss00 folder and settings.xml with that resolution.  in the settings.xml choose your sampling value between 1~9.  Save both files and run RealConfig.bat pressing H.
>     ![4](https://user-images.githubusercontent.com/40308295/153537843-b99ff9e0-3144-4569-b5cb-bc2e6d5b5d6c.jpg)
> 11. Test the game!  Mine was weird I had a rectangular view on the desktop and really bad parallax the first few times until playing with more and got it displaying square on the desktop and perfect in the headset after messing with settings.  The clarity is so worth all this trouble.

Very thoroughly explained, much appreciated.
I guess the issue I was having had to do with the fact that my TV doesn't support 90hz so I'm now using 60hz instead. And maybe it's just me, but the difference doesn't seem that big to justify resetting the resolutions and tinkering with CRU every time we want to play anything other than GTA in VR 😅 but maybe the difference is bigger on a headset like Pimax than my Quest 2...

**Comment by drclawscat** [comment]
Glad you got it working and yes it's a lot of work to do.  I have a spare 2560 monitor so just unplug my 4k OLED and plug that in and it will remember all my desktop config and resolutions so I'm ready to play immediately.  

Try playing with the sampling value, raise it to 9, if using VD, set your quality settings to the max in virtual desktop if you have a good router connection.  
Not sure what you can do if you're using the link cable.  

I've tested both on and off and it goes from super aliased or blurry with TSAA off for mid distant objects to crisp sharp and clear. I'm also running with MSAA 2x TSAA which clears up any jaggies.
