### ISSUE TITLE
black screen in gta vr 

### ISSUE THREAD

**Issue by Jaydenleefortune** [LukeRoss00/gta5-real-mod#426]
Black screen v hook critical error and real vr Asi something went wrong error

**Comment by Jaydenleefortune** [comment]
How do i fix it

**Comment by Jaydenleefortune** [comment]
It says a error ocurd while executing real vr. Asi

**Comment by Max3651** [comment]
I have the exact same issue, I tried resetting my pc, I reinstalled Gta V too. I have no other mods, I am running a quest 2 on air link and I am using a 1650 super with an i5-9400f. The vr mod worked perfectly fine a few days ago too.

**Comment by Max3651** [comment]
CPU: i5-9400f
GPU: 1650 super
VR headset model: Oculus quest 2
game version and build: Newest build of gta and version 7 of r.e.a.l mod. I also have the newest script-hook version installed.
release of the mod: 115e0c9
did you follow all the Quick setup steps carefully, in particular step 4? Yes.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Medium
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? Other then the newest version of script-hook, no.

**Comment by Max3651** [comment]
Also it seems to be unrelated to #424 for me because it crashes after the 5 star cinematic(main menu cutscene)

**Comment by Jaydenleefortune** [comment]
I get into the game I can only see the mini map and the actual game is black 
But if I look at the game in my pc it’s clearly playing 
I get the error I close it then it loads in to the game with a black screen

**Comment by LukeRoss00** [comment]
@Max3651 Please open a separate issue, as you seem to have a different problem (your game crashes, while Jayden's doesn't)

@Jaydenleefortune Please provide the information that we need to help you as per #239

**Comment by Jaydenleefortune** [comment]
Ryzen 2700
1660 ti
Quest 2 link cable 
Newest build 
Newest mod version 
Step 4 yes 
Medium settings 
Graphics settings I did not change 
No 

how do I check the batch file you asked for

**Comment by LukeRoss00** [comment]
@Jaydenleefortune you simply need to download the latest Script Hook V from Alexander Blade's page (http://www.dev-c.com/gtav/scripthookv/) and update the `ScriptHookV.dll` file that you have in the game folder. Be careful that the new file must go exactly in the folder where `GTA5.exe` is, not in other places like for example a bin subfolder

**Comment by Jaydenleefortune** [comment]
I have script hook in the main folder and it won’t work that’s where it’s been the whole time and black screen still

**Comment by Jaydenleefortune** [comment]
The games running but inside the headset is a black screen

**Comment by LukeRoss00** [comment]
Please attach here your `asiloader.log` and `ScriptHookV.log` files

**Comment by Jaydenleefortune** [comment]
Where do I get those

**Comment by Jaydenleefortune** [comment]
i dont know how to do that

**Comment by Jaydenleefortune** [comment]
it says we dont support file type

**Comment by Jaydenleefortune** [comment]
sorry found it
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7921480/ScriptHookV.log)
t

**Comment by Jaydenleefortune** [comment]
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7921482/asiloader.log)

**Comment by Jaydenleefortune** [comment]
heres the updated ones
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7921493/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7921494/asiloader.log)

**Comment by LukeRoss00** [comment]
The logs look correct, except for the fact that the script crashes immediately (which it should never do). Are you absolutely positive that you're using Release 7 of the mod? You wrote "newest" in reply to my question, just like I advise NOT to do, so I wonder if you actually checked

**Comment by Jaydenleefortune** [comment]
100% postive its 7

**Comment by Jaydenleefortune** [comment]
I’m so sorry I relised it was r4 it’s working now so sorry
