### ISSUE TITLE
GTA crash

### ISSUE THREAD

**Issue by Max3651** [LukeRoss00/gta5-real-mod#427]
I have an issue with the GTA R.E.A.L mod. My screen crashes instantly after opening the game while using the mod, it wasn’t an issue a day ago and GTA works without the VR mod. I tried resetting my pc, I reinstalled Gta V too. I have no other mods, I am running a quest 2 on air link and I am using a 1650 super with an i5-9400f.

CPU: i5-9400f
GPU: 1650 super
VR headset model: Oculus quest 2
game version and build: Newest build of gta and version 7 of r.e.a.l mod. I also have the newest script-hook version installed.
release of the mod: 115e0c9
did you follow all the Quick setup steps carefully, in particular step 4? Yes.
which settings did you choose (H/M/L) when running the batch file RealConfig.bat? Medium
did the batch file report any errors? No
did you change the graphics settings manually? No
are you using any other mods? Other then the newest version of script-hook, no.

Also it seems to be unrelated to #424 for me because it crashes after the 5 star cinematic(main menu cutscene)

**Comment by LukeRoss00** [comment]
A possible explanation is that something got corrupted with your Oculus runtime installation. Let's check the logs. Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and launch the game. After it crashes there will be a new `RVRLog.txt` file in the game folder, which you can attach here. Please also include your `RealVR.ini` renamed as `RealVR.txt`, `asiloader.log` and `ScriptHookV.log`

**Comment by Max3651** [comment]
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/7921199/RVRLog.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/7921200/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/7921201/asiloader.log)
Here you go!

**Comment by LukeRoss00** [comment]
Yes, something is definitely wrong with your Oculus installation. You should repair it from the "Add or remove programs" Windows settings page

**Comment by Max3651** [comment]
I will try that, Thank you.

**Comment by LukeRoss00** [comment]
Let me know if that solves it for you, otherwise we'll go on investigating!

**Comment by Max3651** [comment]
So, it worked temporarily for one run, but right after that the same problem occurred and repairing it again did nothing. What should I do?

**Comment by LukeRoss00** [comment]
Did anything strange occur between the successful run and the next? Like a system crash or BSOD, power outage, hardware disconnect, etc.? Usually the only reason why the Oculus runtime gets corrupted is when there are hardware or software problems that leave its files or drivers in a corrupted state.

**Comment by Max3651** [comment]
Actually, my screen turned black for a second in between, I didn’t think anything of it.

**Comment by Max3651** [comment]
Could it be because of MSI afterburner? Or maybe my game booster?

**Comment by LukeRoss00** [comment]
It's possible, yes. Overclocking can make the video driver crash, which in turn can damage the Oculus installation. I would advise resetting the clocks and profiles to factory state, and trying again (you might need to reinstall Oculus from scratch). Are you running Windows 11 by any chance?

**Comment by Max3651** [comment]
No, I’m running the latest version of windows 10, I will be home in an hour and I will tell you if disabling the overclock helps.

**Comment by Max3651** [comment]
It worked, thank you. I had to uninstall MSI afterburner but it’s working perfectly smooth and I even installed VisualV on the side!

**Comment by LukeRoss00** [comment]
Awesome!
