### ISSUE TITLE
Gta v vr stutter 

### ISSUE THREAD

**Issue by Jaydenleefortune** [LukeRoss00/gta5-real-mod#428]
The game is a little stuttery can you fix it when I look around with a gun or when I get in a car it’s stutters can I fix it the gun is the main issue

**Comment by LukeRoss00** [comment]
It's an artefact of alternate eye rendering (see https://github.com/LukeRoss00/gta5-real-mod#faq). The VR runtime's ATW can only compensate one rigid rotation at any given time. If you want the world to be stable when you rotate the camera from the game (not with your real head), you have to accept that the gun will ghost. If you prefer it to be the other way around, that is stable gun but doubling world when you turn the camera, you can activate the mod hotkeys with `F11` and then use the undocumented `[~]` (tilde) hotkey to toggle between the two behaviors.
