### ISSUE TITLE
Question: What is the frame scaling doing? (I already read everything.)

### ISSUE THREAD

**Issue by michael-persch** [LukeRoss00/gta5-real-mod#429]
In the original GTA V when I set the resolution to 1280x720 and set frame scaling to 200% the game would still output 720p, but the image would look better because the internal resolution is higher.

Is frame scaling still just increasing the internal resolution or the output resolution?
It unfortunately isn't that clear to me.

Sometimes I've got the feeling that the picture does not look sharp enough on my Vive Pro 2 at 1080p@200%, what should be 2160p.

**Comment by LukeRoss00** [comment]
My mod sends the internal buffer to the VR headset, so the higher the frame scaling, the sharper the world will look in the headset.

See https://github.com/LukeRoss00/gta5-real-mod#even-more-advanced-resolution-tweaking to increase the resolution even further

**Comment by drclawscat** [comment]
Try this for a really clear image if you have a decent gfx card: https://github.com/LukeRoss00/gta5-real-mod/issues/425
