### ISSUE TITLE
Revive - Works on vive but the scale is no good. 

### ISSUE THREAD

**Issue by CuriousRddit** [LukeRoss00/gta5-real-mod#43]
Hi Luke, how do I change the scale, right now it feels like the character is half their size, thanks

**Comment by LukeRoss00** [comment]
I just put out a [new release](https://github.com/LukeRoss00/gta5-real-mod/releases/tag/r2) with native SteamVR rendering. Check it out (follow the instructions in the release and do not use Revive), and please report back in issue #44
