### ISSUE TITLE
unable to get into the game in VR

### ISSUE THREAD

**Issue by neonamite** [LukeRoss00/gta5-real-mod#431]
I have a 1st gen oculus quest I have been trying to get the game to open in vr for about 2 days now and I cant get it to work all it dose is tell me "grand theft auto V dose not support VR. it will appear on your desktop and may affect VP performance"

I have reinstalled the game got rid of all of my other mods got the latest version for the mod and scripthook and still cant get it to work for me. Can someone help me ?

**Comment by LukeRoss00** [comment]
See #239 for new issues
