### ISSUE TITLE
GTA 5 isn't launching inside VR Headset.

### ISSUE THREAD

**Issue by Gamermoments6793** [LukeRoss00/gta5-real-mod#432]
- CPU: Ryzen 5 5600x
- GPU: RTX 3070 Ti
- VR headset model: Quest 2
- Game Version and build number: Steam Version on 1.0.2545.0 (Also installed the latest ScriptHookV)
- Release of the mod: Release 7
I did everything that you needed to do carefully, but the game simply doesn't run on my headset, it just runs on desktop.
![problem](https://user-images.githubusercontent.com/100979189/156861701-6cd12ea5-afae-4e3d-92b4-d8bc341733df.PNG)
(Oculus Software is running in the background, and my Quest 2 is linked up)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/8189556/asiloader.log)
[RealVR(dot)ini.txt](https://github.com/LukeRoss00/gta5-real-mod/files/8189559/RealVR.dot.ini.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/8189560/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
Thank you for providing great detail! All looks in order, weird that it shouldn't start in VR (I just finished a test session with the Quest 2 so I'm sure it still works).

Let's see what the mod log says. Add a new line `RVRLog = 1` at the end of your `RealVR.ini` and play the game until you get control of your character, then quit. There will be a new `RVRLog.txt` file in the game folder, which you can zip (it might be quite big) and attach here.

**Comment by Gamermoments6793** [comment]
Okay for some weird ass reason, it just randomly started working. I'll send the RVRLog.txt file in a minute. Guess I had to restart steam

**Comment by Gamermoments6793** [comment]
[RVRLog.zip](https://github.com/LukeRoss00/gta5-real-mod/files/8189612/RVRLog.zip)
Here's the file just in case you still need it for whatever. Cried actual tears when playing lmao. Thanks for making this mod!

**Comment by LukeRoss00** [comment]
Yep, all looks good with the log! Have fun :-)
