### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Jalexooo** [LukeRoss00/gta5-real-mod#433]
Hi last night in downloaded the mod and it worked fine, but then I tried to install the shader pack "redux" and now every time I load up the game when I get in all I can see is the minimap, please help I've been looking forward to this mod for a while.

**Comment by LukeRoss00** [comment]
I wouldn't advise using Redux, but if you really must see here for info: https://github.com/LukeRoss00/gta5-real-mod#more-advanced-graphics-tweaking
