### ISSUE TITLE
Blackscreen / GTA V VR.

### ISSUE THREAD

**Issue by PayoatePlant** [LukeRoss00/gta5-real-mod#435]
My GTA 5 in VR just shows a black screen and I can go in settings only. And see the map!

My specs are:
RTX 2060
Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz
Memory: 16 GB
Internet: Ethernet, 90 mb download spped, 16 mb upload speed!

Please give me a solution so I can fix this and play VR!!

**Comment by LukeRoss00** [comment]
Please see #239 when opening new issues
