### ISSUE TITLE
2 FPS on a GTX 1660 Ti 

### ISSUE THREAD

**Issue by pcethu** [LukeRoss00/gta5-real-mod#437]
I am getting a constant 2 FPS no matter what settings I try on my GTX 1660 Ti.
GTX 1660 Ti 
i7 10700F
32gb 3200 ddr4 pny
HTC VIVE PRO 2

I checked around everywhere and I cannot find a solution to this issue. My pc runs GTA V at 100+ fps without the vr mod and now I have only 20% gpu usage and around 20% cpu usage. I made sure that there were no duplicate files and my pc usage is set to max performance mode in the NVIDIA control panel. Like I stated earlier I tried every single setting in the bat file and results were the same. The only other mod I have installed is menyoo which was in the "compatible mods" list. Every other VR game runs well. Please help me out.. I really want to enjoy this mod..

**Comment by LukeRoss00** [comment]
Very low frame rates usually indicate that an obsolete version of the mod is being used. Please make sure that you're on Release 7 (https://github.com/LukeRoss00/gta5-real-mod/releases)

**Comment by pcethu** [comment]
I downloaded version 7 and I am sure about that. It still gives me 2 FPS..

**Comment by LukeRoss00** [comment]
Please zip and attach here your `RealVR.ini`, `asiloader.log` and `ScriptHookV.log` files (don't simply paste them as they would lose all formatting)

**Comment by pcethu** [comment]
; GTA V R.E.A.L. mod Release 7

[Defaults]

; F11         Activate hotkeys - off at start
Hotkeys = 0

; 0           Select stereo mode in cutscenes (normal, dynamic, flat screen) - dynamic at start
StereoInCutscenes = 1

; T           Select dominant eye for aiming down sights (none, left, right) - right at start
DominantEye = 2

; Y           Select heading control (always, only when aiming, never) - always at start
HeadingControl = 0

; J           Select pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
CutscenePitchMode = 2

; N           Show FPS counter - off at start
ShowFPS = 0

; End         Activate gyro stabilization of view in vehicle - off at start
GyroVehicle = 0

;             Select universal FOV fix (never, only cutscenes, only aiming, always) - always at start
UniversalFOVFix = 3

; NUMPAD.     Select zoom/FOV override (never, only cutscenes, always except cutscenes, always) - never at start
ZoomOverride = 0

; NUMPAD2     Activate stereo rendering (alternate eyes) - on at start
Stereo = 1

;             Select VR API to use (autodetect, Oculus, OpenVR, OpenXR) - autodetect by default
VRAPI = 0

**Comment by pcethu** [comment]
IT wouldn't let me paste the ini file, I saw another folder that had realvr.asi in it and deleted it and now I get like 85fps but it feels a lot lower and stutters when I turn and move. My CPU usage is only hitting 20% but the gpu is 95% so idk if its a bottleneck

**Comment by LukeRoss00** [comment]
Well, at this point you can experiment. Your card is quite underpowered to play this kind of game in VR, but if you use the `N` hotkey as explained [here](https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys) to monitor your actual in-game fps and find settings that allow you to get a stable 90 fps you will get a good experience!

**Comment by pcethu** [comment]
Alright, thanks once again I am planning on upgrading my GPU once ada lovelace hits.

**Comment by LukeRoss00** [comment]
That would be an awesome upgrade!
