### ISSUE TITLE
RealConfig freezing/not working

### ISSUE THREAD

**Issue by LuckyK65** [LukeRoss00/gta5-real-mod#438]
When I try to put in a graphic setting on RealConfig it just sits there and doesnt let me type anything after I put in a letter
![image](https://user-images.githubusercontent.com/81326062/164109936-06a48c81-610a-4c92-bf68-09ae422ef0ec.png)

Important stuff
CPU: AMD Ryzen 5 3600 6 Core Processer
GPU: Nivida Geforce GTX 1660
VR headset model: Rift S
game version and build: build 2545 and version 1.0.2545.0
release of the mod: Release 7
I did do the steps other than this cause you know, no work

**Comment by LukeRoss00** [comment]
You might have an issue with your PowerShell installation. Copy this in a command prompt window:

`powershell "(new-object -COM Shell.Application).Namespace(0x05).Self.Path"`

if it works correctly, it should output your documents path.

**Comment by LuckyK65** [comment]
It also did nothing, so I'll try reinstalling it or something

**Comment by LuckyK65** [comment]
Ok thanks it worked
