### ISSUE TITLE
Outdated recenter instructions

### ISSUE THREAD

**Issue by GodsBadAssBlade** [LukeRoss00/gta5-real-mod#439]
In the description of recentering your head doing a sharp enough left or right head movement and recentering your head never has worked for me, but recently I discovered that shaking my head left and right gently recenters it. So maybe an update to the description is needed?

**Comment by LukeRoss00** [comment]
I guess it may be subjective... I haven't changed anything in the recentering code though. Which headset are you using?

**Comment by GodsBadAssBlade** [comment]
> I guess it may be subjective... I haven't changed anything in the recentering code though. Which headset are you using?

I'm using a rift s, if you want to check for verification you can checkout my recent vod on twitch, just try to find me in a car, that's where I did it the most. Like all I took was a gentle left and right shake with a pause in movement to confirm. The way I read your instructions I thought it was a quick sharp turn to the left or right and back to where you're looking to recenter but my way works like 95% of the time. But regardless, mad respect for the project!

**Comment by LukeRoss00** [comment]
I do agree, in fact I shake gently myself. But whenever I say that, people misinterpret and move waaay too slowly which prevents the gesture from being registered. Do you have a link to you showing the gesture? It might help out other users!

**Comment by GodsBadAssBlade** [comment]
Oh yeah no problem my dude https://clips.twitch.tv/ToughPeppyNeanderthalBIRB-hLwTVWYwmIYOHwua
Sorry for the lag spikes and such, it's hard to get a stable frame rate even on a 3070, but for what it is its pretty dang smooth considering this us a mod

**Comment by LukeRoss00** [comment]
Haha, that's what I would call a rather sharp motion! Anyway you can also see it here in action as demonstrated by my friend Cas: https://youtu.be/OzcKPh8UxJ8?t=194

I'll close the issue now as the matter is quite subjective :-)
