### ISSUE TITLE
Game not launching in VR Headset (Oculus Quest 2)

### ISSUE THREAD

**Issue by D-Tunez** [LukeRoss00/gta5-real-mod#441]
CPU: **Ryzen 9 3900x**
GPU: **MSI Suprim X RTX 3090**
VR headset model: **Oculus Quest 2**
Game version and build: **version 1.0.2.2628.2 (Steam)**
release of the mod: **Version 7**
did you follow all the [Quick setup](https://github.com/LukeRoss00/gta5-real-mod#quick-setup) steps carefully, in particular step 4? 
**I did all the steps multiple times and watched multiple videos on it but I just cant get it to work. I keep getting this:** 

![image](https://user-images.githubusercontent.com/28646347/174433910-da11bc5c-ce7e-4d64-98e4-f540de3ec845.png)

which settings did you choose (H/M/L) when running the batch file RealConfig.bat?
**I chose H**
did the batch file report any errors? **No**
did you change the graphics settings manually? **No**
are you using any other mods? **No**

What I did:

- install a clean copy of GTA V
- disabled that steam vr theater mode checkbox thingie
- opened it, changed the settings of head bobbing etc.
- Closed the game and steam
- extracted your mod in the game folder
- Ran the RealConfig.bat file and typed H and closed it
- Then I downloaded the latest version of scripthookv and dropped the files in there (I tried only scripthookv.dll, that didnt work, then all the files but that also didnt work)
- Started the oculus software (for Air Link)
- then in my oculus I clicked the button to show my desktop in my VR Headset and clicked Play on Steam

I also tried something you said in another issue on GitHub, which is to link the headset and normally launch the game like I always do (so from the dektop on my tv, not inside the VR Headset) but then I only hear the sound and I just see the oculus link home environment.

[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/8933384/asiloader.log)
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/8933386/RVRLog.txt)
[RealVR.ini.txt](https://github.com/LukeRoss00/gta5-real-mod/files/8933383/RealVR.ini.txt)
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/8933385/ScriptHookV.log)

**Comment by LukeRoss00** [comment]
Hey, thanks for already including `RVRLog.txt`! From your log the problem seems clear: in the second line the Oculus runtime returns error `-3005 ("Windows 7 Service Pack 1 or a later operating system version is required.")`

So VR is never activated. Are you running an old version of Windows by any chance? Or if you aren't, can you think of any reason why the Oculus runtime would report that error?

**Comment by LukeRoss00** [comment]
I can think of one perhaps: did you set the game executable to Windows 7 compatibility and then forgot about it?

**Comment by D-Tunez** [comment]
Hey! No I'm running Windows 11. Isnt it compatible with that maybe? I just installed a clean copy of GTA, I didnt do amything to the executable

**Comment by LukeRoss00** [comment]
I don't think it's Windows 11's fault because many other users would have reported the same problem. Instead it's the first time I see anyone having this error. There are only two hits on the whole Internet for the error code, and in both cases the game executable compatibility had been tweaked.

**Comment by LukeRoss00** [comment]
Also, if you just installed a clean copy of GTA V, why do you have `TrainerV.asi` in the game directory? Something doesn't add up. Perhaps you have two copies of the game?

**Comment by D-Tunez** [comment]
I'll look into it but I dont think so. I only added TrainerV.asi to check if scripthookv was working. But thats all I did

**Comment by D-Tunez** [comment]
I'll look into it on Monday

**Comment by Kirby2054** [comment]
I'm running into this exact same issue as well!

Same answers to all questions as D-Tunez.  TrainerV.asi is not in game directory in my case.  I also used latest ScriptHookV

CPU: Ryzen 5 1600X
GPU: GTX1080
VR headset model: Oculus Quest 2
Game version and build: version 1.0.2.2628.2 (Steam)
release of the mod: Version 7

**Comment by LukeRoss00** [comment]
@Kirby2054 Are you on Windows 11 too?

**Comment by Kirby2054** [comment]
@LukeRoss00 I'm on Windows 10 version 21H2/Build 19044.1706

**Comment by D-Tunez** [comment]
@LukeRoss00 @Kirby2054 My GTA5.exe indeed was in Windows 7 compatibility mode, I'm not sure why. I disabled it and now it works excellent! Thanks for your help! I hope you can help Kirby too!

**Comment by Kirby2054** [comment]
@D-Tunez @LukeRoss00 Found my issue as well :) In my case I somehow missed the dinput8.dll when installing ScriptHookV.  I guess that's what you get for trying this out at 4 am :)  All resolved for me!  @LukeRoss00 keep up the good work!!

**Comment by LukeRoss00** [comment]
That's great! I'll close the issue then
