### ISSUE TITLE
Crash to desktop

### ISSUE THREAD

**Issue by milesvor** [LukeRoss00/gta5-real-mod#45]
Steamvr beta. winodws 10 up to date, ryzen 3600 32gb ram; no controller; did not turned on the knuckles. revive started at launch of steamvr.
Done all you said.
Disabled cinena mode when steavr is active
Started steamvr 
Launched gta5 from desktop
The rockstar launcher appears briefly. Then close and nothing happens

**Comment by LukeRoss00** [comment]
> revive started at launch of steamvr

You should NOT be using Revive with this version

**Comment by milesvor** [comment]
Disabled Revive. Turned off SteamVR.
Launched the  gtalauncher outside of steam (with steam opened).
Tha game worked!
Thanks!, wonderful!
