### ISSUE TITLE
Odyssey plus through steam - resolution is off and large pixelated

### ISSUE THREAD

**Issue by d0ugie007** [LukeRoss00/gta5-real-mod#48]
Cup - I9 intel

Gpu - RTX 2080 Ti

HMD - Samsung Odyssey+

Started but we very blurry and poor resolution. Any support would be appreciated

**Comment by LukeRoss00** [comment]
Please attach your `Documents\Rockstar Games\GTA V\settings.xml` file

**Comment by d0ugie007** [comment]
Hi bud,

thanks for getting back to me..

please see setup below... 

<?xml version="1.0" encoding="UTF-8"?>

<Settings>
  <version value="27" />
  <configSource>SMC_AUTO</configSource>
  <graphics>
    <Tessellation value="3" />
    <LodScale value="1.000000" />
    <PedLodBias value="0.200000" />
    <VehicleLodBias value="0.000000" />
    <ShadowQuality value="2" />
    <ReflectionQuality value="2" />
    <ReflectionMSAA value="4" />
    <SSAO value="2" />
    <AnisotropicFiltering value="16" />
    <MSAA value="0" />
    <MSAAFragments value="0" />
    <MSAAQuality value="0" />
    <SamplingMode value="0" />
    <TextureQuality value="2" />
    <ParticleQuality value="2" />
    <WaterQuality value="2" />
    <GrassQuality value="2" />
    <ShaderQuality value="2" />
    <Shadow_SoftShadows value="3" />
    <UltraShadows_Enabled value="false" />
    <Shadow_ParticleShadows value="true" />
    <Shadow_Distance value="1.000000" />
    <Shadow_LongShadows value="false" />
    <Shadow_SplitZStart value="0.930000" />
    <Shadow_SplitZEnd value="0.890000" />
    <Shadow_aircraftExpWeight value="0.990000" />
    <Shadow_DisableScreenSizeCheck value="false" />
    <Reflection_MipBlur value="true" />
    <FXAA_Enabled value="true" />
    <TXAA_Enabled value="false" />
    <Lighting_FogVolumes value="true" />
    <Shader_SSA value="true" />
    <DX_Version value="2" />
    <CityDensity value="1.000000" />
    <PedVarietyMultiplier value="1.000000" />
    <VehicleVarietyMultiplier value="1.000000" />
    <PostFX value="2" />
    <DoF value="false" />
    <HdStreamingInFlight value="false" />
    <MaxLodScale value="0.000000" />
    <MotionBlurStrength value="0.000000" />
  </graphics>
  <system>
    <numBytesPerReplayBlock value="9000000" />
    <numReplayBlocks value="36" />
    <maxSizeOfStreamingReplay value="1024" />
    <maxFileStoreSize value="65536" />
  </system>
  <audio>
    <Audio3d value="false" />
  </audio>
  <video>
    <AdapterIndex value="0" />
    <OutputIndex value="0" />
    <ScreenWidth value="800" />
    <ScreenHeight value="600" />
    <RefreshRate value="60" />
    <Windowed value="2" />
    <VSync value="0" />
    <Stereo value="0" />
    <Convergence value="0.100000" />
    <Separation value="1.000000" />
    <PauseOnFocusLoss value="1" />
    <AspectRatio value="0" />
  </video>
  <VideoCardDescription>NVIDIA GeForce RTX 2080 Ti</VideoCardDescription>
</Settings>

**Comment by d0ugie007** [comment]
<?xml version="1.0" encoding="UTF-8"?>

<Settings>
  <version value="27" />
  <configSource>SMC_AUTO</configSource>
  <graphics>
    <Tessellation value="3" />
    <LodScale value="1.000000" />
    <PedLodBias value="0.200000" />
    <VehicleLodBias value="0.000000" />
    <ShadowQuality value="2" />
    <ReflectionQuality value="2" />
    <ReflectionMSAA value="4" />
    <SSAO value="2" />
    <AnisotropicFiltering value="16" />
    <MSAA value="0" />
    <MSAAFragments value="0" />
    <MSAAQuality value="0" />
    <SamplingMode value="0" />
    <TextureQuality value="2" />
    <ParticleQuality value="2" />
    <WaterQuality value="2" />
    <GrassQuality value="2" />
    <ShaderQuality value="2" />
    <Shadow_SoftShadows value="3" />
    <UltraShadows_Enabled value="false" />
    <Shadow_ParticleShadows value="true" />
    <Shadow_Distance value="1.000000" />
    <Shadow_LongShadows value="false" />
    <Shadow_SplitZStart value="0.930000" />
    <Shadow_SplitZEnd value="0.890000" />
    <Shadow_aircraftExpWeight value="0.990000" />
    <Shadow_DisableScreenSizeCheck value="false" />
    <Reflection_MipBlur value="true" />
    <FXAA_Enabled value="true" />
    <TXAA_Enabled value="false" />
    <Lighting_FogVolumes value="true" />
    <Shader_SSA value="true" />
    <DX_Version value="2" />
    <CityDensity value="1.000000" />
    <PedVarietyMultiplier value="1.000000" />
    <VehicleVarietyMultiplier value="1.000000" />
    <PostFX value="2" />
    <DoF value="false" />
    <HdStreamingInFlight value="false" />
    <MaxLodScale value="0.000000" />
    <MotionBlurStrength value="0.000000" />
  </graphics>
  <system>
    <numBytesPerReplayBlock value="9000000" />
    <numReplayBlocks value="36" />
    <maxSizeOfStreamingReplay value="1024" />
    <maxFileStoreSize value="65536" />
  </system>
  <audio>
    <Audio3d value="false" />
  </audio>
  <video>
    <AdapterIndex value="0" />
    <OutputIndex value="0" />
    <ScreenWidth value="800" />
    <ScreenHeight value="600" />
    <RefreshRate value="60" />
    <Windowed value="2" />
    <VSync value="0" />
    <Stereo value="0" />
    <Convergence value="0.100000" />
    <Separation value="1.000000" />
    <PauseOnFocusLoss value="1" />
    <AspectRatio value="0" />
  </video>
  <VideoCardDescription>NVIDIA GeForce RTX 2080 Ti</VideoCardDescription>
</Settings>

**Comment by d0ugie007** [comment]
think this is what you need, sorry new to this!

**Comment by LukeRoss00** [comment]
You seem to have made several changes to your `settings.xml` file that are breaking the mod, not sure why you did that instead of just using the 'high' template that I provided. Anyway: use 
[this one](https://github.com/LukeRoss00/gta5-real-mod/files/3992510/settings.zip) where I already put in your graphics card name for you. Please report back if that works so we can close the issue

**Comment by d0ugie007** [comment]
Thank you, I will try it now

**Comment by d0ugie007** [comment]
Okay Luke, it looks great and scale is amazing, I do have a lot of  jitter looking from left to right even slowly. But I'm guessing this is just getting the setting correct?

P.s how can I help support you, this mod is killer bro👍

**Comment by LukeRoss00** [comment]
Thank you for the kind words! For the jitter please refer to issue #50
