### ISSUE TITLE
view off center

### ISSUE THREAD

**Issue by ShinyRobotVR** [LukeRoss00/gta5-real-mod#49]
hi just tried the steam vr version with index and the whole screen is to the top left. so the center of my view is the bottom right of the rendered screen. any ideas? thanks

**Comment by ShinyRobotVR** [comment]
ok i had set my gpu name to RTX 2070 Super, instead of RTX 2070 SUPER.

**Comment by LukeRoss00** [comment]
Glad that you solved it!!
