### ISSUE TITLE
Jittering with WMR headsets (post here for peer support)

### ISSUE THREAD

**Issue by LukeRoss00** [LukeRoss00/gta5-real-mod#50]
Guys, unfortunately I don't know what to do on my side for the WMR jitters. I got no reply from Microsoft regarding the issues that I submitted (https://github.com/ValveSoftware/openvr/issues/1253 and https://github.com/ValveSoftware/openvr/issues/1272). There is nothing in my code that tests for specific headsets (except Oculus vs SteamVR), so the fact that it works correctly on some WMR headsets and not on others is totally beyond my control. Also, I don't own a WMR headset, so I cannot even see for myself what the problem is.

What you could do is compare configurations among yourselves (system details, graphics settings, headset, driver versions, SteamVR settings, etc.), to see if you manage to find any specific cause. Also, if you post on the Windows Feedback Hub (https://docs.microsoft.com/en-us/hololens/hololens-feedback) there might be better chances that the right developer at Microsoft sees this.

Some discussion is also going on in [this](https://redd.it/ed03fl/) thread on Reddit, although it is unclear to me if the proposed solution works or not.

**Comment by LukeRoss00** [comment]
Allow me to break the ice with a question: did anybody try monoscopic mode? Press `F11` once to activate the mod hotkeys, `N` to enable the frame rate counter in the lower right corner of your view, and then toggle between AFR and mono rendering with `NUMPAD2`. Does monoscopic mode jitter too?

Also, what does the frame rate counter show during the jittering bursts?

**Comment by Shadowmask72** [comment]
Tried this. @LukeRoss00 Seems stuck at 60 fps and the mono mode was the same jitter.

**Comment by snouglas** [comment]
Hi Luke and everybody reading.
HMD used Samsung O+

I tried your instructions, while maintaining 90fps (although frametime reported by afterburner is in the 12ms range).
I can confirm monoscopic does not jitter while moving your head, but it has this weird shimmering effect and kind of like going cross eyed feeling (even withoud head movement).

**Comment by Shadowmask72** [comment]
@snouglas mono mode didn't jitter for me so much in less-populated areas but did where it's busy. 90 fps turning off the vsync made the mono mode slightly less jitter.

HP Reverb user here.

**Comment by snouglas** [comment]
I have found another weird behavior.
I opened the rotation overlay inside your mod by pressing F11 once ingame and then numpad*.

I saw that the values for **world yaw pitch and roll** wheren't changing, whereas the values for **desired yaw pich and roll** changed as they should.
The world value for yaw was, as expected, changeable by controller.

**Comment by LukeRoss00** [comment]
> I saw that the values for **world yaw pitch and roll** wheren't changing, whereas the values for **desired yaw pich and roll** changed as they should.
> The world value for yaw was, as expected, changeable by controller.

That is correct and how it should be

**Comment by ManuFerHi** [comment]
I also have jittering or tethering, I have Reverb, sometimes it disappears miraculously for a few seconds and everything goes perfect, but it reappears. Driving there is less.
It reminds me a lot of the problem with Argarth Wrath + Revive the effect is very similar and they fixed it with a patch.
https://github.com/LibreVR/Revive/issues/1354

**Comment by yoda123456** [comment]
Made a account to post this, I seem to be having very similar behavior I'm on the original Oculus, when I turn the camera using the controller the jitter is very bad almost like double vision I think one eye is lagging behind the other in these instances when in a car turning or looking out the side windows the double vision is very apparent too anytime I'm walking straight and look to the side you'll see jitter/double vision too now I'm not sure if this is for everyone or just me, any help would be greatly appreciated!

**Comment by Jesusavesouls** [comment]
So when I f11 and 2 I remove the 3d and get atble and then add the 3d and it looks great but when looking around it has some instability but I really dont care.You added so many options and updated this to work with wmr and steamvr.Thanks for that and it really does play and look very excellent.

**Comment by dtdman420** [comment]
Hi thanks to Luke i got this to work with my wmr O+.  My specs 1070ti, 8700k.

My framerate stays at 90 according to the frame thing when you press N.  Moving my head and mouse makes everything jittery.  After pressing numpad 2  it is a much smoother experience and the frames still stay at 90

**Comment by LukeRoss00** [comment]
Yes, unfortunately Microsoft hasn't fixed their driver yet to work correctly with alternate eye rendering, so there is still jittering in stereo mode even at full frame rate.

**Comment by LukeRoss00** [comment]
I'm closing this issue as there seems to be nothing left to say on the matter
