### ISSUE TITLE
gpu usage

### ISSUE THREAD

**Issue by chotus** [LukeRoss00/gta5-real-mod#55]
Hi lukeross

first up awesome job my bro. 

just curious though i use the high settings with my 1080 ti and 8700k oc and noticed that my cpu is at 40% and gpu is around 30% usage was wondering if this is normal i have gone threw your readme etc manytimes to try and fix it. as i noticed sometimes it drops from 90fps down to the low 60s sometimes.

any help would be much appreciated

**Comment by LukeRoss00** [comment]
Thanks! Unfortunately low CPU and GPU usage is pretty much the norm with GTA V.

If you want to double check, do this: temporarily remove the 3 files `RealVR.asi`, `d3d11.dll` and `nvapi64.dll`, which will completely disable the mod. Then run the game (in 2D) without changing any of the graphics settings: you should be seeing even lower usage. At least that's what happens on my system.
