### ISSUE TITLE
Missing information about RealVR.ini in README.md

### ISSUE THREAD

**Issue by jukibom** [LukeRoss00/gta5-real-mod#56]
The README briefly mentions a RealVR.ini file but not where the file is / should be or the format for the options in the file.

**Comment by jukibom** [comment]
Hell's bells, I'm an idiot and I was still on r2. So sorry :|

**Comment by LukeRoss00** [comment]
Hahaha, no problem! Since now you've upgraded to r3, how do you like the new cutscene viewing modes?

**Comment by jukibom** [comment]
That was the main thing I was trying to get going! Figured in lieu of a hotkey I could set it in the ini. I absolutely love the flat screen cutscenes because I've never actually played GTA V before and wanted to see them as intended. I'm loving the vr mod and the manual transmission / steering wheel mod!

I wonder, could the flat screen thing be used when transitioning into and out of a car?

**Comment by LukeRoss00** [comment]
The steering wheel is the best! You're serious about your gaming :-)

> I wonder, could the flat screen thing be used when transitioning into and out of a car?
Mmm, I believe that being dropped in and out of 3D in the middle of action would be even more jarring... Although it's mostly academic, because I don't know how to detect that animation being played. Does the FOV change bother you a lot?

**Comment by jukibom** [comment]
> Does the FOV change bother you a lot?

Not a huge amount, to be honest. That said, I do force zoom override to prevent aiming from being a nightmare - shame that causes graphical artefacts but hey, what can you do? I'm amazed it works as well as it does! I bought the game yesterday and played 11 straight hours ... last day of xmas break 🤷‍♀

**Comment by LukeRoss00** [comment]
> played 11 straight hours ... last day of xmas break 🤷‍♀

Okay, now you can stop laying down the charm, lady. You had me at steering wheel ;-)

Most people don't seem to mind the zooming in while aiming (it actually makes it a bit easier to hit targets). Also, I'm afraid that with zoom override on you will lose scope magnification. Which headset do you have?

**Comment by jukibom** [comment]
> You had me at steering wheel ;-)

lmao, I just meant I didn't get nausea so well done! :P 

> you will lose scope magnification

oh damn I haven't gotten to scopes yet, guessing they play a part in the story :( 

Also I'm on an original vive

**Comment by LukeRoss00** [comment]
> oh damn I haven't gotten to scopes yet, guessing they play a part in the story :(

Oops, sorry for the spoiler!

> Also I'm on an original vive

If I may ask you a somewhat personal question, do you plan to finish the game in VR during the next few days/weeks? Would you be interested in beta testing the next release of the mod?

**Comment by jukibom** [comment]
> Oops, sorry for the spoiler!

Nah no worries, that's hardly a spoiler, just another edge case :P 

> Would you be interested in beta testing the next release of the mod?

Yeah I'm playing the whole thing from start to finish in whatever free time I have, I'd absolutely love to! Catch me on steam https://steamcommunity.com/id/jukibom/
