### ISSUE TITLE
VR Controller Support

### ISSUE THREAD

**Issue by toybotmedia** [LukeRoss00/gta5-real-mod#57]
Hello, I am sorry this is not a bug I am reporting but I am new to github so I couldn't find a way to message you directly.

I fully understand your stance on traditional gameplay and fully agree. I would like to share a way to have what I believe is more traditional gameplay while using a VR controller.

Currently the mod is setup to use HMD aiming and if possible I say keep that as well cause variety is always good. What I would like to see is instead using the controller for "aiming"- i.e also moving the screen while moving the HMD does nothing.

This method allows players to sit still without moving their head around all over the place, and move it precisely. 

Please let me know what you think,

Thank You.

**Comment by LukeRoss00** [comment]
> not a bug I am reporting

No problem, I added the enhancement label for you

> while using a VR controller [...] What I would like to see is instead using the controller for "aiming"- i.e also moving the screen while moving the HMD does nothing

I'm not sure that I understand: you propose to decouple the view in VR from the headset tracking and tie it instead to the VR controller tracking? That would be extremely disorienting for everybody, and nauseating for a lot of people...

**Comment by toybotmedia** [comment]
Exactly.

Would you mind if I playtested such an idea? I personally think it's not as bad as people think it is. I actually believe it's the only way we are ever going to see real competitive VRFPS. 

Remember, when VR first came out until only recently, smooth locomotion was thought to be impossible for comfort. Now, it's standard and people do not want to play a VR game without it.

**Comment by LukeRoss00** [comment]
Oh, but you can already playtest it! I put so many user-configurable options in the mod that even this scenario is covered :-D (not with a VR controller, okay, but you can use your mouse or a traditional gamepad).

Just set heading control to never, pitch control to off, and view matrix fix enable to off. You can do that either by using the mod hotkeys or editing `RealVR.ini`.

**Comment by toybotmedia** [comment]
That's nice and I'll give that a try, but how would I do this with a VR controller?

**Comment by cercata** [comment]
> I fully understand your stance on traditional gameplay and fully agree. I would like to share a way to have what I believe is more traditional gameplay while using a VR controller.
> 
> Currently the mod is setup to use HMD aiming and if possible I say keep that as well cause variety is always good. What I would like to see is instead using the controller for "aiming"- i.e also moving the screen while moving the HMD does nothing.

I think this is the idea Sony had with the "AIM Controller", that from a logical point of view it's identical to a DualShock 4 controller.

Allow easy port from flat games, to be played in a tradicional way in VR, but with aiming, for allowing CoD and other shooters to be migrated easily to PSVR.

**Comment by Jesusavesouls** [comment]
As of now the www.grandtheftvr.com mod works with this one.It's not competition but cooperation.You get the full gta experience with this vanilla mod using a gamepad.And use that gtavr mod losing the full character but getting motion controls to steer and aim.

**Comment by LukeRoss00** [comment]
> That's nice and I'll give that a try

So did it work as you expected?

**Comment by xnemphisx** [comment]
https://uploadvr.com/play-quake-ii-room-scale-vr-rift-vive/ I played this mod, it used an interesting control method through the vr controller, the rotation of the head and arms with weapons worked independently of each other. It was better than just aiming your head. Try running it to test

**Comment by toybotmedia** [comment]
> > That's nice and I'll give that a try
> 
> So did it work as you expected?

Sorry I just didn't have the time to load up GTA with TWDSS and life. When I get around to it I'll post something here.
