### ISSUE TITLE
Has anyone else experienced this VR Mod breaking X360CE Controller Combining?

### ISSUE THREAD

**Issue by YodatheHobbit** [LukeRoss00/gta5-real-mod#58]
I'm looking for a solution. Can't find one. It's the only thing standing between me being able to drive and fly in VR using my Steering Wheel and Flightstick without having to restart the game.

**Comment by LukeRoss00** [comment]
It appears to be an issue with Script Hook V. Have you tried the solutions given [here](https://github.com/x360ce/x360ce/issues/66)?

**Comment by YodatheHobbit** [comment]
Yes. (Love this mod btw) Just retested both solutions on that page to be sure. I tried downloading and renaming dinput.dll to asiloader.dll as well as using the dsound.dll link in the last post. Although those solutions worked for me with other mods, I'm afraid it's not working with yours. Renaming dinput8.dll to asiloader.dll brakes controller combining in my game and makes the headset only inject the overlay(map, menus, hud), the game is replaced with pitch blackness. Using dsound.dll the game injects fine, but still only brakes the controller combining. I use a ps4 controller, Thrustmater wheel, and Logitech flightstick and only the PS4 controller is left working in game when the mod is installed.

**Comment by LukeRoss00** [comment]
Oh. Did you try version 4 of X360CE, which I gather no longer needs special dll's in the game folder?

**Comment by YodatheHobbit** [comment]
Ah, I never noticed their was a Beta on their site. Thanks, I'll try that out.
