### ISSUE TITLE
Online support

### ISSUE THREAD

**Issue by polybasss** [LukeRoss00/gta5-real-mod#59]
Hello, I know that it is not a problem in itself, rather a wish, could a request be made to Rockstar to allow the mod in Online mode? It would be a joy .... I don't know if gathering signatures or something would be possible, in that case if I could collaborate with the Spanish Vr community to make a request from specialized forums, thanks

**Comment by LukeRoss00** [comment]
Rockstar has a very clear position on this: no mods whatsoever allowed for Online :-(

**Comment by polybasss** [comment]
A shame, it would be amazing to enjoy it with friends
