### ISSUE TITLE
crashes when loading into game for first time

### ISSUE THREAD

**Issue by dezarr** [LukeRoss00/gta5-real-mod#60]
applied batch file no issues. Then the game starts fine and gets to the title screen, I can go into settings etc. I click on story mode and the game crashes.

**Comment by LukeRoss00** [comment]
You didn't give any of your system details, so it's a little hard to help you. Game version? Driver version? Does the game work fine without the mod? Which graphics preset did you choose? Are you using other mods? And so on and so forth. The more information you give, the more likely you are to get a solution.

**Comment by CMDRBunbun** [comment]
Got that fixed the immediate crash issue fixed, issue was the documents path where the Realconfig.bat file was trying to write to. I had moved  my documents folder. I went in said file and edited the location to reflect the actual path. I would suggest to anyone having a similar issue to look closely after running the realconfig.bat file it should return "1 file copied". Issue am having now is I cant progress past the intial cut scene where it prompts you to change characters. I'm using a steam controller with the recommended gamepad profile but i simply can't switch....anyone else using a steam controller? i press down on the directional pad just fine, but for the life of me it wont switch to the other character.

**Comment by drowhunter** [comment]
This is also happening to me, when I click story mode and it's just about to load into the game.
It crashes.  I am using an intel 4790 and rtx 2080Ti.  
It tried at first with Pimax, then I tried with a quest with link cable. Both times the same issue.

This is after running the realconfig.bat file.  
Then I edited the settings.xml manually and changed the video card to rtx 2080Ti. And it loaded just fine.  (I thought this wasnt't necessary anymore?

**Comment by LukeRoss00** [comment]
Please post the `commandine.txt` from your `GTA5.exe" folder. Did the batch file give you any errors, like file not found, 0 file(s) copied, etc.?

**Comment by drowhunter** [comment]
here is my commandline.txt
```
-width 1080
-height 1080
-ignoreDifferentVideoCard
```
on pimax the FOV is messed up when you first load into the game,  but if i hit F11 and the numpad . key a couple of times it works , but then I get the wheels flying in the sky issue.

Also the resolution is horribly aliased , what resolution would you suggest for the pimax as the FOV is so much wider.  is it still a good idea to use square resolutions?

**Comment by drowhunter** [comment]
Also re-centering doesn't work by shaking your head on the pimax. Maybe I should split these into separate issues.  I know you said Pimax isn't getting back to you,  I've been making my voice heard on their forums alot on this. 

Hopefully one man in the right place can make a, difference.

**Comment by LukeRoss00** [comment]
I'm terribly sorry, but I don't even have access to a Pimax headset, and they have gone silent on me again for about 20 days now. I think that your best bet for running the mod correctly would be using your Quest with the Link cable.

**Comment by drowhunter** [comment]
apparently im doing something wrong because this dude is having no problem.
https://youtu.be/Q5kWd4ZZ6Ng

**Comment by drowhunter** [comment]
I figured out my issue,  it seems that on Pimax i have to put my FOV to normal or small.  
the largest FOV setting 170 degrees causes problems

**Comment by LukeRoss00** [comment]
That makes sense. High FOV would require special coding, which I cannot do since I don't have any hardware to test on :-(

**Comment by DesignWonk** [comment]
Same issue. Error: GTA quit unexpectedly, right at "Yankton, nine years ago."
Tried M & L settings, which are conservative, and launch through Steam and Rockstar shortcut.

Rift S, Windows 10 Pro, i7-7700, GTX 1080. 
Commandline.txt:
-width 600 -height 600 -ignoreDifferentVideoCard (I tried potato settings "L" last)
No errors on bat

Only other note is that my Steamapps is in D: and my user profile is in C:
Seemed to update fine though with settings.xml showing the correct video card.

**Comment by LukeRoss00** [comment]
Does the game run fine if you remove the mod?

**Comment by DesignWonk** [comment]
Sure does. I removed it bluntly, just by deleting every file that the mod had placed. Works fine. Well, flatscreen fine, obviously.

**Comment by LukeRoss00** [comment]
If you wish to investigate the issue further, you could try this: reinstall the mod; add the line `RVRLog = 2` at the end of your `RealVR.ini`; run the game until it crashes. After the crash, you should have a new `RVRLog.txt` file: please attach it here. The log might give us some hints as to the cause of the CTD
