### ISSUE TITLE
View centering issues

### ISSUE THREAD

**Issue by xnemphisx** [LukeRoss00/gta5-real-mod#62]
Hi, I really like your mod, but no matter how I try, centering the view does not work for me. I tried to shake my head quickly and slowly, but for some reason this does not work for me. Maybe it can be done (optionally) so that the world map is anchored to the lower left edge of the camera? Or center the camera on pressing some buttons on the gamepad?

**Comment by LukeRoss00** [comment]
What headset are you using? Did you follow the instructions [here](https://github.com/LukeRoss00/gta5-real-mod#recentering-your-view-in-vr)? You can also use `NUMPAD/` to recenter ([more info](https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys)). If

**Comment by xnemphisx** [comment]
Using Rift s, Is it possible to do centering with a gamepad?

**Comment by xnemphisx** [comment]
> What headset are you using? Did you follow the instructions [here](https://github.com/LukeRoss00/gta5-real-mod#recentering-your-view-in-vr)? You can also use `NUMPAD/` to recenter ([more info](https://github.com/LukeRoss00/gta5-real-mod#advanced-tweaking-and-hotkeys))

Using Rift s, Is it possible to do centering with a gamepad?

**Comment by xnemphisx** [comment]
I tried again, but nothing helps me. During the game, the map can go almost 180 degrees. When I aim, I see her in my place. but when I remove the weapon the map leaves again. Maybe the alignment can be attached to the aim button? I aim and the map automatically returns to its place. Thanx

**Comment by xnemphisx** [comment]
LukeRoss00 Can I do something with the maps? or should I delete my posts?

**Comment by LukeRoss00** [comment]
You can also recenter using the Oculus system menu, as you would in any other app. If you upload a video of yourself doing the headshake gesture a few times, I can tell you what you're doing wrong. GTA V leaves no free buttons on the gamepad, so recentering cannot be bound to a gamepad button

**Comment by xnemphisx** [comment]
> You can also recenter using the Oculus system menu, as you would in any other app. If you upload a video of yourself doing the headshake gesture a few times, I can tell you what you're doing wrong. GTA V leaves no free buttons on the gamepad, so recentering cannot be bound to a gamepad button

To capture the image on the screen, or how do I shake my head? and can you give me mail?

**Comment by xnemphisx** [comment]
![OculusScreenshot1580588507](https://user-images.githubusercontent.com/46295861/73603982-274fa580-459b-11ea-8ef9-fa2940c25bfc.jpeg)
![OculusScreenshot1580588521](https://user-images.githubusercontent.com/46295861/73603983-274fa580-459b-11ea-9901-ad5e76fae547.jpeg)
Here is the view in the car, I look directly, but the map to my left is almost 90 degrees, I have to constantly turn my head sideways.

**Comment by LukeRoss00** [comment]
I'm sorry but I feel like I'm not getting through to you at all. Is English your native language? I suggest you things to try and you respond with unrelated statements and questions. Please see https://support.oculus.com/200305533724698/, it might be in your native language

**Comment by xnemphisx** [comment]
Sorry, I'm using a translator, I'm from Russia. my centering in the oculus works, but the problem is different. my body in the game is exactly where it should be. The problem is in the world map. She leaves relative to the center of the body. 
![CUgdGVlQoGai20EVTTlvbw](https://user-images.githubusercontent.com/46295861/73607432-f8e7bf80-45c6-11ea-83be-973312332f74.jpeg)
can you attach the map image to a specific place (so that it does not move?)

**Comment by LukeRoss00** [comment]
Every time you recenter with the Oculus menu, the map will be back in front of you! I'm sorry but there's really nothing else I can do

**Comment by xnemphisx** [comment]
I did a recenter through the oculus menu, but the map did not return to its place. Okay, I'm sorry to bother you)

**Comment by LukeRoss00** [comment]
No problem, sorry that it doesn't work for you!
