### ISSUE TITLE
Can't get past...

### ISSUE THREAD

**Issue by Arathrax** [LukeRoss00/gta5-real-mod#64]
Heya Luke!

I had been running v3 then I had uninstalled GTAV (Steam) to free up some SSD space (damn you Skyrim VR sucking me back in).
I reinstalled GTAV today and installed v4 of the mod but can't get past it ingame tellling me I am in offline mode and to activate and then it forces me to quit. 
Please note: I am signed into Rockstar Social Club and yes it's a full legal version of the game fully patched up.

Any ideas how to get it around this? Was I supposed to sign in in pancake mode THEN boot the game up in VR?

**Comment by LukeRoss00** [comment]
Anything left over in the Steam launch parameters for the game perhaps?

**Comment by Arathrax** [comment]
I ran the game directly from the Rockstar Launcher and oddly, that worked although it's saying something about Cloud Saves not synching and when I tried to adjust graphic settings in game it says the game was saving them.
I think I need to jump up to a 2070S card from a 1070. Still kinda jittery on moving head back and forth. But damn, it is amazing to walk around Los Santos. 

Killer job man!
