### ISSUE TITLE
On screen writing cut off

### ISSUE THREAD

**Issue by virtualmisterl** [LukeRoss00/gta5-real-mod#65]
Firstly I'd like to say thanks for the new update.
The new cut scene 3d is great.
Almost makes me want to start the game fresh.
Also shimmer is much better now we can use AA.

The issue I'm seeing is the coloured on screen writing which pops up saying where to go, what to do etc.. at the bottom of the screen is cut off at the start.
Its not a big problem as it's not critical & usually only a word or 2. 
Just something I thought I would mention to see if it's everyone who has this issue, or just me.

8700k 
2080ti
32gb
all oc.
Valve index 
High settings

**Comment by LukeRoss00** [comment]
No parts of the HUD should be cut off. Please post the contents of the `commandline.txt` file in your `GTA5.exe` folder

**Comment by Zeddy12345** [comment]
I'm using release 4 of the mod and also have a problem with subtitles being cut off at the bottom of the screen. It looks like the radar is positioned over them and cuts them off on the left hand side, but they also get cut off when the radar is disabled. I'm hard of hearing, so I like to turn subtitles on.

**Comment by LukeRoss00** [comment]
Same with you: no parts of the HUD should be cut off. Please post the contents of your `commandline.txt` file (the one in your `GTA5.exe` folder). If you don't give any information about your system, how do you expect me to help?

**Comment by Zeddy12345** [comment]
The only lines in my commandline.txt file are:

-width 1080
-height 1080
-ignoreDifferentVideoCard

(The subtitles are only cut off while walking around the map, not during cut scenes)

**Comment by LukeRoss00** [comment]
I cannot reproduce the issue. If you go to the graphics options page while in game, what does it say for Screen Type, Resolution and Aspect Ratio?

**Comment by LukeRoss00** [comment]
Can the two of you @virtualmisterl and @Zeddy12345 please confirm whether the issue only occurs with MSAA turned on?

**Comment by Zeddy12345** [comment]
Yes, I just checked and it only happens when MSAA is turned on. It's to bad that FXAA is so blurry to use compared to MSAA.

**Comment by LukeRoss00** [comment]
Try overwriting your `d3d11.dll` with the one [here](https://github.com/LukeRoss00/gta5-real-mod/files/4164584/d3d11.zip). Please report back whether it works for you, both with MSAA on and off! If it works reliably I'll add it to the release as a hotfix for people who have the same problem

**Comment by Zeddy12345** [comment]
Looks like that new d3d11.dll fixes it! Thank you! It works with MSAA on and off.

**Comment by LukeRoss00** [comment]
Awesome! @virtualmisterl, does it work for you too?

**Comment by virtualmisterl** [comment]
@LukeRoss00 
Sorry I've had a busy week & only just had chance to get on gta v.
Just tested your new d3d11.dll while using MSAA 4x & the issue is fixed.
Thank you!

**Comment by LukeRoss00** [comment]
Guys, thanks for the quick feedback! I've updated the release with the hotfix from this thread

**Comment by Gonzaxpain** [comment]
@LukeRoss00 
Thanks a lot for this, I was having the exact same issue with subtitles on my Index. Is it enough with downloading the d3d11 file or do you recommend I download the updated release?
Amazing mod, by the way, I'm having a fantastic time playing this along with the wheel mod.

**Comment by LukeRoss00** [comment]
The file in this thread is the only change since Release 4. If you're still on Release 3, of course it's better to update everything!
