### ISSUE TITLE
WMR will not start

### ISSUE THREAD

**Issue by dtdman420** [LukeRoss00/gta5-real-mod#66]
I can not seem to get this to work.   My specs  O+ 1070ti and 8700k.

I started with a fresh install of GTA V,  Started the game once to apply the camera settings like you said in your readme.  After that i closed the game and made sure desktop theatre  mode was unchecked.

Then i downloaded release v4 of the mod and extracted to the GTA exe folder and ran your config to use your Medium settings.   I can hear the game in my hmd but my hmd screen is still in the steamvr black room thing. On the monitor window, it is running in full screen mode and from what you say it should not be in full screen.

The file structure in the GTA folder looks like this...

GTAV_REAL_mod_by_LukeRoss_r4
Installers
update
x64

That is the folder structure plus all the files underneath all that.
Any help would be much appreciated.
Everything is all up to date. GTA, steamvr, nvidia, windows, all up to date

Edit. I do not know if this matters but i should mention it.  My documents folder where the settings go is on a different drive then the GTA install.  When i run the batch file i press M for medium and it says 1file copied
        1file copied
press any key to continue

I was reading around and seems like other wmr users have it working but i can not find any comments about it for January. I mention this because WMR for steamvr was updated on January 7th maybe it broke something. Here are the patch notes for the wmr release in case it is related.

Updated to use new scaling capabilities on Windows 1903 and above. This particularly improves scaling for HP Reverb users.
Removes the renderTargetScale setting. On Windows 1903 and above, app buffers are dynamically sized based on what the running app needs. On Windows 1809 and earlier, the maximum value possible on those operating systems is used.
DX12 motion estimation on Windows 1903 and above for faster motion vector generation by lowering CPU cost and improving overlap of GPU work.
New motion reprojection auto switching logic.
Added NoInterEyeRotation exceptions for Fallout 4 VR and Battlezone.
Updates the input profile exposed by the SteamVR driver.
Fix performance and quality issues related to controller input and haptics.
Added settings to enable independent move/turn thumbstick overrides.

**Comment by LukeRoss00** [comment]
> The file structure in the GTA folder looks like this... GTAV_REAL_mod_by_LukeRoss_r4

That's your problem right there. You should extract the mod directly into the `GTA5.exe` folder, not into its own subfolder where the game wouldn't see it

**Comment by dtdman420** [comment]
Holly crap dude thank you so much!
I am glad it was just a stupid mistake i made and now it worked right away.

AMAZING!!!!!!!
