### ISSUE TITLE
vehicle camera pitch

### ISSUE THREAD

**Issue by 5yndr0id** [LukeRoss00/gta5-real-mod#67]
Hi,
driving in first person mode can be pretty jarring due to the camera pitch being locked to the vehicle.
Any chance for an option to lock the pitch to the horizon like in third person mode? Imo, it would help a lot with overall comfort/motion sickness.
Aside from that the VR implementation is nearly perfect.

**Comment by LukeRoss00** [comment]
That doesn't work. It would make flying planes impossible, and also lead to a comical and jarring effect when your car tilts or rolls.

**Comment by 5yndr0id** [comment]
It wouldn't work with planes, yeah.
However, most racing games, including Dirt Rally where the car tilts a lot, use it as the default setting, and it works quiete well there, imo. 
One solution would be adding a hotkey for switching between camera pitch modes.
