### ISSUE TITLE
Hi, not an issue just questions 

### ISSUE THREAD

**Issue by ZOOCH716** [LukeRoss00/gta5-real-mod#70]
Hi LukeRoss00, just tried the R.E.A.L mod for the first time yesterday.... WOW! best vr experience iv had so far. Thanks a lot for all the effort and time you must have put in. Amazing job! 

Just two questions. one is there anyway to disable that head shake for resetting the view? It is very well implemented don't get me wrong but I find myself shaking me head accidentally sometimes and resetting view when not needed. Id personally just rather map the hot key to my steam controller and use that exclusively. 
Would it be possible for this mod to work with SLI? It plays nice with my one 980ti but jaggies are pretty bad, can only imagine how good it would look if my other card was in use.

Thanks again!

**Comment by LukeRoss00** [comment]
Thanks for the kind words! For the moment sadly it's no to both questions :-/

**Comment by ZOOCH716** [comment]
Fair enough, we cant have everything :)

Was the last version of the Mod final or will you be updating it anymore?

I would imagine the SLI part would take a lot of work(especially if you don't use it) but do you think you could add some sort of "disable head shake view reset" to the list of other hotkeys we have if you do?

I currently have the "Recenter HMD" hotkey set to the back paddle of my Steam controller and it works like a charm. Whereas with the head shake sometimes when I'm glancing at the map and back while driving or looking out the window it causes my view to reset suddenly and it can be pretty jarring. 

Thanks again

**Comment by LukeRoss00** [comment]
I gather that you're a power user. If you're comfortable with hex editing, changing the byte at offset 28B9BB from 3F to 4F in `d3d11.dll` should disable headshake detection.

**Comment by ZOOCH716** [comment]
Thanks so much for that m8 it worked perfectly :) I wont lie I had no idea about Hex editing but a few searches and I managed to get the job done. Thanks again (thumbs up)
