### ISSUE TITLE
sound

### ISSUE THREAD

**Issue by ty110072** [LukeRoss00/gta5-real-mod#71]
so my earphones on my oculus stopped working about a year ago. I have to use external head set (IE ear buds) just downloaded your mod works great except no sound cause i cant use the sound in my Oculus. If you could make or tell me away to use external speakers for thoughs of us who s HMDs the sound doesnt work it would be appreciated. Thank you, and thanks for the mod

**Comment by LukeRoss00** [comment]
You can select any audio device you want (just do it before running the game because once it's started GTA V will no longer recognize a new audio device)

**Comment by ty110072** [comment]
I have sound on other rift games to my external speakers not working with this. how do i select an audio device is it in one of the settings in the mod file? thanks

**Comment by LukeRoss00** [comment]
I mean in Windows! https://www.digitalcitizen.life/how-change-default-playback-recording-audio-device
