### ISSUE TITLE
Doesn’t recognize keyboard and controller

### ISSUE THREAD

**Issue by judochopjames** [LukeRoss00/gta5-real-mod#72]
Hi, thanks for your work on this, but I seem to be having an issue. I can play gta v normally with either keyboard or game pad but when I start it up in vr, the vr appears to be working normally but when I get to the title screen (where you select settings or story mode) the game does not recognize either keyboard or game pad. I can’t select anything. Any advice would be greatly appreciated.

**Comment by LukeRoss00** [comment]
Details about your system? Are you using SteamVR? It might be stealing focus from the game

**Comment by judochopjames** [comment]
Hi, thanks for the quick response. I’m using psvr through ivry which
ultimately hooks into steam vr and now that I think about it that’s
probably the most likely culprit although I’m not sure  how because I
didn’t think it did anything with controllers. Otherwise my system is AMD
based (phenom ii x6) with a 1050 ti. Another possible culprit could be that
I’m using a DualShock 4 connected via a usb dongle but like I mentioned
everything works fine when the vr is disabled. If it turns out the psvr
isn’t supported that totally understandable, thanks again for your help!

**Comment by LukeRoss00** [comment]
Haha, what a crazy configuration! I don't do anything special in my mod with KB/M or gamepad that could divert the inputs away from the game, and I have absolutely zero experience with your setup, so you might have better luck posting on the iVRy forums

**Comment by judochopjames** [comment]
No problem, thanks for taking the time to respond, I’ll let you know if I
ever figure it out.
