### ISSUE TITLE
Support)))

### ISSUE THREAD

**Issue by tomreason** [LukeRoss00/gta5-real-mod#73]
Great news, large YouTube channels and Sites from Russia advertise your Mod and praise it very much))) I am very happy for you and thank you very much !!!

**Comment by LukeRoss00** [comment]
That's wonderful, thank you! Do you have any links?

**Comment by tomreason** [comment]
Yes
http://4pda.ru/2020/02/04/367460/
https://www.youtube.com/watch?v=g_buxrxUWzA
The rest I can not find in History (((
But I’ll say for sure that many channels support your Mod!
