### ISSUE TITLE
Blurry Vision when using the analog stick so move the camera (Index)

### ISSUE THREAD

**Issue by D3fcon5** [LukeRoss00/gta5-real-mod#74]
Hi!

I really love your mod, and sofar it worked fine with my Index and mostly I hit 80fps. Something tho bothers me: If I move my analog sticks to pan the camera everything gets little blurry. I have solid 80fps at this time so it wont be reprocection imo. When I look around with my Head its not blurry at all, only when using the analog stick.
Is it because Iam using the Index and not the Oculus ?
Keep up the good work and thanks for that mod!

cheers

**Comment by LukeRoss00** [comment]
That's just normal with alternate eye rendering, see the first entry in the [FAQ](https://github.com/LukeRoss00/gta5-real-mod#faq)

**Comment by D3fcon5** [comment]
thank you for pointing me in that direction! Ill try to disable it to see if its still playable, but since it makes me queezy I need to find a solution for myself
