### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by TallMonkee** [LukeRoss00/gta5-real-mod#75]
On my monitor I see the game without any hud
On my headset I see the hud without any game

any help would be greatly appreciated

**Comment by LukeRoss00** [comment]
Please post your `asiloader.log` and `ScriptHookV.log` files

**Comment by TallMonkee** [comment]
I appreciate the quick reply Luke but managed to fix it as I forgot to put scripthook back into my game. I'm a little bit stupid like that.. sorry for bothering you ;)

**Comment by LukeRoss00** [comment]
No problem, glad you sorted it out!

**Comment by bjzilberman** [comment]
Hey @TallMonkee I'm experiencing the same problem, I have the scripthook.dll file in my game directory but it's not generating the scripthookv.log; It's just kind of vague as to "i forgot to put scripthook back into my game".

Any clue would be helpful! thanks!

also, `asiloader.log`:
```// GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\Windows\system32\dinput8.dll" => 00007FFBA9A80000
API: "DirectInput8Create" => 00007FFBA9A88F80
API: "DllCanUnloadNow" => 00007FFBA9A99EB0
API: "DllGetClassObject" => 00007FFBA9A99F80
API: "DllRegisterServer" => 00007FFBA9AA3CB0
API: "DllUnregisterServer" => 00007FFBA9AA3F30
LOADER: Loading *.asi plugins
LOADER: Finished loading *.asi plugins```

**Comment by TallMonkee** [comment]
@bjzilberman, I very simply didn't have ScriptHookV.dll in my game directory, I solved it by moving the dll into my directory. I can't help you, sorry. I would recommend contacted Luke Ross directly and see if he can help since I'm just some bloke on the internet who doesn't know what he's talking about
