### ISSUE TITLE
RealConfig.bat can't find path

### ISSUE THREAD

**Issue by Rafapim** [LukeRoss00/gta5-real-mod#76]
Hello,

I changed the path because my OS is on C: and documents folder on D: but I still get the message:

The system cannot find the path specified.
0 file(s) copied.
1 file(s) copied.

I edit the bat to be on SET dst=D:\Usuários\Rafael\Documents\Rockstar Games\GTA V
but it didn't work, I try removing the accent
Or putting just SET dst=D:\Documents\Rockstar Games\GTA V
Still getting the path error message.

Please help, thanks!

**Comment by LukeRoss00** [comment]
The accented letter is probably not being recognized correctly by the command interpreter. You can just do manually from the Windows file explorer what the batch file would have done automatically for you. Assuming you want to use Medium settings and you have the Steam version of the game:

- rename D:\Usuários\Rafael\Documents\Rockstar Games\GTA V to `settings_ori.xml`;
- copy `C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\Settings\Medium\commandline.txt` to folder `C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V`;
- copy `C:\Program Files (x86)\Steam\steamapps\common\Grand Theft Auto V\Settings\Medium\commandline.txt` to folder `D:\Usuários\Rafael\Documents\Rockstar Games\GTA V`

**Comment by Rafapim** [comment]
Thanks! it worked. Amazing mod!

**Comment by ryanayoung** [comment]
This is still a problem and I wish there was a better work around, or at least a mention of it in the quick setup page. Could use the $env:USERPROFILE to find the location of the users home folder and search Documents from there.

**Comment by LukeRoss00** [comment]
The Documents folder is in no way guaranteed to be under the user's home folder. The batch file however should be able to find the Documents folder even if it's been moved. Could you open a command prompt and paste in exactly the following command with the quotes and all:

`powershell "(new-object -COM Shell.Application).Namespace(0x05).Self.Path"`

and tell me what the output says?

**Comment by ryanayoung** [comment]
weird, it's something with my system. It said powershell was not a
recognized command, despite "%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\"
being in my path. I had to manually change it to
"C:\WINDOWS\System32\WindowsPowerShell\v1.0\" in my environmental variable
for powershell to be a valid command. After that your script returned my
Documents path.

sorry for the trouble.

**Comment by LukeRoss00** [comment]
No problem, glad you sorted it out! Thanks for getting back to us with your solution 👍
