### ISSUE TITLE
Games freezes after some (random) time, HDMI disconnects

### ISSUE THREAD

**Issue by SoundstormVFX** [LukeRoss00/gta5-real-mod#77]
Hi Luke! 

First, congrats and a big THANK YOU for this mod. It's really great. To my problem:

Everytime after a random amount of minutes the game/picture suddenly freezes. I take off the Rift CV1, the gamewindow is black. I press alt+TAB and that reacativates the windows and I can see the game again, but now the refresh/switching of the 2 images is visibly slower than it was/should be. It's  also randomly switching now... Also the Rift at this point looses the HDMI connection. Even closing the game or Oculus and restarting Oculus does not get the HDMI connection back and I have to restart my computer.

I don't have problems with disconnecting Rift in any other game, be it from Oculus store or Steam or even with VorpX. And no, Vorpx isn't running when I play GTA V. ;) 

I admit I have not tried with the latest version, but I couldn't see any bugfixes that could help me. Should I try with the last version to make sure?  Do you have an idea what could be the problem? 

Thanks for helping!

**Comment by LukeRoss00** [comment]
It sounds like the infamous CV1 disconnect issue. It might be triggered by the headshake gesture, or the rapid head motions that frantic GTA V combat tends to provoke :-)

I'd suggest using the hotkey to recenter (or the Oculus menu) to avoid shaking the HMD, but there is nothing that can be done in software. The root cause is a chip in the middle of the Rift motherboard that was not soldered correctly. If you're VERY lucky, reseating the cable in the headset might alleviate or cure the problem, but for most users the problem was the chip, not the cable.

**Comment by SoundstormVFX** [comment]
Thanks for responding.
My first CV1 had this issue, I remember it exactly... ;) Cable was fine, but the chip wasn't. Luckily they send me a new one and I never had this problem again. As I said, it never disconnects in other games. Even in GTA V with the mod, I can use the recenter method (shaking your head) without problem. The disconnect/freeze is random, sometimes it happens after some minutes, sometimes after an hour. The last time I was just driving around and looking out of the window. ;) Anyway, I'll try moving my head very slowly next time, see if it helps. 

Can I disable the recenter-shaking method? Maybe it get's triggered and crashes or something..?

**Comment by LukeRoss00** [comment]
Even if the game crashes or freezes, the HDMI should not disconnect. There is no chance that a user-space program can bring down the hardware this way (which is confirmed by the fact that you have to reboot the PC to get the connection back up).

I'm sorry but it's without a doubt a hardware problem. This time it might be the cable, or even the GPU overheating or whatnot, but it's not the crashes triggering the disconnection, it's the other way around :-/

**Comment by SoundstormVFX** [comment]
OK, I see... thanks for the valuable info. It seems I'm out of luck then, time for an Rift S. :) Nevertheless I'd like to make some more tests and report back, before closing the thread. If that's ok with you. :)

**Comment by LukeRoss00** [comment]
Sure, we can leave the issue open as long as you wish!

**Comment by LukeRoss00** [comment]
Do you have any further news? Should I close the issue?

**Comment by SoundstormVFX** [comment]
I tried some things but no luck. I guess I have a problem with the USB ports as they change to USB2 instead of USB3. If I disconnect and plug it in, they indicate USB3. But after the crash, it's USB2. 

If I disconnect the HDMI and replug it, it works again after the crash. I think it's not a hardware fault, but software/drivers. I guess your mod is not the problem. I'll close the post.
