### ISSUE TITLE
Help with headset

### ISSUE THREAD

**Issue by dprater81** [LukeRoss00/gta5-real-mod#79]
Help!!!! I’ve tried multiple times to play this in VR. I first bought it on humble bundle and it didn’t work. Then bought on steam and followed all steps and it’s not working. Once you enter steam VR. Are you in the home screen room with the two panels for recently played and the store panel. GTA 5 is not listed on there. When you click play on game, does it override the oculus home or Steamvr room and just show game?  If I just click on game on desktop, it tells me that this game is not intended for VR and plays it flatscreen. Does anyone have any suggestions?

**Comment by tjohnson4** [comment]
I am getting the same behaviour. Followed instructions and only get audio through oculus. Video stays on the monitor

**Comment by LukeRoss00** [comment]
Did you guys try following Mike's tutorial at https://www.youtube.com/watch?v=P4QD_ggjrK8 ? He shows what to do step by step
