### ISSUE TITLE
Possibility to uncap frame rate? 

### ISSUE THREAD

**Issue by skyworxx** [LukeRoss00/gta5-real-mod#8]
Is it possible to uncap the frame rate in order to make alternate eye rendering less blurry?

**Comment by LukeRoss00** [comment]
No, the HMD will not accept submission of more than 90 fps

**Comment by skyworxx** [comment]
But could 'extra' frames not be discarded? This is essentially to just bring the time between alternating frames further down

**Comment by LukeRoss00** [comment]
Not sure what you mean by extra frames. It's not like vsync on a monitor which can be turned on and off: the Oculus SDK just won't let you push more than 90 frames per second.

**Comment by jdawgzim** [comment]
> bring the time between alternating frames further down 
I think the alternating frames is not only to to cut down on the system load but also to accomplish stereoscopic vision.  
Trying to sometimes update both eyes at the same time dynamically would be outside the scope of how this is implemented.  At least as far as I understand the tech here.
