### ISSUE TITLE
AMD ReLive VR Streaming to Oculus Quest not working

### ISSUE THREAD

**Issue by snowzach** [LukeRoss00/gta5-real-mod#80]
AMD Drivers support VR Streaming via Relive. Basically it emulates a headset when you launch SteamVR and streams the output to other devices. It emulates a handful of devices including Oculus Rift S which is what I selected. It's streaming to my Oculus Quest. I launch SteamVR and I can see the normal SteamVR stuff. I launch GTA V and it pops up the square window on the screen but I only ever see SteamVR home in my Oculus Quest. It's like GTA V hasn't taken over the headset. 
Any ideas?

**Comment by LukeRoss00** [comment]
I have no experience with that and no way to test it. However, you could try forcing the mod in SteamVR mode by creating an empty file called `SteamVR.dev` in the `GTA5.exe` folder

**Comment by snowzach** [comment]
Almost! So that worked to get it into the headset. I could see the loading screen but once it switched to 3rd person view, I could only see the map on a black background. It would occasionally flash an image to the headset if I moved my head around a little. Any other quickies to try you can think of?

**Comment by LukeRoss00** [comment]
It could be that ReLive is not compatible with alternate eye rendering. I hear that some people managed to make the Quest work with the mod using Virtual Desktop (and of course it works even better using the Link cable)

**Comment by craftx17** [comment]
I have the Link cable and am trying to get this mod working through my Oculus Quest. I'm having the same issue snowzach is having. I open SteamVR and open GTA 5 by pressing the button "Play in Theater" (Even though I turned off Theater Mode for GTA 5 in Steam like the instructions said). I am taken back to the SteamVR home with the GTA 5 audio playing through the headset, but the actual game only displays on my computer monitor. Any suggestions for getting this working over Oculus Link?

**Comment by LukeRoss00** [comment]
> open GTA 5 by pressing the button "Play in Theater" (Even though I turned off Theater Mode for GTA 5 in Steam like the instructions said)

Why would you use "Play in Theater" to start the game? You must launch the game normally
