### ISSUE TITLE
Weird Slo-Mo Glitch

### ISSUE THREAD

**Issue by Aerotactics** [LukeRoss00/gta5-real-mod#81]
EDIT: 
1) Aim the Sniper
2) Hold the character wheel button
3) Let go of aim
4) You will be in super slow motion

Context:

So I was playing the mission Nervous Ron.

Aiming with the Sniper in VR is weird.

Using a gamepad, I was using Left-Trigger to aim, and I may have entered a weird button combo (Aim + zoom out scope + ?) or I may have double-aimed (Aim + Aim again) and suddenly all the game's animations went super slow motion. The camera was still in real-time, both in first and third person. This persisted when reloading the game.

Pressing "pause" showed the UI-stuck-to-headset mode instead of the static UI.

I have 1 other mod installed which appears to have full compatibility with this one, called Chaos Mod: https://www.gta5-mods.com/scripts/chaos-mod-v-beta
However, none of the current events suggested slow motion.

**Comment by LukeRoss00** [comment]
It's not a bug, it's a feature :-) You just found my super-secret Easter-eggy time-warp command. To toggle it on and off, you hit and release the left trigger while pressing 'Down' on the D-Pad. It also works during normal gameplay, not just when shooting. Using the D-Pad is normal when aiming with a scoped rifle, to control the zoom level, but you're supposed to be holding the left trigger down all the time. You must have accidentally released the left trigger while zooming out, which activated the slow motion.

Anyway, I won't spoil it for you, but once you're in slow motion, you can actually control the time rate using another command ;-)
