### ISSUE TITLE
First-Person ATV is crotch-level and slightly to the right

### ISSUE THREAD

**Issue by Aerotactics** [LukeRoss00/gta5-real-mod#82]
It's not fully crotch-level, but It's not centered. Also, don't know if this is something you can fix.

**Comment by LukeRoss00** [comment]
Many vehicles have bizarre positions for the 1st person camera: it's not something I changed, it was Rockstar's artistic decision when they implemented 1st person. This is also tied to the fact that (particularly in ATVs, bikes and trucks) the camera will climb up as you look to the sides.

I assume they did it to avoid clipping issues, and again for artistic reasons.

If it really bothers you, there are other mods that allow you to customize the camera position, even on a car-by-car basis
