### ISSUE TITLE
Cant use Mouse and Keyboard or controller in Menu...

### ISSUE THREAD

**Issue by Edersteiner** [LukeRoss00/gta5-real-mod#83]
I recently installed this mod and it boots up correctly and shows up in my Valve Index but i cant press any buttons in the menu. Ive tested both with mouse and keyboard and with an xbox one controller connected via USB.

**Comment by LukeRoss00** [comment]
Steam (or SteamVR, or some overlay/utility) is probably redirecting your input. Can you control your character?

**Comment by Edersteiner** [comment]
i just restarted steamVR and it worked now. But now when i try to load into story mode it loads for a while and then it just crashes.

**Comment by LukeRoss00** [comment]
Does the game run fine if you remove the mod?
