### ISSUE TITLE
Game crashes when loading into Story Mode

### ISSUE THREAD

**Issue by Edersteiner** [LukeRoss00/gta5-real-mod#86]
When i try to load into story mode the game loads for a while and then it crashes.

Valve Index HMD
RTX 2070
i7-8700

**Comment by LukeRoss00** [comment]
Please post your `asiloader.log` and `ScriptHookV.log` files

**Comment by Edersteiner** [comment]
[ScriptHookV.log](https://github.com/LukeRoss00/gta5-real-mod/files/4165533/ScriptHookV.log)
[asiloader.log](https://github.com/LukeRoss00/gta5-real-mod/files/4165534/asiloader.log)

**Comment by LukeRoss00** [comment]
Mmm... they look OK. Could you add the line `RVRLog = 2` at the end of your `RealVR.ini` and try launching the game again? After the crash you should have a new `RVRLog.txt` file, please post it here

**Comment by Edersteiner** [comment]
[RVRLog.txt](https://github.com/LukeRoss00/gta5-real-mod/files/4165604/RVRLog.txt)
Here you go

**Comment by LukeRoss00** [comment]
It looks like you didn't run the `RealConfig.bat`, or perhaps it gave you errors and you didn't notice. Try to run it again

**Comment by Edersteiner** [comment]
It gave me errors something: Path couldn't be found, so i follwed your instructions on another issue i found here.

**Comment by LukeRoss00** [comment]
Check the steps again, because the game is trying to run with graphics options that are all wrong; that's probably the cause of the crash

**Comment by Slimmoo** [comment]
I am also having this exact same problem.  Question did you take into account anyone using onedrive? Cause this is what my GTA5 directory is "C:\Users\Username\OneDrive\Documents\Rockstar Games\GTA V", could that have something to do with the issue?

**Comment by LukeRoss00** [comment]
If your Documents folder has been redirected to OneDrive, you should manually edit the batch file in Notepad and replace `%UserProfile%\Documents` with the full path of your Documents folder, then run the batch file again.

**Comment by LukeRoss00** [comment]
Please try with [this](https://github.com/LukeRoss00/gta5-real-mod/files/4176824/RealConfig.zip) updated batch file (zipped because GitHub doesn't like .bat attachments). If it detects the OneDrive redirection correctly, I might add it as a hotfix to the current release

**Comment by Slimmoo** [comment]
Awesome, that worked, quick and simple.Thanks very much for your quick response.
