### ISSUE TITLE
In vehicle camera settings

### ISSUE THREAD

**Issue by nickyb78** [LukeRoss00/gta5-real-mod#87]
When im in a car in first person mode i am on the bonnet of the car. I cant get the view from inside the car. Am i doing something wrong. I can get other camera angles working fine. I just cant get the view from inside holding the steering wheel. Im on valve index. On foot first person is fine as well

**Comment by LukeRoss00** [comment]
https://github.com/LukeRoss00/gta5-real-mod#quick-setup

First Person Vehicle Hood must be Off

**Comment by nickyb78** [comment]
I found it. Think il stick to 3rd person for driving. Blur when turning is a bit more noticable in first person. Love the mod though. :)

**Comment by nickyb78** [comment]
Tried allowing independent camera mode but that messes up the head movement. Take it thats why u say keep it off but just wondering will it or can it be fixed. Its a pain pressing select all the time when going through camera modes. Idealy i want 3rd person driving and first person on foot. Hope it can be fixed

**Comment by LukeRoss00** [comment]
> that messes up the head movement

What do you mean?

**Comment by nickyb78** [comment]
When allowing independent camera when im in the car my head controls the camera instead of right joystick. Its not a fixed camera behind the car. When i move my head the camera moves around the car as if im using the right joystick. But when i turn independent camera off it doesnt do that in car. The camera is fixed behind car and i move camera with right joystick if i want. Head movement doesnt move the camera.

**Comment by nickyb78** [comment]
with independent camera off the camera is fixed behind the car, you can still look around the scene but looking around doesnt pan the camera around the car, having indepent camera on does pan the camera around the car when moving head.

**Comment by LukeRoss00** [comment]
I see. No, I'm very sorry but I cannot fix that. Your best bet would be to set Allow Independent Camera Modes to Off as recommended, and then use the normal game commands to select the 3rd person camera when you drive.

**Comment by nickyb78** [comment]
Yeah thats what iv been doing. Its a bot annoying flicking through camera modes when getting out the car to get to first person but this is the only problem i hsve. Everything else is fine. I can live with it lol
