### ISSUE TITLE
Anyway to disable alternating rendering?

### ISSUE THREAD

**Issue by jaysinvialoux** [LukeRoss00/gta5-real-mod#9]
I'm using a vive pro it it works totally fine in the menus and in the settings but in game it's got that flashing alternating rendering which I get, is an Oculus SDK thing to make it 3D. My question is if it works fine for vive in the menus can we get an option for a monoscopic rendering in game? Basically just turn off the alternating rendering. It would be 2d I know but after seeing Borderlands 2 Vr in monoscopic 2d I don't think it would be they bad, it's at least an option.

**Comment by HollyDamned** [comment]
It would have took you exactly 30 seconds to CTRL+F the readme...
F11 to activate the mod menu.
NUMPAD 2 to activate/deactivate the stereo rendering.

Advanced tweaking and hotkeys :
F11         Toggle hotkeys - off at start
T           Cycle dominant eye for aiming down sights (none, left, right) - right at start
Y           Toggle heading control - on at start
U           Toggle pitch control - on at start
I           Toggle decoupled 3rd person camera - on at start
O           Toggle view fix enable - on at start
J           Cycle pitch mode in cutscenes (absolute, relative, cut relative) - cut relative at start
K           Toggle full camera tracking in cutscenes - on at start
'           Toggle slow motion - off at start
N           Toggle HUD markers and FPS - off at start
-           Cycle HUD tracking mode (normal, force fixed, force headlocked, developer) - normal at start
NUMPAD /    Recenter HMD - centered at start
NUMPAD -    Toggle VR enable - on at start
NUMPAD .    Cycle zoom override (never, only cutscenes, always except cutscenes, always) - never at start
NUMPAD 0    Toggle position tracking - on at start
NUMPAD 2    Toggle stereo rendering (alternate eyes) - on at start
NUMPAD 3    Toggle darts/tennis FOV override - on at start

**Comment by jaysinvialoux** [comment]
Sorry, I looked at those settings last night too. I totally missed numpad 2 stereo toggle. I'll try tonight again

**Comment by Shanesan** [comment]
So I think the real question here is "how did you make it work on VIVE Pro?"

**Comment by jaysinvialoux** [comment]
If I could just turn off that flashing it would work. I tried all the commands and no luck
