### ISSUE TITLE
Aiming in cover and driving

### ISSUE THREAD

**Issue by mattdeanuk** [LukeRoss00/gta5-real-mod#90]
Head aiming works perfectly when just stood in the world looking down the sights.
When in cover and driving the targeting is way off.
I can use the right stick to aim in these instances.
Is this expected behaviour or is something wrong?
Thanks

**Comment by LukeRoss00** [comment]
Did you make sure to set Settings>Camera>First Person Third Person Cover to On as explained at point 2 (https://github.com/LukeRoss00/gta5-real-mod#quick-setup)?
