### ISSUE TITLE
flashing in and out of vr

### ISSUE THREAD

**Issue by chalmers78** [LukeRoss00/gta5-real-mod#92]
Followed all steps but its starts in VR for a few  seconds then flashes on and off for a further few seconds then leaves me with a black screen, head is tracking, hud is there and its fine on my screen (samsung tv, which might be the issue?) 
I'm reinstalling and trying again but if anyone has any ideas or similar problems meantime then any helpwould be greatly appreciated :-)

**Comment by LukeRoss00** [comment]
Did reinstalling solve your problem?

**Comment by chalmers78** [comment]
Yes, unfortunately I was unable to locate my documents folder so I copied the settings file into the gta v folder manually, it works almost perfectly but there's a lot of jarring, this may be normal but from what others say I think it's a little excessive. 
Any extra advice would be great

I think with this mod you've made yourself a legend in the community

**Comment by LukeRoss00** [comment]
Haha, thanks :-) Which headset are you using? Also the more details you give about your system and config, the better I can understand your issue

**Comment by chalmers78** [comment]
rift s
1080ti with a 8700k cpu
24g ram 
I've just copied the settings from the folder that has high, mid, low (using high then low without any difference) straight into the gta v main folder, i feel this has caused an issue somewhere.
will try and do it the way you've outlined in another thread tomrrow and report back. 
(the thread called runconfig.bat issues) 
although im fairly sure my documents folder is also on my c drive 
I had originally installed gta on my d drive but reinstalled it onto the c drive after my first attempt at the mod so thats another thing that might be causing the problem
i also used unrar first then 7 zip neither of which seemed to work before using winrar which has got me to this stage, so damn close haha

**Comment by chalmers78** [comment]
incidentally, it is playable, ive got pretty steely vr legs after 4 years of dirt rally so i am playing it anyway but just trying to eek out some of the jarring to improve it but if it doesnt work ill still finish it as its fecking amazing in vr

**Comment by LukeRoss00** [comment]
You can also try with the new batch file that I added to the release page (Hotfix 4.2). The settings file should _not_ be in your `GTA5.exe` folder

**Comment by chalmers78** [comment]
Tried that new batch file and i still get the same juddering. checked nathies youtube vid to see if maybe mine was just what it was but his looks a hell of a lot smoother and if i can remember correctly from listening to freality then i dont think his specs are too much better than mine
Does verifing the integraty of files return gta to its original state, as i think if i go back and retrace my steps i can get it but feel ive effed it up somewhere along the line. 
if not, my isp is going to love me with my third 100gb download of the week haha
will review the read.me again and get back to you if verifying etc doesnt work. 
thanks again for taking time out to help

**Comment by chalmers78** [comment]
oh i also get the 1 file not copied with the new batch file

**Comment by LukeRoss00** [comment]
Add the line `RVRLog = 2` at the end of your `RealVR.ini` and try launching the game again. Once the game has fully loaded and you have control of your character, wait a couple of seconds and then quit the game. At that point you should have a new `RVRLog.txt` file, please attach it here (zip it if it's too big).

**Comment by chalmers78** [comment]
tried that but coudnt find any rvrlog after exiting the game.
not sure if this matters but my RealVR file doesnt have .ini after it and most files have no bits like that added on at the end either 

[gta v settings page.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4219951/gta.v.settings.page.zip)

**Comment by chalmers78** [comment]
[gta settings page 2.zip](https://github.com/LukeRoss00/gta5-real-mod/files/4219994/gta.settings.page.2.zip)

**Comment by LukeRoss00** [comment]
You're not supposed to use Word to edit text-only or .xml files! You should only use Notepad or similar programs that won't completely reformat the documents making them unusable by the game. Also, you probably have file extensions hidden in Windows Explorer.

Unfortunately there's not much else I can do from my side. Your best bet would be to find someone knowledgeable with computers that can come to your place and help you follow the setup procedure step by step. Good luck!
