### ISSUE TITLE
How can I use car mods?

### ISSUE THREAD

**Issue by Manders3011** [LukeRoss00/gta5-real-mod#93]
Hello👋
I'm trying to trade cars in GTA for some time. I'm doing that with the “replace”cars (no Add On)
The game starts after that. And you can enjoy the beautiful new original interior of various dream cars in VR. But after a few minutes, the game crash. Has anyone ever had a positive experience?
Sorry for my bad English 😏
THX Manders3011

**Comment by LukeRoss00** [comment]
So, it seems that nobody here has any relevant information (including myself, as I don't use car mods).

You might have better luck posting in the forum for the other mods that you want to use!
