### ISSUE TITLE
Pimax 5k plus working 

### ISSUE THREAD

**Issue by Jesusavesouls** [LukeRoss00/gta5-real-mod#94]
It runs good but when I pick higher hertz or large fov gta5 starts distorted.Seems I can only use low rate.Would there be a correct settings to make the real mod work with the large fov in Pimax settings ? Jesus loves you !

**Comment by LukeRoss00** [comment]
High FOV would require special coding, which I cannot do since I don't have any hardware to test on

**Comment by Jesusavesouls** [comment]
If you lived close by you could use my pimax to test or design those
software changes.Where are you approximately ?

**Comment by Jesusavesouls** [comment]
I went into the command line text in gta5 and put it at 2100x2100 and it looks very sharp.
