### ISSUE TITLE
Very low Fps

### ISSUE THREAD

**Issue by JDenisB** [LukeRoss00/gta5-real-mod#96]
Hi! Cannot use your mod even with my new build. Ryzen 7 3700x, RTX 2070 SUPER.
My problem is that the game stay at a very low FPS!(1 to 10 max) The CPU run at 10% and
the graphics card stay at 0%! Hope u can help me!(Poor English sorry)

**Comment by LukeRoss00** [comment]
Did you follow all the steps in the README? Any errors from the `RealConfig.bat` file?

**Comment by JDenisB** [comment]
Yes I follow all the steps and no error from the RealConfig.bat file.

**Comment by LukeRoss00** [comment]
Let's try some advanced troubleshooting ;-) Add the line `RVRLog = 2` at the end of your `RealVR.ini` and try launching the game again. Once the game has fully loaded and you have control of your character, wait a couple of seconds and then quit the game. At that point you should have a new `RVRLog.txt` file, please attach it here

**Comment by LukeRoss00** [comment]
Oh, just saw from your edit that you are using an old (pirated?) version of the game (v1.0.1180.1). I cannot support that

**Comment by JDenisB** [comment]
Oh. Ok. I understand. Sorry and thanks for all....Gonna buy the game very soon...
