### ISSUE TITLE
Steam vr supersampling.

### ISSUE THREAD

**Issue by nickyb78** [LukeRoss00/gta5-real-mod#97]
Does supersampling affect the the game. Like does it actualy supersample or does it have no affect. Im wanting a liitle higher res in game as i think id be ok upping res a bit more as performance is fine. How can i up the res or supersample?

**Comment by nickyb78** [comment]
Im on a rtx 2080 super. Valve index

**Comment by LukeRoss00** [comment]
https://github.com/LukeRoss00/gta5-real-mod#even-more-advanced-resolution-tweaking
