### ISSUE TITLE
stereo rendering off -> close objects look HUGE

### ISSUE THREAD

**Issue by XenoEgger** [LukeRoss00/gta5-real-mod#98]
Hi,

Thanks for this great mod.
I can't play with stereo rendering on because of this ghost effect so I disabled it and it looks and plays great but the close object scaling ( FOV ? Zoom ? ) is very weird. My hands, for example, look giant.

How can I fix this ?

Edit: I use an Oculus Rift S.

**Comment by LukeRoss00** [comment]
That's just the way monoscopic rendering looks, it cannot be "fixed". It's the same as watching a 360° video
