### ISSUE TITLE
Where's the source?

### ISSUE THREAD

**Issue by Eglin** [LukeRoss00/gta5-real-mod#99]
I don't want to point fingers or anything, but some GTA mods have included trojans in the past.  I would like to inspect and compile any binary objects I for myself, but when I download the source archive for this project it only contains a readme file.  Reading the FAQ and HELP WANTED sections, I don't get the impression that you'd mind sharing sources as long as people aren't trying to steal your work.  Is that correct and would you please share the sources that you're able?  Hopefully also documenting the additional works you've included (or is the ASI yours, too?).

Thanks,
Egg

**Comment by LukeRoss00** [comment]
The .asi is mine too. I'm not ready to share the source code ATM, but as you can see for yourself the mod comes completely clean on VirusTotal. That said, if you don't trust it you shouldn't download it of course.
